from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from . import shop_views
from . import stats_views
from . import lead_views
from . import parsing_views
from . import views_levels
from . import bot_webhook
from . import bot_views
from . import binotel_views
from . import binotel_webhook

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(
        template_name='management/login.html',
        redirect_authenticated_user=True
    ), name='management_login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='management_login'), name='management_logout'),
    path('clients/dedupe-preview/', views.client_dedupe_preview, name='management_client_dedupe_preview'),
    path('clients/<int:client_id>/delete/', views.delete_client, name='management_delete_client'),
    path('admin-panel/', views.admin_overview, name='management_admin'),
    path('admin-panel/user/<int:user_id>/clients/', views.admin_user_clients, name='management_admin_user_clients'),
    path('admin-panel/user/<int:user_id>/dossier/', views.admin_manager_dossier_api, name='management_admin_manager_dossier_api'),
    path('admin-panel/user/<int:user_id>/toggle-active/', views.admin_manager_toggle_active_api, name='management_admin_manager_toggle_active_api'),
    path('admin-panel/invoices/<int:invoice_id>/approve/', views.admin_invoice_approve_api, name='management_admin_invoice_approve_api'),
    path('admin-panel/invoices/<int:invoice_id>/reject/', views.admin_invoice_reject_api, name='management_admin_invoice_reject_api'),
    path('admin-panel/weekly-reviews/<int:review_id>/decide/', views.admin_weekly_review_decide_api, name='management_admin_weekly_review_decide_api'),
    path('admin-panel/payouts/api/settings/save/', views.admin_payout_settings_save_api, name='management_admin_payout_settings_save_api'),
    path('admin-panel/payouts/api/request/<int:request_id>/approve/', views.admin_payout_approve_api, name='management_admin_payout_approve_api'),
    path('admin-panel/payouts/api/request/<int:request_id>/reject/', views.admin_payout_reject_api, name='management_admin_payout_reject_api'),
    path('admin-panel/payouts/api/request/<int:request_id>/paid/', views.admin_payout_paid_api, name='management_admin_payout_paid_api'),
    path('admin-panel/payouts/api/manual/', views.admin_payout_manual_create_api, name='management_admin_payout_manual_create_api'),
    path('admin-panel/payouts/api/adjust/', views.admin_payout_adjust_api, name='management_admin_payout_adjust_api'),
    path('admin-panel/payouts-board/', views.admin_payouts_board, name='management_admin_payouts_board'),
    path('reports/', views.reports, name='management_reports'),
    path('reports/send/', views.send_report, name='management_send_report'),
    path('reminders/read/', views.reminder_read, name='management_reminder_read'),
    path('reminders/feed/', views.reminder_feed, name='management_reminder_feed'),
    path('notifications/read/', views.notification_read, name='management_notification_read'),
    path('profile/update/', views.profile_update, name='management_profile_update'),
    path('profile/bind-code/', views.profile_bind_code, name='management_profile_bind_code'),
    path('profile/bind-status/', views.profile_bind_status, name='management_profile_bind_status'),
    path('profile/reset-manager-bot/', views.profile_reset_manager_bot, name='management_profile_reset_manager_bot'),
    path('tg-manager/webhook/<str:token>/', views.management_bot_webhook, name='management_bot_webhook'),
    # Instagram bot webhook (тестова фаза) — публічний, без логіну, CSRF-exempt.
    path('bot/webhook/', bot_webhook.ig_webhook, name='management_ig_bot_webhook'),
    # Instagram bot — панель керування (тільки адміністратори).
    path('bot/', bot_views.bot_dashboard, name='management_bot'),
    path('bot/api/start/', bot_views.bot_start_api, name='management_bot_start_api'),
    path('bot/api/stop/', bot_views.bot_stop_api, name='management_bot_stop_api'),
    path('bot/api/status/', bot_views.bot_status_api, name='management_bot_status_api'),
    path('bot/api/settings/', bot_views.bot_settings_save_api, name='management_bot_settings_api'),
    path('invoices/', views.invoices, name='management_invoices'),
    path('invoices/api/list/', views.invoices_list_api, name='management_invoices_list_api'),
    path('invoices/api/generate/', views.invoices_generate_api, name='management_invoices_generate_api'),
    path('invoices/<int:invoice_id>/download/', views.invoices_download, name='management_invoices_download'),
    path('invoices/api/<int:invoice_id>/delete/', views.invoices_delete_api, name='management_invoices_delete_api'),
    path('invoices/api/<int:invoice_id>/submit/', views.invoices_submit_for_review_api, name='management_invoices_submit_for_review_api'),
    path('invoices/api/<int:invoice_id>/create-payment/', views.invoices_create_payment_api, name='management_invoices_create_payment_api'),
    path('invoices/api/<int:invoice_id>/link-copied/', views.invoices_link_copied_api, name='management_invoices_link_copied_api'),
    path('invoices/api/<int:invoice_id>/refresh-status/', views.invoices_refresh_status_api, name='management_invoices_refresh_status_api'),
    path('invoices/payment-return/', views.invoices_payment_return, name='management_invoices_payment_return'),
    path('onboarding/', views.management_onboarding, name='management_onboarding'),
    path('onboarding/consent/', views.management_onboarding_consent_api, name='management_onboarding_consent_api'),
    path('contracts/', views.contracts, name='management_contracts'),
    path('contracts/api/list/', views.contracts_list_api, name='management_contracts_list_api'),
    path('contracts/api/generate/', views.contracts_generate_api, name='management_contracts_generate_api'),
    path('contracts/api/preview/', views.contracts_preview_api, name='management_contracts_preview_api'),
    path('contracts/<int:contract_id>/download/', views.contracts_download, name='management_contracts_download'),
    path('contracts/api/<int:contract_id>/submit/', views.contracts_submit_for_review_api, name='management_contracts_submit_for_review_api'),
    path('commercial-offer/email/', views.commercial_offer_email, name='management_commercial_offer_email'),
    path('commercial-offer/email/preview/', views.commercial_offer_email_preview_api, name='management_commercial_offer_email_preview_api'),
    path('commercial-offer/email/send/', views.commercial_offer_email_send_api, name='management_commercial_offer_email_send_api'),
    path('commercial-offer/email/check/', views.commercial_offer_email_check_api, name='management_commercial_offer_email_check_api'),
    path('commercial-offer/email/unit-defaults/', views.commercial_offer_email_unit_defaults_api, name='management_commercial_offer_email_unit_defaults_api'),
    path('commercial-offer/email/gallery-defaults/', views.commercial_offer_email_gallery_defaults_api, name='management_commercial_offer_email_gallery_defaults_api'),
    path('commercial-offer/email/resolve-product/', views.commercial_offer_email_resolve_product_api, name='management_commercial_offer_email_resolve_product_api'),
    path('commercial-offer/email/log/<int:log_id>/', views.commercial_offer_email_log_detail_api, name='management_commercial_offer_email_log_detail_api'),
    path('commercial-offer/email/resend/<int:log_id>/', views.commercial_offer_email_resend_api, name='management_commercial_offer_email_resend_api'),
    path('commercial-offer/email/send-test/', views.commercial_offer_email_send_test_api, name='management_commercial_offer_email_send_test_api'),
    path('commercial-offer/email/products/', views.commercial_offer_email_products_api, name='management_commercial_offer_email_products_api'),
    path('commercial-offer/email/link-client/', views.commercial_offer_link_client_api, name='management_commercial_offer_link_client'),
    path('commercial-offer/email/client-search/', views.commercial_offer_client_search_api, name='management_commercial_offer_client_search'),
    path('commercial-offer/email/process/', views.commercial_offer_process_api, name='management_commercial_offer_process'),
    path('cp/o/<uuid:track_token>.png', views.cp_track_open, name='management_cp_track_open'),
    path('cp/c/<uuid:track_token>/', views.cp_track_click, name='management_cp_track_click'),
    path('shops/', shop_views.shops, name='management_shops'),
    path('shops/api/save/', shop_views.shops_save_api, name='management_shops_save_api'),
    path('shops/api/detail/<int:shop_id>/', shop_views.shops_detail_api, name='management_shops_detail_api'),
    path('shops/api/contact/add/', shop_views.shops_add_contact_api, name='management_shops_add_contact_api'),
    path('shops/api/next-contact/', shop_views.shops_set_next_contact_api, name='management_shops_set_next_contact_api'),
    path('shops/api/inventory/move/', shop_views.shops_inventory_move_api, name='management_shops_inventory_move_api'),
    path('shops/api/<int:shop_id>/delete/', shop_views.shops_delete_api, name='management_shops_delete_api'),
    path('shops/shipments/<int:shipment_id>/invoice/download/', shop_views.shop_shipment_invoice_download, name='management_shop_shipment_invoice_download'),
    path('shops/<int:shop_id>/contract/download/', shop_views.shop_contract_download, name='management_shop_contract_download'),
    path('stats/', stats_views.stats, name='management_stats'),
    path('stats/admin/', stats_views.stats_admin_list, name='management_stats_admin'),
    path('stats/admin/<int:user_id>/', stats_views.stats_admin_user, name='management_stats_admin_user'),
    path('stats/advice/dismiss/', stats_views.advice_dismiss, name='management_stats_advice_dismiss'),
    path('stats/mosaic/shadow/', stats_views.shadow_score_json, name='management_stats_shadow_json'),
    path('stats/score/explain/', stats_views.score_explain_json, name='management_stats_explain_json'),
    path('stats/rescue-top/', stats_views.rescue_top_json, name='management_stats_rescue_top_json'),
    path('stats/appeals/create/', stats_views.score_appeal_create, name='management_stats_appeal_create'),
    path('stats/appeals/<int:appeal_id>/resolve/', stats_views.score_appeal_resolve, name='management_stats_appeal_resolve'),
    path('activity/pulse/', stats_views.activity_pulse, name='management_activity_pulse'),
    path('info/', views.info, name='management_info'),
    path('payouts/', views.payouts, name='management_payouts'),
    path('payouts/api/request/', views.payouts_request_api, name='management_payouts_request_api'),
    path('leads/api/create/', lead_views.lead_create_api, name='management_lead_create_api'),
    path('leads/api/<int:lead_id>/detail/', lead_views.lead_detail_api, name='management_lead_detail_api'),
    path('leads/api/<int:lead_id>/process/', lead_views.lead_process_api, name='management_lead_process_api'),
    path('parsing/', parsing_views.parsing_dashboard, name='management_parsing'),
    path('parsing/', parsing_views.parsing_dashboard, name='management_parsing_dashboard'),
    path('parsing/api/start/', parsing_views.parser_start_api, name='management_parser_start_api'),
    path('parsing/api/step/', parsing_views.parser_step_api, name='management_parser_step_api'),
    path('parsing/api/pause/', parsing_views.parser_pause_api, name='management_parser_pause_api'),
    path('parsing/api/resume/', parsing_views.parser_resume_api, name='management_parser_resume_api'),
    path('parsing/api/stop/', parsing_views.parser_stop_api, name='management_parser_stop_api'),
    path('parsing/api/status/', parsing_views.parser_status_api, name='management_parser_status_api'),
    path('parsing/api/moderation/', parsing_views.parser_moderation_api, name='management_parser_moderation_api'),
    path('parsing/api/leads/<int:lead_id>/action/', parsing_views.lead_moderation_action_api, name='management_lead_moderation_action_api'),
    # Manager levels system
    path('profile/', views_levels.manager_profile, name='management_profile'),    path('api/levels/progression/', views_levels.manager_progression_api, name='management_levels_progression_api'),
    path('api/levels/weekly-kpi/', views_levels.manager_weekly_kpi_api, name='management_levels_weekly_kpi_api'),
    path('admin-panel/levels/assign/', views_levels.admin_assign_level_api, name='management_admin_assign_level_api'),
    path('admin-panel/levels/list/', views_levels.admin_managers_list_api, name='management_admin_managers_list_api'),
    # Binotel telephony — тестова пісочниця (тільки адміністратори)
    path('binotel/', binotel_views.binotel_test, name='management_binotel_test'),
    path('binotel/api/status/', binotel_views.binotel_status, name='management_binotel_status'),
    path('binotel/api/employees/', binotel_views.binotel_employees, name='management_binotel_employees'),
    path('binotel/api/voice-files/', binotel_views.binotel_voice_files, name='management_binotel_voice_files'),
    path('binotel/api/call/', binotel_views.binotel_call, name='management_binotel_call'),
    path('binotel/api/hangup/', binotel_views.binotel_hangup, name='management_binotel_hangup'),
    path('binotel/api/call-details/', binotel_views.binotel_call_details, name='management_binotel_call_details'),
    path('binotel/api/call-record/', binotel_views.binotel_call_record, name='management_binotel_call_record'),
    path('binotel/api/online-calls/', binotel_views.binotel_online_calls, name='management_binotel_online_calls'),
    path('binotel/api/calls-period/', binotel_views.binotel_calls_period, name='management_binotel_calls_period'),
    path('binotel/api/customers-search/', binotel_views.binotel_customers_search, name='management_binotel_customers_search'),
    path('binotel/api/raw/', binotel_views.binotel_raw, name='management_binotel_raw'),
    path('binotel/api/webhook-events/', binotel_views.binotel_webhook_events, name='management_binotel_webhook_events'),
    path('binotel/recording/<str:call_id>.mp3', binotel_views.binotel_recording, name='management_binotel_recording'),
    # Єдиний вхідний вебхук Binotel (apiCallSettings + apiCallCompleted).
    # Публічний, CSRF-exempt, без логіну. Опційний токен у шляху.
    path('binotel/webhook/', binotel_webhook.binotel_webhook, name='management_binotel_webhook'),
    path('binotel/webhook/<str:token>/', binotel_webhook.binotel_webhook, name='management_binotel_webhook_token'),
    path('', views.home, name='management_home'),
]
