from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from . import shop_views
from . import stats_views

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(
        template_name='management/login.html',
        redirect_authenticated_user=True
    ), name='management_login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='management_login'), name='management_logout'),
    path('clients/<int:client_id>/delete/', views.delete_client, name='management_delete_client'),
    path('admin-panel/', views.admin_overview, name='management_admin'),
    path('admin-panel/user/<int:user_id>/clients/', views.admin_user_clients, name='management_admin_user_clients'),
    path('admin-panel/invoices/<int:invoice_id>/approve/', views.admin_invoice_approve_api, name='management_admin_invoice_approve_api'),
    path('admin-panel/invoices/<int:invoice_id>/reject/', views.admin_invoice_reject_api, name='management_admin_invoice_reject_api'),
    path('admin-panel/payouts/api/settings/save/', views.admin_payout_settings_save_api, name='management_admin_payout_settings_save_api'),
    path('admin-panel/payouts/api/request/<int:request_id>/approve/', views.admin_payout_approve_api, name='management_admin_payout_approve_api'),
    path('admin-panel/payouts/api/request/<int:request_id>/reject/', views.admin_payout_reject_api, name='management_admin_payout_reject_api'),
    path('admin-panel/payouts/api/request/<int:request_id>/paid/', views.admin_payout_paid_api, name='management_admin_payout_paid_api'),
    path('admin-panel/payouts/api/manual/', views.admin_payout_manual_create_api, name='management_admin_payout_manual_create_api'),
    path('admin-panel/payouts/api/adjust/', views.admin_payout_adjust_api, name='management_admin_payout_adjust_api'),
    path('reports/', views.reports, name='management_reports'),
    path('reports/send/', views.send_report, name='management_send_report'),
    path('reminders/read/', views.reminder_read, name='management_reminder_read'),
    path('reminders/feed/', views.reminder_feed, name='management_reminder_feed'),
    path('profile/update/', views.profile_update, name='management_profile_update'),
    path('profile/bind-code/', views.profile_bind_code, name='management_profile_bind_code'),
    path('tg-manager/webhook/<str:token>/', views.management_bot_webhook, name='management_bot_webhook'),
    path('invoices/', views.invoices, name='management_invoices'),
    path('invoices/api/list/', views.invoices_list_api, name='management_invoices_list_api'),
    path('invoices/api/generate/', views.invoices_generate_api, name='management_invoices_generate_api'),
    path('invoices/<int:invoice_id>/download/', views.invoices_download, name='management_invoices_download'),
    path('invoices/api/<int:invoice_id>/delete/', views.invoices_delete_api, name='management_invoices_delete_api'),
    path('invoices/api/<int:invoice_id>/submit/', views.invoices_submit_for_review_api, name='management_invoices_submit_for_review_api'),
    path('invoices/api/<int:invoice_id>/create-payment/', views.invoices_create_payment_api, name='management_invoices_create_payment_api'),
    path('contracts/', views.contracts, name='management_contracts'),
    path('contracts/api/generate/', views.contracts_generate_api, name='management_contracts_generate_api'),
    path('contracts/api/preview/', views.contracts_preview_api, name='management_contracts_preview_api'),
    path('contracts/<int:contract_id>/download/', views.contracts_download, name='management_contracts_download'),
    path('commercial-offer/email/', views.commercial_offer_email, name='management_commercial_offer_email'),
    path('commercial-offer/email/preview/', views.commercial_offer_email_preview_api, name='management_commercial_offer_email_preview_api'),
    path('commercial-offer/email/send/', views.commercial_offer_email_send_api, name='management_commercial_offer_email_send_api'),
    path('commercial-offer/email/check/', views.commercial_offer_email_check_api, name='management_commercial_offer_email_check_api'),
    path('commercial-offer/email/unit-defaults/', views.commercial_offer_email_unit_defaults_api, name='management_commercial_offer_email_unit_defaults_api'),
    path('commercial-offer/email/gallery-defaults/', views.commercial_offer_email_gallery_defaults_api, name='management_commercial_offer_email_gallery_defaults_api'),
    path('commercial-offer/email/resolve-product/', views.commercial_offer_email_resolve_product_api, name='management_commercial_offer_email_resolve_product_api'),
    path('commercial-offer/email/log/<int:log_id>/', views.commercial_offer_email_log_detail_api, name='management_commercial_offer_email_log_detail_api'),
    path('commercial-offer/email/resend/<int:log_id>/', views.commercial_offer_email_resend_api, name='management_commercial_offer_email_resend_api'),
    path('shops/', shop_views.shops, name='management_shops'),
    path('shops/api/save/', shop_views.shops_save_api, name='management_shops_save_api'),
    path('shops/api/detail/<int:shop_id>/', shop_views.shops_detail_api, name='management_shops_detail_api'),
    path('shops/api/contact/add/', shop_views.shops_add_contact_api, name='management_shops_add_contact_api'),
    path('shops/api/next-contact/', shop_views.shops_set_next_contact_api, name='management_shops_set_next_contact_api'),
    path('shops/api/inventory/move/', shop_views.shops_inventory_move_api, name='management_shops_inventory_move_api'),
    path('shops/api/<int:shop_id>/delete/', shop_views.shops_delete_api, name='management_shops_delete_api'),
    path('shops/shipments/<int:shipment_id>/invoice/download/', shop_views.shop_shipment_invoice_download, name='management_shop_shipment_invoice_download'),
    path('shops/<int:shop_id>/contract/download/', shop_views.shop_contract_download, name='management_shop_contract_download'),
    path('stats/', stats_views.stats, name='management_stats'),
    path('stats/admin/', stats_views.stats_admin_list, name='management_stats_admin'),
    path('stats/admin/<int:user_id>/', stats_views.stats_admin_user, name='management_stats_admin_user'),
    path('stats/advice/dismiss/', stats_views.advice_dismiss, name='management_stats_advice_dismiss'),
    path('activity/pulse/', stats_views.activity_pulse, name='management_activity_pulse'),
    path('info/', views.info, name='management_info'),
    path('payouts/', views.payouts, name='management_payouts'),
    path('payouts/api/request/', views.payouts_request_api, name='management_payouts_request_api'),
    path('', views.home, name='management_home'),
]
