# Generated by Django 5.2.11 on 2026-05-10 17:08

import django.core.validators
import django.db.models.deletion
import reviews.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storefront', '0058_phase21_seed_category_seo_overrides'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text='Відображається на сторінці товару разом із відгуком.', max_length=80, verbose_name="Ім'я для публікації")),
                ('email', models.EmailField(blank=True, help_text="Не публікується. Використовується тільки для зв'язку з модератором.", max_length=254, verbose_name='Email (для модерації)')),
                ('anon_key', models.CharField(blank=True, db_index=True, help_text='Хеш cookie / IP. Дозволяє обмежувати спам гостей.', max_length=64, verbose_name='Anon-ключ')),
                ('rating', models.PositiveSmallIntegerField(help_text='Ціле число 1-5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оцінка')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Заголовок')),
                ('body', models.TextField(help_text='Очікуємо щонайменше 20 символів осмисленого тексту.', verbose_name='Текст відгуку')),
                ('status', models.CharField(choices=[('pending', 'На модерації'), ('approved', 'Опубліковано'), ('rejected', 'Відхилено')], db_index=True, default='pending', max_length=12, verbose_name='Статус')),
                ('moderation_note', models.TextField(blank=True, help_text='Внутрішня — не показується публічно.', verbose_name='Нотатка модератора')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='Час модерації')),
                ('is_verified_purchase', models.BooleanField(default=False, help_text='True, якщо в момент створення відгуку у автора був оплачений заказ із цим товаром.', verbose_name='Перевірена покупка')),
                ('helpful_count', models.PositiveIntegerField(default=0, verbose_name='Корисно')),
                ('unhelpful_count', models.PositiveIntegerField(default=0, verbose_name='Не корисно')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Хто модерував')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='storefront.product', verbose_name='Товар')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=reviews.models._review_image_upload_path, verbose_name='Фото')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reviews.review', verbose_name='Відгук')),
            ],
            options={
                'verbose_name': 'Фото відгуку',
                'verbose_name_plural': 'Фото відгуків',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReviewVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anon_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('value', models.CharField(choices=[('helpful', 'Корисно'), ('unhelpful', 'Не корисно')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='reviews.review', verbose_name='Відгук')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Голос за відгук',
                'verbose_name_plural': 'Голоси за відгуки',
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'status', '-created_at'], name='rev_pdp_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['status', 'product'], name='rev_status_product_idx'),
        ),
        migrations.AddConstraint(
            model_name='reviewvote',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('review', 'user'), name='rev_vote_unique_per_user'),
        ),
        migrations.AddConstraint(
            model_name='reviewvote',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True), models.Q(('anon_key', ''), _negated=True)), fields=('review', 'anon_key'), name='rev_vote_unique_per_anon'),
        ),
        migrations.AddConstraint(
            model_name='reviewvote',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), models.Q(('user__isnull', True), models.Q(('anon_key', ''), _negated=True)), _connector='OR'), name='rev_vote_user_or_anon_required'),
        ),
    ]
