# Generated by Django 5.2.5 on 2025-08-23 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('np_office', models.CharField(blank=True, max_length=200)),
                ('pay_type', models.CharField(blank=True, choices=[('partial', 'Часткова передоплата'), ('full', 'Повна передоплата')], max_length=10)),
                ('is_ubd', models.BooleanField(default=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('ubd_doc', models.ImageField(blank=True, null=True, upload_to='ubd_docs/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
