# Generated by Django 5.2.5 on 2025-08-27 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_full_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='created',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_ubd',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ubd_doc',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pay_type',
            field=models.CharField(choices=[('full', 'Повна оплата'), ('partial', 'Часткова оплата')], default='full', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PointsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_change', models.IntegerField(verbose_name='Зміна балів')),
                ('balance_after', models.PositiveIntegerField(verbose_name='Баланс після зміни')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Причина')),
                ('change_type', models.CharField(choices=[('earned', 'Зароблено'), ('spent', 'Витрачено')], max_length=10, verbose_name='Тип зміни')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Історія балів',
                'verbose_name_plural': 'Історія балів',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Кількість балів')),
                ('total_earned', models.PositiveIntegerField(default=0, verbose_name='Всього зароблено балів')),
                ('total_spent', models.PositiveIntegerField(default=0, verbose_name='Всього витрачено балів')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Бали користувача',
                'verbose_name_plural': 'Бали користувачів',
            },
        ),
    ]
