# Generated by Django 5.2.5 on 2025-08-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_created_remove_userprofile_is_ubd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_ubd',
            field=models.BooleanField(default=False, verbose_name='УБД'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ubd_doc',
            field=models.ImageField(blank=True, null=True, upload_to='ubd_docs/', verbose_name='Фото посвідчення УБД'),
        ),
    ]
