# Generated by Django 5.2.6 on 2025-09-10 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_favoriteproduct'),
        ('accounts', '0008_userprofile_telegram_id'),
    ]

    operations = [
    ]
