# Generated by Django 5.2.6 on 2025-10-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20250910_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Назва компанії/ФОП/ПІБ'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='delivery_address',
            field=models.TextField(blank=True, verbose_name='Адреса доставки'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на магазин'),
        ),
    ]
