# Generated by Django 5.2.6 on 2025-10-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер компанії/ЄДРПОУ/ІПН'),
        ),
    ]
