# Generated by Django 5.2.6 on 2025-10-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofile_company_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='payment_details',
            field=models.TextField(blank=True, verbose_name='Реквізити для виплат'),
        ),
    ]
