# Generated by Django 5.2.6 on 2025-11-18 23:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_userprofile_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['telegram_id'], name='idx_userprofile_telegram'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['phone'], name='idx_userprofile_phone'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user', 'is_ubd'], name='idx_userprofile_user_ubd'),
        ),
    ]
