# Generated by Django 5.2.6 on 2025-12-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_userprofile_is_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='manager_base_salary_uah',
            field=models.PositiveIntegerField(default=0, verbose_name='Ставка (грн)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='manager_commission_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Відсоток з продажів'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='manager_position',
            field=models.CharField(blank=True, max_length=120, verbose_name='Посада/статус'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='manager_started_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата початку роботи'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tg_manager_bind_code',
            field=models.CharField(blank=True, max_length=64, verbose_name='Код привʼязки менеджмент-бота'),
        ),
    ]
