# Generated by Django 5.2.11 on 2026-04-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_userprofile_np_refs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='push_marketing_enabled',
            field=models.BooleanField(default=True, verbose_name='Маркетингові push-сповіщення'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='push_order_updates_enabled',
            field=models.BooleanField(default=True, verbose_name='Push-статуси замовлень'),
        ),
    ]
