# Generated by Django 5.2.11 on 2026-05-16 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_userprofile_push_marketing_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_data', models.JSONField(blank=True, default=dict, help_text='Snapshot of request.session["cart"]', verbose_name='Кошик (звичайні товари)')),
                ('custom_cart_data', models.JSONField(blank=True, default=dict, help_text='Snapshot of request.session["custom_print_cart"]', verbose_name='Кастомний кошик')),
                ('promo_code_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Активний промокод')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='persistent_cart', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Постійний кошик',
                'verbose_name_plural': 'Постійні кошики',
            },
        ),
    ]
