# Generated by Django 5.2.11 on 2026-05-17 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_usercart'),
        ('storefront', '0066_customprintlead_telegram_verified_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramVerificationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Токен сесії')),
                ('purpose', models.CharField(choices=[('custom_print', 'Контакт у формі кастомного принта'), ('profile_link', 'Привʼязка профілю')], default='custom_print', max_length=32, verbose_name='Призначення')),
                ('status', models.CharField(choices=[('pending', 'Очікує підтвердження'), ('bot_opened', 'Користувач відкрив бота'), ('verified', 'Підтверджено'), ('expired', 'Прострочено'), ('cancelled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус')),
                ('session_key', models.CharField(blank=True, default='', max_length=64, verbose_name='Ключ сесії браузера')),
                ('initial_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Імʼя клієнта на момент створення')),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram user_id')),
                ('telegram_username', models.CharField(blank=True, default='', max_length=100, verbose_name='Telegram username')),
                ('telegram_first_name', models.CharField(blank=True, default='', max_length=120, verbose_name='Імʼя у Telegram')),
                ('telegram_last_name', models.CharField(blank=True, default='', max_length=120, verbose_name='Прізвище у Telegram')),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='Телефон, отриманий з Telegram')),
                ('chat_id', models.BigIntegerField(blank=True, null=True, verbose_name='chat_id у боті')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(verbose_name='Діє до')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Підтверджено о')),
                ('last_polled_at', models.DateTimeField(blank=True, null=True, verbose_name='Останній полл')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_verifications', to='storefront.customprintlead', verbose_name='Заявка на кастомний принт')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_verification_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Користувач (якщо авторизований)')),
            ],
            options={
                'verbose_name': 'Сесія верифікації Telegram',
                'verbose_name_plural': 'Сесії верифікації Telegram',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'expires_at'], name='idx_tgverify_status'), models.Index(fields=['session_key'], name='idx_tgverify_session')],
            },
        ),
    ]
