# Generated by Django 5.2.11 on 2026-06-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_telegram_verification_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='access_status',
            field=models.CharField(choices=[('active', 'Активний'), ('blocked_until_document', 'Заблоковано до підпису документа'), ('suspended', 'Призупинено'), ('archived', 'Архів')], db_index=True, default='active', max_length=32, verbose_name='Статус доступу менеджера'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cooperation_started_at',
            field=models.DateField(blank=True, null=True, verbose_name='Початок співпраці'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_required_version',
            field=models.CharField(blank=True, max_length=32, verbose_name='Необхідна версія правил для підпису'),
        ),
    ]
