# Generated by Django 5.2.11 on 2026-06-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_userprofile_access_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='binotel_internal_number',
            field=models.CharField(blank=True, max_length=32, verbose_name='Лінія Binotel (internalNumber)'),
        ),
    ]
