# Generated by Django 5.2.5 on 2025-08-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_color_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'В обробці'), ('prep', 'Готується до відправлення'), ('ship', 'Відправлено'), ('done', 'Отримано'), ('cancelled', 'Скасовано')], default='new', max_length=10),
        ),
    ]
