# Generated by Django 5.2.5 on 2025-08-27 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        # Сначала добавляем поле order_number без unique
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=20, blank=True, null=True),
        ),
        # Изменяем поле user чтобы разрешить null
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='auth.user'),
        ),
        # Генерируем номера заказов для существующих записей
        migrations.RunPython(
            code=lambda apps, schema_editor: None,  # Будет выполнено в post_migrate
            reverse_code=lambda apps, schema_editor: None,
        ),
    ]
