# Generated by Django 5.2.5 on 2025-08-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20250827_1709'),
    ]

    operations = [
        # Добавляем unique constraint для order_number
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=20, unique=True, blank=True),
        ),
    ]
