# Generated by Django 5.2.5 on 2025-08-27 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_options_rename_created_at_order_created_and_more'),
        ('storefront', '0006_alter_promocode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сума знижки'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storefront.promocode', verbose_name='Використаний промокод'),
        ),
    ]
