# Generated by Django 5.2.5 on 2025-08-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_discount_amount_order_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='points_awarded',
            field=models.BooleanField(default=False, verbose_name='Бали нараховані'),
        ),
    ]
