# Generated by Django 5.2.5 on 2025-08-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_points_awarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер ТТН'),
        ),
    ]
