# Generated by Django 5.2.5 on 2025-08-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Не оплачено'), ('partial', 'Внесена передплата'), ('paid', 'Оплачено')], default='unpaid', max_length=10),
        ),
    ]
