# Generated by Django 5.2.5 on 2025-08-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Не оплачено'), ('checking', 'На перевірці'), ('partial', 'Внесена передплата'), ('paid', 'Оплачено повністю')], default='unpaid', max_length=20),
        ),
    ]
