# Generated by Django 5.2.6 on 2025-10-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_payment_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholesaleInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True, verbose_name='Номер накладної')),
                ('company_name', models.CharField(max_length=200, verbose_name='Назва компанії/ФОП/ПІБ')),
                ('contact_phone', models.CharField(max_length=32, verbose_name='Номер телефону')),
                ('delivery_address', models.TextField(verbose_name='Адреса доставки')),
                ('store_link', models.URLField(blank=True, null=True, verbose_name='Посилання на магазин')),
                ('total_tshirts', models.IntegerField(default=0, verbose_name='Кількість футболок')),
                ('total_hoodies', models.IntegerField(default=0, verbose_name='Кількість худі')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Загальна сума')),
                ('status', models.CharField(choices=[('pending', 'Очікує обробки'), ('approved', 'Підтверджено'), ('processing', 'В обробці'), ('shipped', 'Відправлено'), ('delivered', 'Доставлено'), ('cancelled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('order_details', models.JSONField(verbose_name='Деталі замовлення')),
            ],
            options={
                'verbose_name': 'Оптова накладна',
                'verbose_name_plural': 'Оптові накладні',
                'ordering': ['-created_at'],
            },
        ),
    ]
