# Generated by Django 5.2.6 on 2025-10-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_wholesaleinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesaleinvoice',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Шлях до файлу'),
        ),
    ]
