# Generated by Django 5.2.6 on 2025-10-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_wholesaleinvoice_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wholesaleinvoice',
            name='user',
        ),
        migrations.AddField(
            model_name='wholesaleinvoice',
            name='company_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер компанії/ЄДРПОУ/ІПН'),
        ),
    ]
