# Generated by Django 5.2.6 on 2025-10-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_remove_wholesaleinvoice_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesaleinvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Чернетка'), ('pending', 'Очікує перевірки'), ('processing', 'Прийнято в обробку'), ('shipped', 'Готується до відправки'), ('delivered', 'Товари відправлені'), ('cancelled', 'Скасовано')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
