# Generated by Django 5.2.6 on 2025-10-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_alter_wholesaleinvoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesaleinvoice',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Одобрена для оплаты'),
        ),
    ]
