# Generated by Django 5.2.6 on 2025-10-17 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_wholesaleinvoice_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesaleinvoice',
            name='payment_status',
            field=models.CharField(choices=[('not_paid', 'Не оплачена'), ('paid', 'Оплачена'), ('pending', 'Ожидает оплаты'), ('failed', 'Ошибка оплаты')], default='not_paid', max_length=20, verbose_name='Статус оплаты'),
        ),
    ]
