# Generated by Django 5.2.6 on 2025-10-17 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_wholesaleinvoice_payment_status'),
        ('productcolors', '0002_add_alt_text_field'),
        ('storefront', '0026_product_drop_price_product_recommended_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DropshipperOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='ПІБ клієнта')),
                ('client_phone', models.CharField(max_length=32, verbose_name='Телефон клієнта')),
                ('client_np_address', models.CharField(max_length=500, verbose_name='Адреса НП клієнта')),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Номер замовлення')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('pending', 'Очікує підтвердження'), ('confirmed', 'Підтверджено'), ('processing', 'В обробці'), ('shipped', 'Відправлено'), ('delivered', 'Доставлено'), ('cancelled', 'Скасовано')], default='draft', max_length=20, verbose_name='Статус')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Не оплачено'), ('paid', 'Оплачено'), ('refunded', 'Повернено')], default='unpaid', max_length=20, verbose_name='Статус оплати')),
                ('total_drop_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Загальна ціна дропа')),
                ('total_selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Загальна ціна продажу')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Прибуток')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примітки')),
                ('tracking_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер ТТН')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('dropshipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropshipper_orders', to=settings.AUTH_USER_MODEL, verbose_name='Дропшипер')),
            ],
            options={
                'verbose_name': 'Замовлення дропшипера',
                'verbose_name_plural': 'Замовлення дропшиперів',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DropshipperOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=16, verbose_name='Розмір')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('drop_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна дропа')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна продажу')),
                ('recommended_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Рекомендована ціна')),
                ('total_drop_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Загальна ціна дропа')),
                ('total_selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Загальна ціна продажу')),
                ('item_profit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Прибуток з товару')),
                ('color_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productcolors.productcolorvariant', verbose_name='Колір')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.dropshipperorder', verbose_name='Замовлення')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storefront.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в замовленні дропшипера',
                'verbose_name_plural': 'Товари в замовленнях дропшиперів',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DropshipperPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Номер виплати')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума виплати')),
                ('status', models.CharField(choices=[('pending', 'Очікує виплати'), ('processing', 'В обробці'), ('completed', 'Виплачено'), ('cancelled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус')),
                ('payment_method', models.CharField(choices=[('card', 'На картку'), ('bank', 'Банківський переказ'), ('cash', 'Готівка'), ('crypto', 'Криптовалюта')], max_length=20, verbose_name='Спосіб виплати')),
                ('payment_details', models.CharField(max_length=500, verbose_name='Деталі виплати (номер картки/рахунку)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примітки')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата запиту')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обробки')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата виплати')),
                ('dropshipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropshipper_payouts', to=settings.AUTH_USER_MODEL, verbose_name='Дропшипер')),
                ('included_orders', models.ManyToManyField(related_name='payouts', to='orders.dropshipperorder', verbose_name='Включені замовлення')),
            ],
            options={
                'verbose_name': 'Виплата дропшипера',
                'verbose_name_plural': 'Виплати дропшиперів',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='DropshipperStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='Всього замовлень')),
                ('completed_orders', models.PositiveIntegerField(default=0, verbose_name='Виконаних замовлень')),
                ('cancelled_orders', models.PositiveIntegerField(default=0, verbose_name='Скасованих замовлень')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Загальний дохід')),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Загальний прибуток')),
                ('total_drop_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Загальна собівартість')),
                ('total_items_sold', models.PositiveIntegerField(default=0, verbose_name='Всього товарів продано')),
                ('last_order_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата останнього замовлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('dropshipper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dropshipper_stats', to=settings.AUTH_USER_MODEL, verbose_name='Дропшипер')),
            ],
            options={
                'verbose_name': 'Статистика дропшипера',
                'verbose_name_plural': 'Статистика дропшиперів',
            },
        ),
    ]
