# Generated by Django 5.2.6 on 2025-10-20 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_dropshipperorder_dropshipperorderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropshipperorder',
            name='order_source',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Джерело замовлення'),
        ),
    ]
