# Generated by Django 5.2.6 on 2025-10-21 17:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_dropshipperorder_order_source'),
        ('storefront', '0029_product_idx_product_id_desc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dropshipperorder',
            index=models.Index(fields=['-created_at'], name='dropship_ord_created'),
        ),
        migrations.AddIndex(
            model_name='dropshipperorder',
            index=models.Index(fields=['status', '-created_at'], name='dropship_ord_status'),
        ),
        migrations.AddIndex(
            model_name='dropshipperorder',
            index=models.Index(fields=['payment_status', '-created_at'], name='dropship_ord_payment'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created'], name='idx_order_created_desc'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created'], name='idx_order_status_created'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status', '-created'], name='idx_order_payment_created'),
        ),
    ]
