# Generated by Django 5.2.6 on 2025-10-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_dropshipperorder_dropship_ord_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropshipperorder',
            name='dropshipper_payment_required',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Дропшипер має сплатити'),
        ),
        migrations.AddField(
            model_name='dropshipperorder',
            name='payment_method',
            field=models.CharField(choices=[('prepaid', 'Оплачено (передоплата)'), ('cod', 'Накладний платіж')], default='cod', max_length=20, verbose_name='Спосіб оплати'),
        ),
        migrations.AddField(
            model_name='dropshipperorder',
            name='prepayment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сума передоплати'),
        ),
    ]
