# Generated by Django 5.2.6 on 2025-10-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_dropshipperorder_monobank_invoice_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropshipperorder',
            name='monobank_invoice_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID інвойсу Monobank'),
        ),
    ]
