# Generated by Django 5.2.6 on 2025-11-16 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_update_payment_fields'),
        ('storefront', '0033_useraction_utmsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='utm_campaign',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='UTM Campaign'),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_content',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='UTM Content'),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_medium',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='UTM Medium'),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='storefront.utmsession', verbose_name='UTM Сесія'),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_source',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='UTM Source'),
        ),
        migrations.AddField(
            model_name='order',
            name='utm_term',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='UTM Term'),
        ),
        migrations.AlterField(
            model_name='dropshipperorder',
            name='payment_method',
            field=models.CharField(choices=[('prepaid', 'Товар оплачено'), ('cod', 'Накладний платіж'), ('delegation', 'Повне делегування')], default='cod', max_length=20, verbose_name='Спосіб оплати'),
        ),
        migrations.AlterField(
            model_name='dropshipperpayout',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'На картку'), ('iban', 'IBAN')], max_length=20, null=True, verbose_name='Спосіб виплати'),
        ),
    ]
