# Generated by Django 5.2.6 on 2025-12-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_alter_order_email_alter_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Коментар до скасування'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('out_of_stock', 'Немає товару'), ('no_print', 'Немає принта'), ('fake_number', 'Фейковий номер'), ('no_contact', 'Не виходить на зв’язок'), ('changed_mind', 'Передумав'), ('prepayment_refused', 'Не влаштувала передоплата'), ('other', 'Інше')], max_length=50, null=True, verbose_name='Причина скасування'),
        ),
    ]
