# Generated by Django 5.2.6 on 2025-12-13 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_order_cancellation_comment_order_cancellation_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesaleinvoice',
            name='admin_tg_chat_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Telegram admin chat id'),
        ),
        migrations.AddField(
            model_name='wholesaleinvoice',
            name='admin_tg_message_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Telegram admin message id'),
        ),
        migrations.AddField(
            model_name='wholesaleinvoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wholesale_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Створив (менеджер)'),
        ),
        migrations.AddField(
            model_name='wholesaleinvoice',
            name='monobank_invoice_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Monobank invoiceId'),
        ),
        migrations.AddField(
            model_name='wholesaleinvoice',
            name='payment_url',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на оплату'),
        ),
        migrations.AddField(
            model_name='wholesaleinvoice',
            name='review_reject_reason',
            field=models.TextField(blank=True, verbose_name='Причина відхилення'),
        ),
        migrations.AddField(
            model_name='wholesaleinvoice',
            name='review_status',
            field=models.CharField(choices=[('draft', 'Чернетка'), ('pending', 'На перевірці'), ('approved', 'Підтверджено'), ('rejected', 'Відхилено')], default='draft', max_length=20, verbose_name='Статус перевірки'),
        ),
        migrations.AddField(
            model_name='wholesaleinvoice',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата перевірки'),
        ),
        migrations.AddField(
            model_name='wholesaleinvoice',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_wholesale_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Перевірив (адмін)'),
        ),
    ]
