# Generated by Django 5.2.11 on 2026-04-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0042_order_nova_poshta_refs_and_admin_tg_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropshipperorder',
            name='client_np_city_ref',
            field=models.CharField(blank=True, max_length=36, verbose_name='Ref міста НП'),
        ),
        migrations.AddField(
            model_name='dropshipperorder',
            name='client_np_settlement_ref',
            field=models.CharField(blank=True, max_length=36, verbose_name='Ref населеного пункту НП'),
        ),
        migrations.AddField(
            model_name='dropshipperorder',
            name='client_np_warehouse_ref',
            field=models.CharField(blank=True, max_length=36, verbose_name='Ref відділення НП'),
        ),
    ]
