# Generated by Django 5.2.11 on 2026-06-03 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0044_orderitem_fit_options'),
        ('storefront', '0075_backfill_structured_blog_category_translations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Створив (адмін)'),
        ),
        migrations.AddField(
            model_name='order',
            name='manager_comment',
            field=models.TextField(blank=True, default='', verbose_name='Коментар менеджера'),
        ),
        migrations.AddField(
            model_name='order',
            name='sale_source',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Джерело продажу (звідки клієнт)'),
        ),
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('web', 'Сайт'), ('manual', 'Створено вручну')], db_index=True, default='web', max_length=10, verbose_name='Джерело замовлення (спосіб створення)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='color_name_custom',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Колір (для позиції поза каталогом)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_custom',
            field=models.BooleanField(default=False, verbose_name='Позиція поза каталогом'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='storefront.product'),
        ),
    ]
