# Generated by Django 5.2.11 on 2026-06-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0045_manual_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesaleinvoice',
            name='monobank_reference',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Monobank reference (MGMT-INV-{id})'),
        ),
        migrations.AddField(
            model_name='wholesaleinvoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Оплачено'),
        ),
        migrations.AddField(
            model_name='wholesaleinvoice',
            name='payment_amount_minor',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Фактично оплачено (копійки)'),
        ),
        migrations.AddField(
            model_name='wholesaleinvoice',
            name='payment_link_copied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Посилання скопійовано'),
        ),
        migrations.AddField(
            model_name='wholesaleinvoice',
            name='payment_link_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Посилання створено'),
        ),
        migrations.AddField(
            model_name='wholesaleinvoice',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сума повернення'),
        ),
        migrations.AddField(
            model_name='wholesaleinvoice',
            name='refund_reason',
            field=models.TextField(blank=True, verbose_name='Причина повернення'),
        ),
        migrations.AddField(
            model_name='wholesaleinvoice',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Повернення оформлено'),
        ),
        migrations.AddField(
            model_name='wholesaleinvoice',
            name='units_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Кількість одиниць'),
        ),
        migrations.AlterField(
            model_name='wholesaleinvoice',
            name='payment_status',
            field=models.CharField(choices=[('not_paid', 'Не оплачена'), ('paid', 'Оплачена'), ('pending', 'Ожидает оплаты'), ('failed', 'Ошибка оплаты'), ('refunded', 'Повернено')], default='not_paid', max_length=20, verbose_name='Статус оплаты'),
        ),
    ]
