# Generated by Django 6.1 on 2026-08-17 03:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0054_order_tracking_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSideEffectJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=180, unique=True)),
                ('kind', models.CharField(choices=[('attempt_add_payment_info', 'Meta AddPaymentInfo'), ('attempt_telegram_started', 'Telegram: спроба оплати'), ('order_post_payment', 'Події після оплати')], max_length=40)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('state', models.CharField(choices=[('pending', 'Очікує'), ('processing', 'Обробляється'), ('done', 'Завершено'), ('failed', 'Помилка'), ('ambiguous', 'Результат невідомий')], default='pending', max_length=16)),
                ('due_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('lease_token', models.CharField(blank=True, default='', max_length=64)),
                ('lease_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('provider_io_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='side_effect_jobs', to='orders.order')),
                ('payment_attempt', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='side_effect_jobs', to='orders.paymentattempt')),
            ],
            options={
                'ordering': ['due_at', 'id'],
                'indexes': [models.Index(fields=['state', 'due_at', 'id'], name='payment_job_due'), models.Index(fields=['lease_expires_at', 'id'], name='payment_job_lease')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('order__isnull', True), ('payment_attempt__isnull', False)), models.Q(('order__isnull', False), ('payment_attempt__isnull', True)), _connector='OR'), name='payment_job_one_subject')],
            },
        ),
    ]
