"""
Django settings for twocomms project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import warnings
import pymysql

# Настройка PyMySQL для работы с MySQL
pymysql.install_as_MySQLdb()

# Build paths inside the project

# Helper parsers for environment variables
def _env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return str(value).strip().lower() in ('1', 'true', 'yes', 'on')

def _env_list(name, default=''):
    value = os.environ.get(name, default)
    if not value:
        return []
    return [item.strip() for item in value.split(',') if item.strip()]

def _env_int(name, default):
    try:
        return int(os.environ.get(name, default))
    except (TypeError, ValueError):
        return default

def _env_json(name, default=None):
    value = os.environ.get(name)
    if not value:
        return {} if default is None else default
    try:
        import json
        return json.loads(value)
    except Exception:
        return {} if default is None else default
# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production, SECRET_KEY must be set via environment variable
# In development, we provide a fallback for convenience
DEBUG = _env_bool('DEBUG', default=False)

if DEBUG:
    # Development fallback - only used when DEBUG=True
    SECRET_KEY = os.environ.get('SECRET_KEY', 'dev-only-insecure-key-change-in-production')
else:
    # Production - SECRET_KEY must be set
    SECRET_KEY = os.environ.get('SECRET_KEY')
    if not SECRET_KEY:
        raise ValueError(
            "SECRET_KEY environment variable must be set in production! "
            "Generate a secure key with: python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'"
        )

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',') if os.environ.get('ALLOWED_HOSTS') else [
    'test.com',
    'www.test.com',
    'twocomms.shop',
    'www.twocomms.shop',
    'localhost',
    '127.0.0.1',
    'mail.twocomms.shop',  # Added for mail subdomain
    'management.twocomms.shop',
]

# Security settings (только для продакшена)
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'SAMEORIGIN'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
else:
    # Для разработки - менее строгие настройки
    SECURE_BROWSER_XSS_FILTER = False
    SECURE_CONTENT_TYPE_NOSNIFF = False
    X_FRAME_OPTIONS = 'SAMEORIGIN'
    SECURE_HSTS_SECONDS = 0


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",   # ← только один раз!
    "django.contrib.sites",         # Sites framework для redirects
    "django.contrib.sitemaps",      # Sitemap для SEO
    "django.contrib.redirects",     # Редиректы для SEO
    "compressor",                   # Сжатие статических файлов
    # Django REST Framework
    "rest_framework",               # DRF для API
    "drf_spectacular",              # OpenAPI 3 документация
    # Our apps
    "storefront.apps.StorefrontConfig",  # наше приложение из пакета
    "accounts",                     # регистрируем приложение аккаунтов
    "orders.apps.OrdersConfig",     # заказы (корректный AppConfig)
    "productcolors.apps.ProductColorsConfig",  # цветовые варианты товаров
    # Social auth
    "social_django",
    
    # Management Subdomain App
    "management",
]

# Явно переопределим список middleware, чтобы исключить любые лишние строки
MIDDLEWARE = [
    "twocomms.middleware.ForceHTTPSMiddleware",  # Принудительный HTTPS
    "twocomms.middleware.WWWRedirectMiddleware",  # Редирект с www
    "twocomms.middleware.SubdomainURLRoutingMiddleware",  # Subdomain routing (before SecurityMiddleware to handle routing early)
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.gzip.GZipMiddleware",  # Gzip compression for dynamic responses
    "twocomms.middleware.SecurityHeadersMiddleware",  # CSP и дополнительные заголовки
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "twocomms.middleware.SimpleRateLimitMiddleware",  # Rate limiting (ПОСЛЕ статики!)
    "twocomms.image_middleware.ImageOptimizationMiddleware",  # Enabled with caching
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.contrib.redirects.middleware.RedirectFallbackMiddleware",  # SEO редиректы
    "storefront.utm_middleware.UTMTrackingMiddleware",  # UTM tracking (ПЕРЕД SimpleAnalyticsMiddleware!)
    "storefront.tracking.SimpleAnalyticsMiddleware",  # простая аналитика посещений
    "orders.nova_poshta_middleware.NovaPoshtaFallbackMiddleware",  # Резервное обновление статусов НП
]

ROOT_URLCONF = 'twocomms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "twocomms_django_theme" / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'storefront.context_processors.orders_processing_count',
                'storefront.context_processors.analytics_settings',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'twocomms.wsgi.application'

# Sites framework
SITE_ID = 1

# URL для входа в систему
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Социальная аутентификация (Google)
AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.environ.get('GOOGLE_CLIENT_ID', '')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET', '')
SOCIAL_AUTH_REDIRECT_IS_HTTPS = os.environ.get('SOCIAL_AUTH_REDIRECT_IS_HTTPS', 'True').lower() in ('1','true','yes')
SOCIAL_AUTH_URL_NAMESPACE = 'social'
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/'
SOCIAL_AUTH_LOGIN_ERROR_URL = '/login/'

# OpenAI API key from environment
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY') or os.environ.get('OPEN_API_KEY', '')
# Default OpenAI model for AI-assisted SEO keyword generation
OPENAI_MODEL = os.environ.get('OPENAI_MODEL', 'gpt-4o')
# Whether to use AI-generated keywords in addition to rule-based keywords
USE_AI_KEYWORDS = os.environ.get('USE_AI_KEYWORDS', 'False').lower() in ('1','true','yes')
# Whether to use AI-generated product descriptions in SEO meta (experimental)
USE_AI_DESCRIPTIONS = os.environ.get('USE_AI_DESCRIPTIONS', 'False').lower() in ('1','true','yes')

# TikTok Pixel configuration
TIKTOK_PIXEL_ID = os.environ.get('TIKTOK_PIXEL_ID', 'D43L7DBC77UA61AHLTVG')  # Default fallback if not set

# Monobank acquiring
MONOBANK_TOKEN = os.environ.get('MONOBANK_TOKEN', '')
MONOBANK_API_BASE = os.environ.get('MONOBANK_API_BASE', 'https://api.monobank.ua')
# Optional override for webhook URL; if empty we build from request context
MONOBANK_WEBHOOK_URL = os.environ.get('MONOBANK_WEBHOOK_URL', '')

# Mono Checkout (order-based flow) configuration
MONOBANK_CHECKOUT_DELIVERY_METHODS = _env_list('MONOBANK_CHECKOUT_DELIVERY_METHODS', 'pickup,np_brnm,courier,np_box')
if not MONOBANK_CHECKOUT_DELIVERY_METHODS:
    MONOBANK_CHECKOUT_DELIVERY_METHODS = ['pickup', 'np_brnm', 'courier', 'np_box']

MONOBANK_CHECKOUT_PAYMENT_METHODS = _env_list('MONOBANK_CHECKOUT_PAYMENT_METHODS', 'card,payment_on_delivery')
if not MONOBANK_CHECKOUT_PAYMENT_METHODS:
    MONOBANK_CHECKOUT_PAYMENT_METHODS = ['card']

MONOBANK_CHECKOUT_CALLBACK_URL = os.environ.get('MONOBANK_CHECKOUT_CALLBACK_URL', '')
MONOBANK_CHECKOUT_RETURN_URL = os.environ.get('MONOBANK_CHECKOUT_RETURN_URL', '')
MONOBANK_CHECKOUT_PAYMENTS_NUMBER = _env_int('MONOBANK_CHECKOUT_PAYMENTS_NUMBER', 3)
MONOBANK_CHECKOUT_ACCEPTABLE_AGE = _env_int('MONOBANK_CHECKOUT_ACCEPTABLE_AGE', 18)
MONOBANK_CHECKOUT_DLV_PAY_MERCHANT = _env_bool('MONOBANK_CHECKOUT_DLV_PAY_MERCHANT', False)
MONOBANK_CHECKOUT_HOLD = _env_bool('MONOBANK_CHECKOUT_HOLD', False)
MONOBANK_CHECKOUT_FL_RECALL = _env_bool('MONOBANK_CHECKOUT_FL_RECALL', False)
MONOBANK_CHECKOUT_DESTINATION_TEMPLATE = os.environ.get('MONOBANK_CHECKOUT_DESTINATION_TEMPLATE', 'Оплата замовлення {order_number}')
MONOBANK_CHECKOUT_DEFAULT_DLV_INFO = _env_json('MONOBANK_CHECKOUT_DEFAULT_DLV_INFO', {})

# Redirects for social-auth
SOCIAL_AUTH_NEW_USER_REDIRECT_URL = '/profile/setup/'

# Pipeline для обработки данных из Google
SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'storefront.social_pipeline.require_email',
    'social_core.pipeline.social_auth.associate_by_email',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
    'storefront.social_pipeline.get_avatar_url',
    'storefront.social_pipeline.create_or_update_profile',
)

# Дополнительные настройки для Google OAuth
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    'https://www.googleapis.com/auth/userinfo.email',
    'https://www.googleapis.com/auth/userinfo.profile',
]
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/'
SOCIAL_AUTH_LOGIN_ERROR_URL = '/login/'

# Логирование для отладки social-auth
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
        },
        'app_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(BASE_DIR / 'django.log'),
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 5,
            'encoding': 'utf-8',
            'delay': True,
        },
        'app_error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(BASE_DIR / 'stderr.log'),
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 5,
            'encoding': 'utf-8',
            'delay': True,
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'app_file'],
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
        },
        'django.request': {
            'handlers': ['app_error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'storefront.social_pipeline': {
            'handlers': ['console', 'app_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'social_core': {
            'handlers': ['console', 'app_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'orders.nova_poshta_service': {
            'handlers': ['console', 'app_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'orders.nova_poshta_middleware': {
            'handlers': ['console', 'app_file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database selection by DB_ENGINE env: mysql | postgresql | sqlite (default)
# Ожидаемые переменные окружения: DB_ENGINE, DB_NAME, DB_USER, DB_PASSWORD, DB_HOST, DB_PORT
DB_ENGINE = os.environ.get('DB_ENGINE', '').lower()
DB_NAME = os.environ.get('DB_NAME')
DB_USER = os.environ.get('DB_USER')
DB_PASSWORD = os.environ.get('DB_PASSWORD', '')
DB_HOST = os.environ.get('DB_HOST', 'localhost')
DB_PORT = os.environ.get('DB_PORT')

# Для локальной разработки используем SQLite, для продакшена - MySQL
if DEBUG:
    # Локальная разработка - SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
elif DB_ENGINE.startswith('mysql') and DB_NAME and DB_USER:
    # Продакшен - MySQL
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': DB_NAME,
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST,
            'PORT': DB_PORT or '3306',
            'CONN_MAX_AGE': 60,
            'OPTIONS': {
                'charset': 'utf8mb4',
                'use_unicode': True,
                # 'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }
elif (DB_ENGINE.startswith('post') or (DB_NAME and DB_USER)):
    # Продакшен - PostgreSQL
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': DB_NAME,
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST,
            'PORT': DB_PORT or '5432',
            'CONN_MAX_AGE': 60,
            'OPTIONS': {
                'sslmode': os.environ.get('DB_SSLMODE', 'prefer')
            }
        }
    }
else:
    # Fallback на SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Kiev'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


TEMPLATES[0]["DIRS"] = [BASE_DIR / "twocomms_django_theme" / "templates"]
STATICFILES_DIRS = [
    BASE_DIR / "twocomms_django_theme" / "static",
    BASE_DIR / "static",
]
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Email (SMTP)
# cPanel: mail.twocomms.shop, SSL 465, user cooperation@twocomms.shop
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend" if DEBUG else "django.core.mail.backends.smtp.EmailBackend",
)
EMAIL_HOST = os.environ.get("EMAIL_HOST", "mail.twocomms.shop")
EMAIL_PORT = _env_int("EMAIL_PORT", 465)
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "cooperation@twocomms.shop")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_SSL = _env_bool("EMAIL_USE_SSL", default=True)
EMAIL_USE_TLS = _env_bool("EMAIL_USE_TLS", default=False)
EMAIL_TIMEOUT = _env_int("EMAIL_TIMEOUT", 10)

# Prevent invalid SMTP config
if EMAIL_USE_SSL and EMAIL_USE_TLS:
    EMAIL_USE_TLS = False

DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", f"TwoComms <{EMAIL_HOST_USER}>")
SERVER_EMAIL = os.environ.get("SERVER_EMAIL", EMAIL_HOST_USER)

# Image optimization (middleware is disabled by default to avoid CPU-heavy on-the-fly conversions)
IMAGE_OPTIMIZATION_MIDDLEWARE_ENABLED = _env_bool('IMAGE_OPTIMIZATION_MIDDLEWARE_ENABLED', default=False)
IMAGE_OPTIMIZATION_ALLOW_ON_DEMAND = _env_bool('IMAGE_OPTIMIZATION_ALLOW_ON_DEMAND', default=False)


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ===== КЭШИРОВАНИЕ =====
# Используем Redis для кэширования в продакшене, LocMemCache для разработки
from urllib.parse import urlparse

REDIS_URL = os.environ.get('REDIS_URL', '').strip()
if REDIS_URL:
    # Убираем возможные inline-комментарии/хвосты после пробелов
    REDIS_URL = REDIS_URL.split()[0].split('#')[0].strip()
REDIS_SCHEME = os.environ.get('REDIS_SCHEME', '').strip() or 'redis'
REDIS_HOST = os.environ.get('REDIS_HOST', 'localhost')
REDIS_PORT = os.environ.get('REDIS_PORT', '6379')
REDIS_DB = os.environ.get('REDIS_DB', '0')
REDIS_USERNAME = os.environ.get('REDIS_USERNAME', '').strip() or None
REDIS_PASSWORD = os.environ.get('REDIS_PASSWORD', '').strip()  # Redis password for production
REDIS_KEY_PREFIX = os.environ.get('REDIS_KEY_PREFIX', 'twocomms').strip() or 'twocomms'
REDIS_SOCKET_TIMEOUT = float(os.environ.get('REDIS_SOCKET_TIMEOUT', '5.0'))
REDIS_SOCKET_CONNECT_TIMEOUT = float(os.environ.get('REDIS_SOCKET_CONNECT_TIMEOUT', '5.0'))
REDIS_IGNORE_EXCEPTIONS = os.environ.get('REDIS_IGNORE_EXCEPTIONS', 'true').lower() in ('1', 'true', 'yes')

# Если пришёл полный REDIS_URL — парсим его и переопределяем поля
if REDIS_URL:
    parsed = urlparse(REDIS_URL)
    if parsed.scheme:
        REDIS_SCHEME = parsed.scheme
    REDIS_HOST = parsed.hostname or REDIS_HOST
    REDIS_PORT = parsed.port or REDIS_PORT
    REDIS_DB = parsed.path.lstrip('/') or REDIS_DB
    # Username/password могут быть нужны для Redis Cloud
    REDIS_USERNAME = parsed.username or REDIS_USERNAME
    REDIS_PASSWORD = parsed.password or REDIS_PASSWORD

# Собираем финальную строку подключения
if REDIS_PASSWORD:
    REDIS_DSN = f"{REDIS_SCHEME}://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"
else:
    REDIS_DSN = f"{REDIS_SCHEME}://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"
# Если указан оригинальный REDIS_URL (включая username) — используем его в приоритете
if REDIS_URL:
    REDIS_DSN = REDIS_URL

# Для локальной разработки используем LocMemCache, для продакшена - Redis
if DEBUG:
    # Локальная разработка - LocMemCache
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'twocomms-local',
            'TIMEOUT': 300,
            'OPTIONS': {
                'MAX_ENTRIES': 2000,
                'CULL_FREQUENCY': 3,
            }
        }
    }
else:
    # Продакшен - Redis with optional password authentication
    redis_options = {
        'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        'CONNECTION_POOL_KWARGS': {
            'max_connections': 50,
            'retry_on_timeout': True,
        },
        'SOCKET_CONNECT_TIMEOUT': REDIS_SOCKET_CONNECT_TIMEOUT,
        'SOCKET_TIMEOUT': REDIS_SOCKET_TIMEOUT,
        'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
        'IGNORE_EXCEPTIONS': REDIS_IGNORE_EXCEPTIONS,  # Не падать если Redis недоступен
    }

    # Add credentials if provided
    if REDIS_PASSWORD:
        redis_options['PASSWORD'] = REDIS_PASSWORD
    if REDIS_USERNAME:
        redis_options['USERNAME'] = REDIS_USERNAME

    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_DSN,
            'OPTIONS': redis_options,
            'KEY_PREFIX': REDIS_KEY_PREFIX,
            'TIMEOUT': 300,
        }
    }

# ==================== CELERY CONFIGURATION ====================
CELERY_BROKER_URL = REDIS_DSN
CELERY_RESULT_BACKEND = REDIS_DSN

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
# CELERY_TASK_ALWAYS_EAGER = DEBUG  # Optional: run tasks synchronously in debug mode

# ============================================================================
# SESSION CONFIGURATION (E-COMMERCE BEST PRACTICES)
# ============================================================================

# Session backend (cached_db для производительности и персистентности)
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
SESSION_CACHE_ALIAS = 'default'

# Session cookie lifetime (30 дней для удобства пользователей)
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30  # 30 дней

# Session security settings
SESSION_COOKIE_HTTPONLY = True  # Защита от XSS атак (cookie недоступен для JavaScript)
SESSION_COOKIE_SAMESITE = 'Lax'  # Защита от CSRF атак (cookie не отправляется с других сайтов)
SESSION_COOKIE_SECURE = not DEBUG  # HTTPS только в продакшене

# Session serializer (JSON для безопасности)
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer'

# Session save optimization (не сохранять на каждый запрос, только при изменениях)
SESSION_SAVE_EVERY_REQUEST = False

# Кэширование шаблонов (только для продакшена)
if not DEBUG:
    TEMPLATES[0]['OPTIONS']['loaders'] = [
        ('django.template.loaders.cached.Loader', [
            'django.template.loaders.filesystem.Loader',
            'django.template.loaders.app_directories.Loader',
        ]),
    ]
    TEMPLATES[0]['APP_DIRS'] = False
else:
    # В режиме разработки используем стандартные загрузчики
    TEMPLATES[0]['APP_DIRS'] = True

# ===== НАСТРОЙКИ СЖАТИЯ СТАТИЧЕСКИХ ФАЙЛОВ =====
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
]

def ensure_compress_offline(enabled_flag):
    """
    Проверяем, что для offline-компрессии сгенерирован manifest.
    Если его нет (deploy без python manage.py compress), откатываемся
    на on-the-fly режим, чтобы не получать 500-ые ошибки.
    """
    if not enabled_flag:
        return False
    manifest_path = (STATIC_ROOT / 'CACHE' / 'manifest.json')
    if not manifest_path.exists():
        warnings.warn(
            "COMPRESS_OFFLINE=True, но manifest CACHE/manifest.json не найден. "
            "Запустите 'python manage.py compress' перед деплоем, чтобы включить offline-компрессию.",
            RuntimeWarning
        )
        return False
    return True

COMPRESS_ENABLED = True
COMPRESS_OFFLINE = not DEBUG
COMPRESS_CSS_FILTERS = [
    'compressor.filters.css_default.CssAbsoluteFilter',
    'compressor.filters.cssmin.rCSSMinFilter',
]
COMPRESS_JS_FILTERS = [
    'compressor.filters.jsmin.rJSMinFilter',
]

# Настройки для продакшена
if not DEBUG:
    COMPRESS_CSS_HASHING_METHOD = 'content'
    COMPRESS_JS_HASHING_METHOD = 'content'
    # WhiteNoise: gzip+brotli, агрессивный кэш
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
    WHITENOISE_MAX_AGE = 60*60*24*180  # 180 дней
    WHITENOISE_IMMUTABLE_FILE_TEST = lambda path, url: True

# Переключаемся на on-the-fly режим, если offline bundle ещё не сгенерирован
COMPRESS_OFFLINE = ensure_compress_offline(COMPRESS_OFFLINE)

# ===== НАСТРОЙКИ БЕЗОПАСНОСТИ =====
# Базовые настройки безопасности
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'SAMEORIGIN'
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

_CSP_DEFAULT = (
    "default-src 'self'; "
    # Scripts: GTM, Google Ads, Analytics, Facebook Pixel, TikTok Pixel, Clarity, Facebook CAPI
    "script-src 'self' 'unsafe-inline' 'unsafe-eval' "
    "https://www.googletagmanager.com https://googletagmanager.com https://tagmanager.google.com "
    "https://www.google-analytics.com https://ssl.google-analytics.com https://www.googleadservices.com "
    "https://googleads.g.doubleclick.net https://*.doubleclick.net https://www.gstatic.com "
    "https://connect.facebook.net https://www.facebook.com "
    "https://analytics.tiktok.com https://ads.tiktok.com "
    "https://www.clarity.ms https://scripts.clarity.ms "
    "https://cdnjs.cloudflare.com https://cdn.jsdelivr.net "
    "https://*.amazonaws.com; "
    # Styles
    "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://tagmanager.google.com "
    "https://cdnjs.cloudflare.com https://cdn.jsdelivr.net; "
    # Images: GTM, Google Ads, Analytics, Facebook, TikTok Pixel, Clarity
    "img-src 'self' data: blob: "
    "https://twocomms.shop https://www.twocomms.shop https://*.twocomms.shop https://*.amazonaws.com "
    "https://www.googletagmanager.com https://ssl.gstatic.com https://www.gstatic.com "
    "https://www.google-analytics.com https://ssl.google-analytics.com https://www.google.com "
    "https://googleads.g.doubleclick.net https://*.doubleclick.net https://stats.g.doubleclick.net "
    "https://www.googleadservices.com https://pagead2.googlesyndication.com "
    "https://connect.facebook.net https://www.facebook.com https://facebook.com "
    "https://analytics.tiktok.com https://ads.tiktok.com "
    "https://www.clarity.ms https://scripts.clarity.ms https://c.clarity.ms "
    "https://c.bing.com "
    "https://cdn.jsdelivr.net https://cdnjs.cloudflare.com "
    "https://*.google.com.ua; "
    # Fonts
    "font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com data:; "
    # AJAX/Fetch connections: Enhanced Conversions, Analytics, Facebook CAPI, TikTok Pixel, Server-Side Tagging
    "connect-src 'self' "
    "https://www.google-analytics.com https://ssl.google-analytics.com https://analytics.google.com "
    "https://region1.analytics.google.com https://region1.google-analytics.com "
    "https://www.googletagmanager.com https://googletagmanager.com https://tagmanager.google.com "
    "https://www.googleadservices.com https://googleads.g.doubleclick.net https://*.doubleclick.net "
    "https://www.google.com https://*.google.com "
    "https://www.facebook.com https://connect.facebook.net https://graph.facebook.com https://*.facebook.com "
    "https://analytics.tiktok.com https://ads.tiktok.com "
    "https://www.clarity.ms https://scripts.clarity.ms https://*.clarity.ms "
    "https://fonts.googleapis.com https://fonts.gstatic.com "
    "https://cdnjs.cloudflare.com https://cdn.jsdelivr.net "
    "https://*.run.app https://*.datah04.com "
    "https://*.tiktokw.us; "
    # Frames/iframes: GTM preview, Facebook, TikTok Pixel, Server-Side Tagging
    "frame-src 'self' https://www.googletagmanager.com https://googletagmanager.com "
    "https://td.doubleclick.net https://bid.g.doubleclick.net "
    "https://www.facebook.com https://connect.facebook.net https://web.facebook.com "
    "https://analytics.tiktok.com https://ads.tiktok.com "
    "https://*.run.app; "
    # Other security directives
    "object-src 'none'; "
    "base-uri 'self'; "
    "form-action 'self'; "
    "frame-ancestors 'self'; "
    "upgrade-insecure-requests"
)
CONTENT_SECURITY_POLICY = os.environ.get('CONTENT_SECURITY_POLICY', _CSP_DEFAULT)
X_XSS_PROTECTION = os.environ.get('X_XSS_PROTECTION', '1; mode=block')

# Дополнительные настройки безопасности
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'
SECURE_CROSS_ORIGIN_EMBEDDER_POLICY = 'require-corp'

# Настройки для продакшена
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000  # 1 год
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SECURE_REDIRECT_EXEMPT = []  # Принудительный редирект для всех URL
    # SESSION_COOKIE_SECURE и CSRF_COOKIE_SECURE настроены выше и ниже адаптивно (not DEBUG)
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# CSRF cookie security (адаптивная для локальной разработки и продакшена)
CSRF_COOKIE_SECURE = not DEBUG      # HTTPS только в продакшене

# CSRF настройки
CSRF_TRUSTED_ORIGINS = [
    'http://twocomms.shop',
    'http://www.twocomms.shop',
    'https://twocomms.shop',
    'https://www.twocomms.shop',
    'https://management.twocomms.shop',
    # удалён домен pythonanywhere по требованию
]

# ==================== DJANGO REST FRAMEWORK ====================

REST_FRAMEWORK = {
    # Рендереры
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',  # для браузера
    ],
    
    # Парсеры
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    
    # Аутентификация (Session + Basic для browsable API)
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    
    # Права доступа по умолчанию (read-only для всех)
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    
    # Пагинация
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    
    # Throttling (ограничение запросов)
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',  # Анонимные пользователи: 100 запросов/час
        'user': '1000/hour',  # Аутентифицированные: 1000 запросов/час
    },
    
    # OpenAPI Schema (drf-spectacular)
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# ==================== DRF SPECTACULAR (OpenAPI 3 Documentation) ====================

SPECTACULAR_SETTINGS = {
    'TITLE': 'TwoComms Shop API',
    'DESCRIPTION': 'RESTful API для магазина TwoComms - категории, товары, корзина',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    
    # Схема
    'SCHEMA_PATH_PREFIX': r'/api/',
    'COMPONENT_SPLIT_REQUEST': True,
    
    # UI настройки
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
    },
    
    # Аутентификация в документации
    'SECURITY': [
        {'SessionAuth': []},
        {'BasicAuth': []},
    ],
    
    # Сортировка
    'SORT_OPERATIONS': True,
    'SORT_OPERATION_PARAMETERS': True,
}

# ==================== FACEBOOK CONVERSIONS API ====================

# Facebook Pixel ID (находится в Events Manager)
FACEBOOK_PIXEL_ID = os.environ.get('FACEBOOK_PIXEL_ID', '')

# Facebook Conversions API Access Token
# Получается в Events Manager → Settings → Conversions API → Generate Access Token
FACEBOOK_CONVERSIONS_API_TOKEN = os.environ.get('FACEBOOK_CONVERSIONS_API_TOKEN', '')

# Facebook App ID (опционально, для дополнительной аналитики)
FACEBOOK_APP_ID = os.environ.get('FACEBOOK_APP_ID', '')

# ==================== TIKTOK EVENTS API ====================

# Токен доступа для Events API (получается в TikTok Ads Manager)
TIKTOK_EVENTS_ACCESS_TOKEN = os.environ.get('TIKTOK_EVENTS_ACCESS_TOKEN', '')

# Pixel Code (тот же что и для браузерного пикселя)
TIKTOK_EVENTS_PIXEL_CODE = os.environ.get('TIKTOK_EVENTS_PIXEL_CODE', '')

# Опциональный тестовый код события (для тестов через браузер)
TIKTOK_EVENTS_TEST_EVENT_CODE = os.environ.get('TIKTOK_EVENTS_TEST_EVENT_CODE')

# ==================== GOOGLE TAG MANAGER ====================

# Google Tag Manager Container ID (GTM-XXXXXXX)
GTM_CONTAINER_ID = os.environ.get('GTM_CONTAINER_ID', '')

# ==================== TELEGRAM BOT ====================

# Telegram Bot Token для уведомлений
TELEGRAM_BOT_TOKEN = os.environ.get('TELEGRAM_BOT_TOKEN', '')

# Telegram Chat ID для получения уведомлений о заказах
TELEGRAM_ADMIN_CHAT_ID = os.environ.get('TELEGRAM_ADMIN_CHAT_ID', '')

# ==================== MONOBANK / MONOPAY ====================

# Monobank Token для API
MONOBANK_TOKEN = os.environ.get('MONOBANK_TOKEN', '')

# Monobank Merchant ID для Checkout
MONOBANK_MERCHANT_ID = os.environ.get('MONOBANK_MERCHANT_ID', '')

# Monobank API Base URL
MONOBANK_API_URL = os.environ.get('MONOBANK_API_URL', 'https://api.monobank.ua')

# ==================== NOVA POSHTA ====================

# Nova Poshta API Key
NOVA_POSHTA_API_KEY = os.environ.get('NOVA_POSHTA_API_KEY', '')

# Nova Poshta API URL
NOVA_POSHTA_API_URL = os.environ.get('NOVA_POSHTA_API_URL', 'https://api.novaposhta.ua/v2.0/json/')

# Nova Poshta Auto-Update Interval (minutes)
NOVA_POSHTA_UPDATE_INTERVAL = _env_int('NOVA_POSHTA_UPDATE_INTERVAL', 5)

# Nova Poshta Fallback Middleware (включить/выключить резервное обновление)
NOVA_POSHTA_FALLBACK_ENABLED = _env_bool('NOVA_POSHTA_FALLBACK_ENABLED', True)
