# Generated by Django 5.2.6 on 2025-12-10 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('shop_name', models.CharField(max_length=255, verbose_name='Название магазина/Instagram')),
                ('phone', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО (ПІБ)')),
                ('contact_role', models.CharField(choices=[('owner', 'Управляющий'), ('manager', 'Менеджер'), ('realizer', 'Реализатор'), ('other', 'Другое')], default='manager', max_length=20, verbose_name='Статус человека')),
                ('source', models.CharField(blank=True, max_length=255, verbose_name='Где был взят контакт')),
                ('last_call_result', models.CharField(choices=[('order_placed', 'Оформил заказ'), ('sent_offer_email', 'Отправили КП на емейл'), ('sent_offer_messenger', 'Отправили КП на мессенджеры'), ('wrote_instagram', 'Написали в инстаграм'), ('no_answer', 'Не отвечает'), ('not_interested', 'Не интересует'), ('number_unavailable', 'Номер недоступен'), ('connected_xml', 'Подключил выгрузку XML'), ('thinking', 'Подумает'), ('expensive', 'Дорого'), ('other', 'Другое')], default='no_answer', max_length=50, verbose_name='Итог разговора')),
                ('last_call_result_text', models.TextField(blank=True, verbose_name='Детали итога (если Другое)')),
                ('next_call_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время следующего звонка')),
                ('is_non_conversion', models.BooleanField(default=False, verbose_name='Неконверсионный клиент')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-created_at'],
            },
        ),
    ]
