# Generated by Django 5.2.6 on 2025-12-13 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_client_options_alter_client_call_result_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialOfferEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(db_index=True, max_length=254, verbose_name='Email отримувача')),
                ('recipient_name', models.CharField(blank=True, max_length=255, verbose_name='Імʼя/компанія отримувача')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема листа')),
                ('body_html', models.TextField(blank=True, verbose_name='HTML листа')),
                ('body_text', models.TextField(blank=True, verbose_name='Текст листа')),
                ('show_manager', models.BooleanField(default=True, verbose_name='Показувати менеджера')),
                ('manager_name', models.CharField(blank=True, max_length=255, verbose_name='Імʼя менеджера')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('viber', models.CharField(blank=True, max_length=100, verbose_name='Viber')),
                ('whatsapp', models.CharField(blank=True, max_length=100, verbose_name='WhatsApp')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('status', models.CharField(choices=[('sent', 'Надіслано'), ('failed', 'Помилка')], db_index=True, default='sent', max_length=20)),
                ('error', models.TextField(blank=True, verbose_name='Помилка')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_offer_email_logs', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Відправлена КП (лог)',
                'verbose_name_plural': 'Відправлені КП (лог)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommercialOfferEmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_manager', models.BooleanField(default=True, verbose_name='Показувати менеджера')),
                ('manager_name', models.CharField(blank=True, max_length=255, verbose_name='Імʼя менеджера')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('viber_enabled', models.BooleanField(default=False, verbose_name='Viber увімкнено')),
                ('viber', models.CharField(blank=True, max_length=100, verbose_name='Viber (номер)')),
                ('whatsapp_enabled', models.BooleanField(default=False, verbose_name='WhatsApp увімкнено')),
                ('whatsapp', models.CharField(blank=True, max_length=100, verbose_name='WhatsApp (номер)')),
                ('telegram_enabled', models.BooleanField(default=False, verbose_name='Telegram увімкнено')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram (@username або номер)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_offer_email_settings', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Налаштування КП на e-mail',
                'verbose_name_plural': 'Налаштування КП на e-mail',
            },
        ),
    ]
