# Generated by Codex on 2025-12-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0008_commercial_offer_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="commercialofferemailsettings",
            name="hoodie_entry",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Вхід худі (грн)"),
        ),
        migrations.AddField(
            model_name="commercialofferemailsettings",
            name="hoodie_retail_example",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Роздріб худі (приклад, грн)"),
        ),
        migrations.AddField(
            model_name="commercialofferemailsettings",
            name="mode",
            field=models.CharField(
                choices=[("LIGHT", "Light"), ("VISUAL", "Visual")],
                default="VISUAL",
                max_length=10,
                verbose_name="Режим шаблону",
            ),
        ),
        migrations.AddField(
            model_name="commercialofferemailsettings",
            name="segment_mode",
            field=models.CharField(
                choices=[("NEUTRAL", "Neutral"), ("EDGY", "Edgy")],
                default="NEUTRAL",
                max_length=10,
                verbose_name="Сегмент контенту",
            ),
        ),
        migrations.AddField(
            model_name="commercialofferemailsettings",
            name="subject_custom",
            field=models.CharField(blank=True, max_length=255, verbose_name="Кастомна тема"),
        ),
        migrations.AddField(
            model_name="commercialofferemailsettings",
            name="subject_preset",
            field=models.CharField(
                choices=[
                    ("PRESET_1", "Preset 1"),
                    ("PRESET_2", "Preset 2"),
                    ("PRESET_3", "Preset 3"),
                    ("CUSTOM", "Custom"),
                ],
                default="PRESET_1",
                max_length=20,
                verbose_name="Пресет теми",
            ),
        ),
        migrations.AddField(
            model_name="commercialofferemailsettings",
            name="tee_entry",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Вхід футболка (грн)"),
        ),
        migrations.AddField(
            model_name="commercialofferemailsettings",
            name="tee_retail_example",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Роздріб футболка (приклад, грн)"),
        ),
        migrations.AddField(
            model_name="commercialofferemaillog",
            name="hoodie_entry",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Вхід худі (грн)"),
        ),
        migrations.AddField(
            model_name="commercialofferemaillog",
            name="hoodie_profit",
            field=models.IntegerField(blank=True, null=True, verbose_name="Прибуток худі (приклад, грн)"),
        ),
        migrations.AddField(
            model_name="commercialofferemaillog",
            name="hoodie_retail_example",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Роздріб худі (приклад, грн)"),
        ),
        migrations.AddField(
            model_name="commercialofferemaillog",
            name="mode",
            field=models.CharField(
                choices=[("LIGHT", "Light"), ("VISUAL", "Visual")],
                db_index=True,
                default="VISUAL",
                max_length=10,
                verbose_name="Режим шаблону",
            ),
        ),
        migrations.AddField(
            model_name="commercialofferemaillog",
            name="preheader",
            field=models.CharField(blank=True, max_length=255, verbose_name="Preheader"),
        ),
        migrations.AddField(
            model_name="commercialofferemaillog",
            name="segment_mode",
            field=models.CharField(
                choices=[("NEUTRAL", "Neutral"), ("EDGY", "Edgy")],
                db_index=True,
                default="NEUTRAL",
                max_length=10,
                verbose_name="Сегмент контенту",
            ),
        ),
        migrations.AddField(
            model_name="commercialofferemaillog",
            name="subject_custom",
            field=models.CharField(blank=True, max_length=255, verbose_name="Кастомна тема"),
        ),
        migrations.AddField(
            model_name="commercialofferemaillog",
            name="subject_preset",
            field=models.CharField(
                choices=[
                    ("PRESET_1", "Preset 1"),
                    ("PRESET_2", "Preset 2"),
                    ("PRESET_3", "Preset 3"),
                    ("CUSTOM", "Custom"),
                ],
                default="PRESET_1",
                max_length=20,
                verbose_name="Пресет теми",
            ),
        ),
        migrations.AddField(
            model_name="commercialofferemaillog",
            name="tee_entry",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Вхід футболка (грн)"),
        ),
        migrations.AddField(
            model_name="commercialofferemaillog",
            name="tee_profit",
            field=models.IntegerField(blank=True, null=True, verbose_name="Прибуток футболка (приклад, грн)"),
        ),
        migrations.AddField(
            model_name="commercialofferemaillog",
            name="tee_retail_example",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Роздріб футболка (приклад, грн)"),
        ),
    ]

