# Generated by Django 5.2.6 on 2025-12-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_alter_client_options_alter_client_call_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopshipment',
            name='is_test_batch',
        ),
        migrations.AddField(
            model_name='shop',
            name='test_contract_file',
            field=models.FileField(blank=True, null=True, upload_to='shops/contracts/', verbose_name='Договір (тест)'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Instagram / Instashop'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='prom_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Prom.ua'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='website_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Сайт'),
        ),
    ]
