# Generated by Django 5.2.6 on 2025-12-18 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_remove_shopshipment_is_test_batch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementStatsConfig',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('kpd_weights', models.JSONField(blank=True, default=dict, verbose_name='Ваги КПД')),
                ('advice_thresholds', models.JSONField(blank=True, default=dict, verbose_name='Пороги порад')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Налаштування статистики',
                'verbose_name_plural': 'Налаштування статистики',
            },
        ),
        migrations.CreateModel(
            name='ClientFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Створено')),
                ('due_at', models.DateTimeField(db_index=True, verbose_name='Коли передзвонити')),
                ('due_date', models.DateField(db_index=True, verbose_name='Дата (локальна)')),
                ('status', models.CharField(choices=[('open', 'Відкрито'), ('done', 'Виконано'), ('rescheduled', 'Перенесено'), ('cancelled', 'Скасовано'), ('missed', 'Пропущено')], db_index=True, default='open', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Закрито')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Мета')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='management.client', verbose_name='Клієнт')),
                ('closed_by_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_followups', to='management.report', verbose_name='Закрито звітом')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_client_followups', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Передзвон (клієнт)',
                'verbose_name_plural': 'Передзвони (клієнти)',
                'ordering': ['-due_at', '-id'],
                'indexes': [models.Index(fields=['owner', 'due_date', 'status'], name='mgmt_fu_owner_dt_st'), models.Index(fields=['client', 'status'], name='mgmt_fu_client_st')],
            },
        ),
        migrations.CreateModel(
            name='ManagementDailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата (локальна)')),
                ('active_seconds', models.PositiveIntegerField(default=0, verbose_name='Активний час (сек)')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Остання активність')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_daily_activity', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Активність менеджера (доба)',
                'verbose_name_plural': 'Активність менеджера (доба)',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='mgmt_act_user_dt')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ManagementStatsAdviceDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255, verbose_name='Ключ')),
                ('dismissed_at', models.DateTimeField(auto_now_add=True, verbose_name='Коли приховано')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Діє до')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Мета')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_stats_advice_dismissals', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Прихована порада (статистика)',
                'verbose_name_plural': 'Приховані поради (статистика)',
                'indexes': [models.Index(fields=['user', 'expires_at'], name='mgmt_adv_user_exp')],
                'unique_together': {('user', 'key')},
            },
        ),
    ]
