# Generated by Django 5.2.6 on 2025-12-19 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_managementstatsconfig_clientfollowup_and_more'),
        ('orders', '0041_wholesaleinvoice_admin_tg_chat_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerPayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('request', 'Запит менеджера'), ('manual', 'Ручний запис')], db_index=True, default='request', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сума (грн)')),
                ('status', models.CharField(choices=[('processing', 'В обробці'), ('approved', 'Одобрено'), ('rejected', 'Відхилено'), ('paid', 'Виплачено')], db_index=True, default='processing', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина (якщо відхилено)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('admin_tg_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('admin_tg_message_id', models.BigIntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_payout_requests', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_management_payout_requests', to=settings.AUTH_USER_MODEL, verbose_name='Обробив (адмін)')),
            ],
            options={
                'verbose_name': 'Запит на виплату',
                'verbose_name_plural': 'Запити на виплату',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutRejectionReasonRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_chat_id', models.BigIntegerField(db_index=True)),
                ('prompt_message_id', models.BigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payout_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejection_reason_requests', to='management.managerpayoutrequest')),
            ],
            options={
                'verbose_name': 'Причина відхилення виплати (запит)',
                'verbose_name_plural': 'Причини відхилення виплати (запити)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagerCommissionAccrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='База (грн)')),
                ('percent', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Відсоток')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Нараховано (грн)')),
                ('frozen_until', models.DateTimeField(db_index=True, verbose_name='Заморожено до')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='management_commission_accrual', to='orders.wholesaleinvoice', verbose_name='Накладна')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_commission_accruals', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Нарахування менеджера',
                'verbose_name_plural': 'Нарахування менеджера',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='mgmt_comm_owner_dt'), models.Index(fields=['owner', 'frozen_until'], name='mgmt_comm_owner_frz')],
            },
        ),
        migrations.AddIndex(
            model_name='managerpayoutrequest',
            index=models.Index(fields=['owner', 'status', '-created_at'], name='mgmt_pay_owner_st'),
        ),
        migrations.AddIndex(
            model_name='managerpayoutrequest',
            index=models.Index(fields=['status', '-created_at'], name='mgmt_pay_st_dt'),
        ),
        migrations.AddIndex(
            model_name='payoutrejectionreasonrequest',
            index=models.Index(fields=['admin_chat_id', 'is_active'], name='mgmt_payrej_chat_act'),
        ),
    ]
