# Generated by Django 5.2.11 on 2026-02-21 17:51

import re
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _normalize_phone(raw_phone: str) -> str:
    digits = re.sub(r"\D+", "", raw_phone or "")
    if not digits:
        return ""
    if digits.startswith("380") and len(digits) == 12:
        return f"+{digits}"
    if digits.startswith("0") and len(digits) == 10:
        return f"+38{digits}"
    if len(digits) == 9:
        return f"+380{digits}"
    if raw_phone and str(raw_phone).strip().startswith("+"):
        return f"+{digits}"
    return digits


def fill_normalized_client_phone(apps, schema_editor):
    Client = apps.get_model("management", "Client")
    for client in Client.objects.all().only("id", "phone"):
        normalized = _normalize_phone(client.phone)
        if normalized != (client.phone_normalized or ""):
            Client.objects.filter(id=client.id).update(phone_normalized=normalized)


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_contract_review_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone_normalized',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Нормалізований номер'),
        ),
        migrations.AddField(
            model_name='client',
            name='points_override',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Кастомні бали'),
        ),
        migrations.AddField(
            model_name='client',
            name='website_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='contractrejectionreasonrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contractsequence',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='managementcontract',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='managerpayoutrequest',
            name='status',
            field=models.CharField(choices=[('processing', 'В обробці'), ('approved', 'Схвалено'), ('rejected', 'Відхилено'), ('paid', 'Виплачено')], db_index=True, default='processing', max_length=20),
        ),
        migrations.CreateModel(
            name='LeadParsingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Працює'), ('paused', 'Пауза'), ('stopped', 'Зупинено'), ('completed', 'Завершено'), ('failed', 'Помилка')], db_index=True, default='running', max_length=20)),
                ('keywords_raw', models.TextField(blank=True, verbose_name='Ключові слова (raw)')),
                ('cities_raw', models.TextField(blank=True, verbose_name='Міста (raw)')),
                ('keywords', models.JSONField(blank=True, default=list, verbose_name='Ключові слова')),
                ('cities', models.JSONField(blank=True, default=list, verbose_name='Міста')),
                ('request_limit', models.PositiveIntegerField(default=100, verbose_name='Ліміт запитів')),
                ('request_count', models.PositiveIntegerField(default=0, verbose_name='Виконано запитів')),
                ('current_keyword_index', models.PositiveIntegerField(default=0)),
                ('current_city_index', models.PositiveIntegerField(default=0)),
                ('total_found', models.PositiveIntegerField(default=0)),
                ('no_phone_skipped', models.PositiveIntegerField(default=0)),
                ('duplicate_skipped', models.PositiveIntegerField(default=0)),
                ('added_to_moderation', models.PositiveIntegerField(default=0)),
                ('moved_to_bad', models.PositiveIntegerField(default=0)),
                ('already_rejected_skipped', models.PositiveIntegerField(default=0)),
                ('current_query', models.CharField(blank=True, max_length=500)),
                ('next_page_token', models.CharField(blank=True, max_length=255)),
                ('last_error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_lead_parsing_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
            ],
            options={
                'verbose_name': 'Сесія парсингу лідів',
                'verbose_name_plural': 'Сесії парсингу лідів',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagementLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=255, verbose_name='Назва магазину')),
                ('phone', models.CharField(max_length=50, verbose_name='Номер телефону')),
                ('phone_normalized', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Нормалізований номер')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='ПІБ')),
                ('role', models.CharField(choices=[('supervisor', 'Управляючий'), ('manager', 'Менеджер'), ('realizer', 'Реалізатор'), ('owner', 'Власник'), ('other', 'Інше')], default='other', max_length=50, verbose_name='Статус людини')),
                ('source', models.CharField(blank=True, max_length=255, verbose_name='Де взяли контакт')),
                ('website_url', models.CharField(blank=True, max_length=500, verbose_name='Сайт')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Місто')),
                ('parser_keyword', models.CharField(blank=True, max_length=255, verbose_name='Ключове слово парсера')),
                ('parser_query', models.CharField(blank=True, max_length=500, verbose_name='Пошуковий запит')),
                ('google_place_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Google Place ID')),
                ('google_maps_url', models.CharField(blank=True, max_length=500, verbose_name='Google Maps URL')),
                ('details', models.TextField(blank=True, verbose_name='Деталі')),
                ('comments', models.TextField(blank=True, verbose_name='Коментарі')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Сирі дані')),
                ('status', models.CharField(choices=[('moderation', 'На модерації'), ('base', 'У базі'), ('converted', 'Оброблено'), ('rejected', 'Не підходить')], db_index=True, default='base', max_length=20, verbose_name='Статус')),
                ('lead_source', models.CharField(choices=[('manual', 'Ручне додавання'), ('parser', 'Парсинг')], db_index=True, default='manual', max_length=20, verbose_name='Джерело ліда')),
                ('niche_status', models.CharField(choices=[('niche', 'Нішевий'), ('maybe', 'Під питанням'), ('non_niche', 'Не нішевий')], db_index=True, default='maybe', max_length=20, verbose_name='Нішевість')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина відхилення')),
                ('approved_to_base_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Додано у базу')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_leads_added', to=settings.AUTH_USER_MODEL, verbose_name='Додав')),
                ('converted_client', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_lead', to='management.client', verbose_name='Створений клієнт')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_leads_moderated', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
                ('parser_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_leads', to='management.leadparsingjob', verbose_name='Сесія парсингу')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_leads_processed', to=settings.AUTH_USER_MODEL, verbose_name='Обробив')),
            ],
            options={
                'verbose_name': 'Лід',
                'verbose_name_plural': 'Ліди',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadParsingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=255, verbose_name='Ключове слово')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Місто')),
                ('query', models.CharField(blank=True, max_length=500, verbose_name='Запит')),
                ('place_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Place ID')),
                ('place_name', models.CharField(blank=True, max_length=255, verbose_name='Назва')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('website_url', models.CharField(blank=True, max_length=500, verbose_name='Сайт')),
                ('maps_url', models.CharField(blank=True, max_length=500, verbose_name='Google Maps URL')),
                ('status', models.CharField(choices=[('added', 'Додано до модерації'), ('duplicate', 'Дубль'), ('no_phone', 'Без телефону'), ('rejected', 'Раніше відхилено'), ('error', 'Помилка')], db_index=True, default='added', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Причина')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='management.leadparsingjob', verbose_name='Сесія парсингу')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parser_results', to='management.managementlead', verbose_name='Лід')),
            ],
            options={
                'verbose_name': 'Результат парсингу',
                'verbose_name_plural': 'Результати парсингу',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='leadparsingjob',
            index=models.Index(fields=['status', '-started_at'], name='mgmt_parse_status_dt'),
        ),
        migrations.AddIndex(
            model_name='managementlead',
            index=models.Index(fields=['status', '-created_at'], name='mgmt_lead_status_dt'),
        ),
        migrations.AddIndex(
            model_name='managementlead',
            index=models.Index(fields=['lead_source', '-created_at'], name='mgmt_lead_src_dt'),
        ),
        migrations.AddIndex(
            model_name='managementlead',
            index=models.Index(fields=['city', 'status'], name='mgmt_lead_city_st'),
        ),
        migrations.AddIndex(
            model_name='leadparsingresult',
            index=models.Index(fields=['job', '-created_at'], name='mgmt_parse_res_job_dt'),
        ),
        migrations.AddIndex(
            model_name='leadparsingresult',
            index=models.Index(fields=['status', '-created_at'], name='mgmt_parse_res_st_dt'),
        ),
        migrations.RunPython(fill_normalized_client_phone, migrations.RunPython.noop),
    ]
