# Generated by Django 5.2.11 on 2026-03-14 20:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_client_phone_normalized_client_points_override_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentReadiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=64, unique=True, verbose_name='Компонент')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('shadow', 'Тіньовий режим'), ('dormant', 'Неактивно')], db_index=True, default='shadow', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Нотатки')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Мета')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Готовність компонента',
                'verbose_name_plural': 'Готовність компонентів',
                'ordering': ['component'],
            },
        ),
        migrations.AddField(
            model_name='managementstatsconfig',
            name='defaults_version',
            field=models.CharField(default='2026-03-13', max_length=64, verbose_name='Версія дефолтів'),
        ),
        migrations.AddField(
            model_name='managementstatsconfig',
            name='feature_flags',
            field=models.JSONField(blank=True, default=dict, verbose_name='Feature flags'),
        ),
        migrations.AddField(
            model_name='managementstatsconfig',
            name='formula_defaults',
            field=models.JSONField(blank=True, default=dict, verbose_name='Дефолти формул'),
        ),
        migrations.AddField(
            model_name='managementstatsconfig',
            name='formula_version',
            field=models.CharField(default='mosaic-v1', max_length=64, verbose_name='Версія формули'),
        ),
        migrations.AddField(
            model_name='managementstatsconfig',
            name='payload_version',
            field=models.CharField(default='v1', max_length=32, verbose_name='Версія payload'),
        ),
        migrations.AddField(
            model_name='managementstatsconfig',
            name='rollout_state',
            field=models.CharField(default='shadow', max_length=32, verbose_name='Стан rollout'),
        ),
        migrations.AddField(
            model_name='managementstatsconfig',
            name='snapshot_schema_version',
            field=models.CharField(default='v1', max_length=32, verbose_name='Версія snapshot-схеми'),
        ),
        migrations.CreateModel(
            name='CommandRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_name', models.CharField(db_index=True, max_length=128, verbose_name='Команда')),
                ('run_key', models.CharField(max_length=128, unique=True, verbose_name='Ключ запуску')),
                ('status', models.CharField(choices=[('running', 'Виконується'), ('success', 'Успішно'), ('failed', 'Помилка'), ('partial', 'Частково')], db_index=True, default='running', max_length=20)),
                ('rows_processed', models.PositiveIntegerField(default=0, verbose_name='Оброблено рядків')),
                ('warnings_count', models.PositiveIntegerField(default=0, verbose_name='Попереджень')),
                ('error_excerpt', models.TextField(blank=True, verbose_name='Короткий текст помилки')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Мета')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'Лог запуску команди',
                'verbose_name_plural': 'Логи запуску команд',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['command_name', '-started_at'], name='mgmt_cmd_name_dt'), models.Index(fields=['status', '-started_at'], name='mgmt_cmd_status_dt')],
            },
        ),
        migrations.CreateModel(
            name='NightlyScoreSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True, verbose_name='Локальна дата')),
                ('formula_version', models.CharField(max_length=64, verbose_name='Версія формули')),
                ('defaults_version', models.CharField(max_length=64, verbose_name='Версія дефолтів')),
                ('snapshot_schema_version', models.CharField(max_length=32, verbose_name='Версія snapshot-схеми')),
                ('payload_version', models.CharField(max_length=32, verbose_name='Версія payload')),
                ('kpd_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='KPD')),
                ('mosaic_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='MOSAIC')),
                ('score_confidence', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Рівень довіри')),
                ('working_day_factor', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4, verbose_name='Фактор робочого дня')),
                ('freshness_seconds', models.PositiveIntegerField(default=0, verbose_name='Freshness, сек')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='management.commandrunlog', verbose_name='Лог запуску')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_score_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Нічний snapshot score',
                'verbose_name_plural': 'Нічні snapshot-и score',
                'ordering': ['-snapshot_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ScoreAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Відкрито'), ('approved', 'Підтверджено'), ('rejected', 'Відхилено')], db_index=True, default='open', max_length=20)),
                ('reason', models.TextField(verbose_name='Причина')),
                ('evidence', models.JSONField(blank=True, default=dict, verbose_name='Докази')),
                ('resolution_note', models.TextField(blank=True, verbose_name='Рішення')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_score_appeals', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='management.nightlyscoresnapshot', verbose_name='Snapshot')),
            ],
            options={
                'verbose_name': 'Оскарження score',
                'verbose_name_plural': 'Оскарження score',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagerDayStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True, verbose_name='День')),
                ('status', models.CharField(choices=[('working', 'Робочий день'), ('weekend', 'Вихідний'), ('holiday', 'Свято'), ('vacation', 'Відпустка'), ('sick', 'Лікарняний'), ('excused', 'Погоджена відсутність'), ('tech_failure', 'Технічний збій'), ('force_majeure', 'Форс-мажор')], db_index=True, default='working', max_length=32)),
                ('capacity_factor', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4, verbose_name='Фактор доступності')),
                ('source_reason', models.CharField(blank=True, max_length=255, verbose_name='Причина / джерело')),
                ('reintegration_flag', models.BooleanField(default=False, verbose_name='Період повернення')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Мета')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_day_statuses', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Статус дня менеджера',
                'verbose_name_plural': 'Статуси днів менеджера',
                'ordering': ['-day'],
                'indexes': [models.Index(fields=['owner', '-day'], name='mgmt_day_owner_dt'), models.Index(fields=['status', '-day'], name='mgmt_day_status_dt')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'day'), name='mgmt_day_owner_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='nightlyscoresnapshot',
            index=models.Index(fields=['owner', '-snapshot_date'], name='mgmt_snapshot_owner_dt'),
        ),
        migrations.AddConstraint(
            model_name='nightlyscoresnapshot',
            constraint=models.UniqueConstraint(fields=('owner', 'snapshot_date'), name='mgmt_snapshot_owner_day_unique'),
        ),
        migrations.AddIndex(
            model_name='scoreappeal',
            index=models.Index(fields=['owner', 'status', '-created_at'], name='mgmt_appeal_owner_st'),
        ),
    ]
