# Generated by Django 5.2.11 on 2026-03-14 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_componentreadiness_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_shared_phone',
            field=models.BooleanField(default=False, verbose_name='Спільний номер'),
        ),
        migrations.AddField(
            model_name='client',
            name='normalized_name_display',
            field=models.CharField(blank=True, max_length=255, verbose_name="Нормалізоване ім'я"),
        ),
        migrations.AddField(
            model_name='client',
            name='normalized_name_match_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Ключ збігу імені'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_group_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='ID групи номера'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_last7',
            field=models.CharField(blank=True, db_index=True, max_length=7, verbose_name='Останні 7 цифр'),
        ),
        migrations.AddField(
            model_name='client',
            name='shared_phone_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Причина спільного номера'),
        ),
        migrations.AddField(
            model_name='managementlead',
            name='is_shared_phone',
            field=models.BooleanField(default=False, verbose_name='Спільний номер'),
        ),
        migrations.AddField(
            model_name='managementlead',
            name='normalized_name_display',
            field=models.CharField(blank=True, max_length=255, verbose_name="Нормалізоване ім'я"),
        ),
        migrations.AddField(
            model_name='managementlead',
            name='normalized_name_match_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Ключ збігу імені'),
        ),
        migrations.AddField(
            model_name='managementlead',
            name='phone_group_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='ID групи номера'),
        ),
        migrations.AddField(
            model_name='managementlead',
            name='phone_last7',
            field=models.CharField(blank=True, db_index=True, max_length=7, verbose_name='Останні 7 цифр'),
        ),
        migrations.AddField(
            model_name='managementlead',
            name='shared_phone_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Причина спільного номера'),
        ),
        migrations.CreateModel(
            name='DuplicateReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(db_index=True, max_length=20, verbose_name='Зона')),
                ('incoming_shop_name', models.CharField(max_length=255, verbose_name='Вхідна назва')),
                ('incoming_phone', models.CharField(max_length=50, verbose_name='Вхідний номер')),
                ('incoming_payload', models.JSONField(blank=True, default=dict, verbose_name='Вхідні дані')),
                ('candidate_summary', models.JSONField(blank=True, default=list, verbose_name='Кандидати')),
                ('status', models.CharField(choices=[('open', 'Відкрито'), ('resolved', 'Закрито')], db_index=True, default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_duplicate_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Ініціатор')),
            ],
            options={
                'verbose_name': 'Перевірка дубля',
                'verbose_name_plural': 'Перевірки дублів',
                'ordering': ['-created_at'],
            },
        ),
    ]
