# Generated by Django 5.2.11 on 2026-03-14 20:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_client_is_shared_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=64, verbose_name='Провайдер')),
                ('external_call_id', models.CharField(max_length=255, verbose_name='Зовнішній call ID')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='Телефон')),
                ('direction', models.CharField(choices=[('inbound', 'Вхідний'), ('outbound', 'Вихідний'), ('unknown', 'Невідомо')], db_index=True, default='unknown', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Тривалість, сек')),
                ('recording_url', models.URLField(blank=True, verbose_name='Recording URL')),
                ('transcript_excerpt', models.TextField(blank=True, verbose_name='Уривок транскрипту')),
                ('qa_status', models.CharField(choices=[('pending', 'Очікує QA'), ('reviewed', 'Перевірено'), ('exempt', 'Без QA')], db_index=True, default='pending', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_call_records', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('matched_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_records', to='management.client', verbose_name='Матчений клієнт')),
            ],
            options={
                'verbose_name': 'Запис дзвінка',
                'verbose_name_plural': 'Записи дзвінків',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallQAReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='QA score')),
                ('verdict', models.CharField(choices=[('pass', 'ОК'), ('coaching', 'Потрібен коучинг'), ('fail', 'Провал')], db_index=True, default='pass', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Нотатки')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_qa_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Перевірив')),
                ('call_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_reviews', to='management.callrecord', verbose_name='Дзвінок')),
            ],
            options={
                'verbose_name': 'QA review дзвінка',
                'verbose_name_plural': 'QA reviews дзвінків',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DtfBridgeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(db_index=True, max_length=64, verbose_name='Ключ джерела')),
                ('snapshot_date', models.DateField(db_index=True, verbose_name='Дата snapshot')),
                ('status', models.CharField(choices=[('fresh', 'Актуально'), ('degraded', 'Деградація'), ('stale', 'Застаріло')], db_index=True, default='degraded', max_length=20)),
                ('freshness_seconds', models.PositiveIntegerField(default=0, verbose_name='Freshness, сек')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DTF bridge snapshot',
                'verbose_name_plural': 'DTF bridge snapshots',
                'ordering': ['-snapshot_date', '-id'],
                'indexes': [models.Index(fields=['source_key', '-snapshot_date'], name='mgmt_dtf_source_dt')],
                'constraints': [models.UniqueConstraint(fields=('source_key', 'snapshot_date'), name='mgmt_dtf_source_day_unique')],
            },
        ),
        migrations.CreateModel(
            name='OwnershipChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('client', 'Клієнт'), ('lead', 'Лід'), ('shop', 'Магазин')], db_index=True, max_length=20, verbose_name='Тип сутності')),
                ('entity_id', models.PositiveIntegerField(db_index=True, verbose_name='ID сутності')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Причина')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('new_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_new_ownership_changes', to=settings.AUTH_USER_MODEL, verbose_name='Новий owner')),
                ('previous_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_previous_ownership_changes', to=settings.AUTH_USER_MODEL, verbose_name='Попередній owner')),
            ],
            options={
                'verbose_name': 'Лог зміни ownership',
                'verbose_name_plural': 'Логи зміни ownership',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupervisorActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('coaching', 'Коучинг'), ('escalation', 'Ескалація'), ('freeze_override', 'Override freeze'), ('appeal_resolution', 'Рішення по апеляції')], db_index=True, max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_supervisor_actions', to=settings.AUTH_USER_MODEL, verbose_name='Хто виконав')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_actions', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Лог дії супервайзера',
                'verbose_name_plural': 'Логи дій супервайзера',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelephonyHealthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=64, verbose_name='Провайдер')),
                ('status', models.CharField(choices=[('healthy', 'Здорово'), ('degraded', 'Деградація'), ('outage', 'Недоступно')], db_index=True, default='degraded', max_length=20)),
                ('total_events', models.PositiveIntegerField(default=0, verbose_name='Усього подій')),
                ('unmatched_calls', models.PositiveIntegerField(default=0, verbose_name='Не змечені дзвінки')),
                ('backlog_count', models.PositiveIntegerField(default=0, verbose_name='Backlog')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Meta')),
                ('snapshot_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Health snapshot IP-телефонії',
                'verbose_name_plural': 'Health snapshot-и IP-телефонії',
                'ordering': ['-snapshot_at'],
                'indexes': [models.Index(fields=['provider', '-snapshot_at'], name='mgmt_tel_health_dt')],
            },
        ),
        migrations.CreateModel(
            name='TelephonyWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=64, verbose_name='Провайдер')),
                ('external_event_id', models.CharField(max_length=255, verbose_name='Зовнішній event ID')),
                ('event_type', models.CharField(blank=True, max_length=128, verbose_name='Тип події')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('processed', 'Оброблено'), ('failed', 'Помилка'), ('ignored', 'Пропущено')], db_index=True, default='pending', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('error_excerpt', models.TextField(blank=True, verbose_name='Помилка')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'Webhook IP-телефонії',
                'verbose_name_plural': 'Webhook-и IP-телефонії',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['provider', 'status', '-received_at'], name='mgmt_tel_provider_st')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_event_id'), name='mgmt_tel_event_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='callrecord',
            index=models.Index(fields=['manager', '-created_at'], name='mgmt_call_mgr_dt'),
        ),
        migrations.AddIndex(
            model_name='callrecord',
            index=models.Index(fields=['qa_status', '-created_at'], name='mgmt_call_qa_dt'),
        ),
        migrations.AddConstraint(
            model_name='callrecord',
            constraint=models.UniqueConstraint(fields=('provider', 'external_call_id'), name='mgmt_call_provider_ext_unique'),
        ),
        migrations.AddIndex(
            model_name='ownershipchangelog',
            index=models.Index(fields=['entity_type', 'entity_id', '-created_at'], name='mgmt_ownerchange_ent'),
        ),
        migrations.AddIndex(
            model_name='supervisoractionlog',
            index=models.Index(fields=['action_type', '-created_at'], name='mgmt_supervisor_act'),
        ),
    ]
