# Generated by Django 5.2.11 on 2026-03-14 21:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_callrecord_callqareview_dtfbridgesnapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfollowup',
            name='escalation_level',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Рівень ескалації'),
        ),
        migrations.AddField(
            model_name='clientfollowup',
            name='grace_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Пільгове вікно до'),
        ),
        migrations.AddField(
            model_name='clientfollowup',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Останнє нагадування'),
        ),
        migrations.AddField(
            model_name='managementstatsconfig',
            name='forecast_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Конфіг forecast'),
        ),
        migrations.AddField(
            model_name='managementstatsconfig',
            name='legacy_kpd_formula_version',
            field=models.CharField(default='kpd-v1', max_length=64, verbose_name='Версія legacy КПД'),
        ),
        migrations.AddField(
            model_name='managementstatsconfig',
            name='mosaic_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Конфіг MOSAIC'),
        ),
        migrations.AddField(
            model_name='managementstatsconfig',
            name='payroll_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Конфіг payroll'),
        ),
        migrations.AddField(
            model_name='managementstatsconfig',
            name='shadow_mosaic_formula_version',
            field=models.CharField(default='mosaic-v1', max_length=64, verbose_name='Версія shadow MOSAIC'),
        ),
        migrations.AddField(
            model_name='managementstatsconfig',
            name='telephony_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Конфіг телфонії'),
        ),
        migrations.AddField(
            model_name='managementstatsconfig',
            name='ui_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='UI конфіг'),
        ),
        migrations.AddField(
            model_name='managementstatsconfig',
            name='validation_state',
            field=models.JSONField(blank=True, default=dict, verbose_name='Стан валідації'),
        ),
        migrations.AddField(
            model_name='managercommissionaccrual',
            name='accrual_type',
            field=models.CharField(choices=[('new', 'Новий'), ('repeat', 'Повторний'), ('reactivation', 'Реактивація'), ('rescue_spiff', 'Rescue SPIFF'), ('manual', 'Ручне')], db_index=True, default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='managercommissionaccrual',
            name='evidence_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Payload доказів'),
        ),
        migrations.AddField(
            model_name='managercommissionaccrual',
            name='freeze_reason_code',
            field=models.CharField(blank=True, max_length=64, verbose_name='Код причини заморозки'),
        ),
        migrations.AddField(
            model_name='managercommissionaccrual',
            name='freeze_reason_text',
            field=models.TextField(blank=True, verbose_name='Причина заморозки'),
        ),
        migrations.AddField(
            model_name='managercommissionaccrual',
            name='source_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_accruals', to='management.nightlyscoresnapshot', verbose_name='Source snapshot'),
        ),
        migrations.AddField(
            model_name='managercommissionaccrual',
            name='working_factor_applied',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=5, verbose_name='Working factor'),
        ),
        migrations.AddField(
            model_name='scoreappeal',
            name='appeal_type',
            field=models.CharField(choices=[('score', 'Score'), ('freeze', 'Freeze'), ('ownership', 'Ownership')], db_index=True, default='score', max_length=20),
        ),
        migrations.AddField(
            model_name='scoreappeal',
            name='due_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='scoreappeal',
            name='evidence_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Payload доказів'),
        ),
        migrations.AddField(
            model_name='scoreappeal',
            name='manager_note',
            field=models.TextField(blank=True, verbose_name='Нотатка менеджера'),
        ),
        migrations.AddField(
            model_name='scoreappeal',
            name='opened_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='scoreappeal',
            name='reason_code',
            field=models.CharField(blank=True, max_length=64, verbose_name='Код причини'),
        ),
        migrations.AddField(
            model_name='scoreappeal',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_management_score_appeals', to=settings.AUTH_USER_MODEL, verbose_name='Розглянув'),
        ),
    ]
