# Generated by Django 5.2.11 on 2026-03-15 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_client_call_result_reason_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='duplicatereview',
            name='resolution_note',
            field=models.TextField(blank=True, verbose_name='Нотатка по рішенню'),
        ),
        migrations.AddField(
            model_name='duplicatereview',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_duplicate_reviews_resolved', to=settings.AUTH_USER_MODEL, verbose_name='Закрив'),
        ),
        migrations.CreateModel(
            name='ClientInteractionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('order', 'Оформив замовлення'), ('sent_email', 'Відправили КП на e-mail'), ('sent_messenger', 'Відправили КП у месенджери'), ('wrote_ig', 'Написали в Instagram'), ('no_answer', 'Не відповідає'), ('not_interested', 'Не цікавить'), ('invalid_number', 'Номер недоступний'), ('xml_connected', 'Підключив XML'), ('thinking', 'Подумає'), ('expensive', 'Дорого'), ('waiting_payment', 'Очікується оплата'), ('waiting_prepayment', 'Очікується передоплата'), ('test_batch', 'Замовив тестову партію'), ('other', 'Інше')], db_index=True, max_length=50, verbose_name='Підсумок')),
                ('reason_code', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Код причини')),
                ('reason_note', models.TextField(blank=True, verbose_name='Коментар причини')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='Контекст')),
                ('details', models.TextField(blank=True, verbose_name='Деталі')),
                ('next_call_at', models.DateTimeField(blank=True, null=True, verbose_name='Наступний дзвінок')),
                ('verification_level', models.CharField(choices=[('self_reported', 'Самозвіт'), ('linked_evidence', 'Підтверджено доказом'), ('override', 'З override перевіркою')], db_index=True, default='self_reported', max_length=32, verbose_name='Рівень верифікації')),
                ('duplicate_override_reason', models.TextField(blank=True, verbose_name='Причина override')),
                ('messenger_type', models.CharField(blank=True, max_length=32, verbose_name='Месенджер')),
                ('messenger_target_mode', models.CharField(blank=True, max_length=32, verbose_name='Режим цілі месенджера')),
                ('messenger_target_value', models.CharField(blank=True, max_length=255, verbose_name='Ціль месенджера')),
                ('xml_platform', models.CharField(blank=True, max_length=32, verbose_name='XML платформа')),
                ('xml_resource_url', models.CharField(blank=True, max_length=500, verbose_name='XML ресурс')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_attempts', to='management.client', verbose_name='Клієнт')),
                ('cp_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_interaction_attempts', to='management.commercialofferemaillog', verbose_name='Лог КП')),
                ('duplicate_review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interaction_attempts', to='management.duplicatereview', verbose_name='Перевірка дубля')),
                ('linked_shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_interaction_attempts', to='management.shop', verbose_name="Пов'язаний магазин")),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_client_interactions', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Спроба взаємодії з клієнтом',
                'verbose_name_plural': 'Спроби взаємодії з клієнтами',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientCPLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cp_links', to='management.client', verbose_name='Клієнт')),
                ('cp_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_links', to='management.commercialofferemaillog', verbose_name='Лог КП')),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_client_cp_links', to=settings.AUTH_USER_MODEL, verbose_name="Прив'язав")),
                ('interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cp_links', to='management.clientinteractionattempt', verbose_name='Спроба взаємодії')),
            ],
            options={
                'verbose_name': "Зв'язок клієнта з КП",
                'verbose_name_plural': "Зв'язки клієнтів з КП",
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='clientinteractionattempt',
            index=models.Index(fields=['manager', '-created_at'], name='mgmt_client_attempt_mgr_dt'),
        ),
        migrations.AddIndex(
            model_name='clientinteractionattempt',
            index=models.Index(fields=['client', '-created_at'], name='mgmt_client_attempt_cli_dt'),
        ),
        migrations.AddConstraint(
            model_name='clientcplink',
            constraint=models.UniqueConstraint(fields=('client', 'cp_log'), name='mgmt_client_cp_unique'),
        ),
    ]
