# Generated by Django 5.2.11 on 2026-03-20 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_client_manager_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phase_number',
            field=models.PositiveIntegerField(db_index=True, default=1, verbose_name='Номер фази'),
        ),
        migrations.AddField(
            model_name='client',
            name='phase_root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_family_members', to='management.client', verbose_name='Коренева фаза'),
        ),
        migrations.AddField(
            model_name='client',
            name='previous_phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_phase_members', to='management.client', verbose_name='Попередня фаза'),
        ),
    ]
