# Generated by Django 5.2.11 on 2026-03-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_client_phase_number_client_phase_root_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadparsingjob',
            name='duplicate_existing_client_skipped',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadparsingjob',
            name='duplicate_existing_lead_skipped',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadparsingjob',
            name='duplicate_same_job_phone_skipped',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadparsingjob',
            name='duplicate_same_job_place_skipped',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadparsingjob',
            name='is_step_in_progress',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='leadparsingjob',
            name='last_step_duration_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadparsingjob',
            name='last_step_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadparsingjob',
            name='last_step_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadparsingjob',
            name='next_step_not_before',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='leadparsingjob',
            name='request_error_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Помилок API'),
        ),
        migrations.AddField(
            model_name='leadparsingjob',
            name='request_success_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Успішних API запитів'),
        ),
        migrations.AddField(
            model_name='leadparsingjob',
            name='requests_per_minute',
            field=models.PositiveIntegerField(default=20, verbose_name='Запитів за хвилину'),
        ),
        migrations.AddField(
            model_name='leadparsingjob',
            name='retry_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='leadparsingresult',
            name='reason_code',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Код причини'),
        ),
    ]
