# Generated by Django 5.2.11 on 2026-03-24 19:21

import django.db.models.deletion
from django.db import migrations, models


def _convert_parser_tables_to_innodb(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    tables = [
        "management_leadparsingjob",
        "management_leadparsingresult",
        "management_managementlead",
        "management_client",
        "management_leadparsingruntimelock",
    ]
    with schema_editor.connection.cursor() as cursor:
        for table_name in tables:
            cursor.execute(f"ALTER TABLE `{table_name}` ENGINE=InnoDB")


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('management', '0028_leadparsingjob_duplicate_existing_client_skipped_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadparsingjob',
            name='current_request_spec',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='leadparsingjob',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='leadparsingjob',
            name='history_lookback_days',
            field=models.PositiveIntegerField(default=30, verbose_name='Lookback по історії, днів'),
        ),
        migrations.AddField(
            model_name='leadparsingjob',
            name='recent_history_phone_skipped',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadparsingjob',
            name='recent_history_place_skipped',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadparsingjob',
            name='stop_reason_code',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='leadparsingjob',
            name='next_page_token',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='leadparsingjob',
            name='requests_per_minute',
            field=models.PositiveIntegerField(default=10, verbose_name='Запитів за хвилину'),
        ),
        migrations.CreateModel(
            name='LeadParsingRuntimeLock',
            fields=[
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='management.leadparsingjob', verbose_name='Активна сесія')),
            ],
            options={
                'verbose_name': 'Глобальний lock парсингу',
                'verbose_name_plural': 'Глобальні lock-и парсингу',
            },
        ),
        migrations.RunPython(_convert_parser_tables_to_innodb, migrations.RunPython.noop),
    ]
