# Generated by Django 5.2.11 on 2026-03-26 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_leadparsingjob_included_types_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadParsingQueryState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=255, verbose_name='Ключове слово')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Місто')),
                ('included_type', models.CharField(blank=True, max_length=64, verbose_name='Google Places type')),
                ('text_query', models.CharField(blank=True, max_length=500, verbose_name='Текстовий запит')),
                ('status', models.CharField(choices=[('active', 'Активний'), ('exhausted', 'Вичерпано'), ('anomaly', 'Аномалія')], db_index=True, default='active', max_length=20)),
                ('pages_fetched', models.PositiveIntegerField(default=0)),
                ('api_requests_sent', models.PositiveIntegerField(default=0)),
                ('places_seen_count', models.PositiveIntegerField(default=0)),
                ('places_added_count', models.PositiveIntegerField(default=0)),
                ('consecutive_empty_pages', models.PositiveIntegerField(default=0)),
                ('consecutive_repeated_pages', models.PositiveIntegerField(default=0)),
                ('last_next_page_token_hash', models.CharField(blank=True, max_length=64)),
                ('seen_page_fingerprints', models.JSONField(blank=True, default=list)),
                ('exhausted_reason_code', models.CharField(blank=True, db_index=True, max_length=64)),
                ('exhausted_message', models.CharField(blank=True, max_length=255)),
                ('last_progress_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Стан query парсингу',
                'verbose_name_plural': 'Стани query парсингу',
            },
        ),
        migrations.AddField(
            model_name='leadparsingjob',
            name='queries_exhausted_anomaly',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadparsingjob',
            name='queries_exhausted_normal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadparsingjob',
            name='target_leads_limit',
            field=models.PositiveIntegerField(default=0, verbose_name='Ціль по лідах'),
        ),
        migrations.AlterField(
            model_name='leadparsingresult',
            name='status',
            field=models.CharField(choices=[('added', 'Додано до модерації'), ('added_no_phone', 'Додано до модерації без телефону'), ('notice', 'Службове повідомлення'), ('duplicate', 'Дубль'), ('no_phone', 'Без телефону'), ('rejected', 'Раніше відхилено'), ('error', 'Помилка')], db_index=True, default='added', max_length=20),
        ),
        migrations.AddIndex(
            model_name='leadparsingresult',
            index=models.Index(fields=['job', 'place_id'], name='mgmt_parse_res_job_place'),
        ),
        migrations.AddIndex(
            model_name='leadparsingresult',
            index=models.Index(fields=['job', 'phone'], name='mgmt_parse_res_job_phone'),
        ),
        migrations.AddField(
            model_name='leadparsingquerystate',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_states', to='management.leadparsingjob', verbose_name='Сесія парсингу'),
        ),
        migrations.AddIndex(
            model_name='leadparsingquerystate',
            index=models.Index(fields=['job', 'status'], name='mgmt_parse_qs_job_status'),
        ),
        migrations.AddIndex(
            model_name='leadparsingquerystate',
            index=models.Index(fields=['job', '-updated_at'], name='mgmt_parse_qs_job_dt'),
        ),
        migrations.AddConstraint(
            model_name='leadparsingquerystate',
            constraint=models.UniqueConstraint(fields=('job', 'keyword', 'city', 'included_type'), name='mgmt_parse_query_state_unique'),
        ),
    ]
