# Generated by Django 5.2.11 on 2026-03-26 00:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_leadparsingjob_included_types_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfollowup',
            name='close_reason',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Причина закриття'),
        ),
        migrations.AddField(
            model_name='clientfollowup',
            name='completion_quality',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Якість виконання'),
        ),
        migrations.AddField(
            model_name='clientfollowup',
            name='followup_kind',
            field=models.CharField(choices=[('callback', 'Передзвон'), ('promise', 'Обіцянка / очікування'), ('nurture', 'Догрів / продовження контакту'), ('other', 'Інше')], db_index=True, default='callback', max_length=24),
        ),
        migrations.AddField(
            model_name='clientfollowup',
            name='priority_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='Знімок пріоритету'),
        ),
        migrations.AddField(
            model_name='clientfollowup',
            name='reschedule_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Кількість переносів'),
        ),
        migrations.AddField(
            model_name='clientfollowup',
            name='source_interaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spawned_followups', to='management.clientinteractionattempt', verbose_name='Початкова взаємодія'),
        ),
        migrations.CreateModel(
            name='ManagerDayFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True, verbose_name='День')),
                ('fact_key', models.CharField(default='daily_shadow_v7', max_length=64, verbose_name='Ключ факту')),
                ('schema_version', models.CharField(default='v7', max_length=32, verbose_name='Версія схеми')),
                ('day_status', models.CharField(choices=[('working', 'Робочий день'), ('weekend', 'Вихідний'), ('holiday', 'Свято'), ('vacation', 'Відпустка'), ('sick', 'Лікарняний'), ('excused', 'Погоджена відсутність'), ('tech_failure', 'Технічний збій'), ('force_majeure', 'Форс-мажор')], db_index=True, default='working', max_length=32)),
                ('capacity_factor', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4, verbose_name='Фактор доступності')),
                ('interactions_total', models.PositiveIntegerField(default=0, verbose_name='Всього взаємодій')),
                ('verified_interactions', models.PositiveIntegerField(default=0, verbose_name='Верифіковані взаємодії')),
                ('reason_signals_total', models.PositiveIntegerField(default=0, verbose_name='Сигнали причин')),
                ('followups_opened', models.PositiveIntegerField(default=0, verbose_name='Відкриті follow-up')),
                ('followups_closed', models.PositiveIntegerField(default=0, verbose_name='Закриті follow-up')),
                ('followups_completed', models.PositiveIntegerField(default=0, verbose_name='Виконані follow-up')),
                ('followups_overdue', models.PositiveIntegerField(default=0, verbose_name='Прострочені follow-up')),
                ('open_promises', models.PositiveIntegerField(default=0, verbose_name='Відкриті promise')),
                ('open_nurtures', models.PositiveIntegerField(default=0, verbose_name='Відкриті nurture')),
                ('freshness_seconds', models.PositiveIntegerField(default=0, verbose_name='Freshness, сек')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('materialized_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_day_facts', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Денний факт менеджера',
                'verbose_name_plural': 'Денні факти менеджера',
                'ordering': ['-day', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReasonSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=128, unique=True, verbose_name='Ключ сигналу')),
                ('result_code', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Результат')),
                ('reason_code', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Код причини')),
                ('quality_label', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Якість сигналу')),
                ('captured_at', models.DateTimeField(db_index=True, verbose_name='Коли')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reason_signals', to='management.client', verbose_name='Клієнт')),
                ('interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reason_signals', to='management.clientinteractionattempt', verbose_name='Взаємодія')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_reason_signals', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Сигнал причини',
                'verbose_name_plural': 'Сигнали причин',
                'ordering': ['-captured_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ScoreAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=128, unique=True, verbose_name='Ключ поправки')),
                ('effective_date', models.DateField(db_index=True, verbose_name='Дата дії')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('applied', 'Застосовано'), ('rejected', 'Відхилено')], db_index=True, default='pending', max_length=20)),
                ('delta_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Зміна score')),
                ('reason', models.TextField(blank=True, verbose_name='Причина')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appeal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_amendments', to='management.scoreappeal', verbose_name='Апеляція')),
                ('fact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_amendments', to='management.managerdayfact', verbose_name='Факт дня')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_score_amendments', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Поправка до score',
                'verbose_name_plural': 'Поправки до score',
                'ordering': ['-effective_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VerifiedWorkEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=128, unique=True, verbose_name='Ключ верифікації')),
                ('verification_level', models.CharField(choices=[('self_reported', 'Самозвіт'), ('linked_evidence', 'Підтверджено доказом'), ('override', 'З override перевіркою')], db_index=True, max_length=32, verbose_name='Рівень верифікації')),
                ('evidence_kind', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Тип доказу')),
                ('verified_at', models.DateTimeField(db_index=True, verbose_name='Коли')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_work_events', to='management.client', verbose_name='Клієнт')),
                ('interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_work_events', to='management.clientinteractionattempt', verbose_name='Взаємодія')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_verified_work_events', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Подія підтвердженої роботи',
                'verbose_name_plural': 'Події підтвердженої роботи',
                'ordering': ['-verified_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkingCalendarProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Назва профілю')),
                ('timezone_name', models.CharField(default='Europe/Kyiv', max_length=64, verbose_name='Таймзона')),
                ('weekly_template', models.JSONField(blank=True, default=dict, verbose_name='Тижневий шаблон')),
                ('capacity_template', models.JSONField(blank=True, default=dict, verbose_name='Шаблон доступності')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активний')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Мета')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management_working_calendar_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Профіль робочого календаря',
                'verbose_name_plural': 'Профілі робочого календаря',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkingCalendarException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True, verbose_name='День')),
                ('status', models.CharField(choices=[('working', 'Робочий день'), ('weekend', 'Вихідний'), ('holiday', 'Свято'), ('vacation', 'Відпустка'), ('sick', 'Лікарняний'), ('excused', 'Погоджена відсутність'), ('tech_failure', 'Технічний збій'), ('force_majeure', 'Форс-мажор')], db_index=True, default='working', max_length=32)),
                ('capacity_factor', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4, verbose_name='Фактор доступності')),
                ('source_reason', models.CharField(blank=True, max_length=255, verbose_name='Причина / джерело')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Мета')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management_working_calendar_exceptions', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='management.workingcalendarprofile', verbose_name='Профіль')),
            ],
            options={
                'verbose_name': 'Виняток робочого календаря',
                'verbose_name_plural': 'Винятки робочого календаря',
                'ordering': ['-day', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkingCalendarAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(db_index=True, verbose_name='Діє з')),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True, verbose_name='Діє до')),
                ('priority', models.PositiveSmallIntegerField(default=100, verbose_name='Пріоритет')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Мета')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_working_calendar_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='management.workingcalendarprofile', verbose_name='Профіль')),
            ],
            options={
                'verbose_name': 'Призначення робочого календаря',
                'verbose_name_plural': 'Призначення робочих календарів',
                'ordering': ['owner_id', '-effective_from', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='ClientStageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=128, unique=True, verbose_name='Ключ події')),
                ('stage_code', models.CharField(db_index=True, max_length=64, verbose_name='Код стадії')),
                ('phase_number', models.PositiveIntegerField(db_index=True, default=1, verbose_name='Номер фази')),
                ('result_code', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Результат')),
                ('occurred_at', models.DateTimeField(db_index=True, verbose_name='Коли')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_events', to='management.client', verbose_name='Клієнт')),
                ('interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_events', to='management.clientinteractionattempt', verbose_name='Взаємодія')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_stage_events', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Подія стадії клієнта',
                'verbose_name_plural': 'Події стадій клієнта',
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['owner', 'stage_code', '-occurred_at'], name='mgmt_stage_owner_code'), models.Index(fields=['client', '-occurred_at'], name='mgmt_stage_client_dt')],
            },
        ),
        migrations.CreateModel(
            name='FollowUpEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=128, unique=True, verbose_name='Ключ події')),
                ('event_type', models.CharField(choices=[('opened', 'Відкрито'), ('closed', 'Закрито'), ('notified', 'Нагадування відправлено'), ('amended', 'Скориговано')], db_index=True, max_length=24, verbose_name='Тип події')),
                ('followup_kind', models.CharField(choices=[('callback', 'Передзвон'), ('promise', 'Обіцянка / очікування'), ('nurture', 'Догрів / продовження контакту'), ('other', 'Інше')], db_index=True, default='callback', max_length=24)),
                ('status_before', models.CharField(blank=True, max_length=20, verbose_name='Статус до')),
                ('status_after', models.CharField(blank=True, max_length=20, verbose_name='Статус після')),
                ('close_reason', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Причина закриття')),
                ('completion_quality', models.CharField(blank=True, max_length=32, verbose_name='Якість виконання')),
                ('due_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Due at')),
                ('due_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Due date')),
                ('occurred_at', models.DateTimeField(db_index=True, verbose_name='Коли')),
                ('source', models.CharField(db_index=True, default='runtime', max_length=64, verbose_name='Джерело')),
                ('priority_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Знімок пріоритету')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_events', to='management.client', verbose_name='Клієнт')),
                ('followup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='management.clientfollowup', verbose_name='Follow-up')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_followup_events', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('source_interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_events', to='management.clientinteractionattempt', verbose_name='Джерело взаємодії')),
            ],
            options={
                'verbose_name': 'Подія follow-up',
                'verbose_name_plural': 'Події follow-up',
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['owner', 'due_date', 'event_type'], name='mgmt_fuevent_owner_dt'), models.Index(fields=['followup', '-occurred_at'], name='mgmt_fuevent_fu_dt')],
            },
        ),
        migrations.AddIndex(
            model_name='managerdayfact',
            index=models.Index(fields=['owner', '-day'], name='mgmt_day_fact_owner_dt'),
        ),
        migrations.AddIndex(
            model_name='managerdayfact',
            index=models.Index(fields=['fact_key', '-day'], name='mgmt_day_fact_key_dt'),
        ),
        migrations.AddConstraint(
            model_name='managerdayfact',
            constraint=models.UniqueConstraint(fields=('owner', 'day', 'fact_key'), name='mgmt_day_fact_unique'),
        ),
        migrations.AddIndex(
            model_name='reasonsignal',
            index=models.Index(fields=['owner', 'reason_code', '-captured_at'], name='mgmt_reason_owner_code'),
        ),
        migrations.AddIndex(
            model_name='reasonsignal',
            index=models.Index(fields=['client', '-captured_at'], name='mgmt_reason_client_dt'),
        ),
        migrations.AddIndex(
            model_name='scoreamendment',
            index=models.Index(fields=['owner', '-effective_date'], name='mgmt_score_am_owner_dt'),
        ),
        migrations.AddIndex(
            model_name='verifiedworkevent',
            index=models.Index(fields=['owner', 'verification_level', '-verified_at'], name='mgmt_vwork_owner_lvl'),
        ),
        migrations.AddIndex(
            model_name='verifiedworkevent',
            index=models.Index(fields=['client', '-verified_at'], name='mgmt_vwork_client_dt'),
        ),
        migrations.AddConstraint(
            model_name='workingcalendarexception',
            constraint=models.UniqueConstraint(fields=('profile', 'owner', 'day'), name='mgmt_workcal_exception_unique'),
        ),
        migrations.AddConstraint(
            model_name='workingcalendarassignment',
            constraint=models.UniqueConstraint(fields=('owner', 'profile', 'effective_from'), name='mgmt_workcal_assign_unique'),
        ),
    ]
