# Generated by Django 5.2.11 on 2026-03-26 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0032_clientfollowup_close_reason_and_more'),
        ('management', '0032_leadparsingquerystate_and_more'),
    ]

    operations = [
    ]
