# Generated by Django 5.2.11 on 2026-06-06 00:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0036_add_idle_seconds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='managerlevelhistory',
            name='access_blocked_until_signed',
            field=models.BooleanField(default=False, verbose_name='Блокувати доступ до підпису'),
        ),
        migrations.AddField(
            model_name='managerlevelhistory',
            name='requires_document',
            field=models.BooleanField(default=False, verbose_name='Потрібен новий документ'),
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Назва')),
                ('version', models.CharField(max_length=32, verbose_name='Версія')),
                ('role_level_scope', models.CharField(blank=True, max_length=64, verbose_name='Область (рівень)')),
                ('template_file', models.FileField(blank=True, null=True, upload_to='manager_docs/templates/', verbose_name='Файл шаблону')),
                ('body_text', models.TextField(blank=True, verbose_name='Текст шаблону (placeholder до юриста)')),
                ('template_variables', models.JSONField(blank=True, default=dict, verbose_name='Змінні шаблону')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Шаблон договору',
                'verbose_name_plural': 'Шаблони договорів',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'role_level_scope'], name='mgmt_ctpl_active_scope')],
            },
        ),
        migrations.CreateModel(
            name='ManagerEarningsLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('invoice_commission', 'Процентна винагорода (накладна)'), ('weekly_base', 'Базова винагорода (тиждень)'), ('adjustment', 'Коригування'), ('release', 'Розморозка'), ('withdrawal', 'Виплата'), ('refund_cancel', 'Скасування через повернення')], db_index=True, max_length=24, verbose_name='Тип джерела')),
                ('source_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='ID джерела')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Сума (+ нарахування / - списання)')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('frozen', 'Заморожено'), ('available', 'Доступно'), ('paid', 'Виплачено'), ('cancelled', 'Скасовано')], db_index=True, default='pending', max_length=12, verbose_name='Статус')),
                ('available_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Доступно з')),
                ('reason', models.TextField(blank=True, verbose_name='Пояснення')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Мета')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('commission_accrual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='management.managercommissionaccrual', verbose_name='Звʼязане нарахування')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings_ledger_created', to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings_ledger', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Запис ledger винагороди',
                'verbose_name_plural': 'Записи ledger винагороди',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagerOnboardingConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules_version', models.CharField(db_index=True, max_length=32, verbose_name='Версія правил')),
                ('accepted_18plus', models.BooleanField(default=False, verbose_name='Підтвердив 18+')),
                ('accepted_rules', models.BooleanField(default=False, verbose_name='Ознайомлений з правилами')),
                ('accepted_pdn', models.BooleanField(default=False, verbose_name='Згода на обробку ПДн')),
                ('signed_via', models.CharField(choices=[('checkbox', 'Чекбокс'), ('diia', 'Дія')], default='checkbox', max_length=12, verbose_name='Спосіб підтвердження')),
                ('diia_signature_id', models.CharField(blank=True, max_length=255, verbose_name='ID підпису Дія')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_consents', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Згода онбордингу',
                'verbose_name_plural': 'Згоди онбордингу',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagerPersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_enc', models.BinaryField(blank=True, null=True)),
                ('birth_date_enc', models.BinaryField(blank=True, null=True)),
                ('tax_id_enc', models.BinaryField(blank=True, null=True)),
                ('passport_enc', models.BinaryField(blank=True, null=True)),
                ('address_enc', models.BinaryField(blank=True, null=True)),
                ('phone_enc', models.BinaryField(blank=True, null=True)),
                ('tax_id_tail', models.CharField(blank=True, max_length=8, verbose_name='Хвіст ІПН')),
                ('passport_tail', models.CharField(blank=True, max_length=8, verbose_name='Хвіст паспорта')),
                ('source', models.CharField(choices=[('manual', 'Ручний ввід'), ('diia_sharing', 'Дія Sharing'), ('uploaded_doc', 'Завантажений документ'), ('other', 'Інше')], default='manual', max_length=16, verbose_name='Джерело')),
                ('consent_version', models.CharField(blank=True, max_length=32, verbose_name='Версія згоди')),
                ('consent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата згоди')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_data', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Персональні дані менеджера',
                'verbose_name_plural': 'Персональні дані менеджерів',
            },
        ),
        migrations.CreateModel(
            name='ManagerWeeklyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(db_index=True, verbose_name='Початок тижня')),
                ('week_end', models.DateField(verbose_name='Кінець тижня')),
                ('kpi_paid_invoices', models.PositiveIntegerField(default=0, verbose_name='Оплачених накладних')),
                ('kpi_units', models.PositiveIntegerField(default=0, verbose_name='Одиниць продано')),
                ('kpi_sales_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Сума продажів')),
                ('kpi_processed_clients', models.PositiveIntegerField(default=0, verbose_name='Оброблено клієнтів')),
                ('calculated_weekly_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Розрахункова тижнева база')),
                ('admin_decision', models.CharField(blank=True, choices=[('full', 'Повна (100%)'), ('half', 'Половина (50%)'), ('custom', 'Своя сума'), ('none', 'Без винагороди (0%)')], db_index=True, max_length=10, verbose_name='Рішення адміна')),
                ('awarded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Нараховано (грн)')),
                ('reason', models.TextField(blank=True, verbose_name='Причина (обовʼязково якщо не full)')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата рішення')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_reviews_decided', to=settings.AUTH_USER_MODEL, verbose_name='Вирішив')),
                ('ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_reviews', to='management.managerearningsledger', verbose_name='Запис у ledger')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Тижневе рішення',
                'verbose_name_plural': 'Тижневі рішення',
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(blank=True, max_length=64, verbose_name='Роль')),
                ('action', models.CharField(db_index=True, max_length=128, verbose_name='Дія')),
                ('entity_type', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Тип сутності')),
                ('entity_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='ID сутності')),
                ('before', models.JSONField(blank=True, default=dict, verbose_name='До')),
                ('after', models.JSONField(blank=True, default=dict, verbose_name='Після')),
                ('reason', models.TextField(blank=True, verbose_name='Причина')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Хто')),
            ],
            options={
                'verbose_name': 'Запис audit log',
                'verbose_name_plural': 'Audit log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id', '-created_at'], name='mgmt_audit_entity'), models.Index(fields=['action', '-created_at'], name='mgmt_audit_action'), models.Index(fields=['actor', '-created_at'], name='mgmt_audit_actor')],
            },
        ),
        migrations.CreateModel(
            name='ManagerCompensationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_base_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Базова винагорода за період (грн)')),
                ('weeks_per_month', models.PositiveSmallIntegerField(default=4, verbose_name='Тижнів у періоді (для розрахунку тижневої бази)')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Відсоток процентної винагороди')),
                ('frozen_days', models.PositiveSmallIntegerField(default=14, verbose_name='Період заморозки (днів)')),
                ('kpi_min_paid_invoices_per_week', models.PositiveSmallIntegerField(default=2, verbose_name='KPI: мін. оплачених накладних/тиждень')),
                ('kpi_min_units_per_invoice', models.PositiveSmallIntegerField(default=8, verbose_name='KPI: мін. одиниць у накладній')),
                ('effective_from', models.DateField(db_index=True, verbose_name='Діє з')),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True, verbose_name='Діє до (null = чинні зараз)')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Причина зміни')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensation_settings_changed', to=settings.AUTH_USER_MODEL, verbose_name='Змінив')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_settings', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Умови винагороди менеджера',
                'verbose_name_plural': 'Умови винагороди менеджерів',
                'ordering': ['owner_id', '-effective_from'],
                'indexes': [models.Index(fields=['owner', '-effective_from'], name='mgmt_comp_owner_eff'), models.Index(fields=['effective_to'], name='mgmt_comp_eff_to')],
            },
        ),
        migrations.CreateModel(
            name='ManagerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_kind', models.CharField(choices=[('onboarding_rules', 'Правила співпраці'), ('cpd_level1', 'ЦПД (1 рівень)'), ('cpd_level2', 'ЦПД (2 рівень)'), ('top', 'Топ-менеджер'), ('project', 'Project-менеджер'), ('other', 'Інше')], db_index=True, default='other', max_length=24, verbose_name='Тип документа')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('sent_to_sign', 'Надіслано на підпис'), ('signed', 'Підписано'), ('rejected', 'Відхилено'), ('expired', 'Прострочено'), ('revoked', 'Відкликано')], db_index=True, default='draft', max_length=16, verbose_name='Статус')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок')),
                ('generated_pdf', models.FileField(blank=True, null=True, upload_to='manager_docs/generated/', verbose_name='Згенерований PDF')),
                ('signed_file', models.FileField(blank=True, null=True, upload_to='manager_docs/signed/', verbose_name='Підписаний файл')),
                ('signature_provider', models.CharField(blank=True, choices=[('diia', 'Дія.Підпис'), ('vchasno', 'Vchasno'), ('manual', 'Вручну'), ('other', 'Інше')], max_length=16, verbose_name='Провайдер підпису')),
                ('signature_external_id', models.CharField(blank=True, max_length=255, verbose_name='Зовнішній ID підпису')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Підписано')),
                ('required_for_access', models.BooleanField(default=False, verbose_name='Потрібен для доступу')),
                ('access_blocking', models.BooleanField(db_index=True, default=False, verbose_name='Блокує доступ до підпису')),
                ('template_version_snapshot', models.CharField(blank=True, max_length=32, verbose_name='Версія шаблону (snapshot)')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Дані документа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_documents_created', to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_documents', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='management.contracttemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Документ менеджера',
                'verbose_name_plural': 'Документи менеджерів',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'status'], name='mgmt_doc_owner_st'), models.Index(fields=['access_blocking', 'status'], name='mgmt_doc_block_st')],
            },
        ),
        migrations.AddIndex(
            model_name='managerearningsledger',
            index=models.Index(fields=['owner', 'status'], name='mgmt_ledger_owner_st'),
        ),
        migrations.AddIndex(
            model_name='managerearningsledger',
            index=models.Index(fields=['status', 'available_at'], name='mgmt_ledger_st_avail'),
        ),
        migrations.AddIndex(
            model_name='managerearningsledger',
            index=models.Index(fields=['source_type', 'source_id'], name='mgmt_ledger_src'),
        ),
        migrations.AddIndex(
            model_name='manageronboardingconsent',
            index=models.Index(fields=['owner', '-created_at'], name='mgmt_consent_owner_dt'),
        ),
        migrations.AddIndex(
            model_name='manageronboardingconsent',
            index=models.Index(fields=['owner', 'rules_version'], name='mgmt_consent_owner_ver'),
        ),
        migrations.AddIndex(
            model_name='managerweeklyreview',
            index=models.Index(fields=['owner', '-week_start'], name='mgmt_wreview_owner_wk'),
        ),
        migrations.AddIndex(
            model_name='managerweeklyreview',
            index=models.Index(fields=['admin_decision', '-week_start'], name='mgmt_wreview_dec_wk'),
        ),
        migrations.AddConstraint(
            model_name='managerweeklyreview',
            constraint=models.UniqueConstraint(fields=('owner', 'week_start'), name='mgmt_weekly_review_owner_week'),
        ),
    ]
