# Generated by Django 5.2.11 on 2026-06-10 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0037_managerlevelhistory_access_blocked_until_signed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('payout', 'Винагорода'), ('invoice', 'Накладна'), ('contract', 'Договір'), ('system', 'Система')], db_index=True, default='system', max_length=20)),
                ('level', models.CharField(choices=[('info', 'Інфо'), ('success', 'Успіх'), ('warning', 'Увага'), ('danger', 'Помилка')], default='info', max_length=12)),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('body', models.TextField(blank=True, verbose_name='Текст')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сума')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Сповіщення менеджера',
                'verbose_name_plural': 'Сповіщення менеджерів',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='mgmt_notif_user_dt'), models.Index(fields=['user', 'is_read'], name='mgmt_notif_user_read')],
            },
        ),
    ]
