# Generated by Django 5.2.11 on 2026-06-10 21:16
# Production-safe: track_token (unique) is added nullable, backfilled with
# per-row uuid4, then promoted to unique — avoids the single-default
# IntegrityError on tables that already contain rows.

import uuid
from django.db import migrations, models


def backfill_track_tokens(apps, schema_editor):
    Log = apps.get_model('management', 'CommercialOfferEmailLog')
    for pk in Log.objects.filter(track_token__isnull=True).values_list('pk', flat=True):
        Log.objects.filter(pk=pk).update(track_token=uuid.uuid4())


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0038_managernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialofferemaillog',
            name='click_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кліків'),
        ),
        migrations.AddField(
            model_name='commercialofferemaillog',
            name='first_click_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Перший клік'),
        ),
        migrations.AddField(
            model_name='commercialofferemaillog',
            name='opened_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Перше відкриття'),
        ),
        migrations.AddField(
            model_name='commercialofferemaillog',
            name='response_note',
            field=models.TextField(blank=True, verbose_name='Коментар реакції'),
        ),
        migrations.AddField(
            model_name='commercialofferemaillog',
            name='response_outcome',
            field=models.CharField(blank=True, choices=[('', 'Без реакції'), ('not_opened', 'Не відкрив'), ('opened_no_reply', 'Відкрив, не відповів'), ('asked_messenger', 'Просив у месенджер'), ('thinking', 'Думає'), ('rejected', 'Відмова'), ('ordered', 'Замовлення'), ('other', 'Інше')], db_index=True, default='', max_length=24, verbose_name='Реакція на КП'),
        ),
        # track_token: add nullable first, backfill, then make unique.
        migrations.AddField(
            model_name='commercialofferemaillog',
            name='track_token',
            field=models.UUIDField(null=True, editable=False, db_index=True, verbose_name='Токен трекінгу'),
        ),
        migrations.RunPython(backfill_track_tokens, noop_reverse),
        migrations.AlterField(
            model_name='commercialofferemaillog',
            name='track_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, db_index=True, verbose_name='Токен трекінгу'),
        ),
    ]
