# Generated by Django 5.2.11 on 2026-06-14 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0039_commercialofferemaillog_click_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramBotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.CharField(choices=[('info', 'info'), ('success', 'success'), ('warning', 'warning'), ('error', 'error')], default='info', max_length=10)),
                ('event', models.CharField(max_length=120)),
                ('detail', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InstagramBotProcessedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstagramBotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('direct_source', models.CharField(choices=[('env', 'З ENV сервера'), ('custom', 'Свій ключ')], default='env', max_length=10)),
                ('custom_direct_token', models.TextField(blank=True, default='')),
                ('gemini_source', models.CharField(choices=[('env', 'З ENV сервера'), ('custom', 'Свій ключ')], default='env', max_length=10)),
                ('custom_gemini_key', models.TextField(blank=True, default='')),
                ('page_id', models.CharField(default='401216546416228', max_length=64)),
                ('ig_user_id', models.CharField(default='17841467101471112', max_length=64)),
                ('trigger_text', models.CharField(default='1', max_length=255)),
                ('reply_text', models.CharField(default='Привет, ты написал единичку', max_length=1000)),
                ('poll_interval_seconds', models.PositiveIntegerField(default=3)),
                ('reply_after', models.DateTimeField(blank=True, null=True)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_stopped_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('last_poll_at', models.DateTimeField(blank=True, null=True)),
                ('last_inbound_at', models.DateTimeField(blank=True, null=True)),
                ('last_reply_at', models.DateTimeField(blank=True, null=True)),
                ('replies_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instagram bot settings',
                'verbose_name_plural': 'Instagram bot settings',
            },
        ),
    ]
