# Generated by Django 5.2.11 on 2026-06-14 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0040_instagrambotlog_instagrambotprocessedmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrambotsettings',
            name='ai_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='instagrambotsettings',
            name='allowed_senders',
            field=models.TextField(blank=True, default='955313600823130'),
        ),
        migrations.AddField(
            model_name='instagrambotsettings',
            name='gemini_model',
            field=models.CharField(default='gemini-2.5-flash', max_length=80),
        ),
        migrations.AddField(
            model_name='instagrambotsettings',
            name='system_prompt',
            field=models.TextField(blank=True, default='Ты — дружелюбный ассистент бренда TwoComms (украинский магазин одежды: футболки, худи, стильный мерч). Общайся живо и по-человечески, на языке собеседника (украинский или русский). Отвечай кратко и по делу, помогай с вопросами о товарах, заказе и доставке. Не выдумывай факты о наличии и ценах — если не уверен, предложи уточнить у менеджера. Это тестовый режим свободного общения.'),
        ),
    ]
