# Generated by Django 5.2.11 on 2026-06-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0041_instagrambotsettings_ai_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrambotsettings',
            name='receive_via_poll',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='InstagramBotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(db_index=True, max_length=64)),
                ('role', models.CharField(choices=[('user', 'user'), ('model', 'model')], max_length=8)),
                ('text', models.TextField(blank=True, default='')),
                ('mid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('done', 'done'), ('failed', 'failed')], default='done', max_length=12)),
                ('source', models.CharField(default='webhook', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['status', 'role'], name='management__status_5a59eb_idx'), models.Index(fields=['sender_id', 'created_at'], name='management__sender__aec94b_idx')],
            },
        ),
    ]
