# Generated by Django 5.2.11 on 2026-06-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0045_ig_bot_event_driven'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrambotsettings',
            name='receive_via_poll',
            field=models.BooleanField(default=False),
        ),
    ]
