# Generated by Django 5.2.11 on 2026-06-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0048_alter_instagrambotsettings_system_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrambotsettings',
            name='knowledge_base',
            field=models.TextField(blank=True, default=''),
        ),
    ]
