# Generated by Django 5.2.11 on 2026-06-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0049_instagrambotsettings_knowledge_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinotelWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('apiCallSettings', "Налаштування дзвінка (до з'єднання)"), ('apiCallCompleted', 'Дзвінок завершено'), ('unknown', 'Невідомо')], db_index=True, default='unknown', max_length=40)),
                ('company_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='companyID')),
                ('general_call_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='generalCallID')),
                ('call_type', models.CharField(blank=True, max_length=8, verbose_name='callType (0 вх/1 вих)')),
                ('external_number', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Зовнішній номер')),
                ('internal_number', models.CharField(blank=True, max_length=32, verbose_name='Внутрішній номер')),
                ('remote_ip', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='IP джерела')),
                ('ip_allowed', models.BooleanField(default=False, verbose_name='IP у whitelist Binotel')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Вхідний payload')),
                ('response_payload', models.JSONField(blank=True, default=dict, verbose_name='Відповідь')),
                ('handled_ok', models.BooleanField(default=False, verbose_name='Оброблено успішно')),
                ('error', models.TextField(blank=True, verbose_name='Помилка обробки')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Вебхук Binotel',
                'verbose_name_plural': 'Вебхуки Binotel',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['request_type', '-created_at'], name='mgmt_bnwh_type_dt'), models.Index(fields=['general_call_id'], name='mgmt_bnwh_gcid')],
            },
        ),
    ]
