# Generated by Django 5.2.11 on 2026-06-17 18:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0050_binotelwebhookevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallAIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('running', 'Аналізується'), ('done', 'Готово'), ('error', 'Помилка')], db_index=True, default='pending', max_length=20)),
                ('model', models.CharField(blank=True, max_length=64, verbose_name='Модель')),
                ('overall_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Загальний бал')),
                ('verdict', models.CharField(choices=[('pass', 'Сильна розмова'), ('coaching', 'Потрібен коучинг'), ('fail', 'Слабка розмова'), ('unknown', 'Невизначено')], db_index=True, default='unknown', max_length=20)),
                ('transcript', models.TextField(blank=True, verbose_name='Транскрипт')),
                ('summary', models.TextField(blank=True, verbose_name='Резюме розмови')),
                ('client_identification', models.TextField(blank=True, verbose_name='Ідентифікація клієнта')),
                ('axes', models.JSONField(blank=True, default=list, verbose_name='Осі оцінки (Mosaic-style)')),
                ('discussed_well', models.JSONField(blank=True, default=list, verbose_name='Що обговорили добре')),
                ('missed_topics', models.JSONField(blank=True, default=list, verbose_name='Що не обговорили')),
                ('recommendations', models.JSONField(blank=True, default=list, verbose_name='Рекомендації менеджеру')),
                ('manager_context', models.TextField(blank=True, verbose_name='B2B-контекст менеджера')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='Повна сира відповідь')),
                ('audio_bytes', models.PositiveIntegerField(default=0, verbose_name='Розмір аудіо, байт')),
                ('elapsed_ms', models.PositiveIntegerField(default=0, verbose_name='Час аналізу, мс')),
                ('prompt_tokens', models.PositiveIntegerField(default=0, verbose_name='Prompt tokens')),
                ('output_tokens', models.PositiveIntegerField(default=0, verbose_name='Output tokens')),
                ('error', models.TextField(blank=True, verbose_name='Помилка')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='management.callrecord', verbose_name='Дзвінок')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_ai_analyses', to=settings.AUTH_USER_MODEL, verbose_name='Запустив')),
            ],
            options={
                'verbose_name': 'ШІ-аналіз дзвінка',
                'verbose_name_plural': 'ШІ-аналізи дзвінків',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['call_record', '-created_at'], name='mgmt_callai_rec_dt'), models.Index(fields=['status', '-created_at'], name='mgmt_callai_status_dt')],
            },
        ),
    ]
