# Generated by Django 5.2.11 on 2026-06-17 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0051_callaianalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='callaianalysis',
            name='discrepancies',
            field=models.JSONField(blank=True, default=list, verbose_name='Розбіжності з даними менеджера'),
        ),
        migrations.AddField(
            model_name='callaianalysis',
            name='extracted_facts',
            field=models.JSONField(blank=True, default=dict, verbose_name='Факти з розмови (для сверки)'),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='ai_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='ai_locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='callrecord',
            name='ai_status',
            field=models.CharField(choices=[('none', 'Не потрібен'), ('pending', 'У черзі на аналіз'), ('running', 'Аналізується'), ('done', 'Проаналізовано'), ('error', 'Помилка аналізу'), ('skipped', 'Пропущено')], db_index=True, default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='managernotification',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Підтверджено о'),
        ),
        migrations.AddField(
            model_name='managernotification',
            name='action_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Посилання дії'),
        ),
        migrations.AddField(
            model_name='managernotification',
            name='related_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='management.callaianalysis', verbose_name='ШІ-аналіз'),
        ),
        migrations.AddField(
            model_name='managernotification',
            name='related_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='management.client', verbose_name='Клієнт'),
        ),
        migrations.AddField(
            model_name='managernotification',
            name='requires_ack',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Потребує підтвердження'),
        ),
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='binotel', max_length=64)),
                ('internal_number', models.CharField(blank=True, max_length=32, verbose_name='Лінія менеджера')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='Номер клієнта')),
                ('phone_normalized', models.CharField(blank=True, db_index=True, max_length=64)),
                ('general_call_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('dialing', 'Набір'), ('ringing', 'Дзвінок'), ('talking', 'Розмова'), ('ended', 'Завершено'), ('failed', 'Помилка')], db_index=True, default='dialing', max_length=20)),
                ('disposition', models.CharField(blank=True, max_length=32)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='management.callrecord', verbose_name='Запис дзвінка')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_sessions', to='management.client', verbose_name='Клієнт')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_sessions', to='management.managementlead', verbose_name='Лід')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_call_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Сесія дзвінка',
                'verbose_name_plural': 'Сесії дзвінків',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['manager', '-started_at'], name='mgmt_callsess_mgr_dt'), models.Index(fields=['general_call_id'], name='mgmt_callsess_gcid'), models.Index(fields=['status', '-started_at'], name='mgmt_callsess_st_dt')],
            },
        ),
        migrations.CreateModel(
            name='ClientPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер')),
                ('number_normalized', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Нормалізований')),
                ('number_last7', models.CharField(blank=True, db_index=True, max_length=7, verbose_name='Останні 7 цифр')),
                ('category', models.CharField(choices=[('work', 'Робочий'), ('personal', 'Особистий'), ('viber', 'Viber'), ('telegram', 'Telegram'), ('other', 'Інший')], db_index=True, default='work', max_length=20, verbose_name='Категорія')),
                ('label', models.CharField(blank=True, max_length=120, verbose_name='Підпис')),
                ('is_primary', models.BooleanField(db_index=True, default=False, verbose_name='Основний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='management.client', verbose_name='Клієнт')),
            ],
            options={
                'verbose_name': 'Телефон клієнта',
                'verbose_name_plural': 'Телефони клієнта',
                'ordering': ['-is_primary', 'id'],
                'indexes': [models.Index(fields=['client', '-is_primary'], name='mgmt_cliphone_cli_pri'), models.Index(fields=['number_last7'], name='mgmt_cliphone_last7')],
            },
        ),
    ]
