# Generated by Django 5.2.11 on 2026-06-18 07:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0053_backfill_client_primary_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayReportAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True, verbose_name='День звіту')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('running', 'Аналізується'), ('done', 'Готово'), ('error', 'Помилка'), ('skipped', 'Пропущено')], db_index=True, default='pending', max_length=20)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('day_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('verdict', models.CharField(choices=[('strong', 'Сильний день'), ('ok', 'Робочий день'), ('weak', 'Слабкий день'), ('unknown', 'Невизначено')], default='unknown', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('matches', models.JSONField(blank=True, default=list)),
                ('mismatches', models.JSONField(blank=True, default=list)),
                ('missed_callbacks', models.JSONField(blank=True, default=list)),
                ('growth', models.JSONField(blank=True, default=dict)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('prospects', models.TextField(blank=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('tenure_days', models.PositiveIntegerField(default=0)),
                ('reports_count', models.PositiveIntegerField(default=0)),
                ('calls_total', models.PositiveIntegerField(default=0)),
                ('calls_analyzed', models.PositiveIntegerField(default=0)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('elapsed_ms', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_day_audits', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_audits', to='management.report', verbose_name='Звіт')),
            ],
            options={
                'verbose_name': 'ШІ-аудит дня',
                'verbose_name_plural': 'ШІ-аудити дня',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', '-day'], name='mgmt_dayaudit_owner_day'), models.Index(fields=['status', '-created_at'], name='mgmt_dayaudit_status_dt')],
            },
        ),
    ]
