# Generated by Django 5.2.11 on 2026-06-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0054_dayreportaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementlead',
            name='ai_checked_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='AI-перевірено'),
        ),
        migrations.AddField(
            model_name='managementlead',
            name='ai_score',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, verbose_name='AI-оцінка'),
        ),
        migrations.AddField(
            model_name='managementlead',
            name='ai_verdict',
            field=models.CharField(blank=True, db_index=True, max_length=10, verbose_name='AI-вердикт'),
        ),
    ]
