# Generated by Django 5.2.11 on 2026-06-18 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0055_managementlead_ai_checked_at_managementlead_ai_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadCheckerSettings',
            fields=[
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('gemini_api_key', models.CharField(blank=True, max_length=255, verbose_name='Ключ Gemini (опц.)')),
                ('model_chain', models.CharField(blank=True, max_length=255, verbose_name='Цепочка моделей (csv)')),
                ('requests_per_minute', models.PositiveIntegerField(default=8, verbose_name='Запитів за хвилину')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Налаштування чекера',
                'verbose_name_plural': 'Налаштування чекера',
            },
        ),
        migrations.CreateModel(
            name='LeadCheckJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Працює'), ('paused', 'Пауза'), ('stopped', 'Зупинено'), ('completed', 'Завершено'), ('failed', 'Помилка')], db_index=True, default='running', max_length=20)),
                ('scope', models.CharField(choices=[('unchecked', 'Тільки неперевірені'), ('all', 'Усі (перепровірка)'), ('by_city', 'За містом'), ('by_band', 'За смугою вердикту')], default='unchecked', max_length=20)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('band', models.CharField(blank=True, max_length=10)),
                ('target_limit', models.PositiveIntegerField(default=0)),
                ('requests_per_minute', models.PositiveIntegerField(default=8)),
                ('total_selected', models.PositiveIntegerField(default=0)),
                ('processed', models.PositiveIntegerField(default=0)),
                ('scored', models.PositiveIntegerField(default=0)),
                ('errors', models.PositiveIntegerField(default=0)),
                ('fit_count', models.PositiveIntegerField(default=0)),
                ('maybe_count', models.PositiveIntegerField(default=0)),
                ('unfit_count', models.PositiveIntegerField(default=0)),
                ('cursor_id', models.PositiveIntegerField(default=0)),
                ('current_lead_id', models.PositiveIntegerField(blank=True, null=True)),
                ('next_step_not_before', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_step_in_progress', models.BooleanField(db_index=True, default=False)),
                ('last_step_started_at', models.DateTimeField(blank=True, null=True)),
                ('avg_seconds', models.FloatField(default=0.0)),
                ('last_error', models.TextField(blank=True)),
                ('stop_reason_code', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_check_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
            ],
            options={
                'verbose_name': 'Сесія чекера',
                'verbose_name_plural': 'Сесії чекера',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadAICheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В черзі'), ('processing', 'Обробка'), ('done', 'Готово'), ('error', 'Помилка')], db_index=True, default='pending', max_length=20)),
                ('overall_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('criteria', models.JSONField(blank=True, default=list)),
                ('verdict_category', models.CharField(blank=True, max_length=40)),
                ('partnership_fit', models.JSONField(blank=True, default=list)),
                ('confidence', models.CharField(blank=True, max_length=10)),
                ('brand_summary', models.TextField(blank=True)),
                ('audience_guess', models.TextField(blank=True)),
                ('instagram_url', models.CharField(blank=True, max_length=300)),
                ('comment', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('website_fetched', models.BooleanField(default=False)),
                ('model_used', models.CharField(blank=True, max_length=60)),
                ('tokens', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_ai_checks', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_checks', to='management.managementlead')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checks', to='management.leadcheckjob')),
            ],
            options={
                'verbose_name': 'AI-перевірка ліда',
                'verbose_name_plural': 'AI-перевірки лідів',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadCheckRuntimeLock',
            fields=[
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='management.leadcheckjob')),
            ],
            options={
                'verbose_name': 'Lock чекера',
                'verbose_name_plural': 'Lock-и чекера',
            },
        ),
        migrations.AddIndex(
            model_name='leadcheckjob',
            index=models.Index(fields=['status', '-started_at'], name='mgmt_check_status_dt'),
        ),
        migrations.AddIndex(
            model_name='leadaicheck',
            index=models.Index(fields=['lead', '-created_at'], name='mgmt_aicheck_lead_dt'),
        ),
        migrations.AddIndex(
            model_name='leadaicheck',
            index=models.Index(fields=['status', '-created_at'], name='mgmt_aicheck_status_dt'),
        ),
    ]
