# Generated by Django 5.2.11 on 2026-06-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0056_leadcheckersettings_leadcheckjob_leadaicheck_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiKeyState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(max_length=40, unique=True)),
                ('role_hint', models.CharField(blank=True, max_length=20)),
                ('cooldown_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cooldown_scope', models.CharField(blank=True, max_length=10)),
                ('last_status', models.CharField(blank=True, max_length=20)),
                ('last_429_at', models.DateTimeField(blank=True, null=True)),
                ('last_ok_at', models.DateTimeField(blank=True, null=True)),
                ('requests_today', models.PositiveIntegerField(default=0)),
                ('day_date', models.DateField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Стан Gemini-ключа',
                'verbose_name_plural': 'Стани Gemini-ключів',
            },
        ),
        migrations.AddField(
            model_name='leadcheckersettings',
            name='auto_recheck',
            field=models.BooleanField(default=False, verbose_name='Авто-чекінг при відновленні квоти'),
        ),
        migrations.AddField(
            model_name='leadcheckersettings',
            name='auto_recheck_batch',
            field=models.PositiveIntegerField(default=25, verbose_name='Розмір батчу авто-чекінгу'),
        ),
    ]
