# Generated by Django 5.2.11 on 2026-06-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0057_geminikeystate_leadcheckersettings_auto_recheck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcheckjob',
            name='is_auto',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Авто-сесія (cron)'),
        ),
    ]
