# Generated by Django 5.2.11 on 2026-06-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0058_leadcheckjob_is_auto'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramBotRawEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sender_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('attachment_types', models.CharField(blank=True, default='', max_length=255)),
                ('has_referral', models.BooleanField(default=False)),
                ('has_echo', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('payload', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'IG raw webhook event',
                'verbose_name_plural': 'IG raw webhook events',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['-created_at'], name='ig_rawevent_created')],
            },
        ),
    ]
