# Generated by Django 5.2.11 on 2026-06-18 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0059_instagrambotrawevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igsid', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='IG sender id')),
                ('username', models.CharField(blank=True, default='', max_length=120, verbose_name='Username')),
                ('display_name', models.CharField(blank=True, default='', max_length=255, verbose_name="Ім'я")),
                ('profile_pic_url', models.CharField(blank=True, default='', max_length=600, verbose_name='Аватар URL')),
                ('profile_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Телефон')),
                ('phone_normalized', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('stage', models.CharField(choices=[('new', 'Написав'), ('qualifying', "З'ясовуємо потребу"), ('product_matched', 'Товар і ціна визначені'), ('checkout', 'Обирає оплату'), ('payment_pending', 'Очікуємо оплату'), ('paid', 'Оплачено'), ('order_created', 'Замовлення створено'), ('done', 'Завершено'), ('lead_manager', 'Передано менеджеру'), ('spam', 'Спам / заблоковано'), ('cold', 'Не відповідає / охолов')], db_index=True, default='new', max_length=24, verbose_name='Стадія')),
                ('stage_updated_at', models.DateTimeField(blank=True, null=True)),
                ('bot_paused', models.BooleanField(db_index=True, default=False, verbose_name='Бот на паузі')),
                ('paused_reason', models.CharField(blank=True, default='', max_length=255)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('manager_takeover', models.BooleanField(default=False, verbose_name='Веде менеджер')),
                ('ad_ref', models.CharField(blank=True, default='', max_length=255)),
                ('ad_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('ad_source', models.CharField(blank=True, default='', max_length=64)),
                ('ad_title', models.CharField(blank=True, default='', max_length=255)),
                ('ad_creative_url', models.CharField(blank=True, default='', max_length=600)),
                ('referral_payload', models.JSONField(blank=True, default=dict)),
                ('memory_summary', models.TextField(blank=True, default='')),
                ('memory_updated_at', models.DateTimeField(blank=True, null=True)),
                ('purchases_count', models.PositiveIntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('conversion_flags', models.JSONField(blank=True, default=dict)),
                ('spam_strikes', models.PositiveSmallIntegerField(default=0)),
                ('is_blocked', models.BooleanField(default=False)),
                ('first_contact_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_bot_reply_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IG клієнт',
                'verbose_name_plural': 'IG клієнти',
                'ordering': ['-last_message_at', '-id'],
                'indexes': [models.Index(fields=['stage', '-last_message_at'], name='ig_client_stage_dt'), models.Index(fields=['-last_message_at'], name='ig_client_lastmsg')],
            },
        ),
        migrations.AddField(
            model_name='instagrambotmessage',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='management.igclient'),
        ),
    ]
