# Generated by Django 5.2.11 on 2026-06-18 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0061_backfill_ig_clients'),
        ('orders', '0047_checkoutcapture'),
        ('productcolors', '0007_normalize_slugs'),
        ('storefront', '0078_qrdevicegrant'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('quoted', 'Названо ціну'), ('awaiting_payment', 'Очікує оплату'), ('paid', 'Оплачено'), ('order_created', 'Замовлення створено'), ('cancelled', 'Скасовано')], db_index=True, default='draft', max_length=20)),
                ('pay_type', models.CharField(choices=[('online_full', 'Повна онлайн-оплата'), ('prepay_200', 'Передплата 200 грн')], default='online_full', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='UAH', max_length=8)),
                ('invoice_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('invoice_url', models.CharField(blank=True, default='', max_length=600)),
                ('payment_status', models.CharField(default='unpaid', max_length=20)),
                ('payment_payload', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('np_full_name', models.CharField(blank=True, default='', max_length=255)),
                ('np_phone', models.CharField(blank=True, default='', max_length=50)),
                ('np_city', models.CharField(blank=True, default='', max_length=160)),
                ('np_office', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='management.igclient')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ig_deals', to='orders.order')),
            ],
            options={
                'verbose_name': 'IG угода',
                'verbose_name_plural': 'IG угоди',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='IgDealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('size', models.CharField(blank=True, default='', max_length=16)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('color_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productcolors.productcolorvariant')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='management.igdeal')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storefront.product')),
            ],
            options={
                'verbose_name': 'Позиція IG угоди',
                'verbose_name_plural': 'Позиції IG угод',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='igdeal',
            index=models.Index(fields=['client', '-id'], name='ig_deal_client_dt'),
        ),
        migrations.AddIndex(
            model_name='igdeal',
            index=models.Index(fields=['status', '-id'], name='ig_deal_status_dt'),
        ),
    ]
