# Generated by Django 5.2.11 on 2026-06-18 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0062_igdeal_igdealitem_igdeal_ig_deal_client_dt_and_more'),
        ('storefront', '0078_qrdevicegrant'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Текст інструкції')),
                ('intent_tags', models.CharField(blank=True, default='', max_length=400, verbose_name='Ключові слова (через кому)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('priority', models.IntegerField(default=100, verbose_name='Пріоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Інструкція бота',
                'verbose_name_plural': 'Інструкції бота',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BotQuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('size_chart', 'Розмірна сітка'), ('catalog', 'Каталог'), ('highlight', 'Хайлайт'), ('other', 'Інше')], db_index=True, default='other', max_length=20)),
                ('label', models.CharField(max_length=200, verbose_name='Підпис')),
                ('url', models.CharField(max_length=600, verbose_name='Посилання')),
                ('garment_type', models.CharField(blank=True, db_index=True, default='', max_length=40, verbose_name='Тип одягу (tshirt/hoodie/longsleeve…)')),
                ('trigger_keywords', models.CharField(blank=True, default='', max_length=400, verbose_name='Тригер-слова (через кому)')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Швидке посилання бота',
                'verbose_name_plural': 'Швидкі посилання бота',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BotAdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Ad ID')),
                ('ref', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Ref')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Назва кампанії')),
                ('theme', models.CharField(blank=True, default='', max_length=120, verbose_name='Тема')),
                ('landing_note', models.TextField(blank=True, default='', verbose_name='Що в рекламі / CTA')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storefront.product')),
            ],
            options={
                'verbose_name': 'Рекламна кампанія бота',
                'verbose_name_plural': 'Рекламні кампанії бота',
                'ordering': ['-id'],
            },
        ),
    ]
