# Generated by Django 5.2.11 on 2026-06-19 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0063_botinstruction_botquicklink_botadcampaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgClientStageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(blank=True, default='', max_length=24)),
                ('to_stage', models.CharField(max_length=24)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_events', to='management.igclient')),
            ],
            options={
                'verbose_name': 'Подія стадії IG-клієнта',
                'verbose_name_plural': 'Події стадій IG-клієнтів',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['client', '-id'], name='ig_stageevent_client')],
            },
        ),
    ]
