# Generated by Django 5.2.11 on 2026-06-19 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0066_ig_bot_playbook_prompt'),
        ('storefront', '0078_qrdevicegrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='igclient',
            name='current_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='storefront.product', verbose_name='Закріплений товар'),
        ),
    ]
