# Generated by Django 5.2.11 on 2026-06-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0067_igclient_current_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='igclient',
            name='avatar_local',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Аватар (локально)'),
        ),
    ]
