# Generated by Django 5.2.11 on 2026-06-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0068_igclient_avatar_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='igdeal',
            name='shipped_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
