# Generated by Django 5.2.11 on 2026-06-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0069_igdeal_shipped_notified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcheckjob',
            name='tokens_total',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
