# Generated by Django 5.2.11 on 2026-06-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0070_leadcheckjob_tokens_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadaicheck',
            name='collaboration_evidence',
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
        migrations.AddField(
            model_name='leadaicheck',
            name='signals',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='leadaicheck',
            name='verdict_band',
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
    ]
