# Generated by Django 5.2.11 on 2026-06-20 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0071_leadaicheck_collaboration_evidence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='managementlead',
            name='needs_disambiguation',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Родова назва (розрізнити)'),
        ),
        migrations.AddField(
            model_name='managementlead',
            name='network_membership_source',
            field=models.CharField(blank=True, max_length=8, verbose_name='Джерело привʼязки до мережі'),
        ),
        migrations.CreateModel(
            name='LeadNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(max_length=255, verbose_name='Канонічна назва')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('kind', models.CharField(choices=[('chain_brand', 'Мережа-бренд'), ('franchise', 'Франшиза'), ('marketplace', 'Маркетплейс'), ('voentorg_group', 'Група військторгів'), ('unknown', 'Невідомо')], default='unknown', max_length=20)),
                ('policy', models.CharField(choices=[('block_no_collab', 'Не співпрацює — пропускати'), ('block_irrelevant', 'Не наш профіль — пропускати'), ('apply_known_verdict', 'Застосувати вердикт мережі'), ('recheck_each', 'Перевіряти кожну точку'), ('custom_print_only', 'Лише кастом-друк'), ('needs_review', 'Потребує рішення'), ('priority_target', 'Пріоритетна ціль')], db_index=True, default='needs_review', max_length=24)),
                ('policy_params', models.JSONField(blank=True, default=dict)),
                ('extra_instructions', models.TextField(blank=True)),
                ('collaboration_evidence', models.CharField(blank=True, max_length=10)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('suggested_by_ai', models.BooleanField(default=False)),
                ('ai_rationale', models.TextField(blank=True)),
                ('members_count', models.PositiveIntegerField(default=0)),
                ('checked_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('tokens_saved', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_networks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Мережа лідів',
                'verbose_name_plural': 'Мережі лідів',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='managementlead',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='management.leadnetwork', verbose_name='Мережа'),
        ),
        migrations.CreateModel(
            name='NetworkAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_type', models.CharField(choices=[('name', 'Назва'), ('website', 'Сайт'), ('instagram', 'Instagram')], max_length=12)),
                ('key_value', models.CharField(db_index=True, max_length=500)),
                ('source', models.CharField(default='auto', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='management.leadnetwork')),
            ],
            options={
                'verbose_name': 'Алиас мережі',
                'verbose_name_plural': 'Алиаси мереж',
                'constraints': [models.UniqueConstraint(fields=('key_type', 'key_value'), name='uniq_network_alias_key')],
            },
        ),
    ]
