# Generated by Django 5.2.11 on 2026-07-25 21:16

import hashlib
from decimal import Decimal, InvalidOperation

import django.db.models.deletion
from django.db import migrations, models


def _is_superseded_review(row):
    """Support both the live model and the pre-0109 historical migration model."""
    return bool(
        row is not None
        and getattr(row, "status", "") == "superseded"
        and getattr(row, "superseded_by_id", None)
    )


def _unmaterialized_component_counts(apps, alias):
    """Count source rows that still lack an owning commercial episode."""
    from django.db.models import Exists, OuterRef, Q

    IgDeal = apps.get_model("management", "IgDeal")
    IgPaymentConfirmationReview = apps.get_model(
        "management", "IgPaymentConfirmationReview"
    )
    IgOrderAttribution = apps.get_model("management", "IgOrderAttribution")
    IgCommercialEpisode = apps.get_model("management", "IgCommercialEpisode")

    def missing(model, relation_field):
        owned = IgCommercialEpisode.objects.using(alias).filter(
            **{relation_field: OuterRef("pk")}
        )
        return model.objects.using(alias).filter(~Exists(owned)).count()

    episode_rows = IgCommercialEpisode.objects.using(alias)
    episode_attribution_ids = episode_rows.exclude(
        order_attribution_id__isnull=True
    ).values("order_attribution_id")
    attribution_review_ids = IgOrderAttribution.objects.using(alias).filter(
        pk__in=episode_attribution_ids,
        payment_review_id__isnull=False,
    ).values("payment_review_id")
    materialized_reviews = Q(
        pk__in=episode_rows.exclude(
            primary_payment_review_id__isnull=True
        ).values("primary_payment_review_id")
    ) | Q(
        deal_id__isnull=False,
        deal_id__in=episode_rows.exclude(deal_id__isnull=True).values("deal_id"),
    ) | Q(
        order_id__isnull=False,
        order_id__in=episode_rows.exclude(intended_order_id__isnull=True).values(
            "intended_order_id"
        ),
    ) | Q(pk__in=attribution_review_ids)

    return {
        "deals": missing(IgDeal, "deal_id"),
        # Several review attempts may legitimately belong to one connected
        # commercial component. Only the newest is stored as the episode's
        # primary review; older rows are still materialized through the same
        # deal, order, or attributed review edge.
        "reviews": IgPaymentConfirmationReview.objects.using(alias)
        .exclude(materialized_reviews)
        .count(),
        "attributions": missing(IgOrderAttribution, "order_attribution_id"),
    }


def backfill_until_quiescent(apps, schema_editor, max_passes=3):
    """Rescan after each pass so late old-worker writes are converged."""
    alias = schema_editor.connection.alias if schema_editor is not None else "default"
    for _pass in range(max(1, int(max_passes))):
        backfill_commercial_episodes(apps, schema_editor)
        remaining = _unmaterialized_component_counts(apps, alias)
        if not any(remaining.values()):
            return remaining
    raise RuntimeError(
        "Instagram commercial episode backfill did not converge: "
        + ", ".join(f"{key}={value}" for key, value in remaining.items())
    )


def backfill_commercial_episodes(apps, schema_editor):
    """Materialize historical commercial components in real chronology.

    The function validates all cross-client and one-order ownership conflicts
    before the first write.  This matters because the production data migration
    is deliberately non-atomic on MariaDB.
    """
    alias = schema_editor.connection.alias if schema_editor is not None else "default"
    IgClient = apps.get_model("management", "IgClient")
    IgDeal = apps.get_model("management", "IgDeal")
    IgDealItem = apps.get_model("management", "IgDealItem")
    IgPaymentConfirmationReview = apps.get_model(
        "management", "IgPaymentConfirmationReview"
    )
    IgPaymentReviewDecision = apps.get_model("management", "IgPaymentReviewDecision")
    IgPaymentProjection = apps.get_model("management", "IgPaymentProjection")
    IgOrderAttribution = apps.get_model("management", "IgOrderAttribution")
    IgCommercialEpisode = apps.get_model("management", "IgCommercialEpisode")
    IgCommercialEpisodeEvent = apps.get_model(
        "management", "IgCommercialEpisodeEvent"
    )
    Order = apps.get_model("orders", "Order")

    deals = list(IgDeal.objects.using(alias).all())
    reviews = list(IgPaymentConfirmationReview.objects.using(alias).all())
    attributions = list(IgOrderAttribution.objects.using(alias).all())
    projections = list(IgPaymentProjection.objects.using(alias).all())
    projections_by_deal = {row.deal_id: row for row in projections}
    decisions_by_review = {}
    for row in IgPaymentReviewDecision.objects.using(alias).order_by("created_at", "id"):
        decisions_by_review.setdefault(row.review_id, []).append(row)
    orders_by_id = {
        row.pk: row
        for row in Order.objects.using(alias).filter(
            pk__in={
                value
                for value in [
                    *(row.order_id for row in deals),
                    *(row.order_id for row in reviews),
                    *(row.order_id for row in attributions),
                ]
                if value
            }
        )
    }

    deal_owner = {row.pk: row.client_id for row in deals}
    ownership = {}

    def claim(kind, object_id, client_id):
        if not object_id:
            return
        key = (kind, int(object_id))
        previous = ownership.setdefault(key, int(client_id))
        if previous != int(client_id):
            raise RuntimeError(
                f"Instagram commercial backfill conflict: {kind} {object_id} "
                f"belongs to clients {previous} and {client_id}"
            )

    for row in deals:
        claim("deal", row.pk, row.client_id)
        claim("order", row.order_id, row.client_id)
    for row in reviews:
        claim("review", row.pk, row.client_id)
        claim("deal", row.deal_id, row.client_id)
        claim("order", row.order_id, row.client_id)
        if row.deal_id and deal_owner.get(row.deal_id) != row.client_id:
            raise RuntimeError("Instagram review points to another client's deal")
    for row in attributions:
        claim("attribution", row.pk, row.client_id)
        claim("deal", row.deal_id, row.client_id)
        claim("review", row.payment_review_id, row.client_id)
        claim("order", row.order_id, row.client_id)
        if row.deal_id and deal_owner.get(row.deal_id) != row.client_id:
            raise RuntimeError("Instagram attribution points to another client's deal")

    client_ids = set(
        row.client_id for row in attributions
    )
    client_ids.update(row.client_id for row in deals)
    client_ids.update(row.client_id for row in reviews)

    def money(value):
        try:
            amount = Decimal(str(value if value is not None else "0"))
        except (InvalidOperation, TypeError, ValueError):
            amount = Decimal("0")
        return amount.quantize(Decimal("0.01"))

    def order_amounts(order):
        subtotal = money(getattr(order, "total_sum", None))
        discount = max(
            money(getattr(order, "discount_amount", None)), Decimal("0.00")
        )
        return subtotal, discount, max(subtotal - discount, Decimal("0.00"))

    client_plans = []
    for client_id in sorted(value for value in client_ids if value):
        client = IgClient.objects.using(alias).filter(pk=client_id).first()
        if client is None:
            continue
        client_deals = [row for row in deals if row.client_id == client_id]
        client_reviews = [row for row in reviews if row.client_id == client_id]
        client_attrs = [row for row in attributions if row.client_id == client_id]

        parent = {}

        def find(token):
            parent.setdefault(token, token)
            while parent[token] != token:
                parent[token] = parent[parent[token]]
                token = parent[token]
            return token

        def union(*tokens):
            tokens = [token for token in tokens if token]
            if not tokens:
                return
            root = find(tokens[0])
            for token in tokens[1:]:
                other = find(token)
                if other != root:
                    parent[other] = root

        for row in client_deals:
            union(f"d:{row.pk}", f"o:{row.order_id}" if row.order_id else None)
        for row in client_reviews:
            if _is_superseded_review(row):
                union(f"r:{row.pk}")
                continue
            union(
                f"r:{row.pk}",
                f"d:{row.deal_id}" if row.deal_id else None,
                f"o:{row.order_id}" if row.order_id else None,
            )
        for row in client_attrs:
            union(
                f"a:{row.pk}",
                f"d:{row.deal_id}" if row.deal_id else None,
                f"r:{row.payment_review_id}" if row.payment_review_id else None,
                f"o:{row.order_id}" if row.order_id else None,
            )

        components = {}
        for token in list(parent):
            components.setdefault(find(token), set()).add(token)

        candidates = []
        for tokens in components.values():
            deal_rows = [row for row in client_deals if f"d:{row.pk}" in tokens]
            review_rows = [row for row in client_reviews if f"r:{row.pk}" in tokens]
            attr_rows = [row for row in client_attrs if f"a:{row.pk}" in tokens]
            order_ids = {int(token.split(":", 1)[1]) for token in tokens if token.startswith("o:")}
            if len(deal_rows) > 1 or len(attr_rows) > 1 or len(order_ids) > 1:
                raise RuntimeError(
                    "Instagram commercial backfill conflict: one episode maps to "
                    "multiple deals, attributions, or physical orders"
                )
            deal = deal_rows[0] if deal_rows else None
            attribution = attr_rows[0] if attr_rows else None
            order = orders_by_id.get(next(iter(order_ids), None))
            review = max(
                review_rows,
                key=lambda row: (getattr(row, "created_at", None), row.pk),
                default=None,
            )
            timestamps = [
                value for value in [
                    getattr(deal, "created_at", None),
                    *(getattr(row, "created_at", None) for row in review_rows),
                    *(getattr(row, "superseded_at", None) for row in review_rows),
                    getattr(attribution, "created_at", None),
                    getattr(order, "created", None),
                ] if value is not None
            ]
            opened_at = min(timestamps) if timestamps else None
            last_at = max(timestamps) if timestamps else None
            candidates.append({
                "opened_at": opened_at,
                "tokens": sorted(tokens),
                "deal": deal,
                "review": review,
                "attribution": attribution,
                "order": order,
                "last_at": last_at,
            })

        candidates.sort(key=lambda row: (
            row["opened_at"] is None,
            row["opened_at"],
            row["tokens"],
        ))
        client_plans.append((client_id, client, candidates))

    # MariaDB commits schema/data statements around non-atomic migrations. Do
    # every relation/materialization collision check globally before the first
    # historical episode write so a late bad client cannot leave a partial
    # backfill behind.
    for client_id, _client, candidates in client_plans:
        for candidate in candidates:
            deal = candidate["deal"]
            review = candidate["review"]
            attribution = candidate["attribution"]
            order = candidate["order"]
            key_digest = hashlib.sha256(
                "|".join(candidate["tokens"]).encode("utf-8")
            ).hexdigest()[:64]
            materialization_key = f"legacy-component:{key_digest}"
            relation_match = models.Q(materialization_key=materialization_key)
            expected = {
                "deal_id": getattr(deal, "pk", None),
                "primary_payment_review_id": getattr(review, "pk", None),
                "order_attribution_id": getattr(attribution, "pk", None),
                "intended_order_id": getattr(order, "pk", None),
            }
            for field, value in expected.items():
                if value:
                    relation_match |= models.Q(**{field: value})
            existing = list(
                IgCommercialEpisode.objects.using(alias).filter(relation_match)
            )
            if len(existing) > 1:
                matching_episode_ids = sorted(episode.pk for episode in existing)
                raise RuntimeError(
                    "Instagram commercial backfill collision: component already spans "
                    "multiple commercial episodes; "
                    f"client_id={client_id} tokens={candidate['tokens']} "
                    f"expected_relations={expected} "
                    f"matching_episode_ids={matching_episode_ids}"
                )
            if existing:
                episode = existing[0]
                if episode.client_id != client_id:
                    raise RuntimeError(
                        "Instagram commercial backfill collision: component belongs "
                        "to another client"
                    )
                stable_relation_matches = any(
                    value and getattr(episode, field) == value
                    for field, value in expected.items()
                    if field != "primary_payment_review_id"
                )
                for field, value in expected.items():
                    current_value = getattr(episode, field)
                    # Пустое `value` — не конфликт, а отсутствие сведений у
                    # компонента: эпизод просто знает больше. Раньше условие
                    # `current_value not in {None, value}` при `value=None`
                    # означало «эпизод обязан быть тоже пустым», и любая связь
                    # эпизода со сделкой валила весь прогон.
                    #
                    # Прод, 02.08.2026: у клиента #5 появился эпизод со сделкой
                    # (ep#4, deal=5, review=3), а payment review на проде идут с
                    # `deal_id IS NULL` — все 28 записей. Поэтому команда
                    # `reconcile_ig_commercial_episodes` начала падать с
                    # «collision on deal_id», а вместе с ней падал и демон бота:
                    # она вызывается на каждом старте после reload. В логе это
                    # выглядело как `daemon_spawn` каждую минуту без ни одного
                    # `daemon_start`.
                    #
                    # Проверка теперь согласована с блоком записи ниже, где
                    # `updates` формируется через `if value and ...`, то есть
                    # пустые значения и так игнорируются.
                    if not value:
                        continue
                    if current_value not in {None, value}:
                        if (
                            field == "primary_payment_review_id"
                            and stable_relation_matches
                        ):
                            continue
                        raise RuntimeError(
                            f"Instagram commercial backfill collision on {field}"
                        )
                candidate["existing_episode_id"] = episode.pk
            else:
                candidate["existing_episode_id"] = None
            candidate["materialization_key"] = materialization_key

    for client_id, client, candidates in client_plans:
        next_sequence = (
            max(
                IgCommercialEpisode.objects.using(alias)
                .filter(client_id=client_id)
                .values_list("sequence", flat=True),
                default=0,
            ) + 1
        )
        built = []
        for candidate in candidates:
            opened_at = candidate["opened_at"]
            tokens = candidate["tokens"]
            deal = candidate["deal"]
            review = candidate["review"]
            attribution = candidate["attribution"]
            order = candidate["order"]
            last_at = candidate["last_at"]
            order_status = str(getattr(order, "status", "") or "")
            projection = projections_by_deal.get(getattr(deal, "pk", None))
            provider_truth = str(
                getattr(projection, "truth", "")
                or getattr(deal, "payment_truth", "")
                or ""
            )
            if order_status == "done":
                state, outcome = "fulfilled", "fulfilled"
            elif order_status == "cancelled":
                state, outcome = "cancelled", "order_cancelled"
            elif provider_truth in {"refunded", "reversed", "failed", "cancelled"}:
                state, outcome = "cancelled", provider_truth
            elif order is not None:
                state, outcome = "order_created", "order_created"
            elif _is_superseded_review(review):
                state, outcome = "lost", "superseded_duplicate_payment_review"
            elif review is not None and review.status == "cancelled":
                state, outcome = "cancelled", "payment_rejected"
            elif (deal is not None and deal.status == "cancelled") or provider_truth in {
                "partially_refunded", "refunded", "reversed", "failed", "cancelled"
            }:
                state, outcome = "cancelled", provider_truth or "deal_cancelled"
            else:
                state, outcome = "active", ""

            deal_items = list(
                IgDealItem.objects.using(alias).filter(deal_id=getattr(deal, "pk", None))
            ) if deal is not None else []
            product_snapshot = [
                {
                    "product_id": item.product_id,
                    "color_variant_id": item.color_variant_id,
                    "title": item.title,
                    "size": item.size or "",
                    "fit_option_code": item.fit_option_code or "",
                    "qty": item.qty,
                    "unit_price": str(item.unit_price),
                    "line_total": str(item.line_total),
                    "price_source": item.price_source or "",
                    "price_evidence_message_ids": item.price_evidence_message_ids or [],
                }
                for item in deal_items
            ]
            exact_decisions = decisions_by_review.get(getattr(review, "pk", None), [])
            decision = exact_decisions[-1] if exact_decisions else None
            negotiated_total = getattr(attribution, "negotiated_total", None)
            if negotiated_total is None:
                negotiated_total = getattr(deal, "amount", None)
            order_subtotal, order_discount, payable_order_total = order_amounts(order)
            price_snapshot = {
                "negotiated_total": str(negotiated_total) if negotiated_total is not None else "",
                "order_subtotal": f"{order_subtotal:.2f}" if order is not None else "",
                "order_discount_amount": f"{order_discount:.2f}" if order is not None else "",
                "actual_order_total": f"{payable_order_total:.2f}" if order is not None else "",
                "price_source": getattr(attribution, "price_source", "") or "",
                "price_evidence_message_ids": getattr(
                    attribution, "price_evidence_message_ids", []
                ) or [],
            }
            provider_gross = money(getattr(projection, "gross_amount", None))
            provider_refunded = money(getattr(projection, "refunded_amount", None))
            if projection is None:
                provider_gross = money(getattr(deal, "paid_amount", None))
                provider_refunded = money(getattr(deal, "refunded_amount", None))
            provider_confirmed = Decimal("0.00")
            if provider_truth in {"confirmed", "partially_refunded"}:
                provider_confirmed = max(
                    provider_gross - provider_refunded, Decimal("0.00")
                )
            payment_snapshot = {
                "requested_payment_amount": str(
                    getattr(deal, "requested_payment_amount", "") or ""
                ),
                "provider_truth": provider_truth,
                "provider_source": (
                    "monobank_projection" if projection is not None else "legacy_deal_mirror"
                ),
                "provider_confirmed_amount": f"{provider_confirmed:.2f}",
                "provider_refunded_amount": f"{provider_refunded:.2f}",
                "needs_reconciliation": bool(
                    getattr(projection, "needs_reconciliation", False)
                ),
                "manager_truth": getattr(decision, "decision", "") or "",
                "manager_confirmed_amount": (
                    str(decision.confirmed_amount)
                    if decision is not None and decision.confirmed_amount is not None
                    else ""
                ),
            }
            fulfillment_snapshot = {
                "order_status": order_status,
                "payment_status": getattr(order, "payment_status", "") or "",
                "tracking_number": getattr(order, "tracking_number", "") or "",
                "shipment_status": getattr(order, "shipment_status", "") or "",
            } if order is not None else {}
            defaults = {
                    "client_id": client_id,
                    "sequence": next_sequence,
                    "open_slot": None,
                    "state": state,
                    "repeat_kind": "first_purchase" if next_sequence == 1 else "reorder",
                    "deal_id": getattr(deal, "pk", None),
                    "primary_payment_review_id": getattr(review, "pk", None),
                    "order_attribution_id": getattr(attribution, "pk", None),
                    "intended_order_id": getattr(order, "pk", None),
                    "stage_snapshot": {"stage": getattr(client, "stage", "") or ""},
                    "product_snapshot": product_snapshot or getattr(attribution, "item_provenance", []) or [],
                    "price_snapshot": price_snapshot,
                    "payment_snapshot": payment_snapshot,
                    "fulfillment_snapshot": fulfillment_snapshot,
                    "outcome": outcome,
                    "opened_watermark_message_id": max(
                        [
                            int(getattr(review, "watermark_message_id", 0) or 0),
                            int(getattr(attribution, "evidence_watermark_message_id", 0) or 0),
                        ]
                    ),
                    "closed_at": last_at if state != "active" else None,
            }
            if candidate["existing_episode_id"]:
                episode = IgCommercialEpisode.objects.using(alias).get(
                    pk=candidate["existing_episode_id"]
                )
                created = False
            else:
                episode, created = IgCommercialEpisode.objects.using(alias).get_or_create(
                    materialization_key=candidate["materialization_key"],
                    defaults=defaults,
                )
            if created:
                next_sequence += 1
                if opened_at is not None:
                    IgCommercialEpisode.objects.using(alias).filter(pk=episode.pk).update(
                        opened_at=opened_at
                    )
                    episode.opened_at = opened_at
            else:
                expected = {
                    "deal_id": getattr(deal, "pk", None),
                    "primary_payment_review_id": getattr(review, "pk", None),
                    "order_attribution_id": getattr(attribution, "pk", None),
                    "intended_order_id": getattr(order, "pk", None),
                }
                updates = {
                    field: value
                    for field, value in expected.items()
                    if value and (
                        getattr(episode, field) is None
                        or field == "primary_payment_review_id"
                    )
                }
                updates.update({
                    "state": state,
                    "outcome": outcome,
                    "product_snapshot": product_snapshot or getattr(attribution, "item_provenance", []) or [],
                    "price_snapshot": price_snapshot,
                    "payment_snapshot": payment_snapshot,
                    "fulfillment_snapshot": fulfillment_snapshot,
                    "closed_at": last_at if state != "active" else None,
                })
                IgCommercialEpisode.objects.using(alias).filter(pk=episode.pk).update(
                    **updates
                )
                for field, value in updates.items():
                    setattr(episode, field, value)
            IgCommercialEpisodeEvent.objects.using(alias).get_or_create(
                dedupe_key=f"episode-backfill:{episode.pk}",
                defaults={
                    "episode_id": episode.pk,
                    "event_type": "historical_backfill",
                    "from_state": "",
                    "to_state": state,
                    "stage": getattr(client, "stage", "") or "",
                    "source": "migration_0107",
                    "evidence": {"tokens": tokens},
                },
            )
            built.append(episode)

        current = max(
            (row for row in built if row.state == "active" and row.intended_order_id is None),
            key=lambda row: (row.opened_at, row.sequence, row.pk),
            default=None,
        )
        IgCommercialEpisode.objects.using(alias).filter(
            client_id=client_id, open_slot=1
        ).update(open_slot=None)
        if current is not None:
            IgCommercialEpisode.objects.using(alias).filter(pk=current.pk).update(
                open_slot=1
            )
        IgClient.objects.using(alias).filter(pk=client_id).update(
            current_commercial_episode_id=current.pk if current is not None else None
        )


def noop_backfill(apps, schema_editor):
    pass


def create_append_only_triggers(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor in {"mysql", "mariadb"}:
        schema_editor.execute("DROP TRIGGER IF EXISTS ig_episode_event_no_update")
        schema_editor.execute("DROP TRIGGER IF EXISTS ig_episode_event_no_delete")
        schema_editor.execute(
            "CREATE TRIGGER ig_episode_event_no_update BEFORE UPDATE "
            "ON management_igcommercialepisodeevent FOR EACH ROW SIGNAL SQLSTATE '45000' "
            "SET MESSAGE_TEXT = 'IgCommercialEpisodeEvent is append-only'"
        )
        schema_editor.execute(
            "CREATE TRIGGER ig_episode_event_no_delete BEFORE DELETE "
            "ON management_igcommercialepisodeevent FOR EACH ROW SIGNAL SQLSTATE '45000' "
            "SET MESSAGE_TEXT = 'IgCommercialEpisodeEvent is append-only'"
        )
    elif vendor == "sqlite":
        schema_editor.execute("DROP TRIGGER IF EXISTS ig_episode_event_no_update")
        schema_editor.execute("DROP TRIGGER IF EXISTS ig_episode_event_no_delete")
        schema_editor.execute(
            "CREATE TRIGGER ig_episode_event_no_update BEFORE UPDATE ON "
            "management_igcommercialepisodeevent BEGIN SELECT RAISE(ABORT, "
            "'IgCommercialEpisodeEvent is append-only'); END"
        )
        schema_editor.execute(
            "CREATE TRIGGER ig_episode_event_no_delete BEFORE DELETE ON "
            "management_igcommercialepisodeevent BEGIN SELECT RAISE(ABORT, "
            "'IgCommercialEpisodeEvent is append-only'); END"
        )


def drop_append_only_triggers(apps, schema_editor):
    if schema_editor.connection.vendor in {"mysql", "mariadb", "sqlite"}:
        schema_editor.execute("DROP TRIGGER IF EXISTS ig_episode_event_no_update")
        schema_editor.execute("DROP TRIGGER IF EXISTS ig_episode_event_no_delete")


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('management', '0105_ig_deal_delivery_truth'),
        ('orders', '0052_dynamic_prepayment_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='igpaymentreviewdecision',
            name='amount_evidence_message_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='igpaymentreviewdecision',
            name='amount_source',
            field=models.CharField(blank=True, default='', max_length=48),
        ),
        migrations.AddField(
            model_name='igpaymentreviewdecision',
            name='confirmed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Точна сума, фактично перевірена менеджером; не повна вартість замовлення за замовчуванням.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='igpaymentreviewdecision',
            name='currency',
            field=models.CharField(default='UAH', max_length=8),
        ),
        migrations.AddField(
            model_name='igdeal',
            name='requested_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Сума конкретного платіжного запиту; не замінює повну вартість замовлення.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='igdeal',
            name='requested_payment_evidence_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='igdeal',
            name='pay_type',
            field=models.CharField(choices=[('online_full', 'Повна онлайн-оплата'), ('prepayment', 'Передоплата за погодженою сумою'), ('prepay_200', 'Передоплата 200 грн (legacy)')], default='online_full', max_length=20),
        ),
        migrations.CreateModel(
            name='IgCommercialEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('open_slot', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('materialization_key', models.CharField(max_length=96, unique=True)),
                ('state', models.CharField(choices=[('active', 'Активний цикл'), ('order_created', 'Замовлення створено'), ('fulfilled', 'Замовлення виконано'), ('cancelled', 'Скасовано'), ('lost', 'Втрачено')], db_index=True, default='active', max_length=24)),
                ('repeat_kind', models.CharField(choices=[('first_purchase', 'Перша покупка'), ('explicit_more', 'Хоче ще'), ('reorder', 'Повторне замовлення'), ('gift', 'Подарунок'), ('another_recipient', 'Для іншого отримувача')], db_index=True, default='first_purchase', max_length=32)),
                ('stage_snapshot', models.JSONField(blank=True, default=dict)),
                ('product_snapshot', models.JSONField(blank=True, default=list)),
                ('price_snapshot', models.JSONField(blank=True, default=dict)),
                ('payment_snapshot', models.JSONField(blank=True, default=dict)),
                ('fulfillment_snapshot', models.JSONField(blank=True, default=dict)),
                ('outcome', models.CharField(blank=True, default='', max_length=64)),
                ('repeat_evidence_message_ids', models.JSONField(blank=True, default=list)),
                ('repeat_confidence', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('analysis_model', models.CharField(blank=True, default='', max_length=80)),
                ('analysis_prompt_version', models.CharField(blank=True, default='', max_length=80)),
                ('opened_watermark_message_id', models.BigIntegerField(db_index=True, default=0)),
                ('shipment_notified_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='commercial_episodes', to='management.igclient')),
                ('deal', models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='commercial_episode', to='management.igdeal')),
                ('intended_order', models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instagram_commercial_episode', to='orders.order')),
                ('order_attribution', models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='commercial_episode', to='management.igorderattribution')),
                ('primary_payment_review', models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='commercial_episode', to='management.igpaymentconfirmationreview')),
            ],
            options={
                'verbose_name': 'Комерційний епізод Instagram',
                'verbose_name_plural': 'Комерційні епізоди Instagram',
                'ordering': ['-sequence', '-id'],
            },
        ),
        migrations.AddField(
            model_name='igclient',
            name='current_commercial_episode',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_for_clients', to='management.igcommercialepisode'),
        ),
        migrations.CreateModel(
            name='IgCommercialEpisodeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dedupe_key', models.CharField(max_length=160, unique=True)),
                ('event_type', models.CharField(max_length=40)),
                ('from_state', models.CharField(blank=True, default='', max_length=32)),
                ('to_state', models.CharField(blank=True, default='', max_length=32)),
                ('stage', models.CharField(blank=True, default='', max_length=32)),
                ('source', models.CharField(blank=True, default='', max_length=40)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('episode', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='management.igcommercialepisode')),
            ],
            options={
                'verbose_name': 'Подія комерційного епізоду Instagram',
                'verbose_name_plural': 'Події комерційних епізодів Instagram',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='igcommercialepisode',
            index=models.Index(fields=['client', '-opened_at'], name='ig_episode_client_opened'),
        ),
        migrations.AddIndex(
            model_name='igcommercialepisode',
            index=models.Index(fields=['state', '-updated_at'], name='ig_episode_state_updated'),
        ),
        migrations.AddConstraint(
            model_name='igcommercialepisode',
            constraint=models.UniqueConstraint(fields=('client', 'sequence'), name='ig_episode_client_sequence_once'),
        ),
        migrations.AddConstraint(
            model_name='igcommercialepisode',
            constraint=models.UniqueConstraint(fields=('client', 'open_slot'), name='ig_episode_one_open_slot'),
        ),
        migrations.AddConstraint(
            model_name='igcommercialepisode',
            constraint=models.CheckConstraint(condition=models.Q(('open_slot__isnull', True), ('open_slot', 1), _connector='OR'), name='ig_episode_open_slot_null_or_one'),
        ),
        migrations.AddIndex(
            model_name='igcommercialepisodeevent',
            index=models.Index(fields=['episode', '-created_at'], name='ig_episode_event_dt'),
        ),
        migrations.AddField(
            model_name='igconversationanalysissnapshot',
            name='repeat_intent',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='igconversationanalysissnapshot',
            name='commercial_episode',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='analysis_snapshots', to='management.igcommercialepisode'),
        ),
    ]
