# Generated by Django 5.2.11 on 2026-07-26 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0108_alter_instagrambotsettings_system_prompt'),
        ('orders', '0052_dynamic_prepayment_choice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='igpaymentconfirmationreview',
            name='supersede_reason',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='igpaymentconfirmationreview',
            name='superseded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='igpaymentconfirmationreview',
            name='superseded_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_reviews', to='management.igpaymentconfirmationreview'),
        ),
        migrations.AlterField(
            model_name='igpaymentconfirmationreview',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує підтвердження'), ('confirmed', 'Підтверджено менеджером'), ('cancelled', 'Скасовано менеджером'), ('superseded', 'Замінено канонічною перевіркою')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AddIndex(
            model_name='igpaymentconfirmationreview',
            index=models.Index(fields=['superseded_by', '-id'], name='ig_payreview_superseded'),
        ),
    ]
