# Generated by Django 5.2.11 on 2026-07-26 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0109_igpaymentconfirmationreview_supersede_reason_and_more'),
        ('orders', '0052_dynamic_prepayment_choice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IgPostSaleCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(choices=[('exchange', 'Обмін'), ('return', 'Повернення')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('needs_details', 'Потрібні уточнення'), ('open', 'Відкрито'), ('approved', 'Погоджено'), ('in_transit', 'У дорозі'), ('received', 'Отримано'), ('completed', 'Завершено'), ('rejected', 'Відхилено'), ('cancelled', 'Скасовано')], db_index=True, default='needs_details', max_length=24)),
                ('source_item_title', models.CharField(blank=True, default='', max_length=255)),
                ('source_fit', models.CharField(blank=True, default='', max_length=64)),
                ('source_size', models.CharField(blank=True, default='', max_length=32)),
                ('requested_fit', models.CharField(blank=True, default='', max_length=64)),
                ('requested_size', models.CharField(blank=True, default='', max_length=32)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('manager_note', models.TextField(blank=True, default='')),
                ('evidence_message_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='post_sale_cases', to='management.igclient')),
                ('commercial_episode', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='post_sale_cases', to='management.igcommercialepisode')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ig_post_sale_cases_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instagram_post_sale_cases', to='orders.order')),
                ('source_message', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='post_sale_case', to='management.instagrambotmessage')),
            ],
            options={
                'verbose_name': 'Післяпродажне звернення Instagram',
                'verbose_name_plural': 'Післяпродажні звернення Instagram',
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['client', 'status', '-updated_at'], name='ig_postsale_client_state'), models.Index(fields=['order', '-updated_at'], name='ig_postsale_order_dt')],
            },
        ),
    ]
