# Generated by Django 5.2.11 on 2026-07-30 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


REFRESH_TABLES = (
    "management_iginboxrefreshrun",
    "management_iginboxrefreshitem",
)


def convert_refresh_tables_to_innodb(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    quote = schema_editor.quote_name
    with schema_editor.connection.cursor() as cursor:
        for table in REFRESH_TABLES:
            cursor.execute(
                "SELECT ENGINE FROM information_schema.TABLES "
                "WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=%s",
                [table],
            )
            row = cursor.fetchone()
            if row is None:
                raise RuntimeError(f"required inbox refresh table is missing: {table}")
            if str(row[0]).lower() != "innodb":
                schema_editor.execute(f"ALTER TABLE {quote(table)} ENGINE=InnoDB")


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('management', '0114_instagrambotsettings_link_send_circuit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IgInboxRefreshRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_owner_id', models.CharField(db_index=True, max_length=128)),
                ('transport', models.CharField(default='instagram_login', max_length=32)),
                ('open_slot', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('status', models.CharField(choices=[('queued', 'У черзі'), ('discovering', 'Пошук переписок'), ('running', 'Оновлення повідомлень'), ('cancelling', 'Скасування'), ('completed', 'Завершено'), ('completed_errors', 'Завершено з помилками'), ('cancelled', 'Скасовано'), ('failed', 'Помилка')], db_index=True, default='queued', max_length=24)),
                ('recovery_cutoff', models.DateTimeField(db_index=True)),
                ('discovery_cursor', models.TextField(blank=True, default='')),
                ('discovery_pages_seen', models.PositiveSmallIntegerField(default=0)),
                ('discovery_complete', models.BooleanField(default=False)),
                ('lease_token', models.CharField(blank=True, default='', max_length=64)),
                ('lease_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=1000)),
                ('cancel_requested_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ig_inbox_refresh_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Оновлення Instagram inbox',
                'verbose_name_plural': 'Оновлення Instagram inbox',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='IgInboxRefreshItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=255)),
                ('participant_igsid', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('provider_updated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('processing', 'Обробка'), ('done', 'Готово'), ('skipped', 'Пропущено'), ('failed', 'Помилка'), ('cancelled', 'Скасовано')], db_index=True, default='pending', max_length=16)),
                ('skip_reason', models.CharField(blank=True, default='', max_length=64)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('lease_token', models.CharField(blank=True, default='', max_length=64)),
                ('lease_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('messages_seen', models.PositiveSmallIntegerField(default=0)),
                ('messages_created', models.PositiveSmallIntegerField(default=0)),
                ('messages_existing', models.PositiveSmallIntegerField(default=0)),
                ('messages_after_cutoff', models.PositiveSmallIntegerField(default=0)),
                ('analysis_watermark_message_id', models.PositiveBigIntegerField(default=0)),
                ('history_cursor', models.TextField(blank=True, default='')),
                ('history_complete', models.BooleanField(default=False)),
                ('truncated_reason', models.CharField(blank=True, default='', max_length=64)),
                ('provider_http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=1000)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_refresh_items', to='management.igclient')),
                ('run', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='management.iginboxrefreshrun')),
            ],
            options={
                'verbose_name': 'Переписка оновлення Instagram inbox',
                'verbose_name_plural': 'Переписки оновлення Instagram inbox',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='iginboxrefreshrun',
            index=models.Index(fields=['status', 'next_attempt_at', 'id'], name='ig_refresh_run_due'),
        ),
        migrations.AddIndex(
            model_name='iginboxrefreshrun',
            index=models.Index(fields=['provider_owner_id', '-created_at'], name='ig_refresh_owner_dt'),
        ),
        migrations.AddConstraint(
            model_name='iginboxrefreshrun',
            constraint=models.UniqueConstraint(fields=('provider_owner_id', 'open_slot'), name='ig_refresh_one_open_owner'),
        ),
        migrations.AddConstraint(
            model_name='iginboxrefreshrun',
            constraint=models.CheckConstraint(condition=models.Q(('open_slot__isnull', True), ('open_slot', 1), _connector='OR'), name='ig_refresh_open_null_one'),
        ),
        migrations.AddIndex(
            model_name='iginboxrefreshitem',
            index=models.Index(fields=['status', 'next_attempt_at', 'id'], name='ig_refresh_item_due'),
        ),
        migrations.AddIndex(
            model_name='iginboxrefreshitem',
            index=models.Index(fields=['run', 'status', 'id'], name='ig_refresh_item_run'),
        ),
        migrations.AddIndex(
            model_name='iginboxrefreshitem',
            index=models.Index(fields=['participant_igsid', 'status'], name='ig_refresh_item_user'),
        ),
        migrations.AddConstraint(
            model_name='iginboxrefreshitem',
            constraint=models.UniqueConstraint(fields=('run', 'conversation_id'), name='ig_refresh_item_run_conv'),
        ),
        migrations.RunPython(
            convert_refresh_tables_to_innodb,
            migrations.RunPython.noop,
        ),
    ]
