# Generated by Django 5.2.11 on 2026-07-30 21:15

import django.db.models.deletion
import django.utils.timezone
import management.ig_bot_models
import uuid
from django.db import migrations, models


CHECKOUT_TABLES = (
    'management_igcheckoutproposal',
    'management_igcheckoutaccesstoken',
    'management_igcheckoutproposalitem',
    'management_igcheckoutinventoryreservation',
    'management_igcheckoutrevision',
    'management_iglifecycleevent',
)

CHECKOUT_TRIGGER_NAMES = (
    'ig_chk_revision_no_update',
    'ig_chk_revision_no_delete',
    'ig_chk_lifecycle_no_delete',
    'ig_chk_lifecycle_identity_no_update',
)


def convert_checkout_tables_to_innodb(apps, schema_editor):
    if schema_editor.connection.vendor != 'mysql':
        return
    quote = schema_editor.quote_name
    with schema_editor.connection.cursor() as cursor:
        for table in CHECKOUT_TABLES:
            cursor.execute(
                'SELECT ENGINE FROM information_schema.TABLES '
                'WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=%s',
                [table],
            )
            row = cursor.fetchone()
            if row is None:
                raise RuntimeError(f'required Instagram checkout table is missing: {table}')
            if str(row[0]).lower() != 'innodb':
                schema_editor.execute(f'ALTER TABLE {quote(table)} ENGINE=InnoDB')


def drop_checkout_evidence_triggers(apps, schema_editor):
    for name in CHECKOUT_TRIGGER_NAMES:
        schema_editor.execute(f'DROP TRIGGER IF EXISTS {name}')


def create_checkout_evidence_triggers(apps, schema_editor):
    drop_checkout_evidence_triggers(apps, schema_editor)
    vendor = schema_editor.connection.vendor
    if vendor in {'mysql', 'mariadb'}:
        schema_editor.execute(
            "CREATE TRIGGER ig_chk_revision_no_update BEFORE UPDATE "
            "ON management_igcheckoutrevision FOR EACH ROW "
            "SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'IgCheckoutRevision is append-only'"
        )
        schema_editor.execute(
            "CREATE TRIGGER ig_chk_revision_no_delete BEFORE DELETE "
            "ON management_igcheckoutrevision FOR EACH ROW "
            "SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'IgCheckoutRevision is append-only'"
        )
        schema_editor.execute(
            "CREATE TRIGGER ig_chk_lifecycle_no_delete BEFORE DELETE "
            "ON management_iglifecycleevent FOR EACH ROW "
            "SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'IgLifecycleEvent is durable'"
        )
        schema_editor.execute(
            "CREATE TRIGGER ig_chk_lifecycle_identity_no_update BEFORE UPDATE "
            "ON management_iglifecycleevent FOR EACH ROW BEGIN "
            "IF NOT (OLD.event_key <=> NEW.event_key) OR OLD.kind <> NEW.kind "
            "OR OLD.client_id <> NEW.client_id OR OLD.deal_id <> NEW.deal_id "
            "OR OLD.proposal_id <> NEW.proposal_id OR OLD.order_id <> NEW.order_id "
            "OR OLD.commercial_episode_id <> NEW.commercial_episode_id "
            "OR OLD.attribution_id <> NEW.attribution_id OR OLD.locale <> NEW.locale "
            "OR NOT (OLD.payload <=> NEW.payload) THEN "
            "SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'IgLifecycleEvent identity is immutable'; "
            "END IF; END"
        )
    elif vendor == 'sqlite':
        schema_editor.execute(
            "CREATE TRIGGER ig_chk_revision_no_update BEFORE UPDATE "
            "ON management_igcheckoutrevision BEGIN SELECT RAISE(ABORT, "
            "'IgCheckoutRevision is append-only'); END"
        )
        schema_editor.execute(
            "CREATE TRIGGER ig_chk_revision_no_delete BEFORE DELETE "
            "ON management_igcheckoutrevision BEGIN SELECT RAISE(ABORT, "
            "'IgCheckoutRevision is append-only'); END"
        )
        schema_editor.execute(
            "CREATE TRIGGER ig_chk_lifecycle_no_delete BEFORE DELETE "
            "ON management_iglifecycleevent BEGIN SELECT RAISE(ABORT, "
            "'IgLifecycleEvent is durable'); END"
        )
        schema_editor.execute(
            "CREATE TRIGGER ig_chk_lifecycle_identity_no_update BEFORE UPDATE "
            "ON management_iglifecycleevent WHEN OLD.event_key IS NOT NEW.event_key "
            "OR OLD.kind IS NOT NEW.kind OR OLD.client_id IS NOT NEW.client_id "
            "OR OLD.deal_id IS NOT NEW.deal_id OR OLD.proposal_id IS NOT NEW.proposal_id "
            "OR OLD.order_id IS NOT NEW.order_id "
            "OR OLD.commercial_episode_id IS NOT NEW.commercial_episode_id "
            "OR OLD.attribution_id IS NOT NEW.attribution_id OR OLD.locale IS NOT NEW.locale "
            "OR OLD.payload IS NOT NEW.payload BEGIN SELECT RAISE(ABORT, "
            "'IgLifecycleEvent identity is immutable'); END"
        )


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('management', '0115_ig_inbox_refresh_runs'),
        ('orders', '0052_dynamic_prepayment_choice'),
        ('productcolors', '0007_normalize_slugs'),
        ('storefront', '0086_marketplace_feed_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgCheckoutProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ready', 'Готова'), ('viewed', 'Переглянута'), ('details_locked', 'Дані зафіксовані'), ('invoice_created', 'Рахунок створено'), ('paid', 'Оплачено'), ('cancelled', 'Рахунок скасовано'), ('expired', 'Протерміновано'), ('revoked', 'Відкликано'), ('superseded', 'Замінено')], db_index=True, default='ready', max_length=24)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('locale', models.CharField(default='uk', max_length=12)),
                ('currency', models.CharField(default='UAH', max_length=8)),
                ('catalog_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('negotiated_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quoted_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('requested_payment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pay_type', models.CharField(choices=[('online_full', 'Повна онлайн-оплата'), ('prepayment', 'Передоплата')], default='online_full', max_length=20)),
                ('allow_promo', models.BooleanField(default=False)),
                ('items_digest', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField(db_index=True, default=management.ig_bot_models.default_checkout_proposal_expiry)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('details_locked_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('provider_cancellation_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_checkout_proposals', to='management.igpaymentevent')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_proposals', to='management.igclient')),
                ('commercial_episode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_proposals', to='management.igcommercialepisode')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_proposals', to='management.igdeal')),
                ('payment_attempt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instagram_checkout_proposal', to='orders.paymentattempt')),
                ('superseded_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supersedes', to='management.igcheckoutproposal')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IgCheckoutAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('kind', models.CharField(choices=[('bot', 'Посилання бота'), ('share', 'Посилання для оплати іншою людиною'), ('replacement', 'Посилання заміни')], default='bot', max_length=16)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='management.igcheckoutproposal')),
            ],
        ),
        migrations.AddField(
            model_name='igdeal',
            name='active_checkout_proposal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_deal', to='management.igcheckoutproposal'),
        ),
        migrations.CreateModel(
            name='IgCheckoutProposalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, default='', max_length=128)),
                ('image_url', models.CharField(blank=True, default='', max_length=600)),
                ('color_code', models.CharField(blank=True, default='', max_length=64)),
                ('color_label', models.CharField(blank=True, default='', max_length=100)),
                ('size', models.CharField(blank=True, default='', max_length=32)),
                ('fit_code', models.CharField(blank=True, default='', max_length=64)),
                ('fit_label', models.CharField(blank=True, default='', max_length=100)),
                ('option_values', models.JSONField(blank=True, default=dict)),
                ('option_labels', models.JSONField(blank=True, default=dict)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('catalog_unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('catalog_line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quoted_unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quoted_line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_source', models.CharField(blank=True, default='catalog', max_length=64)),
                ('evidence_message_ids', models.JSONField(blank=True, default=list)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color_variant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instagram_checkout_items', to='productcolors.productcolorvariant')),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instagram_checkout_items', to='storefront.product')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='management.igcheckoutproposal')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IgCheckoutInventoryReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('reservation_fingerprint', models.CharField(max_length=64, unique=True)),
                ('state', models.CharField(choices=[('active', 'Зарезервовано'), ('released', 'Звільнено'), ('consumed', 'Використано')], db_index=True, default='active', max_length=16)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('release_reason', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color_variant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instagram_checkout_reservations', to='productcolors.productcolorvariant')),
                ('product', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='instagram_checkout_reservations', to='storefront.product')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_reservations', to='management.igcheckoutproposal')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_reservations', to='management.igcheckoutproposalitem')),
            ],
        ),
        migrations.CreateModel(
            name='IgCheckoutRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('digest', models.CharField(max_length=64)),
                ('snapshot', models.JSONField(default=dict)),
                ('source', models.CharField(choices=[('bot_create', 'Створено ботом'), ('bot_update', 'Оновлено ботом'), ('system_supersede', 'Системна заміна')], max_length=24)),
                ('evidence_message_ids', models.JSONField(blank=True, default=list)),
                ('source_watermark_message_id', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='management.igcheckoutproposal')),
            ],
            options={
                'ordering': ['proposal', 'revision'],
            },
        ),
        migrations.CreateModel(
            name='IgLifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=180, unique=True)),
                ('kind', models.CharField(choices=[('payment_verified', 'Оплату підтверджено'), ('ttn_created', 'ТТН створено'), ('delivered_review_requested', 'Замовлення отримано, запит відгуку')], db_index=True, max_length=40)),
                ('locale', models.CharField(default='uk', max_length=12)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('state', models.CharField(choices=[('pending', 'Очікує'), ('processing', 'Обробляється'), ('sent', 'Надіслано'), ('waiting_window', 'Поза вікном відповіді'), ('manager_review', 'Потрібен менеджер'), ('ambiguous', 'Невідомий результат'), ('failed', 'Помилка'), ('cancelled', 'Скасовано')], db_index=True, default='pending', max_length=24)),
                ('due_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('lease_token', models.CharField(blank=True, default='', max_length=64)),
                ('lease_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=128)),
                ('last_error', models.CharField(blank=True, default='', max_length=1000)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_events', to='management.igorderattribution')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_events', to='management.igclient')),
                ('commercial_episode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_events', to='management.igcommercialepisode')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_events', to='management.igdeal')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instagram_lifecycle_events', to='orders.order')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_events', to='management.igcheckoutproposal')),
            ],
            options={
                'ordering': ['due_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='igcheckoutproposal',
            index=models.Index(fields=['status', 'expires_at'], name='ig_prop_status_exp'),
        ),
        migrations.AddIndex(
            model_name='igcheckoutproposal',
            index=models.Index(fields=['client', '-created_at'], name='ig_prop_client_dt'),
        ),
        migrations.AddIndex(
            model_name='igcheckoutproposal',
            index=models.Index(fields=['deal', '-created_at'], name='ig_prop_deal_dt'),
        ),
        migrations.AddConstraint(
            model_name='igcheckoutproposal',
            constraint=models.CheckConstraint(condition=models.Q(('catalog_total__gt', 0)), name='ig_prop_catalog_positive'),
        ),
        migrations.AddConstraint(
            model_name='igcheckoutproposal',
            constraint=models.CheckConstraint(condition=models.Q(('quoted_total__gt', 0)), name='ig_prop_quoted_positive'),
        ),
        migrations.AddConstraint(
            model_name='igcheckoutproposal',
            constraint=models.CheckConstraint(condition=models.Q(('requested_payment_amount__gt', 0)), name='ig_prop_payment_positive'),
        ),
        migrations.AddConstraint(
            model_name='igcheckoutproposal',
            constraint=models.CheckConstraint(condition=models.Q(('negotiated_discount__gte', 0)), name='ig_prop_discount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='igcheckoutproposal',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='ig_prop_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='igcheckoutproposal',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'superseded'), ('superseded_by__isnull', False)) | ~models.Q(('status', 'superseded')), name='ig_prop_superseded_link'),
        ),
        migrations.AddConstraint(
            model_name='igcheckoutproposal',
            constraint=models.CheckConstraint(condition=~models.Q(('status', 'paid'), ('superseded_by__isnull', False)), name='ig_prop_paid_not_superseded'),
        ),
        migrations.AddIndex(
            model_name='igcheckoutaccesstoken',
            index=models.Index(fields=['proposal', 'kind', 'expires_at'], name='ig_token_prop_exp'),
        ),
        migrations.AddConstraint(
            model_name='igcheckoutproposalitem',
            constraint=models.UniqueConstraint(fields=('proposal', 'position'), name='ig_prop_item_position_once'),
        ),
        migrations.AddConstraint(
            model_name='igcheckoutproposalitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ig_prop_item_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='igcheckoutproposalitem',
            constraint=models.CheckConstraint(condition=models.Q(('catalog_unit_price__gte', 0), ('quoted_unit_price__gte', 0)), name='ig_prop_item_prices_nonneg'),
        ),
        migrations.AddIndex(
            model_name='igcheckoutinventoryreservation',
            index=models.Index(fields=['state', 'expires_at'], name='ig_res_state_exp'),
        ),
        migrations.AddIndex(
            model_name='igcheckoutinventoryreservation',
            index=models.Index(fields=['proposal', 'state'], name='ig_res_prop_state'),
        ),
        migrations.AddConstraint(
            model_name='igcheckoutinventoryreservation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='ig_res_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='igcheckoutrevision',
            constraint=models.UniqueConstraint(fields=('proposal', 'revision'), name='ig_prop_revision_once'),
        ),
        migrations.AddConstraint(
            model_name='igcheckoutrevision',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='ig_prop_revision_num_pos'),
        ),
        migrations.AddIndex(
            model_name='iglifecycleevent',
            index=models.Index(fields=['state', 'due_at', 'id'], name='ig_life_state_due'),
        ),
        migrations.AddIndex(
            model_name='iglifecycleevent',
            index=models.Index(fields=['client', '-created_at'], name='ig_life_client_dt'),
        ),
        migrations.AddIndex(
            model_name='iglifecycleevent',
            index=models.Index(fields=['order', 'kind'], name='ig_life_order_kind'),
        ),
        migrations.RunPython(
            convert_checkout_tables_to_innodb,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            create_checkout_evidence_triggers,
            drop_checkout_evidence_triggers,
        ),
    ]
