# Generated by Django 5.2.11 on 2026-07-30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0116_igcheckoutproposal_igcheckoutaccesstoken_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="igpaymentconfirmationreview",
            name="resolution_kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Не завершено окремим рішенням"),
                    (
                        "historical_paid_archived",
                        "Старий оплачений продаж архівовано",
                    ),
                ],
                db_index=True,
                default="",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="igpaymentconfirmationreview",
            name="resolution_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="igpaymentconfirmationreview",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="igpaymentconfirmationreview",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_ig_payment_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
