# Generated by Django 5.2.11 on 2026-07-31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0117_ig_payment_review_resolution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IgFunnelResetAudit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reset_after_message_id", models.PositiveBigIntegerField(db_index=True, default=0)),
                ("previous_state", models.JSONField(blank=True, default=dict)),
                ("resulting_stage", models.CharField(blank=True, default="", max_length=24)),
                ("reason", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("actor", models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ig_funnel_reset_audits", to=settings.AUTH_USER_MODEL)),
                ("client", models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name="funnel_reset_audits", to="management.igclient")),
            ],
            options={
                "verbose_name": "Скидання воронки Instagram",
                "verbose_name_plural": "Скидання воронок Instagram",
                "ordering": ["-id"],
                "indexes": [models.Index(fields=["client", "-created_at"], name="ig_funnel_reset_client_dt")],
            },
        ),
    ]
