# Generated by Django 5.2.11 on 2026-07-31 10:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def _assignment_source(attribution):
    if attribution.payment_source.startswith('provider_'):
        return 'provider_auto'
    if attribution.creation_mode == 'manager_review':
        return 'manager_payment_review'
    if attribution.creation_mode == 'linked_existing':
        return 'manager_manual'
    return 'legacy_attribution'


def _backfill_operation_id(attribution_id):
    return uuid.uuid5(
        uuid.NAMESPACE_URL,
        f'twocomms:ig-order-assignment-backfill:{attribution_id}',
    )


def backfill_assignments(apps, schema_editor):
    Attribution = apps.get_model('management', 'IgOrderAttribution')
    Assignment = apps.get_model('management', 'IgOrderAssignment')
    Event = apps.get_model('management', 'IgOrderAssignmentEvent')

    for attribution in Attribution.objects.order_by('id').iterator(chunk_size=200):
        source = _assignment_source(attribution)
        assignment, created = Assignment.objects.get_or_create(
            order_id=attribution.order_id,
            defaults={
                'client_id': attribution.client_id,
                'source': source,
                'assigned_by_id': attribution.created_by_id,
                'assigned_at': attribution.created_at,
                'version': 1,
                'last_reason_code': 'legacy_attribution',
                'last_reason': 'Backfilled from immutable Instagram attribution',
            },
        )
        if not created:
            continue
        Event.objects.create(
            operation_id=_backfill_operation_id(attribution.pk),
            assignment_id=assignment.pk,
            order_id=attribution.order_id,
            kind='linked',
            to_client_id=attribution.client_id,
            actor_id=attribution.created_by_id,
            actor_source='migration',
            assignment_source=source,
            reason_code='legacy_attribution',
            reason='Backfilled from immutable Instagram attribution',
            assignment_version=1,
            snapshot={
                'attribution_id': attribution.pk,
                'creation_mode': attribution.creation_mode,
                'payment_source': attribution.payment_source,
            },
        )


def reverse_backfill_assignments(apps, schema_editor):
    Attribution = apps.get_model('management', 'IgOrderAttribution')
    Assignment = apps.get_model('management', 'IgOrderAssignment')
    Event = apps.get_model('management', 'IgOrderAssignmentEvent')
    CustomerEvent = apps.get_model('management', 'IgOrderCustomerEvent')

    for attribution in Attribution.objects.order_by('id').iterator(chunk_size=200):
        source = _assignment_source(attribution)
        event = Event.objects.filter(
            operation_id=_backfill_operation_id(attribution.pk),
            order_id=attribution.order_id,
            kind='linked',
            to_client_id=attribution.client_id,
            actor_id=attribution.created_by_id,
            actor_source='migration',
            assignment_source=source,
            reason_code='legacy_attribution',
            assignment_version=1,
        ).first()
        if event is None:
            continue

        assignment = Assignment.objects.filter(
            pk=event.assignment_id,
            order_id=attribution.order_id,
            client_id=attribution.client_id,
            source=source,
            assigned_by_id=attribution.created_by_id,
            assigned_at=attribution.created_at,
            unassigned_at__isnull=True,
            version=1,
            last_reason_code='legacy_attribution',
            last_reason='Backfilled from immutable Instagram attribution',
        ).first()
        if assignment is None:
            continue
        if Event.objects.filter(assignment_id=assignment.pk).exclude(pk=event.pk).exists():
            continue
        if CustomerEvent.objects.filter(assignment_id=assignment.pk).exists():
            continue

        Event.objects.filter(pk=event.pk).delete()
        Assignment.objects.filter(pk=assignment.pk).delete()


def create_assignment_event_guards(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    drop_assignment_event_guards(apps, schema_editor)
    if vendor in {'mysql', 'mariadb'}:
        schema_editor.execute(
            "CREATE TRIGGER ig_assignment_evt_no_update BEFORE UPDATE "
            "ON management_igorderassignmentevent FOR EACH ROW "
            "SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = "
            "'IgOrderAssignmentEvent is append-only'"
        )
        schema_editor.execute(
            "CREATE TRIGGER ig_assignment_evt_no_delete BEFORE DELETE "
            "ON management_igorderassignmentevent FOR EACH ROW "
            "SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = "
            "'IgOrderAssignmentEvent is append-only'"
        )
    elif vendor == 'sqlite':
        schema_editor.execute(
            "CREATE TRIGGER ig_assignment_evt_no_update BEFORE UPDATE "
            "ON management_igorderassignmentevent BEGIN SELECT RAISE(ABORT, "
            "'IgOrderAssignmentEvent is append-only'); END"
        )
        schema_editor.execute(
            "CREATE TRIGGER ig_assignment_evt_no_delete BEFORE DELETE "
            "ON management_igorderassignmentevent BEGIN SELECT RAISE(ABORT, "
            "'IgOrderAssignmentEvent is append-only'); END"
        )
    elif vendor == 'postgresql':
        schema_editor.execute(
            "CREATE OR REPLACE FUNCTION ig_assignment_event_append_only_raise() "
            "RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN "
            "RAISE EXCEPTION 'IgOrderAssignmentEvent is append-only'; END; $$"
        )
        schema_editor.execute(
            "CREATE TRIGGER ig_assignment_evt_no_update BEFORE UPDATE "
            "ON management_igorderassignmentevent FOR EACH ROW "
            "EXECUTE FUNCTION ig_assignment_event_append_only_raise()"
        )
        schema_editor.execute(
            "CREATE TRIGGER ig_assignment_evt_no_delete BEFORE DELETE "
            "ON management_igorderassignmentevent FOR EACH ROW "
            "EXECUTE FUNCTION ig_assignment_event_append_only_raise()"
        )


def drop_assignment_event_guards(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor in {'mysql', 'mariadb', 'sqlite'}:
        schema_editor.execute('DROP TRIGGER IF EXISTS ig_assignment_evt_no_update')
        schema_editor.execute('DROP TRIGGER IF EXISTS ig_assignment_evt_no_delete')
    elif vendor == 'postgresql':
        schema_editor.execute(
            'DROP TRIGGER IF EXISTS ig_assignment_evt_no_update '
            'ON management_igorderassignmentevent'
        )
        schema_editor.execute(
            'DROP TRIGGER IF EXISTS ig_assignment_evt_no_delete '
            'ON management_igorderassignmentevent'
        )
        schema_editor.execute(
            'DROP FUNCTION IF EXISTS ig_assignment_event_append_only_raise()'
        )


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('management', '0118_ig_funnel_reset_audit'),
        ('orders', '0052_dynamic_prepayment_choice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IgOrderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('provider_auto', 'Автоматично за оплатою'), ('checkout_auto', 'Автоматично через Direct checkout'), ('manager_payment_review', 'Менеджер після перевірки оплати'), ('manager_manual', 'Менеджер вручну'), ('manager_created', 'Створено менеджером'), ('legacy_attribution', 'Імпортовано з атрибуції')], db_index=True, max_length=32)),
                ('assigned_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('last_reason_code', models.CharField(blank=True, default='', max_length=64)),
                ('last_reason', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ig_order_assignments', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_assignments', to='management.igclient')),
                ('order', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instagram_assignment', to='orders.order')),
            ],
            options={
                'ordering': ['-assigned_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IgOrderAssignmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('linked', "Прив'язано"), ('unlinked', "Відв'язано"), ('auto_confirmed', "Автоматичну прив'язку підтверджено")], db_index=True, max_length=24)),
                ('actor_source', models.CharField(choices=[('management_user', 'Користувач management'), ('automation', 'Автоматизація'), ('migration', 'Міграція')], max_length=24)),
                ('assignment_source', models.CharField(choices=[('provider_auto', 'Автоматично за оплатою'), ('checkout_auto', 'Автоматично через Direct checkout'), ('manager_payment_review', 'Менеджер після перевірки оплати'), ('manager_manual', 'Менеджер вручну'), ('manager_created', 'Створено менеджером'), ('legacy_attribution', 'Імпортовано з атрибуції')], max_length=32)),
                ('reason_code', models.CharField(blank=True, default='', max_length=64)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('assignment_version', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ig_order_assignment_events', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='management.igorderassignment')),
                ('from_client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_assignment_events_from', to='management.igclient')),
                ('order', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instagram_assignment_events', to='orders.order')),
                ('to_client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_assignment_events_to', to='management.igclient')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='IgOrderCustomerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=180, unique=True)),
                ('assignment_version', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('ttn_assigned', "ТТН прив'язано"), ('delivered_review', 'Запит відгуку після отримання')], db_index=True, max_length=32)),
                ('locale', models.CharField(default='uk', max_length=12)),
                ('message_snapshot', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('state', models.CharField(choices=[('pending', 'Очікує'), ('processing', 'Обробляється'), ('sent', 'Надіслано'), ('waiting_window', 'Очікує вікна відповіді'), ('manager_review', 'Потрібен менеджер'), ('ambiguous', 'Невідомий результат'), ('failed', 'Помилка'), ('cancelled', 'Скасовано')], db_index=True, default='pending', max_length=24)),
                ('due_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('lease_token', models.CharField(blank=True, default='', max_length=64)),
                ('lease_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=128)),
                ('last_error', models.CharField(blank=True, default='', max_length=1000)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_events', to='management.igorderassignment')),
                ('client', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_customer_events', to='management.igclient')),
                ('order', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instagram_customer_events', to='orders.order')),
            ],
            options={
                'ordering': ['due_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='igorderassignment',
            index=models.Index(fields=['client', '-assigned_at'], name='ig_assign_client_dt'),
        ),
        migrations.AddIndex(
            model_name='igorderassignment',
            index=models.Index(fields=['source', '-assigned_at'], name='ig_assign_source_dt'),
        ),
        migrations.AddIndex(
            model_name='igorderassignmentevent',
            index=models.Index(fields=['assignment', '-created_at'], name='ig_assign_evt_dt'),
        ),
        migrations.AddIndex(
            model_name='igorderassignmentevent',
            index=models.Index(fields=['order', '-created_at'], name='ig_assign_order_evt'),
        ),
        migrations.AddIndex(
            model_name='igordercustomerevent',
            index=models.Index(fields=['state', 'due_at', 'id'], name='ig_order_evt_state_due'),
        ),
        migrations.AddIndex(
            model_name='igordercustomerevent',
            index=models.Index(fields=['client', '-created_at'], name='ig_order_evt_client_dt'),
        ),
        migrations.AddIndex(
            model_name='igordercustomerevent',
            index=models.Index(fields=['order', 'kind'], name='ig_order_evt_kind'),
        ),
        migrations.RunPython(backfill_assignments, reverse_backfill_assignments),
        migrations.RunPython(
            create_assignment_event_guards,
            drop_assignment_event_guards,
        ),
    ]
