# Generated by Django 5.2.11 on 2026-08-01 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0122_ig_interaction_type_post_sale'),
        ('orders', '0053_paymentattempt_generic_prepayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='igordercustomerevent',
            name='kind',
            field=models.CharField(choices=[('ttn_assigned', "ТТН прив'язано"), ('exchange_shipped', 'Заміну відправлено'), ('delivered_review', 'Запит відгуку після отримання')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='IgOrderShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=64)),
                ('direction', models.CharField(choices=[('outbound', 'Ми відправили'), ('inbound', 'Клієнт відправив нам')], db_index=True, max_length=16)),
                ('purpose', models.CharField(choices=[('initial', 'Перша відправка'), ('exchange_replacement', 'Заміна відправлена'), ('return_inbound', 'Повернення від клієнта'), ('correction', 'Переоформлена ТТН')], db_index=True, max_length=32)),
                ('source', models.CharField(choices=[('order_field', 'Поле замовлення'), ('manager_manual', 'Введено менеджером'), ('customer_message', 'З повідомлення клієнта')], default='order_field', max_length=32)),
                ('evidence_message_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ig_order_shipments', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instagram_shipments', to='orders.order')),
                ('post_sale_case', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shipments', to='management.igpostsalecase')),
                ('supersedes', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='superseded_by_shipments', to='management.igordershipment')),
            ],
            options={
                'verbose_name': 'Відправка замовлення Instagram',
                'verbose_name_plural': 'Відправки замовлень Instagram',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['order', 'created_at'], name='ig_shipment_order_dt'), models.Index(fields=['post_sale_case', 'created_at'], name='ig_shipment_case_dt')],
                'constraints': [models.UniqueConstraint(fields=('order', 'tracking_number', 'direction'), name='ig_shipment_once_per_direction')],
            },
        ),
    ]
