# Generated by Django 5.2.11 on 2026-08-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0123_ig_order_shipments'),
    ]

    operations = [
        migrations.AddField(
            model_name='igordershipment',
            name='payer',
            field=models.CharField(choices=[('shop', 'За наш рахунок'), ('customer', 'За рахунок клієнта'), ('unknown', 'Не визначено')], default='shop', max_length=16),
        ),
        migrations.AddField(
            model_name='igordershipment',
            name='reuses_outbound_tracking',
            field=models.BooleanField(default=False),
        ),
    ]
