# Generated by Django 5.2.11 on 2026-08-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0124_ig_shipment_payer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igordercustomerevent',
            name='kind',
            field=models.CharField(choices=[('ttn_assigned', "ТТН прив'язано"), ('exchange_shipped', 'Заміну відправлено'), ('payment_confirmed', 'Оплату підтверджено'), ('delivered_review', 'Запит відгуку після отримання')], db_index=True, max_length=32),
        ),
    ]
