# Generated by Django 5.2.11 on 2026-08-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0125_ig_payment_confirmed_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='igdeal',
            name='invoice_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
