# Generated by Django 5.2.11 on 2026-08-02 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0126_ig_invoice_expires_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotPromptRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('instruction', 'Інструкція бота'), ('knowledge_base', 'Оперативні директиви')], db_index=True, max_length=32)),
                ('target_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('kind', models.CharField(choices=[('edit', 'Зміна'), ('rollback', 'Відкат')], default='edit', max_length=16)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('previous_body', models.TextField(blank=True, default='')),
                ('actor_label', models.CharField(blank=True, default='', max_length=150)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_prompt_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ревізія промпту бота',
                'verbose_name_plural': 'Ревізії промпту бота',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['target', 'target_id', '-id'], name='bot_prompt_rev_target')],
            },
        ),
    ]
