# Generated by Django 5.2.11 on 2026-08-02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0127_bot_prompt_revision"),
        ("orders", "0053_paymentattempt_generic_prepayment"),
        ("storefront", "0087_promocodegroup_innodb"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IgUgcReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assignment_version", models.PositiveIntegerField()),
                (
                    "evidence_type",
                    models.CharField(
                        choices=[
                            ("direct_message", "Повідомлення Direct"),
                            ("instagram_url", "Посилання Instagram"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "evidence_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                (
                    "evidence_fingerprint",
                    models.CharField(max_length=64, unique=True),
                ),
                (
                    "review_note",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ugc_rewards",
                        to="management.igorderassignment",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ugc_rewards",
                        to="management.igclient",
                    ),
                ),
                (
                    "evidence_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ugc_rewards",
                        to="management.instagrambotmessage",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instagram_ugc_reward",
                        to="orders.order",
                    ),
                ),
                (
                    "promo_code",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instagram_ugc_reward",
                        to="storefront.promocode",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_ig_ugc_rewards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-reviewed_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["client", "-reviewed_at"],
                        name="ig_ugc_client_dt",
                    ),
                    models.Index(
                        fields=["assignment", "assignment_version"],
                        name="ig_ugc_assign_ver",
                    ),
                ],
            },
        ),
    ]
