# Generated by Django 5.2.11 on 2026-08-03 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0131_igfollowuptask_durable_claim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igconversationsignal',
            name='signal_type',
            field=models.CharField(choices=[('price_objection', 'Дорого'), ('prepayment_objection', 'Передоплата'), ('size_concern', 'Розмір'), ('thinking_objection', 'Подумаю'), ('gift', 'На подарунок'), ('self_purchase', 'Для себе'), ('custom_print', 'Кастомний принт'), ('ad_reply', 'Відповідь з реклами'), ('no_reply', 'Не відповідає'), ('checkout_started', 'Checkout started'), ('payment_pending', 'Очікує оплату'), ('paid', 'Оплачено'), ('lost', 'Втрачено'), ('spam', 'Спам'), ('manager_takeover', 'Взяв менеджер'), ('discount_offer', 'Знижка'), ('product_interest', 'Інтерес до товару')], db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='IgObjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objection_type', models.CharField(choices=[('price', 'Дорого'), ('thinking', 'Подумаю'), ('size_risk', 'Не підійде розмір'), ('prepayment_trust', 'Не довіряє передоплаті'), ('defect_risk', 'Боїться браку'), ('delivery_time', 'Довго чекати'), ('cheaper_elsewhere', 'Є дешевше'), ('print_quality', 'Якість принта'), ('out_of_stock', 'Немає розміру/варіанта'), ('payday', 'Після зарплати'), ('compare_brand', 'Порівнює з брендом'), ('ask_partner', 'Порадиться з близькою людиною')], db_index=True, max_length=32)),
                ('state', models.CharField(choices=[('open', 'Відкрите'), ('handled', 'Метод застосовано'), ('resolved', 'Закрито фактом'), ('abandoned', 'Втрачено')], db_index=True, default='open', max_length=16)),
                ('is_true_objection', models.BooleanField(default=True)),
                ('repeat_count', models.PositiveIntegerField(default=1)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('resolution_method', models.CharField(blank=True, default='', max_length=48)),
                ('outcome', models.CharField(choices=[('unresolved', 'Не вирішено'), ('purchased', 'Купив'), ('lost', 'Втрачено'), ('silent', 'Замовк'), ('manager_taken', 'Передано менеджеру')], default='unresolved', max_length=24)),
                ('readiness_before', models.PositiveSmallIntegerField(default=0)),
                ('readiness_after', models.PositiveSmallIntegerField(default=0)),
                ('opened_watermark_message_id', models.PositiveBigIntegerField(db_index=True, default=0)),
                ('dedupe_key', models.CharField(max_length=160, unique=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='objection_lifecycles', to='management.igclient')),
                ('episode', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='objections', to='management.igcommercialepisode')),
                ('first_message', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='opened_objections', to='management.instagrambotmessage')),
                ('last_message', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='latest_objections', to='management.instagrambotmessage')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IgObjectionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(db_index=True, default='none', max_length=48)),
                ('claimed_by', models.CharField(default='model', max_length=24)),
                ('verified', models.BooleanField(db_index=True, default=False)),
                ('verification_reason', models.CharField(blank=True, default='', max_length=255)),
                ('result', models.CharField(choices=[('pending', 'Очікує реакції'), ('accepted', 'Прийнято'), ('re_objected', 'Повторив заперечення'), ('silent', 'Без відповіді'), ('escalated', 'Передано менеджеру'), ('purchased', 'Купив'), ('ignored', 'Метод не застосовано')], default='pending', max_length=24)),
                ('readiness_before', models.PositiveSmallIntegerField(default=0)),
                ('readiness_after', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client_response_message', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='objection_responses', to='management.instagrambotmessage')),
                ('objection', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='attempts', to='management.igobjection')),
                ('reply_message', models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='objection_attempts', to='management.instagrambotmessage')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='igobjection',
            index=models.Index(fields=['client', 'state', '-id'], name='ig_obj_client_state'),
        ),
        migrations.AddIndex(
            model_name='igobjection',
            index=models.Index(fields=['objection_type', 'state'], name='ig_obj_type_state'),
        ),
        migrations.AddIndex(
            model_name='igobjectionattempt',
            index=models.Index(fields=['objection', '-id'], name='ig_obj_attempt_dt'),
        ),
    ]
