# Generated by Django 5.2.11 on 2026-08-03 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0132_ig_objection_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgFunnelStepEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=160, unique=True)),
                ('event_type', models.CharField(choices=[('conversation_started', 'Діалог розпочато'), ('bot_replied_first', 'Перша відповідь бота'), ('product_pinned', 'Товар визначено'), ('variant_selected', 'Варіант визначено'), ('price_quoted', 'Ціну названо'), ('paylink_issued', 'Посилання на оплату видано'), ('paylink_viewed', 'Посилання на оплату відкрито'), ('payment_confirmed', 'Оплату підтверджено'), ('objection_raised', 'Заперечення зафіксовано'), ('objection_handled', 'Заперечення опрацьовано'), ('discount_offered', 'Знижку запропоновано'), ('manager_engaged', 'Менеджер долучився'), ('order_created', 'Замовлення створено'), ('ttn_created', 'ТТН створено'), ('delivered', 'Замовлення отримано'), ('drop_off', 'Відвал зафіксовано'), ('recovered', 'Клієнт повернувся')], db_index=True, max_length=32)),
                ('stage', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('actor', models.CharField(blank=True, default='', max_length=40)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('is_backfilled', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='funnel_step_events', to='management.igcommercialepisode')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IgFunnelDropOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('silence', 'Мовчання'), ('explicit_refusal', 'Явна відмова'), ('opt_out', 'Відмова від повідомлень'), ('unreachable', 'Недоступний через доставку'), ('spam', 'Спам'), ('superseded', 'Цикл заміщено')], db_index=True, max_length=24)),
                ('reason_code', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('stage_at_drop', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('objection_at_drop', models.CharField(blank=True, default='', max_length=32)),
                ('silence_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('followups_sent_before', models.PositiveSmallIntegerField(default=0)),
                ('detected_by', models.CharField(blank=True, default='', max_length=40)),
                ('is_recoverable', models.BooleanField(db_index=True, default=False)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('recovered_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('recovered_by_followup', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='drop_offs', to='management.igcommercialepisode')),
                ('recovery_event', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recovered_drop_offs', to='management.igfunnelstepevent')),
                ('step_event', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='drop_off', to='management.igfunnelstepevent')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='igfunnelstepevent',
            index=models.Index(fields=['episode', 'occurred_at'], name='ig_fstep_episode_dt'),
        ),
        migrations.AddIndex(
            model_name='igfunnelstepevent',
            index=models.Index(fields=['event_type', 'occurred_at'], name='ig_fstep_type_dt'),
        ),
        migrations.AddIndex(
            model_name='igfunneldropoff',
            index=models.Index(fields=['episode', '-occurred_at'], name='ig_drop_episode_dt'),
        ),
        migrations.AddIndex(
            model_name='igfunneldropoff',
            index=models.Index(fields=['kind', 'recovered_at'], name='ig_drop_kind_recovery'),
        ),
    ]
