# Generated by Django 5.2.11 on 2026-08-03 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0133_ig_funnel_step_analytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgDealInvoiceLifecycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('status', models.CharField(choices=[('open', 'Активний моніторинг'), ('paid', 'Оплачено'), ('failed', 'Помилка оплати'), ('cancelled', 'Скасовано'), ('expired', 'Протерміновано'), ('unknown', 'Термін моніторингу вичерпано')], db_index=True, default='open', max_length=16)),
                ('provider_status', models.CharField(blank=True, default='', max_length=32)),
                ('superseded_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('next_poll_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('terminal_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('poll_attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_lifecycles', to='management.igdeal')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['deal', 'status'], name='ig_inv_life_deal_status'), models.Index(fields=['status', 'next_poll_at'], name='ig_inv_life_poll_due')],
            },
        ),
    ]
