# Generated by Django 5.2.11 on 2026-08-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0134_ig_deal_invoice_lifecycle"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstagramBotTaskHeartbeat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("task_key", models.CharField(max_length=64, unique=True)),
                ("label", models.CharField(max_length=160)),
                ("expected_interval_seconds", models.PositiveIntegerField()),
                ("stale_after_seconds", models.PositiveIntegerField()),
                ("first_expected_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("last_started_at", models.DateTimeField(blank=True, null=True)),
                ("last_succeeded_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("last_failed_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("last_duration_ms", models.PositiveIntegerField(default=0)),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                ("last_error_kind", models.CharField(blank=True, default="", max_length=128)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["task_key"],
            },
        ),
    ]
