# Generated by Django 5.2.11 on 2026-08-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0135_gemini_resilience_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="IgAiReplyRecoveryJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("dedupe_key", models.CharField(max_length=160, unique=True)),
                ("status", models.CharField(choices=[("pending", "Очікує відновлення"), ("processing", "Готується відповідь"), ("sending", "Надсилається"), ("sent", "Надіслано"), ("cancelled", "Скасовано"), ("ambiguous", "Невідомий результат"), ("failed", "Помилка відновлення")], db_index=True, default="pending", max_length=16)),
                ("draft_text", models.TextField(blank=True, default="")),
                ("provider_message_id", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("settings_permission_epoch", models.PositiveBigIntegerField(default=0)),
                ("client_permission_epoch", models.PositiveBigIntegerField(default=0)),
                ("message_floor", models.PositiveBigIntegerField(default=0)),
                ("response_window_deadline", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("lease_token", models.CharField(blank=True, default="", max_length=40)),
                ("lease_until", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_error", models.CharField(blank=True, default="", max_length=1000)),
                ("sending_started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client", models.ForeignKey(db_constraint=False, on_delete=models.deletion.CASCADE, related_name="ai_reply_recovery_jobs", to="management.igclient")),
                ("holding_message", models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=models.deletion.SET_NULL, related_name="ai_recovery_holding_for", to="management.instagrambotmessage")),
                ("reply_message", models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=models.deletion.SET_NULL, related_name="ai_recovery_reply_for", to="management.instagrambotmessage")),
                ("source_message", models.OneToOneField(db_constraint=False, on_delete=models.deletion.CASCADE, related_name="ai_reply_recovery_job", to="management.instagrambotmessage")),
            ],
            options={
                "verbose_name": "Відновлення AI-відповіді IG",
                "verbose_name_plural": "Відновлення AI-відповідей IG",
                "ordering": ["id"],
                "indexes": [models.Index(fields=["status", "response_window_deadline"], name="ig_ai_recovery_due"), models.Index(fields=["client", "status"], name="ig_ai_recovery_client")],
            },
        ),
    ]
