# Generated by Django 5.2.11 on 2026-08-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0135_instagrambottaskheartbeat'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiModelState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=80, unique=True)),
                ('circuit_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('circuit_reason', models.CharField(blank=True, default='', max_length=32)),
                ('transient_failures', models.PositiveSmallIntegerField(default=0)),
                ('last_failure_project', models.CharField(blank=True, default='', max_length=80)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('last_ok_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Стан моделі Gemini',
                'verbose_name_plural': 'Стани моделей Gemini',
            },
        ),
        migrations.AddField(
            model_name='geminikeystate',
            name='consecutive_failures',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='geminikeystate',
            name='last_failure_kind',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='geminikeystate',
            name='last_http_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geminikeystate',
            name='latency_ewma_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='geminikeystate',
            name='lease_role',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='geminikeystate',
            name='lease_token',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='geminikeystate',
            name='lease_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='GeminiRequestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, max_length=40)),
                ('role', models.CharField(max_length=20)),
                ('key_name', models.CharField(max_length=40)),
                ('project_group', models.CharField(blank=True, default='', max_length=80)),
                ('model', models.CharField(max_length=80)),
                ('outcome', models.CharField(max_length=24)),
                ('failure_kind', models.CharField(blank=True, default='', max_length=32)),
                ('http_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('provider_reason', models.CharField(blank=True, default='', max_length=80)),
                ('decision', models.CharField(blank=True, default='', max_length=48)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('remaining_deadline_ms', models.PositiveIntegerField(default=0)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('thoughts_tokens', models.PositiveIntegerField(default=0)),
                ('candidates_tokens', models.PositiveIntegerField(default=0)),
                ('error_detail', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['request_id', '-id'], name='gemini_attempt_request'), models.Index(fields=['role', '-id'], name='gemini_attempt_role')],
            },
        ),
    ]
