# Generated by Django 5.2.11 on 2026-08-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0137_ig_ai_reply_recovery"),
    ]

    operations = [
        migrations.AddField(
            model_name="igaireplyrecoveryjob",
            name="activated_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
