# Generated by Django 5.2.11 on 2026-08-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0138_ig_ai_reply_recovery_activation"),
    ]

    operations = [
        migrations.AddField(
            model_name="igaireplyrecoveryjob",
            name="next_attempt_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="igaireplyrecoveryjob",
            index=models.Index(
                fields=["status", "activated_at", "next_attempt_at"],
                name="ig_ai_recovery_ready",
            ),
        ),
    ]
