# Generated by Django 5.2.11 on 2026-08-04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0136_encrypt_instagram_bot_settings_secrets"),
        ("management", "0139_ig_ai_reply_recovery_retry_schedule"),
    ]

    operations = []
