# Generated by Django 5.2.11 on 2026-08-05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0140_merge_gemini_resilience_and_credential_encryption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="igfollowuptask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Очікує"),
                    ("processing", "Надсилається"),
                    ("sent", "Надіслано"),
                    ("ambiguous", "Потрібна перевірка доставки"),
                    ("completed", "Завершено"),
                    ("cancelled", "Скасовано"),
                    ("skipped", "Пропущено"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="igfollowuptask",
            name="delivery_review_for",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_review",
                to="management.igfollowuptask",
            ),
        ),
    ]
