# Generated by Django 5.2.11 on 2026-08-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0141_igfollowuptask_delivery_fsm'),
    ]

    operations = [
        migrations.AddField(
            model_name='igpaymentconfirmationreview',
            name='resolution_outcome',
            field=models.CharField(blank=True, choices=[('', 'Не вказано'), ('already_received', 'Старе замовлення отримано'), ('already_delivered', 'Старе замовлення доставлено'), ('completed_unknown', 'Старе замовлення завершено; спосіб невідомий')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='igpaymentreviewdecision',
            name='order_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Повна вартість замовлення, відновлена для історичного завершення.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='igpaymentreviewdecision',
            name='order_total_source',
            field=models.CharField(blank=True, default='', max_length=48),
        ),
        migrations.AlterField(
            model_name='igpaymentreviewdecision',
            name='verification_scope',
            field=models.CharField(choices=[('full_payment', 'Повна оплата'), ('prepayment', 'Передоплата'), ('payment_claim', 'Заявлений платіж'), ('historical_fulfilled', 'Історично виконане замовлення')], max_length=32),
        ),
    ]
