# Generated by Django 5.2.11 on 2026-08-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0142_ig_payment_review_legacy_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='igfollowuptask',
            name='event_occurred_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='igfollowuptask',
            name='event_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='igfollowuptask',
            name='policy_started_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='igfollowuptask',
            name='policy_version',
            field=models.CharField(default='followup-v1', max_length=32),
        ),
        migrations.AddField(
            model_name='igfollowuptask',
            name='trigger',
            field=models.CharField(choices=[('time', 'За часом'), ('event', 'Подія'), ('reactive', 'Реактивно')], db_index=True, default='time', max_length=16),
        ),
        migrations.AddIndex(
            model_name='igfollowuptask',
            index=models.Index(fields=['trigger', 'event_occurred_at'], name='ig_fu_trigger_event'),
        ),
    ]
