# Generated by Django 5.2.11 on 2026-08-05 16:38

import django.db.models.deletion
from django.db import migrations, models


def normalize_legacy_consumed(apps, schema_editor):
    reservation = apps.get_model("management", "IgCheckoutInventoryReservation")
    reservation.objects.filter(state="consumed").update(
        state="fulfilled",
        allocation_source="catalog_variant",
    )

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0143_igfollowuptask_event_continuation'),
        ('orders', '0054_order_tracking_lifecycle'),
        ('productcolors', '0007_normalize_slugs'),
        ('storefront', '0088_product_sales_semantic_profiles'),
        ('warehouse', '0011_alter_stockmovement_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='igcheckoutinventoryreservation',
            name='allocation_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='igcheckoutinventoryreservation',
            name='allocation_source',
            field=models.CharField(default='catalog_variant', max_length=24),
        ),
        migrations.AddField(
            model_name='igcheckoutinventoryreservation',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='igcheckoutinventoryreservation',
            name='line_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='igcheckoutinventoryreservation',
            name='order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instagram_inventory_reservations', to='orders.order'),
        ),
        migrations.AddField(
            model_name='igcheckoutinventoryreservation',
            name='order_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instagram_inventory_reservations', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='igcheckoutinventoryreservation',
            name='paid_committed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='igcheckoutinventoryreservation',
            name='stock_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instagram_checkout_reservations', to='warehouse.stockitem'),
        ),
        migrations.AddField(
            model_name='igcheckoutinventoryreservation',
            name='stock_movement',
            field=models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instagram_inventory_reservation', to='warehouse.stockmovement'),
        ),
        migrations.AddField(
            model_name='igcheckoutinventoryreservation',
            name='write_off_request',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instagram_inventory_reservations', to='warehouse.writeoffrequest'),
        ),
        migrations.AlterField(
            model_name='igcheckoutinventoryreservation',
            name='state',
            field=models.CharField(choices=[('active', 'Зарезервовано'), ('paid_committed', 'Оплата підтверджена'), ('fulfilled', 'Виконано'), ('released', 'Звільнено'), ('overbooked_review', 'Потрібна перевірка дефіциту'), ('consumed', 'Використано')], db_index=True, default='active', max_length=24),
        ),
        migrations.RunPython(normalize_legacy_consumed, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='igcheckoutinventoryreservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('allocation_source', 'warehouse'), ('stock_item__isnull', False)), ('allocation_source', 'catalog_variant'), ('allocation_source', 'untracked'), _connector='OR'), name='ig_res_allocation_source_valid'),
        ),
    ]
