# Generated by Django 5.2.11 on 2026-08-05 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


COMMERCE_TABLES = (
    'management_igcommerceselectionsession',
    'management_igcommerceselectiontransition',
    'management_igcommerceturndecision',
    'management_igcommercemanagerreview',
)


def ensure_commerce_tables_innodb(apps, schema_editor):
    if schema_editor.connection.vendor not in {'mysql', 'mariadb'}:
        return
    quote = schema_editor.quote_name
    with schema_editor.connection.cursor() as cursor:
        for table in COMMERCE_TABLES:
            cursor.execute(
                'SELECT ENGINE FROM information_schema.TABLES '
                'WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=%s',
                [table],
            )
            row = cursor.fetchone()
            if row is None:
                raise RuntimeError(f'required Instagram commerce table is missing: {table}')
            if str(row[0]).lower() != 'innodb':
                schema_editor.execute(f'ALTER TABLE {quote(table)} ENGINE=InnoDB')


def drop_commerce_state_guards(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    names = (
        'ig_com_tr_no_upd',
        'ig_com_tr_no_del',
        'ig_com_dec_identity_upd',
        'ig_com_dec_no_del',
    )
    if vendor in {'mysql', 'mariadb', 'sqlite'}:
        for name in names:
            schema_editor.execute(f'DROP TRIGGER IF EXISTS {name}')
    elif vendor == 'postgresql':
        for table, table_names in (
            (
                'management_igcommerceselectiontransition',
                ('ig_com_tr_no_upd', 'ig_com_tr_no_del'),
            ),
            (
                'management_igcommerceturndecision',
                ('ig_com_dec_identity_upd', 'ig_com_dec_no_del'),
            ),
        ):
            for name in table_names:
                schema_editor.execute(f'DROP TRIGGER IF EXISTS {name} ON {table}')
        for function in (
            'ig_com_transition_immutable_raise()',
            'ig_com_decision_identity_raise()',
            'ig_com_decision_delete_raise()',
        ):
            schema_editor.execute(f'DROP FUNCTION IF EXISTS {function}')


def create_commerce_state_guards(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    drop_commerce_state_guards(apps, schema_editor)
    if vendor in {'mysql', 'mariadb'}:
        schema_editor.execute(
            "CREATE TRIGGER ig_com_tr_no_upd BEFORE UPDATE ON "
            "management_igcommerceselectiontransition FOR EACH ROW "
            "SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = "
            "'IgCommerceSelectionTransition is append-only'"
        )
        schema_editor.execute(
            "CREATE TRIGGER ig_com_tr_no_del BEFORE DELETE ON "
            "management_igcommerceselectiontransition FOR EACH ROW "
            "SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = "
            "'IgCommerceSelectionTransition is append-only'"
        )
        schema_editor.execute(
            "CREATE TRIGGER ig_com_dec_identity_upd BEFORE UPDATE ON "
            "management_igcommerceturndecision FOR EACH ROW BEGIN "
            "IF NOT (OLD.source_message_id <=> NEW.source_message_id) "
            "OR NOT (OLD.session_id <=> NEW.session_id) "
            "OR NOT (OLD.transition_id <=> NEW.transition_id) "
            "OR NOT (OLD.request_payload <=> NEW.request_payload) "
            "OR NOT (OLD.result_payload <=> NEW.result_payload) "
            "OR NOT (OLD.reply_payload <=> NEW.reply_payload) "
            "OR NOT (OLD.effects_payload <=> NEW.effects_payload) "
            "OR NOT (OLD.accepted <=> NEW.accepted) "
            "OR NOT (OLD.is_stale <=> NEW.is_stale) "
            "OR NOT (OLD.delivery_required <=> NEW.delivery_required) THEN "
            "SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = "
            "'IgCommerceTurnDecision identity is immutable'; END IF; END"
        )
        schema_editor.execute(
            "CREATE TRIGGER ig_com_dec_no_del BEFORE DELETE ON "
            "management_igcommerceturndecision FOR EACH ROW "
            "SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = "
            "'IgCommerceTurnDecision is durable'"
        )
    elif vendor == 'sqlite':
        schema_editor.execute(
            "CREATE TRIGGER ig_com_tr_no_upd BEFORE UPDATE ON "
            "management_igcommerceselectiontransition BEGIN SELECT RAISE(ABORT, "
            "'IgCommerceSelectionTransition is append-only'); END"
        )
        schema_editor.execute(
            "CREATE TRIGGER ig_com_tr_no_del BEFORE DELETE ON "
            "management_igcommerceselectiontransition BEGIN SELECT RAISE(ABORT, "
            "'IgCommerceSelectionTransition is append-only'); END"
        )
        schema_editor.execute(
            "CREATE TRIGGER ig_com_dec_identity_upd BEFORE UPDATE ON "
            "management_igcommerceturndecision WHEN "
            "OLD.source_message_id IS NOT NEW.source_message_id OR "
            "OLD.session_id IS NOT NEW.session_id OR "
            "OLD.transition_id IS NOT NEW.transition_id OR "
            "OLD.request_payload IS NOT NEW.request_payload OR "
            "OLD.result_payload IS NOT NEW.result_payload OR "
            "OLD.reply_payload IS NOT NEW.reply_payload OR "
            "OLD.effects_payload IS NOT NEW.effects_payload OR "
            "OLD.accepted IS NOT NEW.accepted OR OLD.is_stale IS NOT NEW.is_stale OR "
            "OLD.delivery_required IS NOT NEW.delivery_required BEGIN "
            "SELECT RAISE(ABORT, 'IgCommerceTurnDecision identity is immutable'); END"
        )
        schema_editor.execute(
            "CREATE TRIGGER ig_com_dec_no_del BEFORE DELETE ON "
            "management_igcommerceturndecision BEGIN SELECT RAISE(ABORT, "
            "'IgCommerceTurnDecision is durable'); END"
        )
    elif vendor == 'postgresql':
        schema_editor.execute(
            "CREATE OR REPLACE FUNCTION ig_com_transition_immutable_raise() "
            "RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION "
            "'IgCommerceSelectionTransition is append-only'; END; $$"
        )
        for name, operation in (
            ('ig_com_tr_no_upd', 'UPDATE'),
            ('ig_com_tr_no_del', 'DELETE'),
        ):
            schema_editor.execute(
                f"CREATE TRIGGER {name} BEFORE {operation} ON "
                "management_igcommerceselectiontransition FOR EACH ROW "
                "EXECUTE FUNCTION ig_com_transition_immutable_raise()"
            )
        schema_editor.execute(
            "CREATE OR REPLACE FUNCTION ig_com_decision_identity_raise() "
            "RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF "
            "OLD.source_message_id IS DISTINCT FROM NEW.source_message_id OR "
            "OLD.session_id IS DISTINCT FROM NEW.session_id OR "
            "OLD.transition_id IS DISTINCT FROM NEW.transition_id OR "
            "OLD.request_payload IS DISTINCT FROM NEW.request_payload OR "
            "OLD.result_payload IS DISTINCT FROM NEW.result_payload OR "
            "OLD.reply_payload IS DISTINCT FROM NEW.reply_payload OR "
            "OLD.effects_payload IS DISTINCT FROM NEW.effects_payload OR "
            "OLD.accepted IS DISTINCT FROM NEW.accepted OR "
            "OLD.is_stale IS DISTINCT FROM NEW.is_stale OR "
            "OLD.delivery_required IS DISTINCT FROM NEW.delivery_required THEN "
            "RAISE EXCEPTION 'IgCommerceTurnDecision identity is immutable'; "
            "END IF; RETURN NEW; END; $$"
        )
        schema_editor.execute(
            "CREATE TRIGGER ig_com_dec_identity_upd BEFORE UPDATE ON "
            "management_igcommerceturndecision FOR EACH ROW "
            "EXECUTE FUNCTION ig_com_decision_identity_raise()"
        )
        schema_editor.execute(
            "CREATE OR REPLACE FUNCTION ig_com_decision_delete_raise() "
            "RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION "
            "'IgCommerceTurnDecision is durable'; END; $$"
        )
        schema_editor.execute(
            "CREATE TRIGGER ig_com_dec_no_del BEFORE DELETE ON "
            "management_igcommerceturndecision FOR EACH ROW "
            "EXECUTE FUNCTION ig_com_decision_delete_raise()"
        )


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('management', '0145_ig_inventory_revision_safety'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrambotmessage',
            name='quick_reply_payload',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='instagrambotmessage',
            name='reply_to_provider_message_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='IgCommerceSelectionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.PositiveIntegerField()),
                ('open_slot', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('state', models.CharField(choices=[('open', 'Відкрита'), ('closed', 'Закрита')], db_index=True, default='open', max_length=16)),
                ('lines', models.JSONField(blank=True, default=list)),
                ('active_index', models.PositiveIntegerField(default=0)),
                ('selection_constraints', models.JSONField(blank=True, default=dict)),
                ('query_constraints', models.JSONField(blank=True, default=dict)),
                ('candidate_product_ids', models.JSONField(blank=True, default=list)),
                ('candidate_digest', models.CharField(blank=True, default='', max_length=64)),
                ('candidate_generation', models.PositiveIntegerField(default=0)),
                ('candidate_prompt_provider_ids', models.JSONField(blank=True, default=list)),
                ('rejected_selection', models.JSONField(blank=True, default=dict)),
                ('rejected_reason', models.CharField(blank=True, default='', max_length=120)),
                ('pending_field', models.CharField(blank=True, default='', max_length=80)),
                ('pending_clarification', models.CharField(blank=True, default='', max_length=120)),
                ('semantic_block_key', models.CharField(blank=True, db_index=True, default='', max_length=160)),
                ('graph_digest', models.CharField(blank=True, default='', max_length=64)),
                ('last_provider_event_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_provider_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='commerce_selection_sessions', to='management.igclient')),
                ('commercial_episode', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='commerce_selection_sessions', to='management.igcommercialepisode')),
            ],
            options={
                'ordering': ['client_id', '-generation'],
            },
        ),
        migrations.CreateModel(
            name='IgCommerceSelectionTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('from_revision', models.PositiveIntegerField()),
                ('to_revision', models.PositiveIntegerField()),
                ('previous_snapshot', models.JSONField(default=dict)),
                ('next_snapshot', models.JSONField(default=dict)),
                ('effects', models.JSONField(blank=True, default=dict)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('graph_digest', models.CharField(blank=True, default='', max_length=64)),
                ('source_order_key', models.CharField(db_index=True, max_length=360)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='management.igcommerceselectionsession')),
                ('source_message', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='commerce_selection_transition', to='management.instagrambotmessage')),
            ],
            options={
                'ordering': ['session_id', 'to_revision', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IgCommerceTurnDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_payload', models.JSONField(default=dict)),
                ('result_payload', models.JSONField(default=dict)),
                ('reply_payload', models.JSONField(default=dict)),
                ('effects_payload', models.JSONField(default=dict)),
                ('accepted', models.BooleanField(default=True)),
                ('is_stale', models.BooleanField(db_index=True, default=False)),
                ('delivery_required', models.BooleanField(default=True)),
                ('delivery_state', models.CharField(choices=[('pending', 'Очікує'), ('sending', 'Надсилається'), ('unknown', 'Результат невідомий'), ('partial', 'Частково надіслано'), ('sent', 'Надіслано'), ('not_required', 'Доставка не потрібна')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('delivery_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_error', models.CharField(blank=True, default='', max_length=1000)),
                ('text_receipts', models.JSONField(blank=True, default=list)),
                ('media_receipts', models.JSONField(blank=True, default=list)),
                ('provider_message_ids', models.JSONField(blank=True, default=list)),
                ('reconciliation_status', models.CharField(choices=[('not_required', 'Не потрібне'), ('required', 'Потрібне'), ('pending', 'Очікує'), ('reconciled', 'Звірено'), ('manager_review', 'Перевірка менеджера')], db_index=True, default='not_required', max_length=24)),
                ('reconciliation_result', models.JSONField(blank=True, default=dict)),
                ('reconciliation_evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='management.igcommerceselectionsession')),
                ('source_message', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='commerce_turn_decision', to='management.instagrambotmessage')),
                ('transition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='management.igcommerceselectiontransition')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='IgCommerceManagerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=180, unique=True)),
                ('reason', models.CharField(db_index=True, max_length=120)),
                ('selection_snapshot', models.JSONField(blank=True, default=dict)),
                ('selection_digest', models.CharField(blank=True, default='', max_length=64)),
                ('selection_generation', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Відкрита'), ('claimed', 'В роботі'), ('resolved', 'Вирішена'), ('cancelled', 'Скасована')], db_index=True, default='open', max_length=16)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claim_lease_token', models.CharField(blank=True, default='', max_length=64)),
                ('claim_lease_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('resolution_payload', models.JSONField(blank=True, default=dict)),
                ('resolution_note', models.CharField(blank=True, default='', max_length=1000)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='commerce_manager_reviews', to='management.igclient')),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ig_commerce_reviews_owned', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ig_commerce_reviews_resolved', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_reviews', to='management.igcommerceselectionsession')),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_reviews', to='management.igcommerceturndecision')),
            ],
            options={
                'ordering': ['due_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='igcommerceselectionsession',
            index=models.Index(fields=['client', 'state', '-generation'], name='ig_com_sess_client_state'),
        ),
        migrations.AddIndex(
            model_name='igcommerceselectionsession',
            index=models.Index(fields=['state', '-updated_at'], name='ig_com_sess_state_dt'),
        ),
        migrations.AddConstraint(
            model_name='igcommerceselectionsession',
            constraint=models.UniqueConstraint(fields=('client', 'generation'), name='ig_commerce_client_generation'),
        ),
        migrations.AddConstraint(
            model_name='igcommerceselectionsession',
            constraint=models.UniqueConstraint(fields=('client', 'open_slot'), name='ig_commerce_one_open_slot'),
        ),
        migrations.AddConstraint(
            model_name='igcommerceselectionsession',
            constraint=models.CheckConstraint(condition=models.Q(('open_slot__isnull', True), ('open_slot', 1), _connector='OR'), name='ig_commerce_open_slot_valid'),
        ),
        migrations.AddIndex(
            model_name='igcommerceselectiontransition',
            index=models.Index(fields=['session', '-created_at'], name='ig_com_trans_session_dt'),
        ),
        migrations.AddIndex(
            model_name='igcommerceselectiontransition',
            index=models.Index(fields=['action', '-created_at'], name='ig_com_trans_action_dt'),
        ),
        migrations.AddConstraint(
            model_name='igcommerceselectiontransition',
            constraint=models.UniqueConstraint(fields=('session', 'to_revision'), name='ig_commerce_session_revision'),
        ),
        migrations.AddIndex(
            model_name='igcommerceturndecision',
            index=models.Index(fields=['delivery_state', 'created_at'], name='ig_com_decision_delivery'),
        ),
        migrations.AddIndex(
            model_name='igcommerceturndecision',
            index=models.Index(fields=['session', '-created_at'], name='ig_com_decision_session'),
        ),
        migrations.AddIndex(
            model_name='igcommerceturndecision',
            index=models.Index(fields=['reconciliation_status', '-updated_at'], name='ig_com_decision_recon'),
        ),
        migrations.AddIndex(
            model_name='igcommercemanagerreview',
            index=models.Index(fields=['status', 'due_at', 'id'], name='ig_com_review_status_due'),
        ),
        migrations.AddIndex(
            model_name='igcommercemanagerreview',
            index=models.Index(fields=['owner', 'status', 'due_at'], name='ig_com_review_owner_due'),
        ),
        migrations.AddIndex(
            model_name='igcommercemanagerreview',
            index=models.Index(fields=['client', '-created_at'], name='ig_com_review_client_dt'),
        ),
        migrations.RunPython(
            ensure_commerce_tables_innodb,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            create_commerce_state_guards,
            drop_commerce_state_guards,
        ),
    ]
