# Generated by Django 5.2.11 on 2026-08-08

import django.db.models.deletion
from django.db import migrations, models
import django.utils.timezone


TABLE = "management_igpermissiontransitionjob"


def ensure_permission_transition_table_innodb(apps, schema_editor):
    if schema_editor.connection.vendor not in {"mysql", "mariadb"}:
        return
    quote = schema_editor.quote_name
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT ENGINE FROM information_schema.TABLES "
            "WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=%s",
            [TABLE],
        )
        row = cursor.fetchone()
    if row is None:
        raise RuntimeError(f"required permission transition table is missing: {TABLE}")
    if str(row[0]).lower() != "innodb":
        schema_editor.execute(f"ALTER TABLE {quote(TABLE)} ENGINE=InnoDB")


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("management", "0146_ig_commerce_selection_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="IgPermissionTransitionJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("opt_out", "Відмова від повідомлень"), ("manager_takeover", "Діалог веде менеджер"), ("client_pause", "Ручна пауза для клієнта"), ("global_pause", "Глобальна пауза бота")], db_index=True, max_length=32)),
                ("status", models.CharField(choices=[("pending", "Очікує застосування"), ("processing", "Застосовується"), ("applied", "Застосовано"), ("superseded", "Вже не актуально"), ("failed", "Потрібне відновлення")], db_index=True, default="pending", max_length=16)),
                ("dedupe_key", models.CharField(max_length=255, unique=True)),
                ("next_attempt_at", models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ("lease_token", models.CharField(blank=True, default="", max_length=40)),
                ("lease_until", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_error_kind", models.CharField(blank=True, default="", max_length=64)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client", models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="permission_transition_jobs", to="management.igclient")),
                ("settings", models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="permission_transition_jobs", to="management.instagrambotsettings")),
                ("source_message", models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name="permission_transition_jobs", to="management.instagrambotmessage")),
            ],
            options={
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["status", "next_attempt_at", "id"], name="ig_perm_transition_due"),
                    models.Index(fields=["client", "status"], name="ig_perm_transition_client"),
                    models.Index(fields=["lease_until"], name="ig_perm_transition_lease"),
                ],
            },
        ),
        migrations.RunPython(ensure_permission_transition_table_innodb, migrations.RunPython.noop),
    ]
