# Generated by Django 5.2.11 on 2026-08-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0147_ig_permission_transition_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrambotmessage',
            name='delivery_delivered_chunk_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instagrambotmessage',
            name='delivery_failure_boundary',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='instagrambotmessage',
            name='delivery_original_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='instagrambotmessage',
            name='delivery_planned_chunk_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instagrambotmessage',
            name='delivery_provider_message_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
