# Generated by Django 5.2.11 on 2026-08-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0148_ig_reply_delivery_evidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrambotsettings',
            name='allowed_senders',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='instagrambotsettings',
            name='ig_user_id',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='instagrambotsettings',
            name='page_id',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='instagrambotsettings',
            name='reply_text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='instagrambotsettings',
            name='trigger_text',
            field=models.CharField(default='', max_length=255),
        ),
    ]
