# Generated by Django 5.2.11 on 2026-08-08 16:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0149_secure_instagram_bot_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgConversationAnalysisEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=160, unique=True)),
                ('event_type', models.CharField(choices=[('repeat_episode', 'Новий епізод повторного замовлення')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('required_state_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('source_digest', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Очікує матеріалізації'), ('applied', 'Матеріалізовано'), ('rejected', 'Відхилено перевіркою'), ('failed', 'Вичерпано повторні спроби')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=1000)),
                ('rejected_reason', models.CharField(blank=True, default='', max_length=120)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_episode', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='analysis_events', to='management.igcommercialepisode')),
                ('client', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='analysis_events', to='management.igclient')),
                ('snapshot', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='operational_event', to='management.igconversationanalysissnapshot')),
            ],
            options={
                'verbose_name': 'Операційна подія аналізу IG',
                'verbose_name_plural': 'Операційні події аналізу IG',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at', 'id'], name='ig_analysis_event_due'), models.Index(fields=['client', 'status'], name='ig_analysis_event_client')],
            },
        ),
    ]
