# Generated by Django 5.2.11 on 2026-08-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0155_gemini_37_message_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='igordercustomerevent',
            name='delivery_provider_message_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='igordercustomerevent',
            name='provider_message_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
