# Generated by Django 5.2.11 on 2026-08-14 14:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


FOLLOW_TABLES = (
    'management_igfollowcapabilitystate',
    'management_igfollowstate',
    'management_igfollowobservation',
    'management_igfollowrefreshjob',
    'management_igfollowctadecision',
)


def ensure_follow_tables_innodb(apps, schema_editor):
    if schema_editor.connection.vendor not in {'mysql', 'mariadb'}:
        return
    quote = schema_editor.quote_name
    with schema_editor.connection.cursor() as cursor:
        for table in FOLLOW_TABLES:
            cursor.execute(
                'SELECT ENGINE FROM information_schema.TABLES '
                'WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=%s',
                [table],
            )
            row = cursor.fetchone()
            if row is None:
                raise RuntimeError(f'required follow intelligence table is missing: {table}')
            if str(row[0]).lower() != 'innodb':
                schema_editor.execute(f'ALTER TABLE {quote(table)} ENGINE=InnoDB')


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('management', '0156_ig_order_event_delivery_receipts'),
        ('orders', '0054_order_tracking_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgFollowCapabilityState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, unique=True)),
                ('transport', models.CharField(blank=True, default='', max_length=32)),
                ('graph_version', models.CharField(blank=True, default='', max_length=16)),
                ('ig_user_id', models.CharField(blank=True, default='', max_length=64)),
                ('config_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('unknown', 'Невідомо'), ('available', 'Доступно'), ('degraded', 'Тимчасово недоступно'), ('blocked', 'Заблоковано політикою Meta')], db_index=True, default='unknown', max_length=16)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('next_probe_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('blocked_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('last_error_kind', models.CharField(blank=True, default='', max_length=32)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'next_probe_at'], name='ig_follow_cap_status')],
                'constraints': [models.CheckConstraint(condition=models.Q(('singleton_key', 1)), name='ig_follow_cap_singleton_one')],
            },
        ),
        migrations.CreateModel(
            name='IgFollowCtaDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_key', models.CharField(max_length=180, unique=True)),
                ('opportunity', models.CharField(choices=[('payment', 'Підтвердження оплати'), ('hesitation', "М'яке вагання"), ('post_delivery', 'Після позитивної відповіді')], db_index=True, max_length=24)),
                ('policy_version', models.CharField(default='follow-v1', max_length=32)),
                ('state', models.CharField(choices=[('suppressed', 'Заборонено політикою'), ('waiting_follow', 'Очікує перевірки підписки'), ('preparing', 'Готується'), ('prepared', 'Підготовлено'), ('reserved', 'Зарезервовано до відправлення'), ('sent', 'Надіслано'), ('ambiguous', 'Результат невідомий'), ('cancelled', 'Скасовано'), ('failed', 'Помилка')], db_index=True, default='preparing', max_length=24)),
                ('episode_slot_key', models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ('sent_scope_key', models.CharField(blank=True, max_length=180, null=True, unique=True)),
                ('follow_state_revision', models.PositiveBigIntegerField(default=0)),
                ('conversation_watermark', models.PositiveBigIntegerField(default=0)),
                ('context_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('base_text', models.TextField(blank=True, default='')),
                ('candidate_text', models.CharField(blank=True, default='', max_length=300)),
                ('candidate_hash', models.CharField(blank=True, default='', max_length=64)),
                ('final_text', models.TextField(blank=True, default='')),
                ('suppression_reason', models.CharField(blank=True, default='', max_length=64)),
                ('reason_codes', models.JSONField(blank=True, default=list)),
                ('model', models.CharField(blank=True, default='', max_length=80)),
                ('model_key_alias', models.CharField(blank=True, default='', max_length=80)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=40)),
                ('lease_token', models.CharField(blank=True, default='', max_length=64)),
                ('lease_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('provider_message_ids', models.JSONField(blank=True, default=list)),
                ('provider_io_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('follow_observed_after_cta_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_kind', models.CharField(blank=True, default='', max_length=32)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='follow_cta_decisions', to='management.igclient')),
                ('commercial_episode', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='follow_cta_decisions', to='management.igcommercialepisode')),
                ('lifecycle_event', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='follow_cta_decisions', to='management.iglifecycleevent')),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instagram_follow_cta_decisions', to='orders.order')),
                ('source_message', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='follow_cta_decisions', to='management.instagrambotmessage')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['client', '-created_at'], name='ig_follow_dec_client_dt'), models.Index(fields=['state', '-created_at'], name='ig_follow_dec_state_dt'), models.Index(fields=['commercial_episode', 'state'], name='ig_follow_dec_episode')],
            },
        ),
        migrations.CreateModel(
            name='IgFollowObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveBigIntegerField(default=0)),
                ('trigger', models.CharField(max_length=32)),
                ('result', models.CharField(choices=[('known', 'Отримано'), ('error', 'Помилка'), ('skipped', 'Пропущено')], db_index=True, max_length=16)),
                ('observed_value', models.BooleanField(blank=True, null=True)),
                ('field_present', models.BooleanField(default=False)),
                ('field_type', models.CharField(blank=True, default='', max_length=24)),
                ('transport', models.CharField(blank=True, default='', max_length=32)),
                ('graph_version', models.CharField(blank=True, default='', max_length=16)),
                ('config_fingerprint', models.CharField(max_length=64)),
                ('http_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('graph_code', models.PositiveIntegerField(blank=True, null=True)),
                ('graph_subcode', models.PositiveIntegerField(blank=True, null=True)),
                ('error_kind', models.CharField(blank=True, default='', max_length=32)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='follow_observations', to='management.igclient')),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['client', '-created_at'], name='ig_follow_obs_client_dt'), models.Index(fields=['result', '-created_at'], name='ig_follow_obs_result_dt')],
            },
        ),
        migrations.CreateModel(
            name='IgFollowRefreshJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_generation', models.PositiveBigIntegerField(default=0)),
                ('claimed_generation', models.PositiveBigIntegerField(default=0)),
                ('triggers', models.JSONField(blank=True, default=list)),
                ('expected_config_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('processing', 'Обробляється'), ('done', 'Завершено'), ('failed', 'Помилка')], db_index=True, default='pending', max_length=16)),
                ('due_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('lease_token', models.CharField(blank=True, default='', max_length=64)),
                ('lease_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error_kind', models.CharField(blank=True, default='', max_length=32)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='follow_refresh_job', to='management.igclient')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'due_at', 'id'], name='ig_follow_job_due')],
            },
        ),
        migrations.CreateModel(
            name='IgFollowState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('unknown', 'Невідомо'), ('following', 'Підписаний'), ('not_following', 'Не підписаний')], db_index=True, default='unknown', max_length=16)),
                ('revision', models.PositiveBigIntegerField(default=0)),
                ('source', models.CharField(blank=True, default='', max_length=32)),
                ('graph_version', models.CharField(blank=True, default='', max_length=16)),
                ('config_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('observed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('first_observed_following_at', models.DateTimeField(blank=True, null=True)),
                ('last_check_at', models.DateTimeField(blank=True, null=True)),
                ('last_result', models.CharField(choices=[('never', 'Не перевірялось'), ('known', 'Отримано'), ('error', 'Помилка'), ('skipped', 'Пропущено політикою')], default='never', max_length=16)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('last_error_kind', models.CharField(blank=True, default='', max_length=32)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('next_retry_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('refresh_generation', models.PositiveBigIntegerField(default=0)),
                ('refresh_lease_token', models.CharField(blank=True, default='', max_length=64)),
                ('refresh_lease_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_cta_touch_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='follow_state_projection', to='management.igclient')),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'expires_at'], name='ig_follow_state_fresh'), models.Index(fields=['next_retry_at', 'client'], name='ig_follow_state_retry')],
            },
        ),
        migrations.RunPython(ensure_follow_tables_innodb, migrations.RunPython.noop),
    ]
