# Generated by Django 6.1 on 2026-08-23 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def gate_existing_pending_discounts(apps, schema_editor):
    FollowUp = apps.get_model('management', 'IgFollowUpTask')
    FollowUp.objects.filter(
        status='pending',
        discount_percent__gt=0,
        manager_approval_status='not_required',
    ).update(manager_approval_status='pending')


def ungate_existing_pending_discounts(apps, schema_editor):
    FollowUp = apps.get_model('management', 'IgFollowUpTask')
    FollowUp.objects.filter(
        status='pending',
        discount_percent__gt=0,
        manager_approval_status='pending',
        manager_approval_requested_at__isnull=True,
    ).update(manager_approval_status='not_required')


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0168_call_auto_analysis_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='igfollowuptask',
            name='manager_approval_actor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ig_followup_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='igfollowuptask',
            name='manager_approval_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='igfollowuptask',
            name='manager_approval_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='igfollowuptask',
            name='manager_approval_status',
            field=models.CharField(choices=[('not_required', 'Не потрібне'), ('pending', 'Очікує рішення'), ('approved', 'Підтверджено'), ('rejected', 'Відхилено')], db_index=True, default='not_required', max_length=16),
        ),
        migrations.RunPython(
            gate_existing_pending_discounts,
            ungate_existing_pending_discounts,
        ),
    ]
