# Generated by Django 6.1 on 2026-08-28 01:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0169_ig_followup_manager_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgClientDegradationEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('open', 'Відкритий'), ('holding_sent', 'Холдинг надіслано'), ('recovery_pending', 'Готується відновлення'), ('recovered', 'Відновлено'), ('manual', 'Передано менеджеру'), ('superseded', 'Витіснено'), ('cancelled', 'Скасовано')], db_index=True, default='open', max_length=20)),
                ('first_source_message_id', models.PositiveBigIntegerField(default=0)),
                ('latest_source_message_id', models.PositiveBigIntegerField(db_index=True, default=0)),
                ('logical_turn_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('holding_sent_at', models.DateTimeField(blank=True, null=True)),
                ('holding_reserved_at', models.DateTimeField(blank=True, null=True)),
                ('inbound_count', models.PositiveIntegerField(default=0)),
                ('suppressed_count', models.PositiveIntegerField(default=0)),
                ('apology_count', models.PositiveSmallIntegerField(default=0)),
                ('last_decision', models.CharField(blank=True, default='', max_length=24)),
                ('last_decision_reason', models.CharField(blank=True, default='', max_length=48)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Епізод деградації клієнта IG',
                'verbose_name_plural': 'Епізоди деградації клієнтів IG',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='IgProviderIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(db_index=True, max_length=20)),
                ('failure_class', models.CharField(choices=[('quota', 'Квота (429)'), ('unavailable', 'Недоступність (5xx)'), ('timeout', 'Таймаут читання'), ('connect', "Транспорт/з'єднання"), ('invalid_payload', 'Некоректний запит (400)'), ('auth', 'Ключ/доступ (401/403)'), ('empty', 'Порожня відповідь'), ('unknown', 'Інше')], default='unknown', max_length=20)),
                ('fingerprint', models.CharField(db_index=True, max_length=120)),
                ('active_fingerprint', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('state', models.CharField(choices=[('open', 'Відкритий'), ('recovering', 'Відновлюється'), ('closed', 'Закритий')], db_index=True, default='open', max_length=12)),
                ('opened_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_failure_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('first_success_after_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('close_reason', models.CharField(blank=True, default='', max_length=32)),
                ('observed_scopes', models.JSONField(blank=True, default=list)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('consecutive_success_count', models.PositiveSmallIntegerField(default=0)),
                ('affected_clients_count', models.PositiveIntegerField(default=0)),
                ('holding_sent_count', models.PositiveIntegerField(default=0)),
                ('severity', models.PositiveSmallIntegerField(default=1)),
                ('manager_alert_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Інцидент провайдера IG',
                'verbose_name_plural': 'Інциденти провайдера IG',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='geminirequestattempt',
            name='attempt_index',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='geminirequestattempt',
            name='candidate_index',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='geminirequestattempt',
            name='client_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geminirequestattempt',
            name='incident_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geminirequestattempt',
            name='lane',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='geminirequestattempt',
            name='logical_turn_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='geminirequestattempt',
            name='not_attempted_reason',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='geminirequestattempt',
            name='recovery_job_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geminirequestattempt',
            name='reply_message_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geminirequestattempt',
            name='source_message_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='igaireplyrecoveryjob',
            name='active_cursor_key',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='igaireplyrecoveryjob',
            name='superseded_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_jobs', to='management.igaireplyrecoveryjob'),
        ),
        migrations.AddField(
            model_name='instagrambotmessage',
            name='gemini_request_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AddIndex(
            model_name='geminirequestattempt',
            index=models.Index(fields=['source_message_id', '-id'], name='gemini_attempt_source'),
        ),
        migrations.AddIndex(
            model_name='geminirequestattempt',
            index=models.Index(fields=['client_id', '-id'], name='gemini_attempt_client'),
        ),
        migrations.AddIndex(
            model_name='geminirequestattempt',
            index=models.Index(fields=['lane', '-id'], name='gemini_attempt_lane'),
        ),
        migrations.AddField(
            model_name='igclientdegradationepisode',
            name='client',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='degradation_episodes', to='management.igclient'),
        ),
        migrations.AddField(
            model_name='igclientdegradationepisode',
            name='holding_message',
            field=models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='degradation_episode_holding', to='management.instagrambotmessage'),
        ),
        migrations.AddField(
            model_name='igaireplyrecoveryjob',
            name='degradation_episode',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_jobs', to='management.igclientdegradationepisode'),
        ),
        migrations.AddIndex(
            model_name='igproviderincident',
            index=models.Index(fields=['state', '-last_failure_at'], name='ig_incident_state_recent'),
        ),
        migrations.AddIndex(
            model_name='igproviderincident',
            index=models.Index(fields=['role', 'state', '-id'], name='ig_incident_role_state'),
        ),
        migrations.AddField(
            model_name='igclientdegradationepisode',
            name='incident',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='client_episodes', to='management.igproviderincident'),
        ),
        migrations.AddIndex(
            model_name='igclientdegradationepisode',
            index=models.Index(fields=['client', 'state', '-id'], name='ig_degradation_client'),
        ),
        migrations.AddIndex(
            model_name='igclientdegradationepisode',
            index=models.Index(fields=['incident', 'state'], name='ig_degradation_incident'),
        ),
        migrations.AddConstraint(
            model_name='igclientdegradationepisode',
            constraint=models.UniqueConstraint(fields=('client', 'incident'), name='ig_degradation_episode_unique'),
        ),
    ]
