# Generated by Django 6.1 on 2026-08-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0170_ea_provider_incident_and_turn_lineage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iglifecycleevent',
            name='kind',
            field=models.CharField(choices=[('payment_verified', 'Оплату підтверджено'), ('ttn_created', 'ТТН створено'), ('parcel_arrived', 'Посилка у відділенні'), ('delivered_review_requested', 'Замовлення отримано, запит відгуку')], db_index=True, max_length=40),
        ),
    ]
