# Generated by Django 6.1 on 2026-08-28 08:54

from django.db import migrations, models
from django.db.models import Max
from django.db.models.functions import Coalesce


def backfill_window_anchor(apps, schema_editor):
    """Заполнить якорь окна Meta ТОЛЬКО по входящим сообщениям клиента.

    Старое `last_message_at` смешивало входящие и исходящие, поэтому его нельзя
    просто скопировать: это перенесло бы ровно тот дефект, из-за которого
    исходящее сообщение бота «открывало» окно, которого не было.
    """
    IgClient = apps.get_model("management", "IgClient")
    InstagramBotMessage = apps.get_model("management", "InstagramBotMessage")

    anchors = dict(
        InstagramBotMessage.objects.filter(role="user")
        .exclude(client_id__isnull=True)
        .values_list("client_id")
        .annotate(anchor=Max(Coalesce("provider_created_at", "created_at")))
        .values_list("client_id", "anchor")
    )
    if not anchors:
        return
    batch = []
    for client in IgClient.objects.filter(pk__in=list(anchors)).only(
        "id", "last_user_message_at"
    ).iterator(chunk_size=500):
        anchor = anchors.get(client.pk)
        if anchor and client.last_user_message_at != anchor:
            client.last_user_message_at = anchor
            batch.append(client)
        if len(batch) >= 500:
            IgClient.objects.bulk_update(batch, ["last_user_message_at"])
            batch = []
    if batch:
        IgClient.objects.bulk_update(batch, ["last_user_message_at"])


def noop_reverse(apps, schema_editor):
    """Обратная миграция снимает только колонку; данные восстановимы backfill-ом."""


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0171_ig_lifecycle_parcel_arrived'),
    ]

    operations = [
        migrations.AddField(
            model_name='igclient',
            name='last_user_message_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(backfill_window_anchor, noop_reverse),
    ]
