# Generated by Django 6.1 on 2026-08-28 10:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0172_ig_client_last_user_message_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgCustomerTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('window_deadline', models.DateTimeField(db_index=True)),
                ('claim_state', models.CharField(choices=[('open', 'Відкритий'), ('claimed', 'Захоплений'), ('processed', 'Опрацьований'), ('superseded', 'Витіснений')], db_index=True, default='open', max_length=12)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claim_token', models.CharField(blank=True, default='', max_length=40)),
                ('message_count', models.PositiveIntegerField(default=1)),
                ('dedupe_keys', models.JSONField(blank=True, default=list)),
                ('bypass_debounce', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='customer_turns', to='management.igclient')),
                ('episode', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_turns', to='management.igcommercialepisode')),
                ('primary_source_message', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='primary_customer_turn', to='management.instagrambotmessage')),
            ],
            options={
                'verbose_name': 'Хід клієнта IG',
                'verbose_name_plural': 'Ходи клієнтів IG',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='IgTurnMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveSmallIntegerField(default=1)),
                ('role', models.CharField(blank=True, default='', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('message', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='turn_membership', to='management.instagrambotmessage')),
                ('turn', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='turn_messages', to='management.igcustomerturn')),
            ],
            options={
                'verbose_name': 'Повідомлення ходу IG',
                'verbose_name_plural': 'Повідомлення ходів IG',
                'ordering': ['turn_id', 'ordinal', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='igcustomerturn',
            index=models.Index(fields=['client', 'claim_state', '-id'], name='ig_turn_client_state'),
        ),
        migrations.AddIndex(
            model_name='igcustomerturn',
            index=models.Index(fields=['claim_state', 'window_deadline'], name='ig_turn_due'),
        ),
        migrations.AddConstraint(
            model_name='igturnmessage',
            constraint=models.UniqueConstraint(fields=('turn', 'ordinal'), name='ig_turn_message_ordinal_unique'),
        ),
    ]
