# Generated by Django 6.1 on 2026-08-29 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0173_ig_customer_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrambotmessage',
            name='consumed_by_turn',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absorbed_messages', to='management.igcustomerturn'),
        ),
    ]
