# Generated by Django 6.1 on 2026-08-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0174_ig_message_consumed_by_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='geminikeystate',
            name='model_cooldowns',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
