# Generated by Django 6.1 on 2026-08-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0175_gemini_key_model_cooldowns'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiModelQuotaUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(db_index=True, max_length=40)),
                ('model', models.CharField(db_index=True, max_length=80)),
                ('day_date', models.DateField(db_index=True)),
                ('requests', models.PositiveIntegerField(default=0)),
                ('tokens', models.PositiveBigIntegerField(default=0)),
                ('minute_started_at', models.DateTimeField(blank=True, null=True)),
                ('minute_requests', models.PositiveIntegerField(default=0)),
                ('minute_tokens', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Витрата квоти Gemini',
                'verbose_name_plural': 'Витрати квоти Gemini',
                'indexes': [models.Index(fields=['day_date', 'model'], name='gemini_quota_day_model')],
                'constraints': [models.UniqueConstraint(fields=('key_name', 'model', 'day_date'), name='gemini_quota_pair_day')],
            },
        ),
    ]
