# Generated by Django 6.1 on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0176_gemini_model_quota_usage"),
    ]

    operations = [
        migrations.AddField(
            model_name="instagrambotsettings",
            name="gemini_routing_mode",
            field=models.CharField(
                choices=[("adaptive", "Адаптивний"), ("pinned", "Тимчасово закріплений")],
                default="adaptive",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="instagrambotsettings",
            name="pinned_chat_model",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="instagrambotsettings",
            name="pinned_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="instagrambotmessage",
            name="gemini_routing_deadline_ms",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="instagrambotmessage",
            name="gemini_routing_model_chain",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="instagrambotmessage",
            name="gemini_routing_policy_version",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="instagrambotmessage",
            name="gemini_routing_reason_codes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="instagrambotmessage",
            name="gemini_task_class",
            field=models.CharField(blank=True, default="", max_length=24),
        ),
        migrations.AddField(
            model_name="instagrambotmessage",
            name="gemini_routing_lane",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="instagrambotmessage",
            name="gemini_routing_authority_version",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="instagrambotmessage",
            name="gemini_routing_requires_media",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="instagrambotmessage",
            name="gemini_routing_commercial_risk",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="instagrambotmessage",
            name="gemini_routing_mode",
            field=models.CharField(blank=True, default="", max_length=12),
        ),
        migrations.AddField(
            model_name="igaireplyrecoveryjob",
            name="routing_decision",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="igugcreward",
            name="discount_percent",
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
