# Generated by Django 6.1 on 2026-08-30; retry-safe for MariaDB partial DDL.

from django.db import migrations, models

from management.migrations._resumable_schema import ensure_additive_schema


FIELD_SPECS = (
    ("management", "InstagramBotSettings", "gemini_routing_mode"),
    ("management", "InstagramBotSettings", "pinned_chat_model"),
    ("management", "InstagramBotSettings", "pinned_until"),
    ("management", "InstagramBotSettings", "settings_revision"),
    ("management", "InstagramBotMessage", "gemini_routing_deadline_ms"),
    ("management", "InstagramBotMessage", "gemini_routing_model_chain"),
    ("management", "InstagramBotMessage", "gemini_routing_policy_version"),
    ("management", "InstagramBotMessage", "gemini_routing_reason_codes"),
    ("management", "InstagramBotMessage", "gemini_task_class"),
    ("management", "InstagramBotMessage", "gemini_routing_lane"),
    ("management", "InstagramBotMessage", "gemini_routing_authority_version"),
    ("management", "InstagramBotMessage", "gemini_routing_requires_media"),
    ("management", "InstagramBotMessage", "gemini_routing_commercial_risk"),
    ("management", "InstagramBotMessage", "gemini_routing_mode"),
    ("management", "InstagramBotMessage", "turn_intelligence_artifact"),
    ("management", "InstagramBotMessage", "private_media_delete_after"),
    ("management", "InstagramBotMessage", "private_media_state"),
    ("management", "InstagramBotMessage", "private_media_delete_token"),
    ("management", "InstagramBotMessage", "private_media_delete_claimed_at"),
    ("management", "InstagramBotMessage", "private_media_use_token"),
    ("management", "InstagramBotMessage", "private_media_use_until"),
    ("management", "IgClient", "privacy_erasure_started_at"),
    ("management", "IgAiReplyRecoveryJob", "routing_decision"),
    ("management", "IgUgcReward", "discount_percent"),
)

INDEX_SPECS = (
    ("management", "InstagramBotMessage", "mgmt_igmsg_media_del"),
    ("management", "InstagramBotMessage", "mgmt_igmsg_media_use"),
)

CONSTRAINT_SPECS = (
    ("management", "InstagramBotMessage", "mgmt_igmsg_media_state"),
)


def ensure_0177_schema(apps, schema_editor):
    ensure_additive_schema(
        apps,
        schema_editor,
        field_specs=FIELD_SPECS,
        index_specs=INDEX_SPECS,
        constraint_specs=CONSTRAINT_SPECS,
    )


STATE_OPERATIONS = [
    migrations.AddField(
        model_name="instagrambotsettings",
        name="gemini_routing_mode",
        field=models.CharField(
            choices=[("adaptive", "Адаптивний"), ("pinned", "Тимчасово закріплений")],
            default="adaptive",
            max_length=12,
        ),
    ),
    migrations.AddField(
        model_name="instagrambotsettings",
        name="pinned_chat_model",
        field=models.CharField(blank=True, default="", max_length=80),
    ),
    migrations.AddField(
        model_name="instagrambotsettings",
        name="pinned_until",
        field=models.DateTimeField(blank=True, null=True),
    ),
    migrations.AddField(
        model_name="instagrambotsettings",
        name="settings_revision",
        field=models.PositiveBigIntegerField(default=0),
    ),
    migrations.AddField(
        model_name="instagrambotmessage",
        name="gemini_routing_deadline_ms",
        field=models.PositiveIntegerField(default=0),
    ),
    migrations.AddField(
        model_name="instagrambotmessage",
        name="gemini_routing_model_chain",
        field=models.JSONField(blank=True, default=list),
    ),
    migrations.AddField(
        model_name="instagrambotmessage",
        name="gemini_routing_policy_version",
        field=models.CharField(blank=True, default="", max_length=32),
    ),
    migrations.AddField(
        model_name="instagrambotmessage",
        name="gemini_routing_reason_codes",
        field=models.JSONField(blank=True, default=list),
    ),
    migrations.AddField(
        model_name="instagrambotmessage",
        name="gemini_task_class",
        field=models.CharField(blank=True, default="", max_length=24),
    ),
    migrations.AddField(
        model_name="instagrambotmessage",
        name="gemini_routing_lane",
        field=models.CharField(blank=True, default="", max_length=16),
    ),
    migrations.AddField(
        model_name="instagrambotmessage",
        name="gemini_routing_authority_version",
        field=models.CharField(blank=True, default="", max_length=32),
    ),
    migrations.AddField(
        model_name="instagrambotmessage",
        name="gemini_routing_requires_media",
        field=models.BooleanField(default=False),
    ),
    migrations.AddField(
        model_name="instagrambotmessage",
        name="gemini_routing_commercial_risk",
        field=models.CharField(blank=True, default="", max_length=16),
    ),
    migrations.AddField(
        model_name="instagrambotmessage",
        name="gemini_routing_mode",
        field=models.CharField(blank=True, default="", max_length=12),
    ),
    migrations.AddField(
        model_name="instagrambotmessage",
        name="turn_intelligence_artifact",
        field=models.JSONField(blank=True, default=dict),
    ),
    migrations.AddField(
        model_name="instagrambotmessage",
        name="private_media_delete_after",
        field=models.DateTimeField(blank=True, null=True),
    ),
    migrations.AddField(
        model_name="instagrambotmessage",
        name="private_media_state",
        field=models.CharField(
            blank=True,
            choices=[
                ("", "none"), ("active", "active"),
                ("delete_pending", "delete_pending"),
                ("deleting", "deleting"),
                ("delete_failed", "delete_failed"),
                ("deleted", "deleted"),
            ],
            default="",
            max_length=20,
        ),
    ),
    migrations.AddField(
        model_name="instagrambotmessage",
        name="private_media_delete_token",
        field=models.CharField(blank=True, default="", max_length=64),
    ),
    migrations.AddField(
        model_name="instagrambotmessage",
        name="private_media_delete_claimed_at",
        field=models.DateTimeField(blank=True, null=True),
    ),
    migrations.AddField(
        model_name="instagrambotmessage",
        name="private_media_use_token",
        field=models.CharField(blank=True, default="", max_length=64),
    ),
    migrations.AddField(
        model_name="instagrambotmessage",
        name="private_media_use_until",
        field=models.DateTimeField(blank=True, null=True),
    ),
    migrations.AddField(
        model_name="igclient",
        name="privacy_erasure_started_at",
        field=models.DateTimeField(blank=True, null=True),
    ),
    migrations.AddField(
        model_name="igaireplyrecoveryjob",
        name="routing_decision",
        field=models.JSONField(blank=True, default=dict),
    ),
    migrations.AddField(
        model_name="igugcreward",
        name="discount_percent",
        field=models.PositiveSmallIntegerField(default=10),
    ),
    migrations.AddIndex(
        model_name="instagrambotmessage",
        index=models.Index(
            fields=["private_media_delete_after"],
            name="mgmt_igmsg_media_del",
        ),
    ),
    migrations.AddIndex(
        model_name="instagrambotmessage",
        index=models.Index(
            fields=["private_media_use_until"],
            name="mgmt_igmsg_media_use",
        ),
    ),
    migrations.AddConstraint(
        model_name="instagrambotmessage",
        constraint=models.CheckConstraint(
            condition=models.Q(private_media_state__in=[
                "", "active", "delete_pending", "deleting",
                "delete_failed", "deleted",
            ]),
            name="mgmt_igmsg_media_state",
        ),
    ),
]


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("management", "0176_gemini_model_quota_usage"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=STATE_OPERATIONS,
        ),
        migrations.RunPython(
            ensure_0177_schema,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
