# Generated by Django 6.1 on 2026-08-30 12:27

import django.db.models.deletion
from django.db import migrations as django_migrations, models

from management.migration_operations import (
    IdempotentAddConstraint,
    IdempotentAddExactUniqueConstraint,
    IdempotentAddField,
    IdempotentAddIndex,
    IdempotentCreateModel,
)


class _RetrySafeOperations:
    """Keep generated operation bodies readable while making DDL replay-safe."""

    Migration = django_migrations.Migration
    AddField = IdempotentAddField
    CreateModel = IdempotentCreateModel
    AddIndex = IdempotentAddIndex
    AddConstraint = IdempotentAddConstraint
    AddExactUniqueConstraint = IdempotentAddExactUniqueConstraint


migrations = _RetrySafeOperations


class Migration(migrations.Migration):

    # MariaDB commits each DDL operation separately. Every operation below is
    # introspection-backed and skips an already-applied object on retry.
    atomic = False

    dependencies = [
        ('management', '0178_gemini_accounting_prerequisite_innodb'),
    ]

    operations = [
        migrations.AddField(
            model_name='geminirequestattempt',
            name='accounting_mode',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='geminirequestattempt',
            name='dispatch_pacific_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geminirequestattempt',
            name='estimated_prompt_tokens',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='geminirequestattempt',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geminirequestattempt',
            name='fsm_state',
            field=models.CharField(choices=[('legacy', 'Legacy telemetry'), ('planned', 'Заплановано'), ('reserved', 'Квоту зарезервовано'), ('provider_started', 'Виклик провайдера розпочато'), ('succeeded', 'Успішно'), ('failed', 'Помилка'), ('timeout_ambiguous', 'Неоднозначний таймаут'), ('succeeded_late', 'Пізній успіх'), ('cancelled_pre_dispatch', 'Скасовано до виклику')], default='legacy', max_length=24),
        ),
        migrations.AddField(
            model_name='geminirequestattempt',
            name='permit_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geminirequestattempt',
            name='permit_released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geminirequestattempt',
            name='project_identity',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='geminirequestattempt',
            name='provider_block_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geminirequestattempt',
            name='provider_quota_dimensions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='geminirequestattempt',
            name='provider_quota_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='geminirequestattempt',
            name='provider_quota_metric',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='geminirequestattempt',
            name='provider_retry_after_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='geminirequestattempt',
            name='provider_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geminirequestattempt',
            name='reservation_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geminirequestattempt',
            name='reservation_released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geminirequestattempt',
            name='reserved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geminirequestattempt',
            name='reserved_prompt_tokens',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='geminirequestattempt',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geminirequestattempt',
            name='shadow_decision',
            field=models.CharField(choices=[('unknown', 'Невідомо'), ('allow', 'Було б дозволено'), ('deny', 'Було б відхилено')], default='unknown', max_length=8),
        ),
        migrations.AddField(
            model_name='geminirequestattempt',
            name='shadow_deny_reason',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='geminirequestattempt',
            name='total_tokens',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='geminirequestattempt',
            name='winner_claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GeminiQuotaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_version', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=80)),
                ('rpm_limit', models.PositiveIntegerField()),
                ('input_tpm_limit', models.PositiveBigIntegerField()),
                ('rpd_limit', models.PositiveIntegerField()),
                ('permit_limit', models.PositiveSmallIntegerField()),
                ('estimator_version', models.CharField(max_length=32)),
                ('source', models.CharField(choices=[('owner_observed', 'Підтверджено власником'), ('provider_docs', 'Документація провайдера'), ('provider_error', 'Структурована помилка провайдера'), ('admin', 'Версія адміністратора')], max_length=24)),
                ('source_reference', models.CharField(blank=True, default='', max_length=120)),
                ('observed_at', models.DateTimeField()),
                ('effective_from', models.DateTimeField()),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Профіль квоти Gemini',
                'verbose_name_plural': 'Профілі квот Gemini',
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['model', 'effective_from'], name='gem_qprof_model_effective')],
                'constraints': [models.UniqueConstraint(fields=('profile_version', 'model'), name='gem_qprof_version_model_uniq'), models.CheckConstraint(condition=models.Q(('rpm_limit__gt', 0)), name='gem_qprof_rpm_gt_zero'), models.CheckConstraint(condition=models.Q(('input_tpm_limit__gt', 0)), name='gem_qprof_tpm_gt_zero'), models.CheckConstraint(condition=models.Q(('rpd_limit__gt', 0)), name='gem_qprof_rpd_gt_zero'), models.CheckConstraint(condition=models.Q(('permit_limit__gt', 0)), name='gem_qprof_permit_gt_zero'), models.CheckConstraint(condition=models.Q(('effective_until__isnull', True), ('effective_until__gt', models.F('effective_from')), _connector='OR'), name='gem_qprof_effective_window')],
            },
        ),
        migrations.AddField(
            model_name='geminirequestattempt',
            name='quota_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='management.geminiquotaprofile'),
        ),
        migrations.CreateModel(
            name='GeminiQuotaState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_identity', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=80)),
                ('pacific_day', models.DateField(blank=True, null=True)),
                ('rpd_reserved', models.PositiveIntegerField(default=0)),
                ('rpd_dispatched', models.PositiveIntegerField(default=0)),
                ('rpd_uncertain', models.PositiveIntegerField(default=0)),
                ('in_flight_count', models.PositiveSmallIntegerField(default=0)),
                ('next_permit_expiry_at', models.DateTimeField(blank=True, null=True)),
                ('provider_blocks', models.JSONField(blank=True, default=dict)),
                ('external_usage_suspected', models.BooleanField(default=False)),
                ('accounting_status', models.CharField(choices=[('unknown', 'Невідомо'), ('available', 'Доступно за локальним станом'), ('blocked', 'Заблоковано провайдером'), ('degraded', 'Облік деградував')], default='unknown', max_length=12)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_kind', models.CharField(blank=True, default='', max_length=32)),
                ('last_http_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_latency_ms', models.PositiveIntegerField(default=0)),
                ('latency_ewma_ms', models.PositiveIntegerField(default=0)),
                ('revision', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quota_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quota_states', to='management.geminiquotaprofile')),
            ],
            options={
                'verbose_name': 'Стан квоти Gemini V2',
                'verbose_name_plural': 'Стани квот Gemini V2',
            },
        ),
        migrations.CreateModel(
            name='GeminiRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=40, unique=True)),
                ('lane', models.CharField(blank=True, default='', max_length=16)),
                ('task_class', models.CharField(blank=True, default='', max_length=24)),
                ('reasoning_task', models.CharField(blank=True, default='', max_length=40)),
                ('logical_turn_id', models.CharField(blank=True, default='', max_length=64)),
                ('source_message_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('client_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('recovery_job_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('reply_message_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('routing_policy_version', models.CharField(blank=True, default='', max_length=32)),
                ('accounting_policy_version', models.CharField(blank=True, default='', max_length=32)),
                ('quota_profile_version', models.CharField(blank=True, default='', max_length=40)),
                ('authority_snapshot_version', models.CharField(blank=True, default='', max_length=32)),
                ('routing_mode', models.CharField(blank=True, default='', max_length=12)),
                ('commercial_risk', models.CharField(blank=True, default='', max_length=16)),
                ('requires_media_reasoning', models.BooleanField(default=False)),
                ('candidate_plan', models.JSONField(blank=True, default=list)),
                ('candidate_plan_digest', models.CharField(blank=True, default='', max_length=64)),
                ('candidate_outcomes', models.JSONField(blank=True, default=dict)),
                ('deadline_ms', models.PositiveIntegerField(default=0)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('accounting_mode', models.CharField(choices=[('off', 'Вимкнено'), ('shadow', 'Тіньовий облік'), ('enforced', "Обов'язковий облік"), ('emergency', 'Аварійний Lite')], default='off', max_length=12)),
                ('terminal_resolution', models.CharField(blank=True, default='', max_length=24)),
                ('terminal_reason', models.CharField(blank=True, default='', max_length=48)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider_phase_started_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_requests', to='management.geminirequest')),
                ('winner_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='won_gemini_requests', to='management.geminirequestattempt')),
            ],
            options={
                'verbose_name': 'Запит Gemini',
                'verbose_name_plural': 'Запити Gemini',
            },
        ),
        migrations.AddField(
            model_name='geminirequestattempt',
            name='request_graph',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='management.geminirequest'),
        ),
        migrations.AddIndex(
            model_name='geminirequestattempt',
            index=models.Index(fields=['project_identity', 'model', 'provider_started_at'], name='gem_att_pair_started'),
        ),
        migrations.AddIndex(
            model_name='geminirequestattempt',
            index=models.Index(fields=['project_identity', 'model', 'dispatch_pacific_day', 'fsm_state'], name='gem_att_pair_day_state'),
        ),
        migrations.AddIndex(
            model_name='geminirequestattempt',
            index=models.Index(fields=['fsm_state', 'reservation_expires_at'], name='gem_att_state_reserve'),
        ),
        migrations.AddIndex(
            model_name='geminirequestattempt',
            index=models.Index(fields=['fsm_state', 'permit_expires_at'], name='gem_att_state_permit'),
        ),
        migrations.AddConstraint(
            model_name='geminirequestattempt',
            constraint=models.UniqueConstraint(fields=('request_graph', 'attempt_index'), name='gem_att_graph_index_unique'),
        ),
        migrations.AddConstraint(
            model_name='geminirequestattempt',
            constraint=models.CheckConstraint(condition=models.Q(('provider_started_at__isnull', True), ('dispatch_pacific_day__isnull', False), _connector='OR'), name='gem_att_started_has_day'),
        ),
        migrations.AddIndex(
            model_name='geminiquotastate',
            index=models.Index(fields=['accounting_status', 'updated_at'], name='gem_qstate_status_updated'),
        ),
        migrations.AddIndex(
            model_name='geminiquotastate',
            index=models.Index(fields=['next_permit_expiry_at'], name='gem_qstate_permit_expiry'),
        ),
        migrations.AddConstraint(
            model_name='geminiquotastate',
            constraint=models.UniqueConstraint(fields=('project_identity', 'model'), name='gem_qstate_project_model_uniq'),
        ),
        migrations.AddIndex(
            model_name='geminirequest',
            index=models.Index(fields=['lane', '-created_at'], name='gem_req_lane_created'),
        ),
        migrations.AddIndex(
            model_name='geminirequest',
            index=models.Index(fields=['logical_turn_id', '-created_at'], name='gem_req_turn_created'),
        ),
        migrations.AddIndex(
            model_name='geminirequest',
            index=models.Index(fields=['terminal_resolution', 'deadline_at'], name='gem_req_resolution_deadline'),
        ),
        migrations.AddExactUniqueConstraint(
            model_name='geminirequest',
            constraint=models.UniqueConstraint(fields=('source_message_id', 'lane'), name='gem_req_source_lane_uniq'),
        ),
    ]
