# Generated by Django 6.1 on 2026-08-30 19:17

import django.db.models.deletion
from django.db import migrations, models

from management.migrations._resumable_schema import ensure_additive_schema


STATE_OPERATIONS = [
        migrations.CreateModel(
            name='IgCheckoutInvoiceGenerationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=180, unique=True)),
                ('kind', models.CharField(choices=[('created', 'Generation created'), ('provider_started', 'Provider request started'), ('provider_succeeded', 'Provider request succeeded'), ('provider_failed', 'Provider request failed'), ('provider_ambiguous', 'Provider request ambiguous'), ('terminalized', 'Generation terminalized'), ('winner_claimed', 'Winner claimed'), ('loser_paid_review', 'Paid loser needs review'), ('resource_review', 'Paid generation lacks resources')], db_index=True, max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['id'],
                'base_manager_name': 'objects',
            },
        ),
        migrations.AddField(
            model_name='igcheckoutproposal',
            name='assisted_checkout_v2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='igcheckoutproposal',
            name='custom_print_full_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='igcheckoutproposal',
            name='payment_policy',
            field=models.CharField(choices=[('legacy', 'Legacy checkout policy'), ('full_only', 'Only full payment'), ('full_or_200_cod', 'Full payment or 200 UAH + cash on delivery')], default='legacy', max_length=24),
        ),
        migrations.AddField(
            model_name='igcheckoutproposal',
            name='payment_policy_evidence_digest',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='igcheckoutproposal',
            name='payment_policy_evidence_kind',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='igcheckoutproposal',
            name='payment_policy_evidence_message',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='checkout_payment_policy_evidence', to='management.instagrambotmessage'),
        ),
        migrations.AddField(
            model_name='igcheckoutproposal',
            name='payment_policy_evidence_revision',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='IgCheckoutInvoiceGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.PositiveIntegerField()),
                ('series_key', models.CharField(max_length=64)),
                ('proposal_revision', models.PositiveIntegerField()),
                ('active_slot', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('winner_slot', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('state', models.CharField(choices=[('planned', 'Planned'), ('provider_inflight', 'Provider request in flight'), ('invoice_created', 'Invoice created'), ('provider_ambiguous', 'Provider result ambiguous'), ('failed', 'Generation failed'), ('expired', 'Generation expired'), ('cancelled', 'Generation cancelled'), ('winner_claimed', 'Verified winner claimed'), ('paid_winner', 'Winner order materialized'), ('late_paid_review', 'Paid losing generation review'), ('resource_review', 'Paid but resources need review')], db_index=True, default='planned', max_length=28)),
                ('payment_choice', models.CharField(choices=[('online_full', 'Full online payment'), ('prepay_200_cod', '200 UAH + COD')], default='online_full', max_length=24)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('policy_evidence_kind', models.CharField(blank=True, default='', max_length=32)),
                ('policy_evidence_digest', models.CharField(blank=True, default='', max_length=64)),
                ('provider', models.CharField(default='monobank', max_length=24)),
                ('provider_invoice_id', models.CharField(blank=True, max_length=128, null=True)),
                ('provider_call_token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('provider_started_at', models.DateTimeField(blank=True, null=True)),
                ('provider_completed_at', models.DateTimeField(blank=True, null=True)),
                ('winner_claimed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('terminal_at', models.DateTimeField(blank=True, null=True)),
                ('review_reason', models.CharField(blank=True, default='', max_length=96)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_attempt', models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instagram_checkout_generation', to='orders.paymentattempt')),
                ('policy_evidence_message', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='checkout_invoice_generation_policy_evidence', to='management.instagrambotmessage')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_generations', to='management.igcheckoutproposal')),
            ],
            options={
                'ordering': ['proposal_id', 'generation'],
            },
        ),
        migrations.AddField(
            model_name='igcheckoutinventoryreservation',
            name='invoice_generation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventory_reservations', to='management.igcheckoutinvoicegeneration'),
        ),
        migrations.AddField(
            model_name='igcheckoutproposal',
            name='current_invoice_generation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_for_proposals', to='management.igcheckoutinvoicegeneration'),
        ),
        migrations.AddField(
            model_name='igcheckoutproposal',
            name='winner_invoice_generation',
            field=models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='winner_for_proposal', to='management.igcheckoutinvoicegeneration'),
        ),
        migrations.AddIndex(
            model_name='igcheckoutinventoryreservation',
            index=models.Index(fields=['invoice_generation', 'state', 'id'], name='ig_res_generation_state'),
        ),
        migrations.AddConstraint(
            model_name='igcheckoutproposal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assisted_checkout_v2', False), ('payment_policy', 'legacy')), models.Q(('assisted_checkout_v2', True), ('payment_policy__in', ['full_only', 'full_or_200_cod'])), _connector='OR'), name='ig_prop_v2_policy_shape'),
        ),
        migrations.AddConstraint(
            model_name='igcheckoutproposal',
            constraint=models.CheckConstraint(condition=models.Q(('custom_print_full_only', False), ('payment_policy', 'full_only'), _connector='OR'), name='ig_prop_custom_full_only'),
        ),
        migrations.AddField(
            model_name='igcheckoutinvoicegenerationevent',
            name='generation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='management.igcheckoutinvoicegeneration'),
        ),
        migrations.AddField(
            model_name='igcheckoutinvoicegenerationevent',
            name='payment_attempt',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instagram_checkout_generation_events', to='orders.paymentattempt'),
        ),
        migrations.AddField(
            model_name='igcheckoutinvoicegenerationevent',
            name='proposal',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoice_generation_events', to='management.igcheckoutproposal'),
        ),
        migrations.AddIndex(
            model_name='igcheckoutinvoicegeneration',
            index=models.Index(fields=['proposal', 'state', 'generation'], name='ig_invgen_prop_state_gen'),
        ),
        migrations.AddIndex(
            model_name='igcheckoutinvoicegeneration',
            index=models.Index(fields=['state', 'expires_at', 'id'], name='ig_invgen_state_expiry'),
        ),
        migrations.AddIndex(
            model_name='igcheckoutinvoicegeneration',
            index=models.Index(fields=['provider', 'provider_invoice_id'], name='ig_invgen_provider_invoice'),
        ),
        migrations.AddConstraint(
            model_name='igcheckoutinvoicegeneration',
            constraint=models.UniqueConstraint(fields=('proposal', 'generation'), name='ig_invgen_proposal_generation_uniq'),
        ),
        migrations.AddConstraint(
            model_name='igcheckoutinvoicegeneration',
            constraint=models.UniqueConstraint(fields=('proposal', 'active_slot'), name='ig_invgen_active_slot_uniq'),
        ),
        migrations.AddConstraint(
            model_name='igcheckoutinvoicegeneration',
            constraint=models.UniqueConstraint(fields=('proposal', 'winner_slot'), name='ig_invgen_winner_slot_uniq'),
        ),
        migrations.AddConstraint(
            model_name='igcheckoutinvoicegeneration',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_invoice_id'), name='ig_invgen_provider_invoice_uniq'),
        ),
        migrations.AddConstraint(
            model_name='igcheckoutinvoicegeneration',
            constraint=models.CheckConstraint(condition=models.Q(('generation__gte', 1)), name='ig_invgen_generation_positive'),
        ),
        migrations.AddConstraint(
            model_name='igcheckoutinvoicegeneration',
            constraint=models.CheckConstraint(condition=models.Q(('active_slot__isnull', True), ('active_slot', 1), _connector='OR'), name='ig_invgen_active_slot_shape'),
        ),
        migrations.AddConstraint(
            model_name='igcheckoutinvoicegeneration',
            constraint=models.CheckConstraint(condition=models.Q(('winner_slot__isnull', True), ('winner_slot', 1), _connector='OR'), name='ig_invgen_winner_slot_shape'),
        ),
        migrations.AddConstraint(
            model_name='igcheckoutinvoicegeneration',
            constraint=models.CheckConstraint(condition=models.Q(('payment_amount__gt', 0)), name='ig_invgen_payment_positive'),
        ),
        migrations.AddIndex(
            model_name='igcheckoutinvoicegenerationevent',
            index=models.Index(fields=['generation', 'kind', 'id'], name='ig_invgevt_generation_kind'),
        ),
        migrations.AddIndex(
            model_name='igcheckoutinvoicegenerationevent',
            index=models.Index(fields=['proposal', 'kind', 'id'], name='ig_invgevt_proposal_kind'),
        ),
    ]


GENERATION_TABLE = "management_igcheckoutinvoicegeneration"
EVENT_TABLE = "management_igcheckoutinvoicegenerationevent"
PROPOSAL_TABLE = "management_igcheckoutproposal"
RESERVATION_TABLE = "management_igcheckoutinventoryreservation"

GENERATION_FIELDS = (
    "id", "generation", "series_key", "proposal_revision", "active_slot",
    "winner_slot", "state", "payment_choice", "payment_amount",
    "policy_evidence_kind", "policy_evidence_digest", "provider",
    "provider_invoice_id", "provider_call_token", "expires_at",
    "provider_started_at", "provider_completed_at", "winner_claimed_at",
    "paid_at", "terminal_at", "review_reason", "created_at", "updated_at",
    "payment_attempt", "policy_evidence_message", "proposal",
)
EVENT_FIELDS = (
    "id", "event_key", "kind", "payload", "created_at", "generation",
    "payment_attempt", "proposal",
)
PROPOSAL_FIELDS = (
    "assisted_checkout_v2", "custom_print_full_only", "payment_policy",
    "payment_policy_evidence_digest", "payment_policy_evidence_kind",
    "payment_policy_evidence_message", "payment_policy_evidence_revision",
    "current_invoice_generation", "winner_invoice_generation",
)
RESERVATION_FIELDS = ("invoice_generation",)

FIELD_SPECS = tuple(
    ("management", "IgCheckoutInvoiceGeneration", field)
    for field in GENERATION_FIELDS
) + tuple(
    ("management", "IgCheckoutInvoiceGenerationEvent", field)
    for field in EVENT_FIELDS
) + tuple(
    ("management", "IgCheckoutProposal", field)
    for field in PROPOSAL_FIELDS
) + tuple(
    ("management", "IgCheckoutInventoryReservation", field)
    for field in RESERVATION_FIELDS
)

INDEX_SPECS = (
    ("management", "IgCheckoutInvoiceGeneration", "ig_invgen_prop_state_gen"),
    ("management", "IgCheckoutInvoiceGeneration", "ig_invgen_state_expiry"),
    ("management", "IgCheckoutInvoiceGeneration", "ig_invgen_provider_invoice"),
    ("management", "IgCheckoutInvoiceGenerationEvent", "ig_invgevt_generation_kind"),
    ("management", "IgCheckoutInvoiceGenerationEvent", "ig_invgevt_proposal_kind"),
    ("management", "IgCheckoutInventoryReservation", "ig_res_generation_state"),
)

CHECK_SPECS = (
    ("management", "IgCheckoutInvoiceGeneration", "ig_invgen_generation_positive"),
    ("management", "IgCheckoutInvoiceGeneration", "ig_invgen_active_slot_shape"),
    ("management", "IgCheckoutInvoiceGeneration", "ig_invgen_winner_slot_shape"),
    ("management", "IgCheckoutInvoiceGeneration", "ig_invgen_payment_positive"),
    ("management", "IgCheckoutProposal", "ig_prop_v2_policy_shape"),
    ("management", "IgCheckoutProposal", "ig_prop_custom_full_only"),
)

UNIQUE_SPECS = (
    (
        "management", "IgCheckoutInvoiceGeneration",
        "ig_invgen_proposal_generation_uniq", ("proposal", "generation"),
    ),
    (
        "management", "IgCheckoutInvoiceGeneration",
        "ig_invgen_active_slot_uniq", ("proposal", "active_slot"),
    ),
    (
        "management", "IgCheckoutInvoiceGeneration",
        "ig_invgen_winner_slot_uniq", ("proposal", "winner_slot"),
    ),
    (
        "management", "IgCheckoutInvoiceGeneration",
        "ig_invgen_provider_invoice_uniq", ("provider", "provider_invoice_id"),
    ),
    (
        "management", "IgCheckoutInvoiceGeneration",
        "ig_invgen_call_token_uniq", ("provider_call_token",),
    ),
    (
        "management", "IgCheckoutInvoiceGeneration",
        "ig_invgen_attempt_uniq", ("payment_attempt",),
    ),
    (
        "management", "IgCheckoutInvoiceGenerationEvent",
        "ig_invgevt_event_key_uniq", ("event_key",),
    ),
    (
        "management", "IgCheckoutProposal",
        "ig_prop_winner_generation_uniq", ("winner_invoice_generation",),
    ),
)


def _ensure_innodb(schema_editor, table_name):
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT ENGINE FROM information_schema.TABLES "
            "WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=%s",
            [table_name],
        )
        row = cursor.fetchone()
    if not row:
        raise RuntimeError(f"required checkout V2 table missing: {table_name}")
    if str(row[0] or "").upper() != "INNODB":
        schema_editor.execute(
            f"ALTER TABLE {schema_editor.quote_name(table_name)} ENGINE=InnoDB"
        )


def _constraints(schema_editor, table_name):
    with schema_editor.connection.cursor() as cursor:
        return schema_editor.connection.introspection.get_constraints(
            cursor,
            table_name,
        )


def _ensure_unique_shape(apps, schema_editor, spec):
    app_label, model_name, name, field_names = spec
    model = apps.get_model(app_label, model_name)
    expected = tuple(
        model._meta.get_field(field_name).column for field_name in field_names
    )
    existing = _constraints(schema_editor, model._meta.db_table)
    named = existing.get(name)
    if named is not None:
        if not named.get("unique") or tuple(named.get("columns") or ()) != expected:
            raise RuntimeError(f"{name} has incompatible unique shape")
        return
    equivalent = next(
        (
            row for row in existing.values()
            if row.get("unique")
            and tuple(row.get("columns") or ()) == expected
        ),
        None,
    )
    if equivalent is not None:
        return
    schema_editor.add_constraint(
        model,
        models.UniqueConstraint(fields=field_names, name=name),
    )


def _validate_named_shapes(apps, schema_editor):
    for app_label, model_name, index_name in INDEX_SPECS:
        model = apps.get_model(app_label, model_name)
        actual = _constraints(schema_editor, model._meta.db_table).get(index_name)
        index = next(row for row in model._meta.indexes if row.name == index_name)
        expected = tuple(
            model._meta.get_field(field.lstrip("-")).column
            for field in index.fields
        )
        if (
            actual is None
            or tuple(actual.get("columns") or ()) != expected
            or actual.get("unique")
            or actual.get("check")
            or actual.get("foreign_key")
        ):
            raise RuntimeError(f"{index_name} has incompatible index shape")
    for app_label, model_name, check_name in CHECK_SPECS:
        model = apps.get_model(app_label, model_name)
        actual = _constraints(schema_editor, model._meta.db_table).get(check_name)
        if actual is None or not actual.get("check"):
            raise RuntimeError(f"{check_name} is missing or is not a check")
    for spec in UNIQUE_SPECS:
        app_label, model_name, name, field_names = spec
        model = apps.get_model(app_label, model_name)
        expected = tuple(
            model._meta.get_field(field_name).column for field_name in field_names
        )
        actual = _constraints(schema_editor, model._meta.db_table).get(name)
        if actual is not None and (
            not actual.get("unique")
            or tuple(actual.get("columns") or ()) != expected
        ):
            raise RuntimeError(f"{name} has incompatible unique shape")
        if actual is None and not any(
            row.get("unique")
            and tuple(row.get("columns") or ()) == expected
            for row in _constraints(schema_editor, model._meta.db_table).values()
        ):
            raise RuntimeError(f"{name} unique shape is missing")


def ensure_checkout_generation_schema(apps, schema_editor):
    tables = set(schema_editor.connection.introspection.table_names())
    generation_model = apps.get_model(
        "management", "IgCheckoutInvoiceGeneration"
    )
    event_model = apps.get_model(
        "management", "IgCheckoutInvoiceGenerationEvent"
    )
    generation_existed = GENERATION_TABLE in tables
    event_existed = EVENT_TABLE in tables
    if not generation_existed:
        schema_editor.create_model(generation_model)
    _ensure_innodb(schema_editor, GENERATION_TABLE)
    if not event_existed:
        schema_editor.create_model(event_model)
    _ensure_innodb(schema_editor, EVENT_TABLE)

    existing_models = {
        "IgCheckoutProposal",
        "IgCheckoutInventoryReservation",
    }
    if generation_existed:
        existing_models.add("IgCheckoutInvoiceGeneration")
    if event_existed:
        existing_models.add("IgCheckoutInvoiceGenerationEvent")
    ensure_additive_schema(
        apps,
        schema_editor,
        field_specs=tuple(
            spec for spec in FIELD_SPECS if spec[1] in existing_models
        ),
        index_specs=tuple(
            spec for spec in INDEX_SPECS if spec[1] in existing_models
        ),
        constraint_specs=tuple(
            spec for spec in CHECK_SPECS if spec[1] in existing_models
        ),
    )
    for spec in UNIQUE_SPECS:
        model = apps.get_model(spec[0], spec[1])
        if model._meta.db_table in set(
            schema_editor.connection.introspection.table_names()
        ):
            _ensure_unique_shape(apps, schema_editor, spec)

    # Existing proposals are deliberately not promoted or re-expired. This is
    # an idempotent validation-only backfill boundary: legacy TTL/status and
    # active pointers remain byte-for-byte owned by Slice 1.
    proposal_model = apps.get_model("management", "IgCheckoutProposal")
    invalid_legacy = proposal_model.objects.filter(
        assisted_checkout_v2=False,
    ).exclude(
        payment_policy="legacy",
        current_invoice_generation__isnull=True,
        winner_invoice_generation__isnull=True,
    ).exists()
    if invalid_legacy:
        raise RuntimeError("legacy checkout proposal has unexpected V2 state")
    _validate_named_shapes(apps, schema_editor)


def create_generation_event_triggers(apps, schema_editor):
    del apps
    update_name = "ig_invgevt_no_update"
    delete_name = "ig_invgevt_no_delete"
    if schema_editor.connection.vendor == "mysql":
        schema_editor.execute(f"DROP TRIGGER IF EXISTS {update_name}")
        schema_editor.execute(f"DROP TRIGGER IF EXISTS {delete_name}")
        schema_editor.execute(
            f"CREATE TRIGGER {update_name} BEFORE UPDATE ON {EVENT_TABLE} "
            "FOR EACH ROW SIGNAL SQLSTATE '45000' "
            "SET MESSAGE_TEXT='IgCheckoutInvoiceGenerationEvent is append-only'"
        )
        schema_editor.execute(
            f"CREATE TRIGGER {delete_name} BEFORE DELETE ON {EVENT_TABLE} "
            "FOR EACH ROW SIGNAL SQLSTATE '45000' "
            "SET MESSAGE_TEXT='IgCheckoutInvoiceGenerationEvent is append-only'"
        )
    elif schema_editor.connection.vendor == "sqlite":
        schema_editor.execute(f"DROP TRIGGER IF EXISTS {update_name}")
        schema_editor.execute(f"DROP TRIGGER IF EXISTS {delete_name}")
        schema_editor.execute(
            f"CREATE TRIGGER {update_name} BEFORE UPDATE ON {EVENT_TABLE} "
            "BEGIN SELECT RAISE(ABORT, "
            "'IgCheckoutInvoiceGenerationEvent is append-only'); END"
        )
        schema_editor.execute(
            f"CREATE TRIGGER {delete_name} BEFORE DELETE ON {EVENT_TABLE} "
            "BEGIN SELECT RAISE(ABORT, "
            "'IgCheckoutInvoiceGenerationEvent is append-only'); END"
        )


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("management", "0183_analysis_v2_result_proposals"),
        ("orders", "0058_paymentattempt_checkout_series"),
    ]
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=STATE_OPERATIONS,
        ),
        migrations.RunPython(ensure_checkout_generation_schema),
        migrations.RunPython(create_generation_event_triggers),
    ]
