# Generated by Django 6.1 on 2026-08-30 19:17

import django.db.models.deletion
import re
from django.db import migrations, models

from management.migrations._resumable_schema import ensure_additive_schema


STATE_OPERATIONS = [
        migrations.CreateModel(
            name='IgCheckoutInvoiceGenerationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=180, unique=True)),
                ('kind', models.CharField(choices=[('created', 'Generation created'), ('provider_started', 'Provider request started'), ('provider_succeeded', 'Provider request succeeded'), ('provider_failed', 'Provider request failed'), ('provider_ambiguous', 'Provider request ambiguous'), ('terminalized', 'Generation terminalized'), ('winner_claimed', 'Winner claimed'), ('loser_paid_review', 'Paid loser needs review'), ('resource_review', 'Paid generation lacks resources')], db_index=True, max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['id'],
                'base_manager_name': 'objects',
            },
        ),
        migrations.AddField(
            model_name='igcheckoutproposal',
            name='assisted_checkout_v2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='igcheckoutproposal',
            name='custom_print_full_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='igcheckoutproposal',
            name='payment_policy',
            field=models.CharField(choices=[('legacy', 'Legacy checkout policy'), ('full_only', 'Only full payment'), ('full_or_200_cod', 'Full payment or 200 UAH + cash on delivery')], default='legacy', max_length=24),
        ),
        migrations.AddField(
            model_name='igcheckoutproposal',
            name='payment_policy_evidence_digest',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='igcheckoutproposal',
            name='payment_policy_evidence_kind',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='igcheckoutproposal',
            name='payment_policy_evidence_message',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='checkout_payment_policy_evidence', to='management.instagrambotmessage'),
        ),
        migrations.AddField(
            model_name='igcheckoutproposal',
            name='payment_policy_evidence_revision',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='IgCheckoutInvoiceGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.PositiveIntegerField()),
                ('series_key', models.CharField(max_length=64)),
                ('proposal_revision', models.PositiveIntegerField()),
                ('active_slot', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('winner_slot', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('state', models.CharField(choices=[('planned', 'Planned'), ('provider_inflight', 'Provider request in flight'), ('invoice_created', 'Invoice created'), ('provider_ambiguous', 'Provider result ambiguous'), ('ambiguity_review', 'Ambiguous call needs review'), ('late_provider_review', 'Late create result review'), ('failed', 'Generation failed'), ('expired', 'Generation expired'), ('cancelled', 'Generation cancelled'), ('winner_claimed', 'Verified winner claimed'), ('paid_winner', 'Winner order materialized'), ('late_paid_review', 'Paid losing generation review'), ('resource_review', 'Paid but resources need review')], db_index=True, default='planned', max_length=28)),
                ('payment_choice', models.CharField(choices=[('online_full', 'Full online payment'), ('prepay_200_cod', '200 UAH + COD')], default='online_full', max_length=24)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('policy_evidence_kind', models.CharField(blank=True, default='', max_length=32)),
                ('policy_evidence_digest', models.CharField(blank=True, default='', max_length=64)),
                ('promo_reservation_generation', models.CharField(blank=True, default='', max_length=64)),
                ('provider', models.CharField(default='monobank', max_length=24)),
                ('provider_invoice_id', models.CharField(blank=True, max_length=128, null=True)),
                ('provider_call_token', models.CharField(max_length=64, unique=True)),
                ('provider_request_digest', models.CharField(blank=True, default='', max_length=64)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('ambiguity_review_due_at', models.DateTimeField(blank=True, null=True)),
                ('ambiguity_resolved_at', models.DateTimeField(blank=True, null=True)),
                ('provider_started_at', models.DateTimeField(blank=True, null=True)),
                ('provider_completed_at', models.DateTimeField(blank=True, null=True)),
                ('winner_claimed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('terminal_at', models.DateTimeField(blank=True, null=True)),
                ('review_reason', models.CharField(blank=True, default='', max_length=96)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_attempt', models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instagram_checkout_generation', to='orders.paymentattempt')),
                ('policy_evidence_message', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='checkout_invoice_generation_policy_evidence', to='management.instagrambotmessage')),
                ('proposal', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_generations', to='management.igcheckoutproposal')),
            ],
            options={
                'ordering': ['proposal_id', 'generation'],
            },
        ),
        migrations.AddField(
            model_name='igcheckoutinventoryreservation',
            name='invoice_generation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventory_reservations', to='management.igcheckoutinvoicegeneration'),
        ),
        migrations.AddField(
            model_name='igcheckoutproposal',
            name='current_invoice_generation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_for_proposals', to='management.igcheckoutinvoicegeneration'),
        ),
        migrations.AddField(
            model_name='igcheckoutproposal',
            name='winner_invoice_generation',
            field=models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='winner_for_proposal', to='management.igcheckoutinvoicegeneration'),
        ),
        migrations.AddIndex(
            model_name='igcheckoutinventoryreservation',
            index=models.Index(fields=['invoice_generation', 'state', 'id'], name='ig_res_generation_state'),
        ),
        migrations.AddConstraint(
            model_name='igcheckoutproposal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assisted_checkout_v2', False), ('payment_policy', 'legacy')), models.Q(('assisted_checkout_v2', True), ('payment_policy__in', ['full_only', 'full_or_200_cod'])), _connector='OR'), name='ig_prop_v2_policy_shape'),
        ),
        migrations.AddConstraint(
            model_name='igcheckoutproposal',
            constraint=models.CheckConstraint(condition=models.Q(('custom_print_full_only', False), ('payment_policy', 'full_only'), _connector='OR'), name='ig_prop_custom_full_only'),
        ),
        migrations.AddField(
            model_name='igcheckoutinvoicegenerationevent',
            name='generation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='management.igcheckoutinvoicegeneration'),
        ),
        migrations.AddField(
            model_name='igcheckoutinvoicegenerationevent',
            name='payment_attempt',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instagram_checkout_generation_events', to='orders.paymentattempt'),
        ),
        migrations.AddField(
            model_name='igcheckoutinvoicegenerationevent',
            name='proposal',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoice_generation_events', to='management.igcheckoutproposal'),
        ),
        migrations.AddIndex(
            model_name='igcheckoutinvoicegeneration',
            index=models.Index(fields=['proposal', 'state', 'generation'], name='ig_invgen_prop_state_gen'),
        ),
        migrations.AddIndex(
            model_name='igcheckoutinvoicegeneration',
            index=models.Index(fields=['state', 'expires_at', 'id'], name='ig_invgen_state_expiry'),
        ),
        migrations.AddIndex(
            model_name='igcheckoutinvoicegeneration',
            index=models.Index(fields=['provider', 'provider_invoice_id'], name='ig_invgen_provider_invoice'),
        ),
        migrations.AddIndex(
            model_name='igcheckoutinvoicegeneration',
            index=models.Index(fields=['state', 'ambiguity_review_due_at', 'id'], name='ig_invgen_ambiguity_due'),
        ),
        migrations.AddConstraint(
            model_name='igcheckoutinvoicegeneration',
            constraint=models.UniqueConstraint(fields=('proposal', 'generation'), name='ig_invgen_proposal_generation_uniq'),
        ),
        migrations.AddConstraint(
            model_name='igcheckoutinvoicegeneration',
            constraint=models.UniqueConstraint(fields=('proposal', 'active_slot'), name='ig_invgen_active_slot_uniq'),
        ),
        migrations.AddConstraint(
            model_name='igcheckoutinvoicegeneration',
            constraint=models.UniqueConstraint(fields=('proposal', 'winner_slot'), name='ig_invgen_winner_slot_uniq'),
        ),
        migrations.AddConstraint(
            model_name='igcheckoutinvoicegeneration',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_invoice_id'), name='ig_invgen_provider_invoice_uniq'),
        ),
        migrations.AddConstraint(
            model_name='igcheckoutinvoicegeneration',
            constraint=models.CheckConstraint(condition=models.Q(('generation__gte', 1)), name='ig_invgen_generation_positive'),
        ),
        migrations.AddConstraint(
            model_name='igcheckoutinvoicegeneration',
            constraint=models.CheckConstraint(condition=models.Q(('active_slot__isnull', True), ('active_slot', 1), _connector='OR'), name='ig_invgen_active_slot_shape'),
        ),
        migrations.AddConstraint(
            model_name='igcheckoutinvoicegeneration',
            constraint=models.CheckConstraint(condition=models.Q(('winner_slot__isnull', True), ('winner_slot', 1), _connector='OR'), name='ig_invgen_winner_slot_shape'),
        ),
        migrations.AddConstraint(
            model_name='igcheckoutinvoicegeneration',
            constraint=models.CheckConstraint(condition=models.Q(('payment_amount__gt', 0)), name='ig_invgen_payment_positive'),
        ),
        migrations.AddIndex(
            model_name='igcheckoutinvoicegenerationevent',
            index=models.Index(fields=['generation', 'kind', 'id'], name='ig_invgevt_generation_kind'),
        ),
        migrations.AddIndex(
            model_name='igcheckoutinvoicegenerationevent',
            index=models.Index(fields=['proposal', 'kind', 'id'], name='ig_invgevt_proposal_kind'),
        ),
    ]


GENERATION_TABLE = "management_igcheckoutinvoicegeneration"
EVENT_TABLE = "management_igcheckoutinvoicegenerationevent"
PROPOSAL_TABLE = "management_igcheckoutproposal"
RESERVATION_TABLE = "management_igcheckoutinventoryreservation"

GENERATION_FIELDS = (
    "id", "generation", "series_key", "proposal_revision", "active_slot",
    "winner_slot", "state", "payment_choice", "payment_amount",
    "policy_evidence_kind", "policy_evidence_digest",
    "promo_reservation_generation", "provider", "provider_invoice_id",
    "provider_call_token", "provider_request_digest", "expires_at",
    "ambiguity_review_due_at", "ambiguity_resolved_at",
    "provider_started_at", "provider_completed_at", "winner_claimed_at",
    "paid_at", "terminal_at", "review_reason", "created_at", "updated_at",
    "payment_attempt", "policy_evidence_message", "proposal",
)
EVENT_FIELDS = (
    "id", "event_key", "kind", "payload", "created_at", "generation",
    "payment_attempt", "proposal",
)
PROPOSAL_FIELDS = (
    "assisted_checkout_v2", "custom_print_full_only", "payment_policy",
    "payment_policy_evidence_digest", "payment_policy_evidence_kind",
    "payment_policy_evidence_message", "payment_policy_evidence_revision",
    "current_invoice_generation", "winner_invoice_generation",
)
RESERVATION_FIELDS = ("invoice_generation",)

FIELD_SPECS = tuple(
    ("management", "IgCheckoutInvoiceGeneration", field)
    for field in GENERATION_FIELDS
) + tuple(
    ("management", "IgCheckoutInvoiceGenerationEvent", field)
    for field in EVENT_FIELDS
) + tuple(
    ("management", "IgCheckoutProposal", field)
    for field in PROPOSAL_FIELDS
) + tuple(
    ("management", "IgCheckoutInventoryReservation", field)
    for field in RESERVATION_FIELDS
)

INDEX_SPECS = (
    ("management", "IgCheckoutInvoiceGeneration", "ig_invgen_prop_state_gen"),
    ("management", "IgCheckoutInvoiceGeneration", "ig_invgen_state_expiry"),
    ("management", "IgCheckoutInvoiceGeneration", "ig_invgen_provider_invoice"),
    ("management", "IgCheckoutInvoiceGeneration", "ig_invgen_ambiguity_due"),
    ("management", "IgCheckoutInvoiceGenerationEvent", "ig_invgevt_generation_kind"),
    ("management", "IgCheckoutInvoiceGenerationEvent", "ig_invgevt_proposal_kind"),
    ("management", "IgCheckoutInventoryReservation", "ig_res_generation_state"),
)

CHECK_SPECS = (
    ("management", "IgCheckoutInvoiceGeneration", "ig_invgen_generation_positive"),
    ("management", "IgCheckoutInvoiceGeneration", "ig_invgen_active_slot_shape"),
    ("management", "IgCheckoutInvoiceGeneration", "ig_invgen_winner_slot_shape"),
    ("management", "IgCheckoutInvoiceGeneration", "ig_invgen_payment_positive"),
    ("management", "IgCheckoutProposal", "ig_prop_v2_policy_shape"),
    ("management", "IgCheckoutProposal", "ig_prop_custom_full_only"),
)

CHECK_COLUMNS = {
    "ig_invgen_generation_positive": {"generation"},
    "ig_invgen_active_slot_shape": {"active_slot"},
    "ig_invgen_winner_slot_shape": {"winner_slot"},
    "ig_invgen_payment_positive": {"payment_amount"},
    "ig_prop_v2_policy_shape": {"assisted_checkout_v2", "payment_policy"},
    "ig_prop_custom_full_only": {"custom_print_full_only", "payment_policy"},
}

CHECK_TRUTH_TABLES = {
    "ig_invgen_generation_positive": (
        ({"generation": 0}, False),
        ({"generation": 1}, True),
        ({"generation": 2}, True),
    ),
    "ig_invgen_active_slot_shape": (
        ({"active_slot": None}, True),
        ({"active_slot": 1}, True),
        ({"active_slot": 0}, False),
        ({"active_slot": 2}, False),
    ),
    "ig_invgen_winner_slot_shape": (
        ({"winner_slot": None}, True),
        ({"winner_slot": 1}, True),
        ({"winner_slot": 0}, False),
        ({"winner_slot": 2}, False),
    ),
    "ig_invgen_payment_positive": (
        ({"payment_amount": 0}, False),
        ({"payment_amount": 0.01}, True),
        ({"payment_amount": 900}, True),
    ),
    "ig_prop_v2_policy_shape": tuple(
        (
            {
                "assisted_checkout_v2": enabled,
                "payment_policy": policy,
            },
            (not enabled and policy == "legacy")
            or (enabled and policy in {"full_only", "full_or_200_cod"}),
        )
        for enabled in (False, True)
        for policy in ("legacy", "full_only", "full_or_200_cod")
    ),
    "ig_prop_custom_full_only": tuple(
        (
            {
                "custom_print_full_only": custom,
                "payment_policy": policy,
            },
            (not custom) or policy == "full_only",
        )
        for custom in (False, True)
        for policy in ("legacy", "full_only", "full_or_200_cod")
    ),
}

UNIQUE_SPECS = (
    (
        "management", "IgCheckoutInvoiceGeneration",
        "ig_invgen_proposal_generation_uniq", ("proposal", "generation"),
    ),
    (
        "management", "IgCheckoutInvoiceGeneration",
        "ig_invgen_active_slot_uniq", ("proposal", "active_slot"),
    ),
    (
        "management", "IgCheckoutInvoiceGeneration",
        "ig_invgen_winner_slot_uniq", ("proposal", "winner_slot"),
    ),
    (
        "management", "IgCheckoutInvoiceGeneration",
        "ig_invgen_provider_invoice_uniq", ("provider", "provider_invoice_id"),
    ),
    (
        "management", "IgCheckoutInvoiceGeneration",
        "ig_invgen_call_token_uniq", ("provider_call_token",),
    ),
    (
        "management", "IgCheckoutInvoiceGeneration",
        "ig_invgen_attempt_uniq", ("payment_attempt",),
    ),
    (
        "management", "IgCheckoutInvoiceGenerationEvent",
        "ig_invgevt_event_key_uniq", ("event_key",),
    ),
    (
        "management", "IgCheckoutProposal",
        "ig_prop_winner_generation_uniq", ("winner_invoice_generation",),
    ),
)


def _ensure_innodb(schema_editor, table_name):
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT ENGINE FROM information_schema.TABLES "
            "WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=%s",
            [table_name],
        )
        row = cursor.fetchone()
    if not row:
        raise RuntimeError(f"required checkout V2 table missing: {table_name}")
    if str(row[0] or "").upper() != "INNODB":
        schema_editor.execute(
            f"ALTER TABLE {schema_editor.quote_name(table_name)} ENGINE=InnoDB"
        )


def _flush_deferred_sql(schema_editor):
    deferred = list(schema_editor.deferred_sql)
    schema_editor.deferred_sql.clear()
    for statement in deferred:
        schema_editor.execute(statement)


def _constraints(schema_editor, table_name):
    with schema_editor.connection.cursor() as cursor:
        return schema_editor.connection.introspection.get_constraints(
            cursor,
            table_name,
        )


def _sqlite_check_clause(schema_editor, table_name, check_name):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT sql FROM sqlite_master WHERE type='table' AND name=%s",
            [table_name],
        )
        row = cursor.fetchone()
    create_sql = str(row[0] if row else "")
    match = re.search(
        rf"CONSTRAINT\s+['\"`]?{re.escape(check_name)}['\"`]?\s+CHECK\s*\(",
        create_sql,
        re.IGNORECASE,
    )
    if match is None:
        return ""
    start = match.end() - 1
    depth = 0
    quote = ""
    for index in range(start, len(create_sql)):
        character = create_sql[index]
        if quote:
            if character == quote:
                quote = ""
            continue
        if character in {"'", '"'}:
            quote = character
        elif character == "(":
            depth += 1
        elif character == ")":
            depth -= 1
            if depth == 0:
                return create_sql[start + 1:index]
    return ""


def _physical_check_clause(schema_editor, table_name, check_name):
    if schema_editor.connection.vendor == "mysql":
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "SELECT cc.CHECK_CLAUSE FROM information_schema.CHECK_CONSTRAINTS cc "
                "JOIN information_schema.TABLE_CONSTRAINTS tc ON "
                "tc.CONSTRAINT_SCHEMA=cc.CONSTRAINT_SCHEMA AND "
                "tc.CONSTRAINT_NAME=cc.CONSTRAINT_NAME "
                "WHERE tc.TABLE_SCHEMA=DATABASE() AND tc.TABLE_NAME=%s "
                "AND tc.CONSTRAINT_NAME=%s AND tc.CONSTRAINT_TYPE='CHECK'",
                [table_name, check_name],
            )
            rows = cursor.fetchall()
        return str(rows[0][0] or "") if len(rows) == 1 else ""
    if schema_editor.connection.vendor == "sqlite":
        return _sqlite_check_clause(schema_editor, table_name, check_name)
    raise RuntimeError("checkout S2b CHECK validation supports MariaDB/SQLite")


def _validate_check_predicate(schema_editor, table_name, check_name):
    clause = _physical_check_clause(schema_editor, table_name, check_name)
    if not clause:
        raise RuntimeError(f"{check_name} physical predicate is missing")
    quote = schema_editor.quote_name
    for values, expected in CHECK_TRUTH_TABLES[check_name]:
        columns = list(values)
        numeric_columns = {
            "generation", "active_slot", "winner_slot", "payment_amount",
            "assisted_checkout_v2", "custom_print_full_only",
        }
        numeric_type = (
            "DECIMAL(20,4)"
            if schema_editor.connection.vendor == "mysql"
            else "NUMERIC"
        )
        select_columns = ", ".join(
            (
                f"CAST(%s AS {numeric_type}) AS {quote(column)}"
                if column in numeric_columns
                else f"%s AS {quote(column)}"
            )
            for column in columns
        )
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                f"SELECT CASE WHEN ({clause}) THEN 1 ELSE 0 END "
                f"FROM (SELECT {select_columns}) candidate",
                [values[column] for column in columns],
            )
            actual = bool(cursor.fetchone()[0])
        if actual != expected:
            raise RuntimeError(
                f"{check_name} has incompatible predicate for {values!r}: {clause}"
            )


def _ensure_unique_shape(apps, schema_editor, spec):
    app_label, model_name, name, field_names = spec
    model = apps.get_model(app_label, model_name)
    expected = tuple(
        model._meta.get_field(field_name).column for field_name in field_names
    )
    existing = _constraints(schema_editor, model._meta.db_table)
    named = existing.get(name)
    if named is not None:
        if not named.get("unique") or tuple(named.get("columns") or ()) != expected:
            raise RuntimeError(f"{name} has incompatible unique shape")
        return
    equivalent = next(
        (
            row for row in existing.values()
            if row.get("unique")
            and tuple(row.get("columns") or ()) == expected
        ),
        None,
    )
    if equivalent is not None:
        return
    schema_editor.add_constraint(
        model,
        models.UniqueConstraint(fields=field_names, name=name),
    )


def _validate_named_shapes(apps, schema_editor):
    for app_label, model_name, index_name in INDEX_SPECS:
        model = apps.get_model(app_label, model_name)
        actual = _constraints(schema_editor, model._meta.db_table).get(index_name)
        index = next(row for row in model._meta.indexes if row.name == index_name)
        expected = tuple(
            model._meta.get_field(field.lstrip("-")).column
            for field in index.fields
        )
        if (
            actual is None
            or tuple(actual.get("columns") or ()) != expected
            or actual.get("unique")
            or actual.get("check")
            or actual.get("foreign_key")
        ):
            raise RuntimeError(
                f"{index_name} has incompatible index shape: "
                f"actual={actual!r}, expected={expected!r}"
            )
    for app_label, model_name, check_name in CHECK_SPECS:
        model = apps.get_model(app_label, model_name)
        actual = _constraints(schema_editor, model._meta.db_table).get(check_name)
        actual_columns = set((actual or {}).get("columns") or ())
        if (
            actual is None
            or not actual.get("check")
            or (actual_columns and actual_columns != CHECK_COLUMNS[check_name])
        ):
            raise RuntimeError(f"{check_name} is missing or is not a check")
        _validate_check_predicate(
            schema_editor,
            model._meta.db_table,
            check_name,
        )
    for spec in UNIQUE_SPECS:
        app_label, model_name, name, field_names = spec
        model = apps.get_model(app_label, model_name)
        expected = tuple(
            model._meta.get_field(field_name).column for field_name in field_names
        )
        actual = _constraints(schema_editor, model._meta.db_table).get(name)
        if actual is not None and (
            not actual.get("unique")
            or tuple(actual.get("columns") or ()) != expected
        ):
            raise RuntimeError(f"{name} has incompatible unique shape")
        if actual is None and not any(
            row.get("unique")
            and tuple(row.get("columns") or ()) == expected
            for row in _constraints(schema_editor, model._meta.db_table).values()
        ):
            raise RuntimeError(f"{name} unique shape is missing")


def ensure_checkout_generation_schema(apps, schema_editor):
    tables = set(schema_editor.connection.introspection.table_names())
    generation_model = apps.get_model(
        "management", "IgCheckoutInvoiceGeneration"
    )
    event_model = apps.get_model(
        "management", "IgCheckoutInvoiceGenerationEvent"
    )
    generation_existed = GENERATION_TABLE in tables
    event_existed = EVENT_TABLE in tables
    if not generation_existed:
        schema_editor.create_model(generation_model)
        _flush_deferred_sql(schema_editor)
    _ensure_innodb(schema_editor, GENERATION_TABLE)
    if not event_existed:
        schema_editor.create_model(event_model)
        _flush_deferred_sql(schema_editor)
    _ensure_innodb(schema_editor, EVENT_TABLE)

    existing_models = {
        "IgCheckoutProposal",
        "IgCheckoutInventoryReservation",
    }
    if generation_existed:
        existing_models.add("IgCheckoutInvoiceGeneration")
    if event_existed:
        existing_models.add("IgCheckoutInvoiceGenerationEvent")
    ensure_additive_schema(
        apps,
        schema_editor,
        field_specs=tuple(
            spec for spec in FIELD_SPECS if spec[1] in existing_models
        ),
        index_specs=tuple(
            spec for spec in INDEX_SPECS if spec[1] in existing_models
        ),
        constraint_specs=tuple(
            spec for spec in CHECK_SPECS if spec[1] in existing_models
        ),
    )
    for spec in UNIQUE_SPECS:
        model = apps.get_model(spec[0], spec[1])
        if model._meta.db_table in set(
            schema_editor.connection.introspection.table_names()
        ):
            _ensure_unique_shape(apps, schema_editor, spec)

    # Existing proposals are deliberately not promoted or re-expired. This is
    # an idempotent validation-only backfill boundary: legacy TTL/status and
    # active pointers remain byte-for-byte owned by Slice 1.
    proposal_model = apps.get_model("management", "IgCheckoutProposal")
    invalid_legacy = proposal_model.objects.filter(
        assisted_checkout_v2=False,
    ).exclude(
        payment_policy="legacy",
        current_invoice_generation__isnull=True,
        winner_invoice_generation__isnull=True,
    ).exists()
    if invalid_legacy:
        raise RuntimeError("legacy checkout proposal has unexpected V2 state")
    _validate_named_shapes(apps, schema_editor)


def create_generation_event_triggers(apps, schema_editor):
    del apps
    update_name = "ig_invgevt_no_update"
    delete_name = "ig_invgevt_no_delete"
    if schema_editor.connection.vendor == "mysql":
        schema_editor.execute(f"DROP TRIGGER IF EXISTS {update_name}")
        schema_editor.execute(f"DROP TRIGGER IF EXISTS {delete_name}")
        schema_editor.execute(
            f"CREATE TRIGGER {update_name} BEFORE UPDATE ON {EVENT_TABLE} "
            "FOR EACH ROW SIGNAL SQLSTATE '45000' "
            "SET MESSAGE_TEXT='IgCheckoutInvoiceGenerationEvent is append-only'"
        )
        schema_editor.execute(
            f"CREATE TRIGGER {delete_name} BEFORE DELETE ON {EVENT_TABLE} "
            "FOR EACH ROW SIGNAL SQLSTATE '45000' "
            "SET MESSAGE_TEXT='IgCheckoutInvoiceGenerationEvent is append-only'"
        )
    elif schema_editor.connection.vendor == "sqlite":
        schema_editor.execute(f"DROP TRIGGER IF EXISTS {update_name}")
        schema_editor.execute(f"DROP TRIGGER IF EXISTS {delete_name}")
        schema_editor.execute(
            f"CREATE TRIGGER {update_name} BEFORE UPDATE ON {EVENT_TABLE} "
            "BEGIN SELECT RAISE(ABORT, "
            "'IgCheckoutInvoiceGenerationEvent is append-only'); END"
        )
        schema_editor.execute(
            f"CREATE TRIGGER {delete_name} BEFORE DELETE ON {EVENT_TABLE} "
            "BEGIN SELECT RAISE(ABORT, "
            "'IgCheckoutInvoiceGenerationEvent is append-only'); END"
        )


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("management", "0183_analysis_v2_result_proposals"),
        ("orders", "0058_paymentattempt_checkout_series"),
    ]
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=STATE_OPERATIONS,
        ),
        migrations.RunPython(ensure_checkout_generation_schema),
        migrations.RunPython(create_generation_event_triggers),
    ]
