# Generated by Django 6.1 on 2026-08-31 04:03

import django.db.models.deletion
import hashlib
import importlib
import re
from decimal import Decimal
from django.db import migrations, models

from management.migrations._resumable_schema import ensure_additive_schema

STATE_OPERATIONS = [
        migrations.AddField(
            model_name='igconversationanalysisresult',
            name='language_evidence_message_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='instagrambotsettings',
            name='typed_memory_reconcile_cursor',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='IgMemoryFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_key', models.CharField(max_length=80)),
                ('slot_key', models.CharField(max_length=80)),
                ('scope', models.CharField(choices=[('client', 'Client'), ('episode', 'Episode'), ('line', 'Line'), ('order', 'Order'), ('case', 'Case')], max_length=16)),
                ('line_id', models.CharField(blank=True, default='', max_length=96)),
                ('fact_key', models.CharField(choices=[('observed_language', 'Observed language'), ('objection_observed', 'Observed objection'), ('deferred_intent', 'Deferred intent')], max_length=32)),
                ('schema_version', models.CharField(default='typed-memory.v1', max_length=32)),
                ('operation', models.CharField(choices=[('assert', 'Assert'), ('invalidate', 'Invalidate'), ('expire', 'Expire')], max_length=16)),
                ('typed_value', models.JSONField(blank=True, default=dict)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('source_role', models.CharField(max_length=16)),
                ('producer', models.CharField(max_length=32)),
                ('producer_policy_version', models.CharField(default='typed-memory-projector.v1', max_length=32)),
                ('closure_method', models.CharField(max_length=32)),
                ('source_result_digest', models.CharField(blank=True, default='', max_length=64)),
                ('source_materiality_digest', models.CharField(blank=True, default='', max_length=64)),
                ('source_state_correlation', models.CharField(blank=True, default='', max_length=64)),
                ('source_watermark_message_id', models.PositiveBigIntegerField(default=0)),
                ('source_event_digest', models.CharField(blank=True, default='', max_length=64)),
                ('expected_evidence_count', models.PositiveSmallIntegerField(default=0)),
                ('reason_code', models.CharField(blank=True, default='', max_length=48)),
                ('integrity_hmac', models.CharField(max_length=64)),
                ('integrity_key_id', models.CharField(max_length=32)),
                ('observed_at', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('sensitivity', models.CharField(max_length=24)),
                ('retention_class', models.CharField(max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='memory_facts', to='management.igclient')),
                ('commercial_episode', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='memory_facts', to='management.igcommercialepisode')),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instagram_memory_facts', to='orders.order')),
                ('post_sale_case', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='memory_facts', to='management.igpostsalecase')),
                ('source_result', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='memory_facts', to='management.igconversationanalysisresult')),
                ('supersedes', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='superseding_facts', to='management.igmemoryfact')),
            ],
            options={
                'ordering': ['id'],
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='IgMemoryFactEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveSmallIntegerField()),
                ('message_id', models.PositiveBigIntegerField()),
                ('source_role', models.CharField(max_length=16)),
                ('claim_code', models.CharField(max_length=32)),
                ('evidence_hmac', models.CharField(max_length=64)),
                ('integrity_key_id', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fact', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='evidence_rows', to='management.igmemoryfact')),
            ],
            options={
                'ordering': ['ordinal', 'id'],
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='IgMemoryHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_key', models.CharField(max_length=80)),
                ('scope', models.CharField(choices=[('client', 'Client'), ('episode', 'Episode'), ('line', 'Line'), ('order', 'Order'), ('case', 'Case')], max_length=16)),
                ('line_id', models.CharField(blank=True, default='', max_length=96)),
                ('fact_key', models.CharField(choices=[('observed_language', 'Observed language'), ('objection_observed', 'Observed objection'), ('deferred_intent', 'Deferred intent')], max_length=32)),
                ('schema_version', models.CharField(default='typed-memory.v1', max_length=32)),
                ('state', models.CharField(choices=[('active', 'Active'), ('invalidated', 'Invalidated'), ('expired', 'Expired')], max_length=16)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('projection_policy_version', models.CharField(default='typed-memory-projector.v1', max_length=32)),
                ('projection_hmac', models.CharField(max_length=64)),
                ('integrity_key_id', models.CharField(max_length=32)),
                ('projected_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='memory_heads', to='management.igclient')),
                ('commercial_episode', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='memory_heads', to='management.igcommercialepisode')),
                ('current_fact', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_for_heads', to='management.igmemoryfact')),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='instagram_memory_heads', to='orders.order')),
                ('post_sale_case', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='memory_heads', to='management.igpostsalecase')),
            ],
            options={
                'ordering': ['slot_key'],
                'base_manager_name': 'objects',
            },
        ),
        migrations.AddIndex(
            model_name='igmemoryfact',
            index=models.Index(fields=['client', '-observed_at'], name='ig_memfact_client_obs'),
        ),
        migrations.AddIndex(
            model_name='igmemoryfact',
            index=models.Index(fields=['slot_key', '-id'], name='ig_memfact_slot_id'),
        ),
        migrations.AddIndex(
            model_name='igmemoryfact',
            index=models.Index(fields=['source_result', 'fact_key'], name='ig_memfact_result_key'),
        ),
        migrations.AddIndex(
            model_name='igmemoryfact',
            index=models.Index(fields=['valid_until', 'id'], name='ig_memfact_valid_until'),
        ),
        migrations.AddConstraint(
            model_name='igmemoryfact',
            constraint=models.UniqueConstraint(fields=('record_key',), name='ig_memfact_record_uniq'),
        ),
        migrations.AddConstraint(
            model_name='igmemoryfact',
            constraint=models.UniqueConstraint(fields=('supersedes',), name='ig_memfact_supersedes_uniq'),
        ),
        migrations.AddConstraint(
            model_name='igmemoryfact',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__isnull', True), models.Q(('confidence__gte', Decimal('0')), ('confidence__lte', Decimal('1'))), _connector='OR'), name='ig_memfact_conf_range'),
        ),
        migrations.AddConstraint(
            model_name='igmemoryfact',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gt', models.F('observed_at')), _connector='OR'), name='ig_memfact_expiry_order'),
        ),
        migrations.AddConstraint(
            model_name='igmemoryfact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('commercial_episode__isnull', True), ('line_id', ''), ('order__isnull', True), ('post_sale_case__isnull', True), ('scope', 'client')), models.Q(('commercial_episode__isnull', False), ('line_id', ''), ('order__isnull', True), ('post_sale_case__isnull', True), ('scope', 'episode')), models.Q(('commercial_episode__isnull', False), ('order__isnull', True), ('post_sale_case__isnull', True), ('scope', 'line'), models.Q(('line_id', ''), _negated=True)), models.Q(('commercial_episode__isnull', True), ('line_id', ''), ('order__isnull', False), ('post_sale_case__isnull', True), ('scope', 'order')), models.Q(('commercial_episode__isnull', True), ('line_id', ''), ('order__isnull', True), ('post_sale_case__isnull', False), ('scope', 'case')), _connector='OR'), name='ig_memfact_scope_shape'),
        ),
        migrations.AddConstraint(
            model_name='igmemoryfact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closure_method', 'analysis_assertion'), ('expected_evidence_count__gte', 1), ('expected_evidence_count__lte', 40), ('operation', 'assert'), ('producer', 'analysis_v2'), ('producer_policy_version', 'typed-memory-projector.v1'), ('reason_code', ''), ('source_event_digest', ''), ('source_result__isnull', False), ('source_role', 'user')), models.Q(('closure_method', 'deterministic_invalidation'), ('expected_evidence_count', 0), ('operation', 'invalidate'), ('producer', 'deterministic_projector'), ('producer_policy_version', 'typed-memory-projector.v1'), ('reason_code__in', ('episode_closed', 'explicit_retraction', 'line_replaced', 'reset_boundary', 'superseded_by_new_assertion')), ('source_materiality_digest', ''), ('source_result__isnull', True), ('source_result_digest', ''), ('source_role__in', ('system', 'authority')), ('source_state_correlation', ''), ('source_watermark_message_id', 0)), models.Q(('closure_method', 'ttl_expiry'), ('expected_evidence_count', 0), ('operation', 'expire'), ('producer', 'deterministic_projector'), ('producer_policy_version', 'typed-memory-projector.v1'), ('reason_code', 'valid_until_elapsed'), ('source_materiality_digest', ''), ('source_result__isnull', True), ('source_result_digest', ''), ('source_role__in', ('system', 'authority')), ('source_state_correlation', ''), ('source_watermark_message_id', 0)), _connector='OR'), name='ig_memfact_source_shape'),
        ),
        migrations.AddConstraint(
            model_name='igmemoryfactevidence',
            constraint=models.UniqueConstraint(fields=('fact', 'ordinal'), name='ig_memev_fact_ord_uniq'),
        ),
        migrations.AddIndex(
            model_name='igmemoryfactevidence',
            index=models.Index(fields=['message_id', 'id'], name='ig_memev_message_id'),
        ),
        migrations.AddConstraint(
            model_name='igmemoryfactevidence',
            constraint=models.UniqueConstraint(fields=('fact', 'message_id', 'claim_code'), name='ig_memev_fact_msg_claim_uniq'),
        ),
        migrations.AddConstraint(
            model_name='igmemoryfactevidence',
            constraint=models.CheckConstraint(condition=models.Q(('ordinal__gte', 1)), name='ig_memev_ordinal_positive'),
        ),
        migrations.AddConstraint(
            model_name='igmemoryfactevidence',
            constraint=models.CheckConstraint(condition=models.Q(('message_id__gte', 1)), name='ig_memev_message_positive'),
        ),
        migrations.AddIndex(
            model_name='igmemoryhead',
            index=models.Index(fields=['client', 'scope', 'fact_key'], name='ig_memhead_client_scope'),
        ),
        migrations.AddIndex(
            model_name='igmemoryhead',
            index=models.Index(fields=['commercial_episode', 'line_id', 'fact_key'], name='ig_memhead_episode_line'),
        ),
        migrations.AddIndex(
            model_name='igmemoryhead',
            index=models.Index(fields=['state', '-updated_at'], name='ig_memhead_state_updated'),
        ),
        migrations.AddConstraint(
            model_name='igmemoryhead',
            constraint=models.UniqueConstraint(fields=('slot_key',), name='ig_memhead_slot_uniq'),
        ),
        migrations.AddConstraint(
            model_name='igmemoryhead',
            constraint=models.UniqueConstraint(fields=('current_fact',), name='ig_memhead_fact_uniq'),
        ),
        migrations.AddConstraint(
            model_name='igmemoryhead',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='ig_memhead_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='igmemoryhead',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('commercial_episode__isnull', True), ('line_id', ''), ('order__isnull', True), ('post_sale_case__isnull', True), ('scope', 'client')), models.Q(('commercial_episode__isnull', False), ('line_id', ''), ('order__isnull', True), ('post_sale_case__isnull', True), ('scope', 'episode')), models.Q(('commercial_episode__isnull', False), ('order__isnull', True), ('post_sale_case__isnull', True), ('scope', 'line'), models.Q(('line_id', ''), _negated=True)), models.Q(('commercial_episode__isnull', True), ('line_id', ''), ('order__isnull', False), ('post_sale_case__isnull', True), ('scope', 'order')), models.Q(('commercial_episode__isnull', True), ('line_id', ''), ('order__isnull', True), ('post_sale_case__isnull', False), ('scope', 'case')), _connector='OR'), name='ig_memhead_scope_shape'),
        ),
]


FACT_TABLE = "management_igmemoryfact"
EVIDENCE_TABLE = "management_igmemoryfactevidence"
HEAD_TABLE = "management_igmemoryhead"
CLIENT_TABLE = "management_igclient"
RESULT_TABLE = "management_igconversationanalysisresult"
PROPOSAL_TABLE = "management_iganalysisproposal"
MATERIALITY_TABLE = "management_iganalysismaterialityevent"
ANALYSIS_EVENT_TABLE = "management_igconversationanalysisevent"

FACT_FIELDS = (
    "id", "record_key", "slot_key", "client", "scope",
    "commercial_episode", "line_id", "order", "post_sale_case",
    "fact_key", "schema_version", "operation", "typed_value", "confidence",
    "source_role", "producer", "producer_policy_version", "closure_method",
    "source_result", "source_result_digest",
    "source_materiality_digest", "source_state_correlation",
    "source_watermark_message_id", "source_event_digest",
    "expected_evidence_count", "supersedes", "reason_code",
    "integrity_hmac", "integrity_key_id", "observed_at", "valid_until",
    "sensitivity", "retention_class", "created_at",
)
EVIDENCE_FIELDS = (
    "id", "fact", "ordinal", "message_id", "source_role", "claim_code",
    "evidence_hmac", "integrity_key_id", "created_at",
)
HEAD_FIELDS = (
    "id", "slot_key", "client", "scope", "commercial_episode", "line_id",
    "order", "post_sale_case", "fact_key", "schema_version", "current_fact",
    "state", "revision", "projection_policy_version", "projection_hmac",
    "integrity_key_id", "projected_at", "created_at", "updated_at",
)
FIELD_SPECS = tuple(
    ("management", "IgMemoryFact", field) for field in FACT_FIELDS
) + tuple(
    ("management", "IgMemoryFactEvidence", field) for field in EVIDENCE_FIELDS
) + tuple(
    ("management", "IgMemoryHead", field) for field in HEAD_FIELDS
) + (
    ("management", "InstagramBotSettings", "typed_memory_reconcile_cursor"),
    ("management", "IgConversationAnalysisResult", "language_evidence_message_ids"),
)
INDEX_SPECS = (
    ("management", "IgMemoryFact", "ig_memfact_client_obs"),
    ("management", "IgMemoryFact", "ig_memfact_slot_id"),
    ("management", "IgMemoryFact", "ig_memfact_result_key"),
    ("management", "IgMemoryFact", "ig_memfact_valid_until"),
    ("management", "IgMemoryFactEvidence", "ig_memev_message_id"),
    ("management", "IgMemoryHead", "ig_memhead_client_scope"),
    ("management", "IgMemoryHead", "ig_memhead_episode_line"),
    ("management", "IgMemoryHead", "ig_memhead_state_updated"),
)
CHECK_SPECS = (
    ("management", "IgMemoryFact", "ig_memfact_conf_range"),
    ("management", "IgMemoryFact", "ig_memfact_expiry_order"),
    ("management", "IgMemoryFact", "ig_memfact_scope_shape"),
    ("management", "IgMemoryFact", "ig_memfact_source_shape"),
    ("management", "IgMemoryFactEvidence", "ig_memev_ordinal_positive"),
    ("management", "IgMemoryFactEvidence", "ig_memev_message_positive"),
    ("management", "IgMemoryHead", "ig_memhead_revision_positive"),
    ("management", "IgMemoryHead", "ig_memhead_scope_shape"),
)
UNIQUE_SPECS = (
    ("management", "IgMemoryFact", "ig_memfact_record_uniq", ("record_key",)),
    ("management", "IgMemoryFact", "ig_memfact_supersedes_uniq", ("supersedes",)),
    ("management", "IgMemoryFactEvidence", "ig_memev_fact_ord_uniq", ("fact", "ordinal")),
    (
        "management", "IgMemoryFactEvidence", "ig_memev_fact_msg_claim_uniq",
        ("fact", "message_id", "claim_code"),
    ),
    ("management", "IgMemoryHead", "ig_memhead_slot_uniq", ("slot_key",)),
    ("management", "IgMemoryHead", "ig_memhead_fact_uniq", ("current_fact",)),
)
CHECK_COLUMNS = {
    "ig_memfact_conf_range": {"confidence"},
    "ig_memfact_expiry_order": {"valid_until", "observed_at"},
    "ig_memfact_scope_shape": {
        "scope", "commercial_episode_id", "line_id", "order_id",
        "post_sale_case_id",
    },
    "ig_memfact_source_shape": {
        "operation", "producer", "producer_policy_version", "closure_method",
        "source_role", "source_result_id", "source_result_digest",
        "source_materiality_digest", "source_state_correlation",
        "source_watermark_message_id",
        "source_event_digest", "reason_code", "expected_evidence_count",
    },
    "ig_memev_ordinal_positive": {"ordinal"},
    "ig_memev_message_positive": {"message_id"},
    "ig_memhead_revision_positive": {"revision"},
    "ig_memhead_scope_shape": {
        "scope", "commercial_episode_id", "line_id", "order_id",
        "post_sale_case_id",
    },
}
CHECK_FRAGMENTS = {
    "ig_memfact_conf_range": ("confidenceisnull", "confidence>=0", "confidence<=1"),
    "ig_memfact_expiry_order": ("valid_untilisnull", "valid_until>observed_at"),
    "ig_memfact_scope_shape": (
        "scope='client'", "scope='episode'", "scope='line'",
        "scope='order'", "scope='case'", "commercial_episode_id",
        "post_sale_case_id",
    ),
    "ig_memfact_source_shape": (
        "operation='assert'", "producer='analysis_v2'",
        "producer_policy_version='typed-memory-projector.v1'",
        "closure_method='analysis_assertion'", "source_role='user'",
        "expected_evidence_count<=40",
        "operation='invalidate'", "closure_method='deterministic_invalidation'",
        "operation='expire'", "closure_method='ttl_expiry'",
    ),
    "ig_memev_ordinal_positive": ("ordinal>=1",),
    "ig_memev_message_positive": ("message_id>=1",),
    "ig_memhead_revision_positive": ("revision>=1",),
    "ig_memhead_scope_shape": (
        "scope='client'", "scope='episode'", "scope='line'",
        "scope='order'", "scope='case'", "commercial_episode_id",
        "post_sale_case_id",
    ),
}
_SCOPE_CASES = (
    ({"scope": "client", "commercial_episode_id": None, "line_id": "", "order_id": None, "post_sale_case_id": None}, True),
    ({"scope": "episode", "commercial_episode_id": 1, "line_id": "", "order_id": None, "post_sale_case_id": None}, True),
    ({"scope": "line", "commercial_episode_id": 1, "line_id": "line:1", "order_id": None, "post_sale_case_id": None}, True),
    ({"scope": "order", "commercial_episode_id": None, "line_id": "", "order_id": 1, "post_sale_case_id": None}, True),
    ({"scope": "case", "commercial_episode_id": None, "line_id": "", "order_id": None, "post_sale_case_id": 1}, True),
    ({"scope": "client", "commercial_episode_id": 1, "line_id": "", "order_id": None, "post_sale_case_id": None}, False),
    ({"scope": "line", "commercial_episode_id": 1, "line_id": "", "order_id": None, "post_sale_case_id": None}, False),
    ({"scope": "order", "commercial_episode_id": None, "line_id": "", "order_id": 1, "post_sale_case_id": 1}, False),
    ({"scope": "unknown", "commercial_episode_id": None, "line_id": "", "order_id": None, "post_sale_case_id": None}, False),
)
CHECK_TRUTH_TABLES = {
    "ig_memfact_conf_range": (
        ({"confidence": None}, True), ({"confidence": -0.1}, False),
        ({"confidence": 0}, True), ({"confidence": 1}, True),
        ({"confidence": 1.1}, False),
    ),
    "ig_memfact_expiry_order": (
        ({"valid_until": None, "observed_at": "2026-01-02T00:00:00+00:00"}, True),
        ({"valid_until": "2026-01-03T00:00:00+00:00", "observed_at": "2026-01-02T00:00:00+00:00"}, True),
        ({"valid_until": "2026-01-02T00:00:00+00:00", "observed_at": "2026-01-02T00:00:00+00:00"}, False),
        ({"valid_until": "2026-01-01T00:00:00+00:00", "observed_at": "2026-01-02T00:00:00+00:00"}, False),
    ),
    "ig_memfact_scope_shape": _SCOPE_CASES,
    "ig_memhead_scope_shape": _SCOPE_CASES,
    "ig_memfact_source_shape": (
        ({"operation": "assert", "producer": "analysis_v2", "producer_policy_version": "typed-memory-projector.v1", "closure_method": "analysis_assertion", "source_role": "user", "source_result_id": 1, "source_result_digest": "a"*64, "source_materiality_digest": "b"*64, "source_state_correlation": "c"*64, "source_watermark_message_id": 1, "source_event_digest": "", "reason_code": "", "expected_evidence_count": 1}, True),
        ({"operation": "invalidate", "producer": "deterministic_projector", "producer_policy_version": "typed-memory-projector.v1", "closure_method": "deterministic_invalidation", "source_role": "system", "source_result_id": None, "source_result_digest": "", "source_materiality_digest": "", "source_state_correlation": "", "source_watermark_message_id": 0, "source_event_digest": "a" * 64, "reason_code": "reset_boundary", "expected_evidence_count": 0}, True),
        ({"operation": "expire", "producer": "deterministic_projector", "producer_policy_version": "typed-memory-projector.v1", "closure_method": "ttl_expiry", "source_role": "authority", "source_result_id": None, "source_result_digest": "", "source_materiality_digest": "", "source_state_correlation": "", "source_watermark_message_id": 0, "source_event_digest": "b" * 64, "reason_code": "valid_until_elapsed", "expected_evidence_count": 0}, True),
        ({"operation": "assert", "producer": "analysis_v2", "producer_policy_version": "typed-memory-projector.v1", "closure_method": "analysis_assertion", "source_role": "manager", "source_result_id": 1, "source_result_digest": "a"*64, "source_materiality_digest": "b"*64, "source_state_correlation": "c"*64, "source_watermark_message_id": 1, "source_event_digest": "", "reason_code": "", "expected_evidence_count": 1}, False),
        ({"operation": "invalidate", "producer": "analysis_v2", "producer_policy_version": "typed-memory-projector.v1", "closure_method": "deterministic_invalidation", "source_role": "system", "source_result_id": None, "source_result_digest": "", "source_materiality_digest": "", "source_state_correlation": "", "source_watermark_message_id": 0, "source_event_digest": "a" * 64, "reason_code": "reset_boundary", "expected_evidence_count": 0}, False),
    ),
    "ig_memev_ordinal_positive": (({"ordinal": 0}, False), ({"ordinal": 1}, True)),
    "ig_memev_message_positive": (({"message_id": 0}, False), ({"message_id": 1}, True)),
    "ig_memhead_revision_positive": (({"revision": 0}, False), ({"revision": 1}, True)),
}


def _ensure_innodb(schema_editor, table_name):
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT ENGINE FROM information_schema.TABLES "
            "WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=%s",
            [table_name],
        )
        row = cursor.fetchone()
    if not row:
        raise RuntimeError(f"required typed-memory table missing: {table_name}")
    if str(row[0] or "").upper() != "INNODB":
        schema_editor.execute(
            f"ALTER TABLE {schema_editor.quote_name(table_name)} ENGINE=InnoDB"
        )


def _flush_deferred_sql(schema_editor):
    deferred = list(schema_editor.deferred_sql)
    schema_editor.deferred_sql.clear()
    for statement in deferred:
        schema_editor.execute(statement)


def _constraints(schema_editor, table_name):
    with schema_editor.connection.cursor() as cursor:
        return schema_editor.connection.introspection.get_constraints(cursor, table_name)


def _ensure_unique_shape(apps, schema_editor, spec):
    app_label, model_name, name, field_names = spec
    model = apps.get_model(app_label, model_name)
    expected = tuple(
        model._meta.get_field(field_name).column for field_name in field_names
    )
    existing = _constraints(schema_editor, model._meta.db_table)
    named = existing.get(name)
    if named is not None:
        if not named.get("unique") or tuple(named.get("columns") or ()) != expected:
            raise RuntimeError(f"{name} has incompatible unique shape")
        return
    schema_editor.add_constraint(
        model,
        models.UniqueConstraint(fields=field_names, name=name),
    )


def _sqlite_check_clause(schema_editor, table_name, check_name):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT sql FROM sqlite_master WHERE type='table' AND name=%s",
            [table_name],
        )
        row = cursor.fetchone()
    create_sql = str(row[0] if row else "")
    match = re.search(
        rf"CONSTRAINT\s+['\"`]?{re.escape(check_name)}['\"`]?\s+CHECK\s*\(",
        create_sql,
        re.IGNORECASE,
    )
    if match is None:
        return ""
    start = match.end() - 1
    depth = 0
    quote = ""
    for index in range(start, len(create_sql)):
        char = create_sql[index]
        if quote:
            if char == quote:
                quote = ""
            continue
        if char in {"'", '"'}:
            quote = char
        elif char == "(":
            depth += 1
        elif char == ")":
            depth -= 1
            if depth == 0:
                return create_sql[start + 1:index]
    return ""


def _physical_check_clause(schema_editor, table_name, check_name):
    if schema_editor.connection.vendor == "mysql":
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "SELECT cc.CHECK_CLAUSE FROM information_schema.CHECK_CONSTRAINTS cc "
                "JOIN information_schema.TABLE_CONSTRAINTS tc ON "
                "tc.CONSTRAINT_SCHEMA=cc.CONSTRAINT_SCHEMA AND "
                "tc.CONSTRAINT_NAME=cc.CONSTRAINT_NAME "
                "WHERE tc.TABLE_SCHEMA=DATABASE() AND tc.TABLE_NAME=%s "
                "AND tc.CONSTRAINT_NAME=%s AND tc.CONSTRAINT_TYPE='CHECK'",
                [table_name, check_name],
            )
            rows = cursor.fetchall()
        return str(rows[0][0] or "") if len(rows) == 1 else ""
    if schema_editor.connection.vendor == "sqlite":
        return _sqlite_check_clause(schema_editor, table_name, check_name)
    raise RuntimeError("typed-memory CHECK validation supports MariaDB/SQLite")


def _normalize_clause(value):
    value = str(value or "").replace("`", "").replace('"', "").casefold()
    value = value.replace("0x00", "0").replace("0x01", "1")
    value = re.sub(r"\bfalse\b", "0", value)
    value = re.sub(r"\btrue\b", "1", value)
    value = re.sub(r"\s+", "", value)
    value = re.sub(
        r"(?P<operator><>|!=|>=|<=|=|>|<)'(?P<number>-?[0-9]+(?:[.][0-9]+)?)'",
        lambda match: match.group("operator") + match.group("number"),
        value,
    )
    value = re.sub(r"\(([^()]+)\)", r"\1", value)
    return value


def _validate_check(apps, schema_editor, spec):
    app_label, model_name, check_name = spec
    model = apps.get_model(app_label, model_name)
    existing = _constraints(schema_editor, model._meta.db_table)
    actual = existing.get(check_name)
    if actual is None:
        constraint = next(
            row for row in model._meta.constraints if row.name == check_name
        )
        schema_editor.add_constraint(model, constraint)
        existing = _constraints(schema_editor, model._meta.db_table)
        actual = existing.get(check_name)
    columns = set((actual or {}).get("columns") or ())
    if (
        actual is None or not actual.get("check")
        or (columns and columns != CHECK_COLUMNS[check_name])
        or actual.get("unique") or actual.get("foreign_key")
    ):
        raise RuntimeError(f"{check_name} has incompatible CHECK shape")
    clause = _physical_check_clause(schema_editor, model._meta.db_table, check_name)
    normalized = _normalize_clause(clause)
    if not clause or any(
        fragment not in normalized for fragment in CHECK_FRAGMENTS[check_name]
    ):
        raise RuntimeError(
            f"{check_name} has incompatible physical predicate: {normalized}"
        )
    quote = schema_editor.quote_name
    for values, expected_result in CHECK_TRUTH_TABLES[check_name]:
        columns = list(values)
        numeric_columns = {
            "confidence", "commercial_episode_id", "order_id",
            "post_sale_case_id", "source_result_id", "source_watermark_message_id",
            "expected_evidence_count", "ordinal", "message_id", "revision",
        }
        numeric_type = (
            "DECIMAL(20,4)"
            if schema_editor.connection.vendor == "mysql"
            else "NUMERIC"
        )
        select_columns = ", ".join(
            (
                f"CAST(%s AS {numeric_type}) AS {quote(column)}"
                if column in numeric_columns
                else f"%s AS {quote(column)}"
            )
            for column in columns
        )
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                f"SELECT CASE WHEN ({clause}) THEN 1 ELSE 0 END "
                f"FROM (SELECT {select_columns}) candidate",
                [values[column] for column in columns],
            )
            actual_result = bool(cursor.fetchone()[0])
        if actual_result != expected_result:
            raise RuntimeError(
                f"{check_name} has incompatible truth table for {values!r}"
            )


def ensure_typed_memory_schema(apps, schema_editor):
    tables = set(schema_editor.connection.introspection.table_names())
    models_in_order = (
        ("IgMemoryFact", FACT_TABLE),
        ("IgMemoryFactEvidence", EVIDENCE_TABLE),
        ("IgMemoryHead", HEAD_TABLE),
    )
    existing_models = {"InstagramBotSettings", "IgConversationAnalysisResult"}
    for model_name, table_name in models_in_order:
        model = apps.get_model("management", model_name)
        existed = table_name in tables
        if not existed:
            schema_editor.create_model(model)
            _flush_deferred_sql(schema_editor)
            tables.add(table_name)
        else:
            existing_models.add(model_name)
        _ensure_innodb(schema_editor, table_name)
    ensure_additive_schema(
        apps,
        schema_editor,
        field_specs=tuple(
            spec for spec in FIELD_SPECS
            if spec[1] in existing_models
            and not (
                schema_editor.connection.vendor == "sqlite" and spec[2] == "id"
            )
        ),
        index_specs=tuple(spec for spec in INDEX_SPECS if spec[1] in existing_models),
        constraint_specs=(),
    )
    if schema_editor.connection.vendor == "sqlite":
        for _model_name, table_name in models_in_order:
            primary = next(
                (
                    row for row in _constraints(schema_editor, table_name).values()
                    if row.get("primary_key")
                ),
                None,
            )
            if primary is None or tuple(primary.get("columns") or ()) != ("id",):
                raise RuntimeError(f"{table_name}.id primary-key shape is incompatible")
    for spec in UNIQUE_SPECS:
        _ensure_unique_shape(apps, schema_editor, spec)
    for app_label, model_name, name, field_names in UNIQUE_SPECS:
        model = apps.get_model(app_label, model_name)
        expected = tuple(
            model._meta.get_field(field_name).column for field_name in field_names
        )
        actual = _constraints(schema_editor, model._meta.db_table).get(name)
        if (
            actual is None or not actual.get("unique")
            or tuple(actual.get("columns") or ()) != expected
        ):
            raise RuntimeError(f"{name} canonical unique shape is missing")
    for spec in CHECK_SPECS:
        _validate_check(apps, schema_editor, spec)
    for app_label, model_name, index_name in INDEX_SPECS:
        model = apps.get_model(app_label, model_name)
        actual = _constraints(schema_editor, model._meta.db_table).get(index_name)
        expected_index = next(row for row in model._meta.indexes if row.name == index_name)
        expected = tuple(
            model._meta.get_field(field.lstrip("-")).column
            for field in expected_index.fields
        )
        if (
            actual is None or tuple(actual.get("columns") or ()) != expected
            or actual.get("unique") or actual.get("check")
        ):
            raise RuntimeError(f"{index_name} has incompatible index shape")
    if schema_editor.connection.vendor == "mysql":
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "SELECT DATA_TYPE, NUMERIC_PRECISION, NUMERIC_SCALE "
                "FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() "
                "AND TABLE_NAME=%s AND COLUMN_NAME='confidence'",
                [FACT_TABLE],
            )
            confidence = cursor.fetchone()
            cursor.execute(
                "SELECT COLUMN_NAME, CHARACTER_MAXIMUM_LENGTH "
                "FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() "
                "AND TABLE_NAME=%s AND COLUMN_NAME IN "
                "('record_key','slot_key','integrity_hmac','integrity_key_id')",
                [FACT_TABLE],
            )
            lengths = {str(name): int(length) for name, length in cursor.fetchall()}
        if tuple(confidence or ()) != ("decimal", 5, 4):
            raise RuntimeError(f"{FACT_TABLE}.confidence physical shape is incompatible")
        if lengths != {
            "record_key": 80, "slot_key": 80,
            "integrity_hmac": 64, "integrity_key_id": 32,
        }:
            raise RuntimeError(f"{FACT_TABLE} canonical identity lengths are incompatible")


_V21_RESULT_GUARD_SHA = {
    "mysql": "a0362862cd2296adfca8cb7e7be0228fb44128677fe750e881cfc96d4d415fb8",
    "sqlite": "267845990c210918e600d456f81eb5d03a10da886e237be361643fda262f3f23",
}


def _trigger_exists(schema_editor, name):
    if schema_editor.connection.vendor == "mysql":
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "SELECT COUNT(*) FROM information_schema.TRIGGERS "
                "WHERE TRIGGER_SCHEMA=DATABASE() AND TRIGGER_NAME=%s",
                [name],
            )
            return bool(cursor.fetchone()[0])
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT COUNT(*) FROM sqlite_master WHERE type='trigger' AND name=%s",
            [name],
        )
        return bool(cursor.fetchone()[0])


def reinstall_analysis_v22_insert_guard(apps, schema_editor):
    """Stage a v2.2 guard before retiring the immutable v2.1 guard."""
    del apps
    vendor = schema_editor.connection.vendor
    if vendor not in {"mysql", "sqlite"}:
        raise RuntimeError("Analysis V2 v2.2 guard supports MariaDB/SQLite")
    module = importlib.import_module(
        "management.migrations.0183_analysis_v2_result_proposals"
    )
    base = (
        module._mysql_result_insert_invalid()
        if vendor == "mysql"
        else module._sqlite_result_insert_invalid()
    )
    if hashlib.sha256(base.encode()).hexdigest() != _V21_RESULT_GUARD_SHA[vendor]:
        raise RuntimeError("0183 result guard source drifted; refusing dynamic upgrade")
    base = base.replace(
        "NEW.result_schema_version <> 'analysis-v2.1'",
        "NEW.result_schema_version NOT IN ('analysis-v2.1', 'analysis-v2.2')",
    )
    if vendor == "mysql":
        language_invalid = f"""(
            NOT JSON_VALID(NEW.language_evidence_message_ids)
            OR COALESCE(JSON_TYPE(NEW.language_evidence_message_ids), '') <> 'ARRAY'
            OR JSON_LENGTH(NEW.language_evidence_message_ids) > 40
            OR (NEW.result_schema_version='analysis-v2.1'
                AND JSON_LENGTH(NEW.language_evidence_message_ids)<>0)
            OR (NEW.result_schema_version='analysis-v2.2'
                AND (NEW.detected_language<>'')<>(JSON_LENGTH(NEW.language_evidence_message_ids)>0))
            OR EXISTS (
                SELECT 1 FROM JSON_TABLE(
                    NEW.language_evidence_message_ids, '$[*]' COLUMNS(
                        item_json JSON PATH '$', message_id BIGINT PATH '$' NULL ON ERROR
                    )
                ) evidence
                WHERE COALESCE(JSON_TYPE(evidence.item_json),'')<>'INTEGER'
                   OR evidence.message_id IS NULL OR evidence.message_id<=0
                   OR NOT EXISTS (
                       SELECT 1 FROM management_instagrambotmessage message
                       WHERE message.id=evidence.message_id
                         AND message.client_id=NEW.client_id AND message.role='user'
                         AND message.id<=NEW.watermark_message_id
                   )
            )
            OR JSON_LENGTH(NEW.language_evidence_message_ids)<>(
                SELECT COUNT(DISTINCT evidence.message_id) FROM JSON_TABLE(
                    NEW.language_evidence_message_ids, '$[*]' COLUMNS(
                        message_id BIGINT PATH '$' NULL ON ERROR
                    )
                ) evidence
            )
        )"""
        body = (
            f"({base} OR {language_invalid} OR NOT EXISTS (SELECT 1 FROM {CLIENT_TABLE} c "
            "WHERE c.id=NEW.client_id AND c.privacy_erasure_started_at IS NULL))"
        )
        staged = "ig_anres_v22_insert_guard"
        if not _trigger_exists(schema_editor, staged):
            schema_editor.execute(
                f"CREATE TRIGGER {staged} BEFORE INSERT ON {RESULT_TABLE} "
                f"FOR EACH ROW BEGIN IF {body} THEN SIGNAL SQLSTATE '45000' "
                "SET MESSAGE_TEXT='IgConversationAnalysisResult v2.2 insert guard'; END IF; END"
            )
        schema_editor.execute("DROP TRIGGER IF EXISTS ig_anres_insert_guard")
    else:
        language_invalid = """(
            NOT json_valid(NEW.language_evidence_message_ids)
            OR COALESCE(json_type(NEW.language_evidence_message_ids),'')<>'array'
            OR json_array_length(NEW.language_evidence_message_ids)>40
            OR (NEW.result_schema_version='analysis-v2.1'
                AND json_array_length(NEW.language_evidence_message_ids)<>0)
            OR (NEW.result_schema_version='analysis-v2.2'
                AND (NEW.detected_language<>'')<>(json_array_length(NEW.language_evidence_message_ids)>0))
            OR EXISTS (
                SELECT 1 FROM json_each(NEW.language_evidence_message_ids) evidence
                WHERE evidence.type<>'integer' OR evidence.value<=0
                   OR NOT EXISTS (
                       SELECT 1 FROM management_instagrambotmessage message
                       WHERE message.id=evidence.value
                         AND message.client_id=NEW.client_id AND message.role='user'
                         AND message.id<=NEW.watermark_message_id
                   )
            )
            OR json_array_length(NEW.language_evidence_message_ids)<>(
                SELECT COUNT(DISTINCT evidence.value)
                FROM json_each(NEW.language_evidence_message_ids) evidence
            )
        )"""
        body = (
            f"({base} OR {language_invalid} OR NOT EXISTS (SELECT 1 FROM {CLIENT_TABLE} c "
            "WHERE c.id=NEW.client_id AND c.privacy_erasure_started_at IS NULL))"
        )
        staged = "ig_anres_v22_insert_guard"
        if not _trigger_exists(schema_editor, staged):
            schema_editor.execute(
                f"CREATE TRIGGER {staged} BEFORE INSERT ON {RESULT_TABLE} "
                f"WHEN {body} BEGIN SELECT RAISE(ABORT, "
                "'IgConversationAnalysisResult v2.2 insert guard'); END"
            )
        schema_editor.execute("DROP TRIGGER IF EXISTS ig_anres_insert_guard")


def _mysql_fact_invalid():
    typed = """(
        NOT JSON_VALID(NEW.typed_value)
        OR COALESCE(JSON_TYPE(NEW.typed_value), '') <> 'OBJECT'
        OR NOT (
            (NEW.operation <> 'assert' AND JSON_LENGTH(NEW.typed_value) = 0)
            OR (
                NEW.operation = 'assert' AND NEW.fact_key = 'observed_language'
                AND JSON_LENGTH(NEW.typed_value) = 1
                AND JSON_CONTAINS_PATH(NEW.typed_value, 'all', '$.code')=1
                AND JSON_TYPE(JSON_EXTRACT(NEW.typed_value, '$.code'))='STRING'
                AND JSON_UNQUOTE(JSON_EXTRACT(NEW.typed_value, '$.code'))
                    IN ('uk','ru','en','mixed','unknown')
            )
            OR (
                NEW.operation = 'assert' AND NEW.fact_key = 'objection_observed'
                AND JSON_LENGTH(NEW.typed_value) = 1
                AND JSON_CONTAINS_PATH(NEW.typed_value, 'all', '$.type')=1
                AND JSON_TYPE(JSON_EXTRACT(NEW.typed_value, '$.type'))='STRING'
                AND JSON_UNQUOTE(JSON_EXTRACT(NEW.typed_value, '$.type')) IN (
                    'price','thinking','size_risk','prepayment_trust','defect_risk',
                    'delivery_time','cheaper_elsewhere','print_quality','out_of_stock',
                    'payday','compare_brand','ask_partner'
                )
            )
            OR (
                NEW.operation = 'assert' AND NEW.fact_key = 'deferred_intent'
                AND JSON_LENGTH(NEW.typed_value) = 3
                AND JSON_CONTAINS_PATH(
                    NEW.typed_value, 'all', '$.kind', '$.condition_code', '$.deferred_until'
                ) = 1
                AND (
                    (JSON_UNQUOTE(JSON_EXTRACT(NEW.typed_value, '$.kind'))='date'
                     AND JSON_UNQUOTE(JSON_EXTRACT(NEW.typed_value, '$.condition_code'))='customer_date'
                     AND JSON_UNQUOTE(JSON_EXTRACT(NEW.typed_value, '$.deferred_until')) REGEXP '^[0-9]{4}-[0-9]{2}-[0-9]{2}T')
                    OR (JSON_UNQUOTE(JSON_EXTRACT(NEW.typed_value, '$.kind'))='event'
                     AND JSON_UNQUOTE(JSON_EXTRACT(NEW.typed_value, '$.condition_code'))='after_event'
                     AND JSON_UNQUOTE(JSON_EXTRACT(NEW.typed_value, '$.deferred_until'))='')
                    OR (JSON_UNQUOTE(JSON_EXTRACT(NEW.typed_value, '$.kind'))='payday'
                     AND JSON_UNQUOTE(JSON_EXTRACT(NEW.typed_value, '$.condition_code'))='payday'
                     AND JSON_UNQUOTE(JSON_EXTRACT(NEW.typed_value, '$.deferred_until'))='')
                    OR (JSON_UNQUOTE(JSON_EXTRACT(NEW.typed_value, '$.kind'))='indefinite'
                     AND JSON_UNQUOTE(JSON_EXTRACT(NEW.typed_value, '$.condition_code'))='indefinite'
                     AND JSON_UNQUOTE(JSON_EXTRACT(NEW.typed_value, '$.deferred_until'))='')
                )
            )
        )
    )"""
    return f"""COALESCE((
        BINARY NEW.record_key NOT REGEXP '^memory-fact:[0-9a-f]{{64}}$'
        OR BINARY NEW.slot_key NOT REGEXP '^memory-slot:[0-9a-f]{{64}}$'
        OR NEW.fact_key NOT IN ('observed_language','objection_observed','deferred_intent')
        OR NEW.schema_version <> 'typed-memory.v1'
        OR NEW.operation NOT IN ('assert','invalidate','expire')
        OR BINARY NEW.integrity_hmac NOT REGEXP '^[0-9a-f]{{64}}$'
        OR BINARY NEW.integrity_key_id NOT REGEXP '^[a-z0-9_.:+-]{{1,32}}$'
        OR BINARY NEW.line_id NOT REGEXP '^[a-z0-9_.:+-]{{0,96}}$'
        OR {typed}
        OR (NEW.operation='assert' AND NOT (
            NEW.producer='analysis_v2'
            AND NEW.producer_policy_version='typed-memory-projector.v1'
            AND NEW.closure_method='analysis_assertion'
            AND NEW.source_role='user' AND NEW.source_result_id IS NOT NULL
            AND NEW.expected_evidence_count BETWEEN 1 AND 40
            AND NEW.source_event_digest='' AND NEW.reason_code=''
        ))
        OR (NEW.operation='invalidate' AND NOT (
            NEW.producer='deterministic_projector'
            AND NEW.producer_policy_version='typed-memory-projector.v1'
            AND NEW.closure_method='deterministic_invalidation'
            AND NEW.source_role IN ('system','authority')
            AND NEW.source_result_id IS NULL AND NEW.source_result_digest=''
            AND NEW.source_materiality_digest='' AND NEW.source_state_correlation=''
            AND NEW.source_watermark_message_id=0 AND NEW.expected_evidence_count=0
            AND NEW.reason_code IN ('reset_boundary','episode_closed','line_replaced',
                'explicit_retraction','superseded_by_new_assertion')
            AND NEW.confidence IS NULL AND NEW.valid_until IS NULL
        ))
        OR (NEW.operation='expire' AND NOT (
            NEW.producer='deterministic_projector'
            AND NEW.producer_policy_version='typed-memory-projector.v1'
            AND NEW.closure_method='ttl_expiry'
            AND NEW.source_role IN ('system','authority')
            AND NEW.source_result_id IS NULL AND NEW.source_result_digest=''
            AND NEW.source_materiality_digest='' AND NEW.source_state_correlation=''
            AND NEW.source_watermark_message_id=0 AND NEW.expected_evidence_count=0
            AND NEW.reason_code='valid_until_elapsed'
            AND NEW.confidence IS NULL AND NEW.valid_until IS NULL
        ))
        OR NOT EXISTS (SELECT 1 FROM {CLIENT_TABLE} c WHERE c.id=NEW.client_id
            AND c.privacy_erasure_started_at IS NULL)
        OR (NEW.commercial_episode_id IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM management_igcommercialepisode episode
            WHERE episode.id=NEW.commercial_episode_id AND episode.client_id=NEW.client_id
        ))
        OR (NEW.operation='assert' AND NOT EXISTS (
            SELECT 1 FROM {RESULT_TABLE} r
            WHERE r.id=NEW.source_result_id AND r.client_id=NEW.client_id
              AND r.result_schema_version='analysis-v2.2'
              AND r.result_digest=NEW.source_result_digest
              AND r.materiality_digest=NEW.source_materiality_digest
              AND r.state_correlation=NEW.source_state_correlation
              AND r.watermark_message_id=NEW.source_watermark_message_id
              AND r.analyzed_at=NEW.observed_at
              AND (
                (NEW.fact_key='observed_language'
                 AND JSON_UNQUOTE(JSON_EXTRACT(NEW.typed_value,'$.code'))=r.detected_language
                 AND NEW.commercial_episode_id IS NULL AND NEW.line_id=''
                 AND NEW.confidence IS NULL AND NEW.valid_until IS NULL)
                OR (NEW.fact_key='objection_observed'
                 AND JSON_UNQUOTE(JSON_EXTRACT(NEW.typed_value,'$.type'))=r.active_objection_type
                 AND NEW.commercial_episode_id=r.commercial_episode_id
                 AND NEW.line_id=r.line_id
                 AND NEW.confidence <=> r.active_objection_confidence
                 AND NEW.valid_until IS NULL)
                OR (NEW.fact_key='deferred_intent'
                 AND JSON_UNQUOTE(JSON_EXTRACT(NEW.typed_value,'$.kind'))=r.deferred_kind
                 AND JSON_UNQUOTE(JSON_EXTRACT(NEW.typed_value,'$.condition_code'))=r.deferred_condition_code
                 AND NEW.commercial_episode_id=r.commercial_episode_id AND NEW.line_id=''
                 AND NEW.confidence IS NULL AND NEW.valid_until <=> r.deferred_until)
              )
        ))
        OR (NEW.operation IN ('invalidate','expire') AND
            BINARY NEW.source_event_digest NOT REGEXP '^[0-9a-f]{{64}}$')
        OR (NEW.operation IN ('invalidate','expire') AND NEW.supersedes_id IS NULL)
        OR (NEW.supersedes_id IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM {FACT_TABLE} previous_fact JOIN {HEAD_TABLE} head
              ON head.current_fact_id=previous_fact.id
            WHERE previous_fact.id=NEW.supersedes_id
              AND previous_fact.slot_key=NEW.slot_key
              AND previous_fact.client_id=NEW.client_id
              AND previous_fact.scope=NEW.scope
              AND previous_fact.fact_key=NEW.fact_key
              AND previous_fact.schema_version=NEW.schema_version
        ))
        OR (NEW.supersedes_id IS NULL AND EXISTS (
            SELECT 1 FROM {HEAD_TABLE} head WHERE head.slot_key=NEW.slot_key
        ))
    ), TRUE)"""


def _sqlite_fact_invalid():
    return """COALESCE((
        NEW.record_key NOT REGEXP '^memory-fact:[0-9a-f]{64}$'
        OR NEW.slot_key NOT REGEXP '^memory-slot:[0-9a-f]{64}$'
        OR NEW.fact_key NOT IN ('observed_language','objection_observed','deferred_intent')
        OR NEW.schema_version <> 'typed-memory.v1'
        OR NEW.operation NOT IN ('assert','invalidate','expire')
        OR NEW.integrity_hmac NOT REGEXP '^[0-9a-f]{64}$'
        OR NEW.integrity_key_id NOT REGEXP '^[a-z0-9_.:+-]{1,32}$'
        OR NEW.line_id NOT REGEXP '^[a-z0-9_.:+-]{0,96}$'
        OR NOT json_valid(NEW.typed_value)
        OR COALESCE(json_type(NEW.typed_value), '') <> 'object'
        OR NOT (
            (NEW.operation <> 'assert' AND (SELECT COUNT(*) FROM json_each(NEW.typed_value))=0)
            OR (NEW.operation='assert' AND NEW.fact_key='observed_language'
                AND (SELECT COUNT(*) FROM json_each(NEW.typed_value))=1
                AND json_type(NEW.typed_value,'$.code')='text'
                AND json_extract(NEW.typed_value,'$.code') IN ('uk','ru','en','mixed','unknown'))
            OR (NEW.operation='assert' AND NEW.fact_key='objection_observed'
                AND (SELECT COUNT(*) FROM json_each(NEW.typed_value))=1
                AND json_type(NEW.typed_value,'$.type')='text'
                AND json_extract(NEW.typed_value,'$.type') IN (
                    'price','thinking','size_risk','prepayment_trust','defect_risk',
                    'delivery_time','cheaper_elsewhere','print_quality','out_of_stock',
                    'payday','compare_brand','ask_partner'))
            OR (NEW.operation='assert' AND NEW.fact_key='deferred_intent'
                AND (SELECT COUNT(*) FROM json_each(NEW.typed_value))=3
                AND ((json_extract(NEW.typed_value,'$.kind')='date'
                      AND json_extract(NEW.typed_value,'$.condition_code')='customer_date'
                      AND json_extract(NEW.typed_value,'$.deferred_until') REGEXP '^[0-9]{4}-[0-9]{2}-[0-9]{2}T')
                  OR (json_extract(NEW.typed_value,'$.kind')='event'
                      AND json_extract(NEW.typed_value,'$.condition_code')='after_event'
                      AND json_extract(NEW.typed_value,'$.deferred_until')='')
                  OR (json_extract(NEW.typed_value,'$.kind')='payday'
                      AND json_extract(NEW.typed_value,'$.condition_code')='payday'
                      AND json_extract(NEW.typed_value,'$.deferred_until')='')
                  OR (json_extract(NEW.typed_value,'$.kind')='indefinite'
                      AND json_extract(NEW.typed_value,'$.condition_code')='indefinite'
                      AND json_extract(NEW.typed_value,'$.deferred_until')='')))
        )
        OR (NEW.operation='assert' AND NOT (
            NEW.producer='analysis_v2'
            AND NEW.producer_policy_version='typed-memory-projector.v1'
            AND NEW.closure_method='analysis_assertion'
            AND NEW.source_role='user' AND NEW.source_result_id IS NOT NULL
            AND NEW.expected_evidence_count BETWEEN 1 AND 40
            AND NEW.source_event_digest='' AND NEW.reason_code=''
        ))
        OR (NEW.operation='invalidate' AND NOT (
            NEW.producer='deterministic_projector'
            AND NEW.producer_policy_version='typed-memory-projector.v1'
            AND NEW.closure_method='deterministic_invalidation'
            AND NEW.source_role IN ('system','authority')
            AND NEW.source_result_id IS NULL AND NEW.source_result_digest=''
            AND NEW.source_materiality_digest='' AND NEW.source_state_correlation=''
            AND NEW.source_watermark_message_id=0 AND NEW.expected_evidence_count=0
            AND NEW.reason_code IN ('reset_boundary','episode_closed','line_replaced',
                'explicit_retraction','superseded_by_new_assertion')
            AND NEW.confidence IS NULL AND NEW.valid_until IS NULL
        ))
        OR (NEW.operation='expire' AND NOT (
            NEW.producer='deterministic_projector'
            AND NEW.producer_policy_version='typed-memory-projector.v1'
            AND NEW.closure_method='ttl_expiry'
            AND NEW.source_role IN ('system','authority')
            AND NEW.source_result_id IS NULL AND NEW.source_result_digest=''
            AND NEW.source_materiality_digest='' AND NEW.source_state_correlation=''
            AND NEW.source_watermark_message_id=0 AND NEW.expected_evidence_count=0
            AND NEW.reason_code='valid_until_elapsed'
            AND NEW.confidence IS NULL AND NEW.valid_until IS NULL
        ))
        OR NOT EXISTS (SELECT 1 FROM management_igclient c WHERE c.id=NEW.client_id
            AND c.privacy_erasure_started_at IS NULL)
        OR (NEW.commercial_episode_id IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM management_igcommercialepisode episode
            WHERE episode.id=NEW.commercial_episode_id AND episode.client_id=NEW.client_id
        ))
        OR (NEW.operation='assert' AND NOT EXISTS (
            SELECT 1 FROM management_igconversationanalysisresult r
            WHERE r.id=NEW.source_result_id AND r.client_id=NEW.client_id
              AND r.result_schema_version='analysis-v2.2'
              AND r.result_digest=NEW.source_result_digest
              AND r.materiality_digest=NEW.source_materiality_digest
              AND r.state_correlation=NEW.source_state_correlation
              AND r.watermark_message_id=NEW.source_watermark_message_id
              AND r.analyzed_at=NEW.observed_at
              AND (
                (NEW.fact_key='observed_language'
                 AND json_extract(NEW.typed_value,'$.code')=r.detected_language
                 AND NEW.commercial_episode_id IS NULL AND NEW.line_id=''
                 AND NEW.confidence IS NULL AND NEW.valid_until IS NULL)
                OR (NEW.fact_key='objection_observed'
                 AND json_extract(NEW.typed_value,'$.type')=r.active_objection_type
                 AND NEW.commercial_episode_id=r.commercial_episode_id
                 AND NEW.line_id=r.line_id
                 AND NEW.confidence IS r.active_objection_confidence
                 AND NEW.valid_until IS NULL)
                OR (NEW.fact_key='deferred_intent'
                 AND json_extract(NEW.typed_value,'$.kind')=r.deferred_kind
                 AND json_extract(NEW.typed_value,'$.condition_code')=r.deferred_condition_code
                 AND NEW.commercial_episode_id=r.commercial_episode_id AND NEW.line_id=''
                 AND NEW.confidence IS NULL AND NEW.valid_until IS r.deferred_until)
              )
        ))
        OR (NEW.operation IN ('invalidate','expire') AND
            NEW.source_event_digest NOT REGEXP '^[0-9a-f]{64}$')
        OR (NEW.operation IN ('invalidate','expire') AND NEW.supersedes_id IS NULL)
        OR (NEW.supersedes_id IS NOT NULL AND NOT EXISTS (
            SELECT 1 FROM management_igmemoryfact previous_fact
            JOIN management_igmemoryhead head ON head.current_fact_id=previous_fact.id
            WHERE previous_fact.id=NEW.supersedes_id
              AND previous_fact.slot_key=NEW.slot_key
              AND previous_fact.client_id=NEW.client_id
              AND previous_fact.scope=NEW.scope
              AND previous_fact.fact_key=NEW.fact_key
              AND previous_fact.schema_version=NEW.schema_version
        ))
        OR (NEW.supersedes_id IS NULL AND EXISTS (
            SELECT 1 FROM management_igmemoryhead head WHERE head.slot_key=NEW.slot_key
        ))
    ), 1)"""


def install_typed_memory_and_privacy_triggers(apps, schema_editor):
    del apps
    vendor = schema_editor.connection.vendor
    trigger_names = (
        "ig_memfact_insert_guard", "ig_memfact_no_update", "ig_memfact_priv_delete",
        "ig_memev_insert_guard", "ig_memev_no_update", "ig_memev_priv_delete",
        "ig_memhead_insert_guard", "ig_memhead_transition", "ig_memhead_priv_delete",
        "ig_anres_priv_delete", "ig_anprop_priv_delete", "ig_mat_priv_delete",
        "ig_anevt_priv_delete",
        "ig_anprop_priv_insert", "ig_mat_priv_insert", "ig_anevt_priv_insert",
    )
    if vendor == "mysql":
        schema_editor.execute(
            f"CREATE OR REPLACE TRIGGER ig_memfact_insert_guard BEFORE INSERT ON {FACT_TABLE} "
            f"FOR EACH ROW BEGIN IF {_mysql_fact_invalid()} THEN SIGNAL SQLSTATE '45000' "
            "SET MESSAGE_TEXT='IgMemoryFact insert guard'; END IF; END"
        )
        schema_editor.execute(
            f"CREATE OR REPLACE TRIGGER ig_memfact_no_update BEFORE UPDATE ON {FACT_TABLE} "
            "FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IgMemoryFact is append-only'"
        )
        schema_editor.execute(
            f"CREATE OR REPLACE TRIGGER ig_memfact_priv_delete BEFORE DELETE ON {FACT_TABLE} "
            f"FOR EACH ROW BEGIN IF NOT EXISTS (SELECT 1 FROM {CLIENT_TABLE} c "
            "WHERE c.id=OLD.client_id AND c.privacy_erasure_started_at IS NOT NULL) "
            "THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IgMemoryFact delete requires privacy fence'; END IF; END"
        )
        evidence_invalid = f"""(
            NEW.ordinal NOT BETWEEN 1 AND 40 OR NEW.message_id <= 0
            OR NEW.source_role <> 'user'
            OR NEW.claim_code NOT IN ('language','objection','deferred_intent')
            OR BINARY NEW.evidence_hmac NOT REGEXP '^[0-9a-f]{{64}}$'
            OR BINARY NEW.integrity_key_id NOT REGEXP '^[a-z0-9_.:+-]{{1,32}}$'
            OR NOT EXISTS (
                SELECT 1 FROM {FACT_TABLE} f JOIN {RESULT_TABLE} r
                  ON r.id=f.source_result_id JOIN {CLIENT_TABLE} c ON c.id=f.client_id
                WHERE f.id=NEW.fact_id AND NEW.ordinal<=f.expected_evidence_count
                  AND c.privacy_erasure_started_at IS NULL
                  AND NEW.claim_code=CASE f.fact_key
                    WHEN 'observed_language' THEN 'language'
                    WHEN 'objection_observed' THEN 'objection'
                    WHEN 'deferred_intent' THEN 'deferred_intent' END
                  AND (
                    (NEW.claim_code='language' AND JSON_CONTAINS(
                        r.language_evidence_message_ids,
                        CAST(NEW.message_id AS CHAR)
                    )=1)
                    OR (NEW.claim_code<>'language' AND EXISTS (
                        SELECT 1 FROM JSON_TABLE(
                            r.evidence_manifest, '$[*]' COLUMNS(
                                message_id BIGINT PATH '$.message_id' NULL ON ERROR,
                                source_role VARCHAR(16) PATH '$.source_role' NULL ON ERROR,
                                claim_codes JSON PATH '$.claim_codes' NULL ON ERROR
                            )
                        ) evidence
                        WHERE evidence.message_id=NEW.message_id
                          AND evidence.source_role='user'
                          AND JSON_CONTAINS(
                              evidence.claim_codes,
                              JSON_QUOTE(NEW.claim_code)
                          )=1
                    ))
                  )
            )
        )"""
        schema_editor.execute(
            f"CREATE OR REPLACE TRIGGER ig_memev_insert_guard BEFORE INSERT ON {EVIDENCE_TABLE} "
            f"FOR EACH ROW BEGIN IF {evidence_invalid} THEN SIGNAL SQLSTATE '45000' "
            "SET MESSAGE_TEXT='IgMemoryFactEvidence insert guard'; END IF; END"
        )
        schema_editor.execute(
            f"CREATE OR REPLACE TRIGGER ig_memev_no_update BEFORE UPDATE ON {EVIDENCE_TABLE} "
            "FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IgMemoryFactEvidence is append-only'"
        )
        schema_editor.execute(
            f"CREATE OR REPLACE TRIGGER ig_memev_priv_delete BEFORE DELETE ON {EVIDENCE_TABLE} "
            f"FOR EACH ROW BEGIN IF NOT EXISTS (SELECT 1 FROM {FACT_TABLE} f JOIN {CLIENT_TABLE} c "
            "ON c.id=f.client_id WHERE f.id=OLD.fact_id AND c.privacy_erasure_started_at IS NOT NULL) "
            "THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IgMemoryFactEvidence delete requires privacy fence'; END IF; END"
        )
        head_match = f"""EXISTS (
            SELECT 1 FROM {FACT_TABLE} f JOIN {CLIENT_TABLE} c ON c.id=f.client_id
              LEFT JOIN {RESULT_TABLE} r ON r.id=f.source_result_id
              WHERE f.id=NEW.current_fact_id AND c.privacy_erasure_started_at IS NULL
              AND f.slot_key=NEW.slot_key AND f.client_id=NEW.client_id
              AND f.scope=NEW.scope AND f.fact_key=NEW.fact_key
              AND f.schema_version=NEW.schema_version
              AND f.commercial_episode_id <=> NEW.commercial_episode_id
              AND f.line_id=NEW.line_id AND f.order_id <=> NEW.order_id
              AND f.post_sale_case_id <=> NEW.post_sale_case_id
              AND ((NEW.state='active' AND f.operation='assert')
                OR (NEW.state='invalidated' AND f.operation='invalidate')
                OR (NEW.state='expired' AND f.operation='expire'))
              AND (SELECT COUNT(*) FROM {EVIDENCE_TABLE} e WHERE e.fact_id=f.id)
                    = f.expected_evidence_count
              AND (
                f.operation<>'assert'
                OR (f.fact_key='observed_language'
                    AND f.expected_evidence_count=JSON_LENGTH(r.language_evidence_message_ids))
                OR (f.fact_key='objection_observed' AND f.expected_evidence_count=(
                    SELECT COUNT(*) FROM JSON_TABLE(
                        r.evidence_manifest, '$[*]' COLUMNS(
                            source_role VARCHAR(16) PATH '$.source_role',
                            claim_codes JSON PATH '$.claim_codes'
                        )
                    ) evidence WHERE evidence.source_role='user'
                      AND JSON_CONTAINS(evidence.claim_codes, '\"objection\"')=1
                ))
                OR (f.fact_key='deferred_intent' AND f.expected_evidence_count=(
                    SELECT COUNT(*) FROM JSON_TABLE(
                        r.evidence_manifest, '$[*]' COLUMNS(
                            source_role VARCHAR(16) PATH '$.source_role',
                            claim_codes JSON PATH '$.claim_codes'
                        )
                    ) evidence WHERE evidence.source_role='user'
                      AND JSON_CONTAINS(evidence.claim_codes, '\"deferred_intent\"')=1
                ))
              )
        )"""
        schema_editor.execute(
            f"CREATE OR REPLACE TRIGGER ig_memhead_insert_guard BEFORE INSERT ON {HEAD_TABLE} "
            f"FOR EACH ROW BEGIN IF NEW.revision<>1 OR NEW.state<>'active' OR NEW.projection_policy_version<>'typed-memory-projector.v1' "
            "OR BINARY NEW.projection_hmac NOT REGEXP '^[0-9a-f]{64}$' "
            "OR BINARY NEW.integrity_key_id NOT REGEXP '^[a-z0-9_.:+-]{1,32}$' "
            f"OR NOT {head_match} OR EXISTS (SELECT 1 FROM {FACT_TABLE} f WHERE f.id=NEW.current_fact_id AND f.supersedes_id IS NOT NULL) "
            "THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IgMemoryHead insert guard'; END IF; END"
        )
        identity_unchanged = " AND ".join(
            f"OLD.{field} <=> NEW.{field}" for field in (
                "slot_key", "client_id", "scope", "commercial_episode_id", "line_id",
                "order_id", "post_sale_case_id", "fact_key", "schema_version", "created_at",
            )
        )
        schema_editor.execute(
            f"CREATE OR REPLACE TRIGGER ig_memhead_transition BEFORE UPDATE ON {HEAD_TABLE} "
            f"FOR EACH ROW BEGIN IF NOT ({identity_unchanged}) OR NEW.revision<>OLD.revision+1 "
            "OR NEW.projection_policy_version<>'typed-memory-projector.v1' "
            "OR BINARY NEW.projection_hmac NOT REGEXP '^[0-9a-f]{64}$' "
            "OR BINARY NEW.integrity_key_id NOT REGEXP '^[a-z0-9_.:+-]{1,32}$' "
            "OR NEW.projected_at < OLD.projected_at "
            f"OR NOT {head_match} OR NOT EXISTS (SELECT 1 FROM {FACT_TABLE} f "
            "WHERE f.id=NEW.current_fact_id AND f.supersedes_id=OLD.current_fact_id) "
            "THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IgMemoryHead invalid transition'; END IF; END"
        )
        schema_editor.execute(
            f"CREATE OR REPLACE TRIGGER ig_memhead_priv_delete BEFORE DELETE ON {HEAD_TABLE} "
            f"FOR EACH ROW BEGIN IF NOT EXISTS (SELECT 1 FROM {CLIENT_TABLE} c "
            "WHERE c.id=OLD.client_id AND c.privacy_erasure_started_at IS NOT NULL) "
            "THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='IgMemoryHead delete requires privacy fence'; END IF; END"
        )
        for name, table in (
            ("ig_anres_priv_delete", RESULT_TABLE),
            ("ig_anprop_priv_delete", PROPOSAL_TABLE),
            ("ig_mat_priv_delete", MATERIALITY_TABLE),
            ("ig_anevt_priv_delete", ANALYSIS_EVENT_TABLE),
        ):
            schema_editor.execute(
                f"CREATE OR REPLACE TRIGGER {name} BEFORE DELETE ON {table} FOR EACH ROW "
                f"BEGIN IF NOT EXISTS (SELECT 1 FROM {CLIENT_TABLE} c WHERE c.id=OLD.client_id "
                "AND c.privacy_erasure_started_at IS NOT NULL) THEN SIGNAL SQLSTATE '45000' "
                "SET MESSAGE_TEXT='analysis delete requires privacy fence'; END IF; END"
            )
        for name, table in (
            ("ig_anprop_priv_insert", PROPOSAL_TABLE),
            ("ig_mat_priv_insert", MATERIALITY_TABLE),
            ("ig_anevt_priv_insert", ANALYSIS_EVENT_TABLE),
        ):
            schema_editor.execute(
                f"CREATE OR REPLACE TRIGGER {name} BEFORE INSERT ON {table} FOR EACH ROW "
                f"BEGIN IF NOT EXISTS (SELECT 1 FROM {CLIENT_TABLE} c WHERE c.id=NEW.client_id "
                "AND c.privacy_erasure_started_at IS NULL) THEN SIGNAL SQLSTATE '45000' "
                "SET MESSAGE_TEXT='analysis insert blocked by privacy fence'; END IF; END"
            )
        # Old unconditional guards remain active until all replacement guards
        # exist. A hard kill is fail-closed; resume retires them afterwards.
        for old_name in ("ig_anres_no_delete", "ig_anprop_no_delete", "ig_mat_no_delete"):
            schema_editor.execute(f"DROP TRIGGER IF EXISTS {old_name}")
    elif vendor == "sqlite":
        schema_editor.execute(
            f"CREATE TRIGGER IF NOT EXISTS ig_memfact_insert_guard BEFORE INSERT ON {FACT_TABLE} "
            f"WHEN {_sqlite_fact_invalid()} BEGIN SELECT RAISE(ABORT, 'IgMemoryFact insert guard'); END"
        )
        schema_editor.execute(
            f"CREATE TRIGGER IF NOT EXISTS ig_memfact_no_update BEFORE UPDATE ON {FACT_TABLE} "
            "BEGIN SELECT RAISE(ABORT, 'IgMemoryFact is append-only'); END"
        )
        schema_editor.execute(
            f"CREATE TRIGGER IF NOT EXISTS ig_memfact_priv_delete BEFORE DELETE ON {FACT_TABLE} "
            f"WHEN NOT EXISTS (SELECT 1 FROM {CLIENT_TABLE} c WHERE c.id=OLD.client_id "
            "AND c.privacy_erasure_started_at IS NOT NULL) BEGIN SELECT RAISE(ABORT, "
            "'IgMemoryFact delete requires privacy fence'); END"
        )
        sqlite_evidence_invalid = f"""(
            NEW.ordinal NOT BETWEEN 1 AND 40 OR NEW.message_id<=0
            OR NEW.source_role<>'user'
            OR NEW.claim_code NOT IN ('language','objection','deferred_intent')
            OR NEW.evidence_hmac NOT REGEXP '^[0-9a-f]{{64}}$'
            OR NEW.integrity_key_id NOT REGEXP '^[a-z0-9_.:+-]{{1,32}}$'
            OR NOT EXISTS (
                SELECT 1 FROM {FACT_TABLE} f JOIN {RESULT_TABLE} r ON r.id=f.source_result_id
                     JOIN {CLIENT_TABLE} c ON c.id=f.client_id
                WHERE f.id=NEW.fact_id AND NEW.ordinal<=f.expected_evidence_count
                  AND c.privacy_erasure_started_at IS NULL
                  AND NEW.claim_code=CASE f.fact_key
                    WHEN 'observed_language' THEN 'language'
                    WHEN 'objection_observed' THEN 'objection'
                    WHEN 'deferred_intent' THEN 'deferred_intent' END
                  AND (
                    (NEW.claim_code='language' AND EXISTS (
                        SELECT 1 FROM json_each(r.language_evidence_message_ids) language
                        WHERE language.type='integer' AND language.value=NEW.message_id
                    ))
                    OR (NEW.claim_code<>'language' AND EXISTS (
                        SELECT 1 FROM json_each(r.evidence_manifest) evidence
                        WHERE json_extract(evidence.value,'$.message_id')=NEW.message_id
                          AND json_extract(evidence.value,'$.source_role')='user'
                          AND EXISTS (
                              SELECT 1 FROM json_each(
                                  json_extract(evidence.value,'$.claim_codes')
                              ) claim WHERE claim.value=NEW.claim_code
                          )
                    ))
                  )
            )
        )"""
        schema_editor.execute(
            f"CREATE TRIGGER IF NOT EXISTS ig_memev_insert_guard BEFORE INSERT ON {EVIDENCE_TABLE} "
            f"WHEN {sqlite_evidence_invalid} BEGIN SELECT RAISE(ABORT, 'IgMemoryFactEvidence insert guard'); END"
        )
        schema_editor.execute(
            f"CREATE TRIGGER IF NOT EXISTS ig_memev_no_update BEFORE UPDATE ON {EVIDENCE_TABLE} "
            "BEGIN SELECT RAISE(ABORT, 'IgMemoryFactEvidence is append-only'); END"
        )
        schema_editor.execute(
            f"CREATE TRIGGER IF NOT EXISTS ig_memev_priv_delete BEFORE DELETE ON {EVIDENCE_TABLE} "
            f"WHEN NOT EXISTS (SELECT 1 FROM {FACT_TABLE} f JOIN {CLIENT_TABLE} c ON c.id=f.client_id "
            "WHERE f.id=OLD.fact_id AND c.privacy_erasure_started_at IS NOT NULL) "
            "BEGIN SELECT RAISE(ABORT, 'IgMemoryFactEvidence delete requires privacy fence'); END"
        )
        sqlite_head_match = f"""EXISTS (
            SELECT 1 FROM {FACT_TABLE} f JOIN {CLIENT_TABLE} c ON c.id=f.client_id
              LEFT JOIN {RESULT_TABLE} r ON r.id=f.source_result_id
              WHERE f.id=NEW.current_fact_id AND c.privacy_erasure_started_at IS NULL
              AND f.slot_key=NEW.slot_key AND f.client_id=NEW.client_id
              AND f.scope=NEW.scope AND f.fact_key=NEW.fact_key
              AND f.schema_version=NEW.schema_version
              AND f.commercial_episode_id IS NEW.commercial_episode_id
              AND f.line_id=NEW.line_id AND f.order_id IS NEW.order_id
              AND f.post_sale_case_id IS NEW.post_sale_case_id
              AND ((NEW.state='active' AND f.operation='assert')
                OR (NEW.state='invalidated' AND f.operation='invalidate')
                OR (NEW.state='expired' AND f.operation='expire'))
              AND (SELECT COUNT(*) FROM {EVIDENCE_TABLE} e WHERE e.fact_id=f.id)
                    = f.expected_evidence_count
              AND (
                f.operation<>'assert'
                OR (f.fact_key='observed_language'
                    AND f.expected_evidence_count=json_array_length(r.language_evidence_message_ids))
                OR (f.fact_key='objection_observed' AND f.expected_evidence_count=(
                    SELECT COUNT(*) FROM json_each(r.evidence_manifest) evidence
                    WHERE json_extract(evidence.value,'$.source_role')='user'
                      AND EXISTS (SELECT 1 FROM json_each(
                          json_extract(evidence.value,'$.claim_codes')
                      ) claim WHERE claim.value='objection')
                ))
                OR (f.fact_key='deferred_intent' AND f.expected_evidence_count=(
                    SELECT COUNT(*) FROM json_each(r.evidence_manifest) evidence
                    WHERE json_extract(evidence.value,'$.source_role')='user'
                      AND EXISTS (SELECT 1 FROM json_each(
                          json_extract(evidence.value,'$.claim_codes')
                      ) claim WHERE claim.value='deferred_intent')
                ))
              )
        )"""
        schema_editor.execute(
            f"CREATE TRIGGER IF NOT EXISTS ig_memhead_insert_guard BEFORE INSERT ON {HEAD_TABLE} "
            f"WHEN NEW.revision<>1 OR NEW.state<>'active' OR NEW.projection_policy_version<>'typed-memory-projector.v1' "
            "OR NEW.projection_hmac NOT REGEXP '^[0-9a-f]{64}$' "
            "OR NEW.integrity_key_id NOT REGEXP '^[a-z0-9_.:+-]{1,32}$' "
            f"OR NOT {sqlite_head_match} OR EXISTS (SELECT 1 FROM {FACT_TABLE} f "
            "WHERE f.id=NEW.current_fact_id AND f.supersedes_id IS NOT NULL) "
            "BEGIN SELECT RAISE(ABORT, 'IgMemoryHead insert guard'); END"
        )
        changed = " OR ".join(
            f"OLD.{field} IS NOT NEW.{field}" for field in (
                "slot_key", "client_id", "scope", "commercial_episode_id", "line_id",
                "order_id", "post_sale_case_id", "fact_key", "schema_version", "created_at",
            )
        )
        schema_editor.execute(
            f"CREATE TRIGGER IF NOT EXISTS ig_memhead_transition BEFORE UPDATE ON {HEAD_TABLE} "
            f"WHEN ({changed}) OR NEW.revision<>OLD.revision+1 OR NOT {sqlite_head_match} "
            "OR NEW.projection_policy_version<>'typed-memory-projector.v1' "
            "OR NEW.projection_hmac NOT REGEXP '^[0-9a-f]{64}$' "
            "OR NEW.integrity_key_id NOT REGEXP '^[a-z0-9_.:+-]{1,32}$' "
            "OR NEW.projected_at < OLD.projected_at "
            f"OR NOT EXISTS (SELECT 1 FROM {FACT_TABLE} f WHERE f.id=NEW.current_fact_id "
            "AND f.supersedes_id=OLD.current_fact_id) BEGIN SELECT RAISE(ABORT, "
            "'IgMemoryHead invalid transition'); END"
        )
        schema_editor.execute(
            f"CREATE TRIGGER IF NOT EXISTS ig_memhead_priv_delete BEFORE DELETE ON {HEAD_TABLE} "
            f"WHEN NOT EXISTS (SELECT 1 FROM {CLIENT_TABLE} c WHERE c.id=OLD.client_id "
            "AND c.privacy_erasure_started_at IS NOT NULL) BEGIN SELECT RAISE(ABORT, "
            "'IgMemoryHead delete requires privacy fence'); END"
        )
        for name, table in (
            ("ig_anres_priv_delete", RESULT_TABLE),
            ("ig_anprop_priv_delete", PROPOSAL_TABLE),
            ("ig_mat_priv_delete", MATERIALITY_TABLE),
            ("ig_anevt_priv_delete", ANALYSIS_EVENT_TABLE),
        ):
            schema_editor.execute(
                f"CREATE TRIGGER IF NOT EXISTS {name} BEFORE DELETE ON {table} "
                f"WHEN NOT EXISTS (SELECT 1 FROM {CLIENT_TABLE} c WHERE c.id=OLD.client_id "
                "AND c.privacy_erasure_started_at IS NOT NULL) BEGIN SELECT RAISE(ABORT, "
                "'analysis delete requires privacy fence'); END"
            )
        for name, table in (
            ("ig_anprop_priv_insert", PROPOSAL_TABLE),
            ("ig_mat_priv_insert", MATERIALITY_TABLE),
            ("ig_anevt_priv_insert", ANALYSIS_EVENT_TABLE),
        ):
            schema_editor.execute(
                f"CREATE TRIGGER IF NOT EXISTS {name} BEFORE INSERT ON {table} "
                f"WHEN NOT EXISTS (SELECT 1 FROM {CLIENT_TABLE} c WHERE c.id=NEW.client_id "
                "AND c.privacy_erasure_started_at IS NULL) BEGIN SELECT RAISE(ABORT, "
                "'analysis insert blocked by privacy fence'); END"
            )
        for old_name in ("ig_anres_no_delete", "ig_anprop_no_delete", "ig_mat_no_delete"):
            schema_editor.execute(f"DROP TRIGGER IF EXISTS {old_name}")
    else:
        raise RuntimeError("typed-memory triggers support MariaDB/SQLite")
    _validate_trigger_contract(schema_editor, trigger_names)


def _trigger_sql(schema_editor, name):
    if schema_editor.connection.vendor == "mysql":
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "SELECT ACTION_STATEMENT FROM information_schema.TRIGGERS "
                "WHERE TRIGGER_SCHEMA=DATABASE() AND TRIGGER_NAME=%s",
                [name],
            )
            rows = cursor.fetchall()
        return str(rows[0][0] or "") if len(rows) == 1 else ""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT sql FROM sqlite_master WHERE type='trigger' AND name=%s",
            [name],
        )
        rows = cursor.fetchall()
    return str(rows[0][0] or "") if len(rows) == 1 else ""


def _validate_trigger_contract(schema_editor, names):
    expected = {
        "ig_memfact_insert_guard": (FACT_TABLE, "BEFORE", "INSERT"),
        "ig_memfact_no_update": (FACT_TABLE, "BEFORE", "UPDATE"),
        "ig_memfact_priv_delete": (FACT_TABLE, "BEFORE", "DELETE"),
        "ig_memev_insert_guard": (EVIDENCE_TABLE, "BEFORE", "INSERT"),
        "ig_memev_no_update": (EVIDENCE_TABLE, "BEFORE", "UPDATE"),
        "ig_memev_priv_delete": (EVIDENCE_TABLE, "BEFORE", "DELETE"),
        "ig_memhead_insert_guard": (HEAD_TABLE, "BEFORE", "INSERT"),
        "ig_memhead_transition": (HEAD_TABLE, "BEFORE", "UPDATE"),
        "ig_memhead_priv_delete": (HEAD_TABLE, "BEFORE", "DELETE"),
        "ig_anres_priv_delete": (RESULT_TABLE, "BEFORE", "DELETE"),
        "ig_anprop_priv_delete": (PROPOSAL_TABLE, "BEFORE", "DELETE"),
        "ig_mat_priv_delete": (MATERIALITY_TABLE, "BEFORE", "DELETE"),
        "ig_anevt_priv_delete": (ANALYSIS_EVENT_TABLE, "BEFORE", "DELETE"),
        "ig_anprop_priv_insert": (PROPOSAL_TABLE, "BEFORE", "INSERT"),
        "ig_mat_priv_insert": (MATERIALITY_TABLE, "BEFORE", "INSERT"),
        "ig_anevt_priv_insert": (ANALYSIS_EVENT_TABLE, "BEFORE", "INSERT"),
    }
    for name in names:
        source = _trigger_sql(schema_editor, name)
        if not source:
            raise RuntimeError(f"typed-memory trigger missing: {name}")
        table_name, timing, event = expected[name]
        if schema_editor.connection.vendor == "mysql":
            with schema_editor.connection.cursor() as cursor:
                cursor.execute(
                    "SELECT EVENT_OBJECT_TABLE, ACTION_TIMING, EVENT_MANIPULATION "
                    "FROM information_schema.TRIGGERS WHERE TRIGGER_SCHEMA=DATABASE() "
                    "AND TRIGGER_NAME=%s",
                    [name],
                )
                metadata = cursor.fetchall()
            if tuple(metadata) != ((table_name, timing, event),):
                raise RuntimeError(f"typed-memory trigger metadata mismatch: {name}")
        else:
            normalized = re.sub(r"\s+", " ", source).upper()
            if (
                f"BEFORE {event} ON {table_name.upper()}" not in normalized
                or not normalized.startswith("CREATE TRIGGER")
            ):
                raise RuntimeError(f"typed-memory trigger metadata mismatch: {name}")
        if "priv_delete" in name or name in {
            "ig_anres_priv_delete", "ig_anprop_priv_delete", "ig_mat_priv_delete",
        }:
            if "privacy_erasure_started_at" not in source:
                raise RuntimeError(f"privacy fence missing from trigger: {name}")
    result_insert = _trigger_sql(schema_editor, "ig_anres_v22_insert_guard")
    if "analysis-v2.2" not in result_insert or "language" not in result_insert:
        raise RuntimeError("Analysis V2 v2.2 insert guard was not upgraded")
    for retired in (
        "ig_anres_insert_guard", "ig_anres_no_delete",
        "ig_anprop_no_delete", "ig_mat_no_delete",
    ):
        if _trigger_exists(schema_editor, retired):
            raise RuntimeError(f"retired trigger is still active: {retired}")


class Migration(migrations.Migration):
    atomic = False
    dependencies = [("management", "0184_assisted_checkout_generation_v2")]
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=STATE_OPERATIONS,
        ),
        migrations.RunPython(ensure_typed_memory_schema, reverse_code=None),
        migrations.RunPython(reinstall_analysis_v22_insert_guard, reverse_code=None),
        migrations.RunPython(
            install_typed_memory_and_privacy_triggers,
            reverse_code=None,
        ),
    ]
