# Generated by Django 6.1 on 2026-08-31 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0186_calibrated_gemini_quota_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='igcustomerturn',
            name='terminal_reason',
            field=models.CharField(blank=True, choices=[('replied', 'Відповідь доставлена'), ('no_reply_needed', 'Відповідь не потрібна'), ('send_unknown', 'Відправка невідома'), ('failed', 'Виконання не вдалося'), ('row_missing', 'Рядок ходу зник'), ('lease_expired', 'Lease застарів'), ('superseded', 'Витіснений новішим ходом')], db_index=True, default='', max_length=20),
        ),
    ]
