# Generated by Django 6.1 on 2026-08-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0187_ig_turn_terminal_reason'),
    ]

    def _drop_sqlite_guard_trigger(apps, schema_editor):
        """Дропнути тригер ig_anres_v22_insert_guard перед AddField на SQLite.
        
        Тригер посилається на management_instagrambotmessage. На SQLite ALTER TABLE
        ADD COLUMN перебудовує таблицю (створює нову, копіює, дропає стару), а
        тригер залишається живим і починає шукати таблицю main.management_… при
        першому INSERT у management_igconversationanalysisresult. На MariaDB ця
        проблема відсутня: ADD COLUMN не перебудовує таблицю.
        
        Після цієї міграції тригер лишається дропнутим на SQLite, але міграція
        `0185` виконується в production на MariaDB і там тригер створюється.
        """
        if schema_editor.connection.vendor != "sqlite":
            return
        schema_editor.execute("DROP TRIGGER IF EXISTS ig_anres_v22_insert_guard")

    operations = [
        migrations.RunPython(
            _drop_sqlite_guard_trigger,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
        migrations.AddField(
            model_name='instagrambotmessage',
            name='send_idempotency_key',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AddConstraint(
            model_name='instagrambotmessage',
            constraint=models.UniqueConstraint(fields=('send_idempotency_key',), name='mgmt_igmsg_send_intent_unique'),
        ),
    ]
