# Generated by Django 6.1 on 2026-08-31 21:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0188_ig_send_idempotency_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgAlertRateBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_key', models.CharField(max_length=64, unique=True)),
                ('window_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('used', models.PositiveIntegerField(default=0)),
                ('denied', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ліміт потоку алертів IG',
                'verbose_name_plural': 'Ліміти потоку алертів IG',
                'ordering': ['bucket_key'],
            },
        ),
    ]
