# Generated by Django 6.1 on 2026-09-02 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0189_ig_alert_rate_bucket'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgFunnelNodeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_key', models.CharField(max_length=190, unique=True)),
                ('branch_type', models.CharField(choices=[('main', 'Основна гілка'), ('repeat', 'Повторна покупка'), ('gift', 'Подарунок отримувачу'), ('exchange', 'Обмін або повернення')], db_index=True, default='main', max_length=16)),
                ('line_id', models.CharField(blank=True, default='', max_length=96)),
                ('recipient_id', models.CharField(blank=True, default='', max_length=96)),
                ('definition_key', models.CharField(db_index=True, max_length=96)),
                ('definition_version', models.CharField(default='', max_length=32)),
                ('status', models.CharField(choices=[('open', 'Відкритий'), ('complete', 'Закритий'), ('partial', 'Частково закритий'), ('skipped', 'Пропущений із причиною'), ('not_applicable', 'Не застосовується'), ('invalidated', 'Знецінений зміною іншого вузла'), ('superseded', 'Витіснений новим значенням')], db_index=True, default='open', max_length=24)),
                ('reason_code', models.CharField(blank=True, default='', max_length=48)),
                ('reason_detail', models.CharField(blank=True, default='', max_length=200)),
                ('invalidated_by_definition_key', models.CharField(blank=True, default='', max_length=96)),
                ('typed_value', models.JSONField(blank=True, default=dict)),
                ('previous_typed_value', models.JSONField(blank=True, default=dict)),
                ('evidence_message_ids', models.JSONField(blank=True, default=list)),
                ('closure_method', models.CharField(blank=True, default='', max_length=32)),
                ('projector_version', models.CharField(blank=True, default='', max_length=32)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('confirm_after', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='funnel_node_states', to='management.igclient')),
                ('commercial_episode', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funnel_node_states', to='management.igcommercialepisode')),
                ('superseded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='management.igfunnelnodestate')),
            ],
            options={
                'verbose_name': 'Стан вузла воронки IG',
                'verbose_name_plural': 'Стани вузлів воронки IG',
                'ordering': ['definition_key', 'id'],
                'indexes': [models.Index(fields=['client', 'commercial_episode', 'definition_key'], name='ig_fnode_client_episode'), models.Index(fields=['status', '-updated_at'], name='ig_fnode_status_dt'), models.Index(fields=['commercial_episode', 'branch_type', 'line_id'], name='ig_fnode_branch')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('status__in', ('skipped', 'not_applicable')), _negated=True), models.Q(('reason_code', ''), _negated=True), _connector='OR'), name='ig_fnode_reason_required')],
            },
        ),
    ]
