# Generated by Django 6.1 on 2026-09-07 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0194_igwebhookinboxevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgCustomerTurnRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveBigIntegerField()),
                ('active_slot', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('state', models.CharField(choices=[('collecting', 'Збирається'), ('preparing', 'Готується'), ('sealed', 'Зафіксовано'), ('claimed', 'Захоплено'), ('processed', 'Опрацьовано'), ('superseded', 'Витіснено'), ('overflow', 'Перевищено межі')], db_index=True, default='collecting', max_length=16)),
                ('quiet_started_at', models.DateTimeField()),
                ('quiet_deadline', models.DateTimeField(db_index=True)),
                ('quiet_cap_at', models.DateTimeField()),
                ('overall_deadline', models.DateTimeField(db_index=True)),
                ('media_prepare_deadline', models.DateTimeField(blank=True, null=True)),
                ('source_count', models.PositiveSmallIntegerField(default=0)),
                ('text_chars', models.PositiveIntegerField(default=0)),
                ('media_part_count', models.PositiveSmallIntegerField(default=0)),
                ('permission_epoch', models.PositiveBigIntegerField(default=0)),
                ('erasure_started_at_snapshot', models.DateTimeField(blank=True, null=True)),
                ('bundle_snapshot', models.JSONField(blank=True, default=dict)),
                ('snapshot_digest', models.CharField(blank=True, default='', max_length=64)),
                ('overflow', models.JSONField(blank=True, default=dict)),
                ('sealed_at', models.DateTimeField(blank=True, null=True)),
                ('claim_token', models.CharField(blank=True, default='', max_length=64)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('lease_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='turn_revisions', to='management.igclient')),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successors', to='management.igcustomerturnrevision')),
                ('turn', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='management.igcustomerturn')),
            ],
            options={
                'ordering': ['client_id', 'revision'],
            },
        ),
        migrations.CreateModel(
            name='IgTurnRevisionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveSmallIntegerField()),
                ('role', models.CharField(max_length=8)),
                ('source_namespace', models.CharField(blank=True, default='', max_length=128)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('synthetic_event_key', models.CharField(blank=True, default='', max_length=64)),
                ('text', models.TextField(blank=True, default='')),
                ('provider_created_at', models.DateTimeField(blank=True, null=True)),
                ('reply_to_provider_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('quick_reply_payload', models.CharField(blank=True, default='', max_length=1000)),
                ('referral', models.JSONField(blank=True, default=dict)),
                ('discovered_media', models.JSONField(blank=True, default=list)),
                ('text_chars', models.PositiveIntegerField(default=0)),
                ('media_part_count', models.PositiveSmallIntegerField(default=0)),
                ('source_digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('message', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='revision_sources', to='management.instagrambotmessage')),
                ('revision', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='management.igcustomerturnrevision')),
            ],
            options={
                'ordering': ['revision_id', 'ordinal', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='igcustomerturnrevision',
            index=models.Index(fields=['state', 'quiet_deadline', 'id'], name='ig_turn_rev_due'),
        ),
        migrations.AddIndex(
            model_name='igcustomerturnrevision',
            index=models.Index(fields=['client', 'active_slot', 'revision'], name='ig_turn_rev_client_head'),
        ),
        migrations.AddConstraint(
            model_name='igcustomerturnrevision',
            constraint=models.UniqueConstraint(fields=('client', 'revision'), name='ig_turn_rev_client_num'),
        ),
        migrations.AddConstraint(
            model_name='igcustomerturnrevision',
            constraint=models.UniqueConstraint(fields=('client', 'active_slot'), name='ig_turn_rev_active_head'),
        ),
        migrations.AddConstraint(
            model_name='igcustomerturnrevision',
            constraint=models.CheckConstraint(condition=models.Q(('active_slot__isnull', True), ('active_slot', 1), _connector='OR'), name='ig_turn_rev_active_slot'),
        ),
        migrations.AddIndex(
            model_name='igturnrevisionsource',
            index=models.Index(fields=['message', 'revision'], name='ig_turn_rev_source_lookup'),
        ),
        migrations.AddConstraint(
            model_name='igturnrevisionsource',
            constraint=models.UniqueConstraint(fields=('revision', 'ordinal'), name='ig_turn_rev_source_ord'),
        ),
        migrations.AddConstraint(
            model_name='igturnrevisionsource',
            constraint=models.UniqueConstraint(fields=('revision', 'message'), name='ig_turn_rev_source_msg'),
        ),
    ]
