# Generated by Django 6.1 on 2026-09-07 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0196_bot_policy_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgRevisionDeliveryEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_key', models.CharField(max_length=160, unique=True)),
                ('actor', models.CharField(default='bot', max_length=16)),
                ('purpose', models.CharField(default='normal_reply', max_length=32)),
                ('group', models.CharField(max_length=32)),
                ('kind', models.CharField(max_length=32)),
                ('order_index', models.PositiveSmallIntegerField()),
                ('part_index', models.PositiveSmallIntegerField()),
                ('part_count', models.PositiveSmallIntegerField()),
                ('plan_digest', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('payload_digest', models.CharField(max_length=64)),
                ('activation_group', models.CharField(blank=True, default='', max_length=32)),
                ('activation_part_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('activation_failure_code', models.CharField(blank=True, default='', max_length=64)),
                ('recipient_igsid', models.CharField(max_length=64)),
                ('provider_namespace', models.CharField(max_length=128)),
                ('generation_request_id', models.CharField(blank=True, default='', max_length=40)),
                ('generation_model', models.CharField(blank=True, default='', max_length=80)),
                ('settings_id_snapshot', models.PositiveIntegerField()),
                ('settings_permission_epoch', models.PositiveBigIntegerField()),
                ('client_permission_epoch', models.PositiveBigIntegerField()),
                ('revision_snapshot_digest', models.CharField(max_length=64)),
                ('publication_id', models.PositiveBigIntegerField()),
                ('publication_version', models.PositiveBigIntegerField()),
                ('publication_hash', models.CharField(max_length=64)),
                ('authority_context_digest', models.CharField(max_length=64)),
                ('fact_bindings', models.JSONField(blank=True, default=list)),
                ('offer_bindings', models.JSONField(blank=True, default=list)),
                ('state', models.CharField(choices=[('planned', 'Заплановано'), ('claimed', 'Захоплено'), ('provider_started', 'Запит почато'), ('sent', 'Надіслано'), ('definite_failed', 'Підтверджена відмова'), ('unknown', 'Результат невідомий'), ('cancelled', 'Скасовано'), ('superseded', 'Витіснено')], db_index=True, default='planned', max_length=20)),
                ('claim_token', models.CharField(blank=True, default='', max_length=64)),
                ('lease_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('provider_started_at', models.DateTimeField(blank=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('provider_http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('provider_response_digest', models.CharField(blank=True, default='', max_length=64)),
                ('failure_code', models.CharField(blank=True, default='', max_length=64)),
                ('terminal_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_effects', to='management.igcustomerturnrevision')),
                ('source_message', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='revision_delivery_effects', to='management.instagrambotmessage')),
            ],
            options={
                'ordering': ['revision_id', 'order_index', 'id'],
                'indexes': [models.Index(fields=['revision', 'group', 'state', 'part_index'], name='ig_rev_effect_group_state'), models.Index(fields=['state', 'lease_until', 'id'], name='ig_rev_effect_due')],
                'constraints': [models.UniqueConstraint(fields=('revision', 'order_index'), name='ig_rev_effect_order'), models.UniqueConstraint(fields=('revision', 'group', 'part_index'), name='ig_rev_effect_group_part'), models.CheckConstraint(condition=models.Q(('part_count__gte', 1)), name='ig_rev_effect_part_count'), models.CheckConstraint(condition=models.Q(('part_index__lt', models.F('part_count'))), name='ig_rev_effect_part_index')],
            },
        ),
    ]
