# Generated by Django 6.1 on 2026-09-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0197_ig_revision_delivery_effect"),
    ]

    operations = [
        migrations.AddField(
            model_name="igcustomerturnrevision",
            name="generation_proposal",
            field=models.JSONField(blank=True, db_default={}, default=dict),
        ),
        migrations.AddField(
            model_name="igcustomerturnrevision",
            name="generation_proposal_digest",
            field=models.CharField(blank=True, db_default="", default="", max_length=64),
        ),
        migrations.AddField(
            model_name="igcustomerturnrevision",
            name="generation_proposed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="igcustomerturnrevision",
            name="action_receipts",
            field=models.JSONField(blank=True, db_default={}, default=dict),
        ),
        migrations.AddField(
            model_name="igcustomerturnrevision",
            name="origin",
            field=models.CharField(
                choices=[("inbound", "Вхідний хід"), ("auto_refresh", "Автоматичне оновлення")],
                db_default="inbound",
                db_index=True,
                default="inbound",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="igcustomerturnrevision",
            name="successor_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Не наступник"),
                    ("publication_changed", "Публікація змінилася"),
                    ("public_policy_inputs_stale", "Публічні правила змінилися"),
                    ("fact_binding_stale", "Факти змінилися"),
                ],
                db_default="",
                default="",
                max_length=32,
            ),
        ),
    ]
