# Generated by Django 6.1 on 2026-09-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0198_revision_generation_proposal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botdatadeletionrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Completed"),
                    ("no_match", "No matching records"),
                    ("received", "Received"),
                    ("erasing", "Erasing"),
                    ("pending_verification", "Pending ownership verification"),
                ],
                default="received",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="botdatadeletionrequest",
            name="erasure_lease_token",
            field=models.CharField(blank=True, db_default="", default="", max_length=64),
        ),
        migrations.AddField(
            model_name="botdatadeletionrequest",
            name="erasure_lease_until",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="botdatadeletionrequest",
            name="erasure_target_client_ids",
            field=models.JSONField(blank=True, db_default=[], default=list),
        ),
        migrations.AddField(
            model_name="botdatadeletionrequest",
            name="erasure_target_message_ids",
            field=models.JSONField(blank=True, db_default=[], default=list),
        ),
        migrations.AddField(
            model_name="botdatadeletionrequest",
            name="erasure_target_sender_ids",
            field=models.JSONField(blank=True, db_default=[], default=list),
        ),
        migrations.AddField(
            model_name="botdatadeletionrequest",
            name="erasure_target_inbox_ids",
            field=models.JSONField(blank=True, db_default=[], default=list),
        ),
        migrations.AddField(
            model_name="botdatadeletionrequest",
            name="erasure_cutoff_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="botdatadeletionrequest",
            name="erasure_actor_label",
            field=models.CharField(blank=True, db_default="", default="", max_length=150),
        ),
        migrations.AddIndex(
            model_name="botdatadeletionrequest",
            index=models.Index(fields=["status", "erasure_lease_until"], name="bot_del_lease_idx"),
        ),
    ]
