# Generated by Django 5.2.11 on 2026-07-14 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0001_initial'),
        ('productcolors', '0007_normalize_slugs'),
        ('storefront', '0083_useraction_unique_order_action'),
        ('warehouse', '0011_alter_stockmovement_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GarmentFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('axes', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name', 'code'),
            },
        ),
        migrations.CreateModel(
            name='CoverSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('upload', 'Завантажено окремо'), ('color_image', 'З фото кольору'), ('product_image', 'З галереї товару')], default='upload', max_length=20)),
                ('source_missing', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color_image', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='productcolors.productcolorimage')),
                ('product', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='product_catalog_cover', to='storefront.product')),
                ('product_image', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='storefront.productimage')),
            ],
        ),
        migrations.CreateModel(
            name='GarmentFlowCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='product_catalog_flow_links', to='storefront.category')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_links', to='product_catalog.garmentflow')),
            ],
        ),
        migrations.AddField(
            model_name='garmentflow',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='product_catalog_flows', through='product_catalog.GarmentFlowCategory', to='storefront.category'),
        ),
        migrations.CreateModel(
            name='ProductEditorState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='product_catalog_editor_state', to='storefront.product')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_catalog_product_edits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImageAltI18n',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('uk', 'Українська'), ('ru', 'Російська'), ('en', 'English')], max_length=2)),
                ('alt', models.CharField(blank=True, default='', max_length=220)),
                ('product_image', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='product_catalog_alts', to='storefront.productimage')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOptionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_key', models.CharField(max_length=160)),
                ('option_values', models.JSONField(blank=True, default=dict)),
                ('price_delta', models.IntegerField(default=0)),
                ('price_delta_reason', models.CharField(blank=True, default='', max_length=255)),
                ('youtube_url', models.URLField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='product_catalog_option_profiles', to='storefront.product')),
            ],
            options={
                'ordering': ('product_id', 'option_key'),
            },
        ),
        migrations.CreateModel(
            name='ProductOptionProfileI18n',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('uk', 'Українська'), ('ru', 'Російська'), ('en', 'English')], max_length=2)),
                ('display_name', models.CharField(blank=True, default='', max_length=220)),
                ('short_description', models.TextField(blank=True, default='')),
                ('full_description', models.TextField(blank=True, default='')),
                ('marketing_text', models.TextField(blank=True, default='')),
                ('seo_title', models.CharField(blank=True, default='', max_length=180)),
                ('seo_description', models.CharField(blank=True, default='', max_length=320)),
                ('seo_keywords', models.CharField(blank=True, default='', max_length=300)),
                ('og_title', models.CharField(blank=True, default='', max_length=180)),
                ('og_description', models.CharField(blank=True, default='', max_length=320)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='i18n', to='product_catalog.productoptionprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOptionSizeGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_key', models.CharField(max_length=160)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='product_catalog_size_grid_assignments', to='storefront.product')),
                ('size_grid', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='product_catalog_product_assignments', to='storefront.sizegrid')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrintLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('print_ref', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_catalog_product_links', to='warehouse.print')),
                ('product', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='product_catalog_print_link', to='storefront.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrintCompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combination_key', models.CharField(max_length=240)),
                ('is_allowed', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility', to='product_catalog.productprintlink')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSizeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_key', models.CharField(max_length=160)),
                ('size', models.CharField(max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='product_catalog_size_rules', to='storefront.product')),
            ],
            options={
                'ordering': ('product_id', 'option_key', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SizeGridProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garment_code', models.SlugField(blank=True, default='')),
                ('option_key', models.CharField(blank=True, default='', max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('size_grid', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='product_catalog_profile', to='storefront.sizegrid')),
            ],
        ),
        migrations.CreateModel(
            name='VariantCombinationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combination_key', models.CharField(max_length=240)),
                ('option_values', models.JSONField(blank=True, default=dict)),
                ('price_delta', models.IntegerField(default=0)),
                ('price_delta_reason', models.CharField(blank=True, default='', max_length=255)),
                ('youtube_url', models.URLField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='product_catalog_combinations', to='productcolors.productcolorvariant')),
            ],
            options={
                'ordering': ('variant_id', 'combination_key'),
            },
        ),
        migrations.CreateModel(
            name='VariantCombinationProfileI18n',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('uk', 'Українська'), ('ru', 'Російська'), ('en', 'English')], max_length=2)),
                ('display_name', models.CharField(blank=True, default='', max_length=220)),
                ('short_description', models.TextField(blank=True, default='')),
                ('full_description', models.TextField(blank=True, default='')),
                ('marketing_text', models.TextField(blank=True, default='')),
                ('seo_title', models.CharField(blank=True, default='', max_length=180)),
                ('seo_description', models.CharField(blank=True, default='', max_length=320)),
                ('seo_keywords', models.CharField(blank=True, default='', max_length=300)),
                ('og_title', models.CharField(blank=True, default='', max_length=180)),
                ('og_description', models.CharField(blank=True, default='', max_length=320)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='i18n', to='product_catalog.variantcombinationprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VariantDetailsI18n',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('uk', 'Українська'), ('ru', 'Російська'), ('en', 'English')], max_length=2)),
                ('display_name', models.CharField(blank=True, default='', max_length=220)),
                ('short_description', models.TextField(blank=True, default='')),
                ('full_description', models.TextField(blank=True, default='')),
                ('marketing_text', models.TextField(blank=True, default='')),
                ('seo_title', models.CharField(blank=True, default='', max_length=180)),
                ('seo_description', models.CharField(blank=True, default='', max_length=320)),
                ('seo_keywords', models.CharField(blank=True, default='', max_length=300)),
                ('og_title', models.CharField(blank=True, default='', max_length=180)),
                ('og_description', models.CharField(blank=True, default='', max_length=320)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='i18n', to='product_catalog.variantdetails')),
            ],
            options={
                'verbose_name': 'Каталог: локалізація кольору',
                'verbose_name_plural': 'Каталог: локалізації кольорів',
            },
        ),
        migrations.CreateModel(
            name='VariantImageAltI18n',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('uk', 'Українська'), ('ru', 'Російська'), ('en', 'English')], max_length=2)),
                ('alt', models.CharField(blank=True, default='', max_length=220)),
                ('color_image', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='product_catalog_alts', to='productcolors.productcolorimage')),
            ],
        ),
        migrations.CreateModel(
            name='EditorDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_key', models.CharField(default='default', max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('product_revision', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_catalog_editor_drafts', to='storefront.product')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='product_catalog_editor_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'draft_key'), name='product_catalog_unique_user_draft_key')],
            },
        ),
        migrations.AddConstraint(
            model_name='garmentflowcategory',
            constraint=models.UniqueConstraint(fields=('flow', 'category'), name='product_catalog_unique_flow_category'),
        ),
        migrations.AddConstraint(
            model_name='productimagealti18n',
            constraint=models.UniqueConstraint(fields=('product_image', 'lang'), name='product_catalog_unique_product_image_alt_lang'),
        ),
        migrations.AddConstraint(
            model_name='productoptionprofile',
            constraint=models.UniqueConstraint(fields=('product', 'option_key'), name='product_catalog_unique_product_option'),
        ),
        migrations.AddConstraint(
            model_name='productoptionprofilei18n',
            constraint=models.UniqueConstraint(fields=('profile', 'lang'), name='product_catalog_unique_product_option_lang'),
        ),
        migrations.AddConstraint(
            model_name='productoptionsizegrid',
            constraint=models.UniqueConstraint(fields=('product', 'option_key'), name='product_catalog_unique_product_option_grid'),
        ),
        migrations.AddConstraint(
            model_name='productprintcompatibility',
            constraint=models.UniqueConstraint(fields=('link', 'combination_key'), name='product_catalog_unique_print_link_combo'),
        ),
        migrations.AddConstraint(
            model_name='productsizerule',
            constraint=models.UniqueConstraint(fields=('product', 'option_key', 'size'), name='product_catalog_unique_product_option_size'),
        ),
        migrations.AddConstraint(
            model_name='variantcombinationprofile',
            constraint=models.UniqueConstraint(fields=('variant', 'combination_key'), name='product_catalog_unique_variant_combination'),
        ),
        migrations.AddConstraint(
            model_name='variantcombinationprofilei18n',
            constraint=models.UniqueConstraint(fields=('profile', 'lang'), name='product_catalog_unique_variant_combo_lang'),
        ),
        migrations.AddConstraint(
            model_name='variantdetailsi18n',
            constraint=models.UniqueConstraint(fields=('details', 'lang'), name='product_catalog_unique_variant_details_lang'),
        ),
        migrations.AddConstraint(
            model_name='variantimagealti18n',
            constraint=models.UniqueConstraint(fields=('color_image', 'lang'), name='product_catalog_unique_color_image_alt_lang'),
        ),
    ]
