# Generated by Django 5.2.11 on 2026-07-14 15:36

from django.db import migrations


FLOW_DEFINITIONS = {
    "tshirt": {
        "name": "Футболка",
        "category_slugs": ("tshirts", "t-shirt", "futbolky", "futbolka"),
        "axes": [
            {
                "code": "fit",
                "label": "Посадка",
                "options": [
                    {"code": "classic", "label": "Класична"},
                    {"code": "oversize", "label": "Оверсайз"},
                ],
            }
        ],
    },
    "hoodie": {
        "name": "Худі",
        "category_slugs": ("hoodie", "hoodies", "hudi", "khudi"),
        "axes": [
            {
                "code": "lining",
                "label": "Утеплення",
                "options": [
                    {"code": "fleece", "label": "Фліс"},
                    {"code": "no_fleece", "label": "Без флісу", "disabled": True},
                ],
            }
        ],
    },
    "longsleeve": {
        "name": "Лонгслів",
        "category_slugs": ("long-sleeve", "longsleeve", "longsleeves", "longsliv"),
        "axes": [
            {
                "code": "fit",
                "label": "Посадка",
                "options": [
                    {"code": "classic", "label": "Класична"},
                ],
            }
        ],
    },
}


def seed_v2_defaults(apps, schema_editor):
    GarmentFlow = apps.get_model("product_catalog", "GarmentFlow")
    GarmentFlowCategory = apps.get_model("product_catalog", "GarmentFlowCategory")
    VariantDetails = apps.get_model("product_catalog", "VariantDetails")
    VariantDetailsI18n = apps.get_model("product_catalog", "VariantDetailsI18n")
    Category = apps.get_model("storefront", "Category")

    for code, definition in FLOW_DEFINITIONS.items():
        flow, _ = GarmentFlow.objects.update_or_create(
            code=code,
            defaults={
                "name": definition["name"],
                "axes": definition["axes"],
                "is_active": True,
            },
        )
        for category_id in Category.objects.filter(
            slug__in=definition["category_slugs"]
        ).values_list("id", flat=True):
            GarmentFlowCategory.objects.get_or_create(
                flow_id=flow.id,
                category_id=category_id,
            )

    for details in VariantDetails.objects.all().iterator():
        defaults = {
            "display_name": details.display_name or "",
            "seo_title": details.seo_title or "",
            "seo_description": details.seo_description or "",
            "seo_keywords": details.seo_keywords or "",
            "marketing_text": details.marketing_html or "",
        }
        if any(defaults.values()):
            VariantDetailsI18n.objects.get_or_create(
                details_id=details.id,
                lang="uk",
                defaults=defaults,
            )


def reverse_noop(apps, schema_editor):
    # Seeded rows can be edited in production; never delete operator data on rollback.
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0002_variant_editor_v2'),
    ]

    operations = [
        migrations.RunPython(seed_v2_defaults, reverse_noop),
    ]
