# Generated by Django 5.2.11 on 2026-07-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0003_seed_garment_flows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoptionprofile',
            name='price_delta',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='variantcombinationprofile',
            name='price_delta',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
