# Generated by Django 5.2.11 on 2026-07-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_catalog", "0004_nullable_sparse_price_overrides"),
    ]

    operations = [
        migrations.CreateModel(
            name="VariantOptionSizeGrid",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("option_key", models.CharField(max_length=160)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("size_grid", models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name="product_catalog_variant_assignments", to="storefront.sizegrid")),
                ("variant", models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name="product_catalog_size_grid_assignments", to="productcolors.productcolorvariant")),
            ],
        ),
        migrations.CreateModel(
            name="VariantBlankLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("option_key", models.CharField(max_length=160)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("storage_subcategory", models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name="product_catalog_variant_links", to="warehouse.storagesubcategory")),
                ("variant", models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name="product_catalog_blank_links", to="productcolors.productcolorvariant")),
            ],
        ),
        migrations.AddConstraint(
            model_name="variantoptionsizegrid",
            constraint=models.UniqueConstraint(fields=("variant", "option_key"), name="product_catalog_unique_variant_option_grid"),
        ),
        migrations.AddConstraint(
            model_name="variantblanklink",
            constraint=models.UniqueConstraint(fields=("variant", "option_key"), name="product_catalog_unique_variant_blank_link"),
        ),
    ]
