# Generated by Django 5.2.11 on 2026-07-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_catalog", "0006_seed_hoodie_lining_profiles"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductOptionAxisPresentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("axis_code", models.SlugField(max_length=50)),
                (
                    "presentation",
                    models.CharField(
                        choices=[
                            ("auto", "Автоматично"),
                            ("switch", "Компактний switch"),
                            ("cards", "Картки"),
                        ],
                        default="auto",
                        max_length=12,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_catalog_axis_presentations",
                        to="storefront.product",
                    ),
                ),
            ],
            options={
                "ordering": ("product_id", "axis_code"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "axis_code"),
                        name="product_catalog_unique_product_axis_presentation",
                    )
                ],
            },
        ),
    ]
