"""SEO Audit 2026-05-15 (Part 6) — refresh stale auto-generated FAQs.

The Phase-13 ``autofill_product_seo`` command wrote five universal
FAQs per product where Q3/Q4/Q5 ("Скільки триває доставка?", "Як
повернути або обміняти товар?", "Чи можна замовити з власним
принтом?") were *byte-identical* across all 65 PDPs. Google clusters
FAQ rich-result candidates by question string and surfaces a rich
result for at most one URL per cluster, so 65 PDPs effectively
competed for one rich-result slot.

The current ``UNIVERSAL_FAQS`` template keeps only product-context
questions. Delivery policy remains untouched here because its canonical
owner is the dedicated delivery page and legacy rows require a separate,
guarded cleanup.

This command finds auto-generated FAQs that still match the old
universal phrasing and rewrites them in place. It deliberately
*never* touches FAQs whose question string does not match the
legacy template, so any human-written FAQ added later through the
admin remains untouched.

Usage:
    python manage.py refresh_product_faqs              # apply
    python manage.py refresh_product_faqs --dry-run    # preview
    python manage.py refresh_product_faqs --slug XYZ   # single product
"""
from __future__ import annotations

from django.core.management.base import BaseCommand

from storefront.models import Product, ProductFAQ
from storefront.services.product_seo_autofill import _build_faqs


# Legacy question strings emitted by the pre-Audit 2026-05-15 template.
# Matched verbatim — if any other text appears we leave the FAQ alone.
LEGACY_QUESTION_PREFIXES = (
    "Як обрати розмір ",
    "Чи можна прати ",
    "Скільки триває доставка",
    "Як повернути або обміняти товар",
    "Чи можна замовити з власним принтом",
)

RETIRED_DELIVERY_QUESTION_PREFIX = "Скільки триває доставка"


def _is_legacy_question(text: str) -> bool:
    if not text:
        return False
    text = text.strip()
    return any(text.startswith(prefix) for prefix in LEGACY_QUESTION_PREFIXES)


def _topic_for_legacy_question(text: str) -> str | None:
    """Classify the legacy question without relying on its stored position."""
    text = (text or "").strip()
    if text.startswith("Як обрати розмір "):
        return "size"
    if text.startswith("Чи можна прати "):
        return "care"
    if text.startswith(RETIRED_DELIVERY_QUESTION_PREFIX):
        return "delivery"
    if text.startswith("Як повернути або обміняти товар"):
        return "returns"
    if text.startswith("Чи можна замовити з власним принтом"):
        return "custom"
    return None


def _generated_faqs_by_topic(product) -> dict[str, tuple[str, str]]:
    size, care, returns, custom = _build_faqs(product)
    return {
        "size": size,
        "care": care,
        "returns": returns,
        "custom": custom,
    }


class Command(BaseCommand):
    help = (
        "Replace legacy universal FAQ questions with title-anchored "
        "variants generated by the new product_seo_autofill template."
    )

    def add_arguments(self, parser):
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help="Preview changes without writing.",
        )
        parser.add_argument(
            "--slug",
            action="append",
            default=[],
            help="Limit to specific slug(s). Can be repeated.",
        )
        parser.add_argument(
            "--include-drafts",
            action="store_true",
            help="Process drafts and archived products too.",
        )

    def handle(self, *args, **opts):
        qs = Product.objects.all().select_related("category").order_by("id")
        if not opts["include_drafts"]:
            qs = qs.filter(status="published")
        if opts["slug"]:
            qs = qs.filter(slug__in=opts["slug"])

        dry = opts["dry_run"]
        total = qs.count()
        self.stdout.write(self.style.NOTICE(
            f"Refreshing FAQs on {total} product(s){' (DRY-RUN)' if dry else ''}…"
        ))

        products_touched: set[int] = set()
        faqs_rewritten = 0

        for product in qs:
            new_faqs_by_topic = _generated_faqs_by_topic(product)
            existing = list(product.faqs.all().order_by("order", "id"))

            for faq in existing:
                topic = _topic_for_legacy_question(faq.question)
                if topic in (None, "delivery"):
                    continue
                new_q, new_a = new_faqs_by_topic[topic]
                if faq.question == new_q and faq.answer == new_a:
                    continue
                if not dry:
                    faq.question = new_q
                    faq.answer = new_a
                    faq.save(update_fields=["question", "answer", "updated_at"])
                faqs_rewritten += 1
                products_touched.add(product.pk)

        self.stdout.write(self.style.SUCCESS(
            f"\nProducts touched: {len(products_touched)}"
            f"\nFAQs rewritten:   {faqs_rewritten}"
        ))
        if dry:
            self.stdout.write(self.style.WARNING(
                "Dry-run: no changes saved."
            ))
