# Generated by Django 5.2.6 on 2026-01-31 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DtfLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_number', models.CharField(blank=True, max_length=24, unique=True)),
                ('lead_type', models.CharField(choices=[('help', 'Потрібна допомога'), ('consultation', 'Консультація'), ('fab', 'Заявка з кнопки')], default='help', max_length=20)),
                ('status', models.CharField(choices=[('new', 'Нова'), ('in_progress', 'В роботі'), ('closed', 'Закрита')], default='new', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(db_index=True, max_length=32)),
                ('contact_channel', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('call', 'Телефонний дзвінок')], default='telegram', max_length=20)),
                ('contact_handle', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('np_branch', models.CharField(blank=True, max_length=200)),
                ('task_description', models.TextField(blank=True)),
                ('deadline_note', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(blank=True, default='', max_length=50)),
                ('manager_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DTF Lead',
                'verbose_name_plural': 'DTF Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DtfOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=24, unique=True)),
                ('order_type', models.CharField(choices=[('ready', 'Готовий ганг-лист'), ('help', 'Потрібна допомога')], default='ready', max_length=20)),
                ('status', models.CharField(choices=[('new_lead', 'Принято (заявка)'), ('new_order', 'Принято'), ('check_mockup', 'Проверка макета'), ('need_fix', 'Нужны правки'), ('awaiting_payment', 'Ожидает оплаты'), ('printing', 'В печати'), ('ready', 'Готово'), ('shipped', 'Отправлено'), ('closed', 'Закрыто')], default='check_mockup', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(db_index=True, max_length=32)),
                ('contact_channel', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('call', 'Телефонний дзвінок')], default='telegram', max_length=20)),
                ('contact_handle', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('np_branch', models.CharField(max_length=200)),
                ('gang_file', models.FileField(blank=True, upload_to='dtf/orders/')),
                ('length_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('length_source', models.CharField(choices=[('manual', 'Ручной ввод'), ('auto', 'Автоопределение')], default='manual', max_length=10)),
                ('copies', models.PositiveIntegerField(default=1)),
                ('meters_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_meter', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pricing_tier', models.CharField(blank=True, max_length=50)),
                ('requires_review', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('need_fix_reason', models.CharField(blank=True, max_length=255)),
                ('tracking_number', models.CharField(blank=True, max_length=64)),
                ('manager_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DTF Order',
                'verbose_name_plural': 'DTF Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DtfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('macro', 'Макро'), ('process', 'Процесс'), ('final', 'Готовое изделие')], default='final', max_length=20)),
                ('image', models.ImageField(upload_to='dtf/works/')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'DTF Work',
                'verbose_name_plural': 'DTF Works',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DtfLeadAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dtf/leads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dtf.dtflead')),
            ],
            options={
                'verbose_name': 'DTF Lead Attachment',
                'verbose_name_plural': 'DTF Lead Attachments',
            },
        ),
    ]
