# Generated by Django 5.2.6 on 2026-01-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtflead',
            name='folder_link',
            field=models.URLField(blank=True),
        ),
    ]
