# Generated by Django 5.2.11 on 2026-02-07

from django.db import migrations, models


def seed_knowledge_posts(apps, schema_editor):
    KnowledgePost = apps.get_model("dtf", "KnowledgePost")
    posts = [
        {
            "title": "Як підготувати файл для DTF-друку без браку",
            "slug": "yak-pidhotuvaty-fail-dlia-dtf-druku",
            "excerpt": "Чекліст підготовки макета: DPI, ширина, прозорість, лінії та експорт.",
            "content_md": """## Короткий чекліст

- Рекомендовано **300 DPI**
- Ширина ганг-листа: **60 см**
- Фон: **прозорий**
- Тонкі елементи перевірити у масштабі 100%

Перед запуском у друк перевірте [вимоги до файлів](/requirements/) та зробіть тестовий фрагмент.
""",
            "pub_date": "2026-01-10",
        },
        {
            "title": "DTF vs DTG: що краще для мерчу у 2026",
            "slug": "dtf-vs-dtg-shcho-krashche-dlia-merchu-2026",
            "excerpt": "Порівняння технологій DTF та DTG: швидкість, собівартість, гнучкість та ризики.",
            "content_md": """## DTF vs DTG

Для коротких і середніх серій DTF зазвичай виграє за гнучкістю та швидкістю.
DTG може бути доречним для дуже специфічних тканин і дрібних запусків.

Якщо важлива прогнозованість, варто почати з DTF і пройти [preflight](/preflight/).
""",
            "pub_date": "2026-02-12",
        },
        {
            "title": "Тренди мерчу 2026: що реально продається",
            "slug": "trendy-merchu-2026-shcho-realno-prodaietsia",
            "excerpt": "Кольори, матеріали та принти, які отримують найкращу реакцію аудиторії.",
            "content_md": """## Що в тренді

1. Контрастні неонові акценти
2. Локальні мікроколекції
3. Точні технічні написи та minimalist-графіка

Перед друком перевіряйте читабельність дрібних деталей на реальній тканині.
""",
            "pub_date": "2026-03-15",
        },
        {
            "title": "Чому DTF часто вигідніше за шовкографію",
            "slug": "chomu-dtf-vyhidnishe-za-shovkohrafiiu",
            "excerpt": "Де DTF економить час і гроші, а де шовкографія все ще має сенс.",
            "content_md": """## Коли DTF вигідніше

- Часті зміни дизайну
- Невеликі та середні тиражі
- Висока деталізація без складної підготовки форм

Для стабільного результату використовуйте [quality-контроль](/quality/).
""",
            "pub_date": "2026-04-11",
        },
        {
            "title": "Як обрати футболку під DTF-друк",
            "slug": "yak-obraty-futbolku-pid-dtf-druk",
            "excerpt": "Щільність, склад тканини, попередня усадка і тестовий перенос.",
            "content_md": """## Підбір матеріалу

Оптимально починати з середньої щільності та стабільної тканини без зайвої ворсистості.

Завжди робіть короткий тест перед великим тиражем.
""",
            "pub_date": "2026-05-14",
        },
        {
            "title": "Колір і щільність плівки: як уникнути сюрпризів",
            "slug": "kolir-i-shchilnist-plivky-iak-unyknuty-siurpryziv",
            "excerpt": "Практичні кроки для стабільного кольору та контроль білої підкладки.",
            "content_md": """## Практика контролю

- Перевіряйте контраст на темних і світлих тканинах
- Не пропускайте пробний друк
- Фіксуйте параметри пресу в одному профілі
""",
            "pub_date": "2026-06-13",
        },
        {
            "title": "Догляд за DTF-нанесенням: прості правила для клієнта",
            "slug": "dohliad-za-dtf-nanesenniam-prosti-pravyla",
            "excerpt": "Температура прання, прасування і зберігання для довгого ресурсу принта.",
            "content_md": """## Догляд

- Прання навиворіт до 40°C
- Без агресивних відбілювачів
- Прасування з вивороту або через захисний шар

Ці кроки помітно збільшують ресурс нанесення.
""",
            "pub_date": "2026-07-16",
        },
    ]
    for payload in posts:
        KnowledgePost.objects.update_or_create(
            slug=payload["slug"],
            defaults={
                "title": payload["title"],
                "excerpt": payload["excerpt"],
                "content_md": payload["content_md"],
                "pub_date": payload["pub_date"],
                "is_published": True,
                "seo_title": payload["title"],
                "seo_description": payload["excerpt"],
            },
        )


def unseed_knowledge_posts(apps, schema_editor):
    KnowledgePost = apps.get_model("dtf", "KnowledgePost")
    slugs = [
        "yak-pidhotuvaty-fail-dlia-dtf-druku",
        "dtf-vs-dtg-shcho-krashche-dlia-merchu-2026",
        "trendy-merchu-2026-shcho-realno-prodaietsia",
        "chomu-dtf-vyhidnishe-za-shovkohrafiiu",
        "yak-obraty-futbolku-pid-dtf-druk",
        "kolir-i-shchilnist-plivky-iak-unyknuty-siurpryziv",
        "dohliad-za-dtf-nanesenniam-prosti-pravyla",
    ]
    KnowledgePost.objects.filter(slug__in=slugs).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("dtf", "0002_dtflead_folder_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgePost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=220)),
                ("slug", models.SlugField(max_length=240, unique=True)),
                ("excerpt", models.CharField(max_length=320)),
                ("content_md", models.TextField()),
                ("content_html", models.TextField(blank=True, editable=False)),
                ("pub_date", models.DateField(db_index=True)),
                ("is_published", models.BooleanField(default=True)),
                ("seo_title", models.CharField(blank=True, max_length=160)),
                ("seo_description", models.CharField(blank=True, max_length=220)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Knowledge Base Post",
                "verbose_name_plural": "Knowledge Base Posts",
                "ordering": ["-pub_date", "-id"],
            },
        ),
        migrations.RunPython(seed_knowledge_posts, unseed_knowledge_posts),
    ]
