# Generated by Django 5.2.11 on 2026-02-07 00:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtf', '0003_knowledgepost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DtfSampleLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_number', models.CharField(blank=True, max_length=24, unique=True)),
                ('status', models.CharField(choices=[('new', 'Нова'), ('contacted', 'В роботі'), ('shipped', 'Відправлено'), ('closed', 'Закрито')], default='new', max_length=20)),
                ('sample_size', models.CharField(choices=[('a4', 'A4 sample'), ('a3', 'A3 sample'), ('strip_60x10', 'Calibration strip 60x10 cm')], default='a4', max_length=20)),
                ('is_brand_volume', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(db_index=True, max_length=32)),
                ('contact_channel', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('call', 'Телефонний дзвінок')], default='telegram', max_length=20)),
                ('contact_handle', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=120)),
                ('np_branch', models.CharField(max_length=240)),
                ('niche', models.CharField(blank=True, max_length=200)),
                ('monthly_volume', models.CharField(blank=True, max_length=120)),
                ('comment', models.TextField(blank=True)),
                ('consent', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, default='sample_page', max_length=50)),
                ('manager_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DTF Sample Lead',
                'verbose_name_plural': 'DTF Sample Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='dtforder',
            name='length_source',
            field=models.CharField(choices=[('manual', 'Ручний ввід'), ('auto', 'Автовизначення')], default='manual', max_length=10),
        ),
        migrations.AlterField(
            model_name='dtforder',
            name='status',
            field=models.CharField(choices=[('new_lead', 'Прийнято (заявка)'), ('new_order', 'Прийнято'), ('check_mockup', 'Перевірка макета'), ('need_fix', 'Потрібні правки'), ('awaiting_payment', 'Очікує оплати'), ('printing', 'У друці'), ('ready', 'Готово'), ('shipped', 'Відправлено'), ('closed', 'Закрито')], default='check_mockup', max_length=20),
        ),
        migrations.AlterField(
            model_name='dtfwork',
            name='category',
            field=models.CharField(choices=[('macro', 'Макро'), ('process', 'Процес'), ('final', 'Готовий виріб')], default='final', max_length=20),
        ),
        migrations.AlterField(
            model_name='knowledgepost',
            name='pub_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.CreateModel(
            name='DtfBuilderSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('submitted', 'Надіслано')], default='draft', max_length=20)),
                ('product_type', models.CharField(choices=[('tshirt', 'T-shirt'), ('hoodie', 'Hoodie'), ('tote', 'Tote'), ('my_item', 'My item')], default='tshirt', max_length=20)),
                ('product_color', models.CharField(default='#151515', max_length=40)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('size_breakdown_json', models.JSONField(blank=True, default=dict)),
                ('placement', models.CharField(choices=[('front', 'Front'), ('back', 'Back'), ('left_chest', 'Left chest'), ('sleeve', 'Sleeve')], default='front', max_length=20)),
                ('placements_json', models.JSONField(blank=True, default=list)),
                ('design_file', models.FileField(blank=True, upload_to='dtf/builder/uploads/')),
                ('preflight_json', models.JSONField(blank=True, default=dict)),
                ('preview_image', models.ImageField(blank=True, upload_to='dtf/builder/previews/')),
                ('risk_ack', models.BooleanField(default=False)),
                ('delivery_city', models.CharField(blank=True, max_length=120)),
                ('delivery_np_branch', models.CharField(blank=True, max_length=240)),
                ('comment', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, default='constructor', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builder_sessions', to='dtf.dtflead')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dtf_builder_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DTF Builder Session',
                'verbose_name_plural': 'DTF Builder Sessions',
                'ordering': ['-updated_at'],
            },
        ),
    ]
