# Generated by Django 5.2.11 on 2026-02-07 01:55

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtf', '0004_dtfsamplelead_alter_dtforder_length_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DtfPreflightReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('pass', 'PASS'), ('warn', 'WARN'), ('fail', 'FAIL')], default='pass', max_length=10)),
                ('checks_json', models.JSONField(blank=True, default=list)),
                ('metrics_json', models.JSONField(blank=True, default=dict)),
                ('warnings_json', models.JSONField(blank=True, default=list)),
                ('errors_json', models.JSONField(blank=True, default=list)),
                ('thumbnail', models.ImageField(blank=True, upload_to='dtf/preflight/thumbs/')),
                ('overlay_image', models.ImageField(blank=True, upload_to='dtf/preflight/overlays/')),
                ('preflight_version', models.CharField(default='2.0', max_length=24)),
                ('engine_version', models.CharField(default='1.0.0', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'DTF Preflight Report',
                'verbose_name_plural': 'DTF Preflight Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DtfPricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default DTF pricing', max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('version', models.PositiveIntegerField(default=1)),
                ('width_cm', models.DecimalField(decimal_places=2, default=Decimal('60.00'), max_digits=5)),
                ('min_order_m', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8)),
                ('base_price_per_meter', models.DecimalField(decimal_places=2, default=Decimal('350.00'), max_digits=8)),
                ('tiers_json', models.JSONField(blank=True, default=list, help_text='List of objects: [{"min_m": 10, "rate": 330}, ...]')),
                ('urgency_multipliers_json', models.JSONField(blank=True, default=dict, help_text="Dict of urgency multipliers, e.g. {'standard': 1.0, 'rush': 1.2}")),
                ('layout_help_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('shipping_estimate_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('validity_days', models.PositiveIntegerField(default=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DTF Pricing Config',
                'verbose_name_plural': 'DTF Pricing Configs',
                'ordering': ['-effective_from', '-id'],
            },
        ),
        migrations.AddField(
            model_name='dtforder',
            name='lifecycle_status',
            field=models.CharField(choices=[('new', 'Нове'), ('needs_review', 'Потребує перевірки'), ('confirmed', 'Підтверджено'), ('in_production', 'У виробництві'), ('qa_check', 'Контроль якості'), ('packed', 'Упаковано'), ('shipped', 'Відправлено'), ('delivered', 'Доставлено'), ('cancelled', 'Скасовано')], db_index=True, default='new', max_length=24),
        ),
        migrations.CreateModel(
            name='DtfQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, default='', max_length=40)),
                ('width_cm', models.DecimalField(decimal_places=2, default=Decimal('60.00'), max_digits=5)),
                ('length_m', models.DecimalField(decimal_places=2, max_digits=8)),
                ('urgency', models.CharField(default='standard', max_length=20)),
                ('services_json', models.JSONField(blank=True, default=dict)),
                ('shipping_method', models.CharField(blank=True, default='', max_length=40)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('base_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('services_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('shipping_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='UAH', max_length=10)),
                ('pricing_version', models.CharField(default='default', max_length=32)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('disclaimer', models.CharField(blank=True, max_length=255)),
                ('raw_inputs', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='dtf.dtforder')),
            ],
            options={
                'verbose_name': 'DTF Quote',
                'verbose_name_plural': 'DTF Quotes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DtfEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(db_index=True, max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logs', to='dtf.dtforder')),
                ('preflight_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logs', to='dtf.dtfpreflightreport')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logs', to='dtf.dtfquote')),
            ],
            options={
                'verbose_name': 'DTF Event Log',
                'verbose_name_plural': 'DTF Event Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DtfStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_from', models.CharField(choices=[('new', 'Нове'), ('needs_review', 'Потребує перевірки'), ('confirmed', 'Підтверджено'), ('in_production', 'У виробництві'), ('qa_check', 'Контроль якості'), ('packed', 'Упаковано'), ('shipped', 'Відправлено'), ('delivered', 'Доставлено'), ('cancelled', 'Скасовано')], max_length=24)),
                ('status_to', models.CharField(choices=[('new', 'Нове'), ('needs_review', 'Потребує перевірки'), ('confirmed', 'Підтверджено'), ('in_production', 'У виробництві'), ('qa_check', 'Контроль якості'), ('packed', 'Упаковано'), ('shipped', 'Відправлено'), ('delivered', 'Доставлено'), ('cancelled', 'Скасовано')], max_length=24)),
                ('actor', models.CharField(choices=[('system', 'System'), ('manager', 'Manager'), ('customer', 'Customer')], default='system', max_length=20)),
                ('public_message', models.CharField(blank=True, max_length=255)),
                ('internal_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='dtf.dtforder')),
            ],
            options={
                'verbose_name': 'DTF Status Event',
                'verbose_name_plural': 'DTF Status Events',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DtfUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dtf/uploads/')),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('source', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='dtf.dtflead')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='dtf.dtforder')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dtf_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DTF Upload',
                'verbose_name_plural': 'DTF Uploads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dtfquote',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='dtf.dtfupload'),
        ),
        migrations.AddField(
            model_name='dtfpreflightreport',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preflight_reports', to='dtf.dtfupload'),
        ),
    ]
