# Generated by Django 5.2.11 on 2026-02-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtf', '0005_dtfpreflightreport_dtfpricingconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtforder',
            name='custom_specs_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dtforder',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dtforder',
            name='delivery_point_code',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='dtforder',
            name='delivery_point_label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dtforder',
            name='delivery_point_type',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='dtforder',
            name='fulfillment_kind',
            field=models.CharField(choices=[('film', 'Плівка DTF'), ('custom_product', 'Готовий виріб під замовлення')], db_index=True, default='film', max_length=24),
        ),
        migrations.AddField(
            model_name='dtforder',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='dtforder',
            name='payment_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='dtforder',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='dtforder',
            name='payment_status',
            field=models.CharField(choices=[('pending_review', 'На модерації менеджером'), ('awaiting_payment', 'Очікує оплату'), ('paid', 'Оплачено'), ('partial', 'Частково оплачено'), ('failed', 'Оплата не пройшла'), ('refunded', 'Повернено')], db_index=True, default='pending_review', max_length=32),
        ),
        migrations.AddField(
            model_name='dtforder',
            name='payment_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dtforder',
            name='print_placement',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='dtforder',
            name='product_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dtforder',
            name='product_type',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='dtforder',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgepost',
            name='content_rich_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='knowledgepost',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='dtforder',
            name='lifecycle_status',
            field=models.CharField(choices=[('new', 'Нове'), ('needs_review', 'Потребує перевірки'), ('confirmed', 'Підтверджено'), ('in_production', 'У виробництві'), ('qa_check', 'Контроль якості'), ('packed', 'Упаковано'), ('shipped', 'Відправлено'), ('delivered', 'Доставлено'), ('received', 'Отримано'), ('cancelled', 'Скасовано')], db_index=True, default='new', max_length=24),
        ),
        migrations.AlterField(
            model_name='dtfstatusevent',
            name='status_from',
            field=models.CharField(choices=[('new', 'Нове'), ('needs_review', 'Потребує перевірки'), ('confirmed', 'Підтверджено'), ('in_production', 'У виробництві'), ('qa_check', 'Контроль якості'), ('packed', 'Упаковано'), ('shipped', 'Відправлено'), ('delivered', 'Доставлено'), ('received', 'Отримано'), ('cancelled', 'Скасовано')], max_length=24),
        ),
        migrations.AlterField(
            model_name='dtfstatusevent',
            name='status_to',
            field=models.CharField(choices=[('new', 'Нове'), ('needs_review', 'Потребує перевірки'), ('confirmed', 'Підтверджено'), ('in_production', 'У виробництві'), ('qa_check', 'Контроль якості'), ('packed', 'Упаковано'), ('shipped', 'Відправлено'), ('delivered', 'Доставлено'), ('received', 'Отримано'), ('cancelled', 'Скасовано')], max_length=24),
        ),
    ]
