# Generated by Django 5.2.11 on 2026-02-15 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtf', '0006_dtforder_custom_specs_json_dtforder_delivered_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtfbuildersession',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dtf_builder_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dtfupload',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dtf_uploads', to=settings.AUTH_USER_MODEL),
        ),
    ]
