# Generated by Django 5.2.11 on 2026-02-16

from django.db import migrations
from django.utils import timezone


CODEX_UA_BLOG_SLUGS = [
    "dtf-vs-dtg-shcho-obraty-dlia-merchu-2026",
    "maket-60sm-gang-lyst-yak-zrobyty-i-pokhuvaty-metrazh",
    "preflight-perevirka-failu-pered-dtf-drukom",
    "hot-peel-vs-cold-peel-instruktsiia-perenosu-dtf",
    "perenos-dtf-temperatura-chas-tysk-dlia-tkanyn",
    "png-dlia-dtf-prozoryi-fon-bez-kvadrata",
    "dribnyi-tekst-tonki-linii-dtf-yak-zrobyty-pravylno",
    "10-pomylok-u-failakh-dlia-dtf-iak-unyknuty",
    "sobivartist-dtf-prynta-tsina-merchu-marzha",
    "dohliad-za-dtf-pryntom-yak-praty-sushyty-prasuvaty",
]


def publish_codex_posts_now(apps, schema_editor):
    KnowledgePost = apps.get_model("dtf", "KnowledgePost")
    today = timezone.localdate()
    (
        KnowledgePost.objects.filter(slug__in=CODEX_UA_BLOG_SLUGS)
        .update(is_published=True, pub_date=today)
    )


class Migration(migrations.Migration):

    dependencies = [
        ("dtf", "0008_seed_codex_blog_posts_ua"),
    ]

    operations = [
        migrations.RunPython(publish_codex_posts_now, migrations.RunPython.noop),
    ]

