# Generated by Django 5.2.11 on 2026-02-16

import importlib

from django.db import migrations
from django.utils import timezone


def ensure_codex_blog_posts_seeded_and_published(apps, schema_editor):
    KnowledgePost = apps.get_model("dtf", "KnowledgePost")
    source = importlib.import_module("dtf.migrations.0008_seed_codex_blog_posts_ua")
    render_markdown = getattr(source, "_render_markdown")

    today = timezone.localdate()
    for payload in source.POSTS:
        KnowledgePost.objects.update_or_create(
            slug=payload["slug"],
            defaults={
                "title": payload["title"],
                "excerpt": payload["excerpt"],
                "content_md": payload["content_md"],
                "content_html": render_markdown(payload["content_md"]),
                "pub_date": today,
                "is_published": True,
                "seo_title": payload["seo_title"],
                "seo_keywords": payload["seo_keywords"],
                "seo_description": payload["seo_description"],
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("dtf", "0009_publish_codex_blog_posts_now"),
    ]

    operations = [
        migrations.RunPython(ensure_codex_blog_posts_seeded_and_published, migrations.RunPython.noop),
    ]

