# Generated by Django 5.2.11 on 2026-03-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtf', '0010_ensure_codex_blog_posts_seeded_and_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtforder',
            name='order_type',
            field=models.CharField(choices=[('ready', 'Макет 60 см (ганг-лист)'), ('help', 'Потрібна допомога')], default='ready', max_length=20),
        ),
    ]
