# Generated by Django 5.2.5 on 2025-08-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Промокод')),
                ('discount_type', models.CharField(choices=[('percentage', 'Відсоток'), ('fixed', 'Фіксована сума')], max_length=10, verbose_name='Тип знижки')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Значення знижки')),
                ('usage_type', models.CharField(choices=[('single', 'Одноразовий'), ('multiple', 'Багаторазовий'), ('unlimited', 'Необмежений')], max_length=10, verbose_name='Тип використання')),
                ('max_uses', models.PositiveIntegerField(default=1, verbose_name='Максимальна кількість використань')),
                ('current_uses', models.PositiveIntegerField(default=0, verbose_name='Поточне використання')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Дійсний до')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоди',
            },
        ),
    ]
