# Generated by Django 5.2.5 on 2025-08-27 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0003_product_created_at_product_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoCode',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
