# Generated by Django 5.2.5 on 2025-08-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0004_delete_promocode_remove_product_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код промокоду')),
                ('discount_type', models.CharField(choices=[('percentage', 'Відсоток'), ('fixed', 'Фіксована сума')], max_length=10, verbose_name='Тип знижки')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Значення знижки')),
                ('max_uses', models.PositiveIntegerField(default=0, verbose_name='Максимальна кількість використань (0 = безліміт)')),
                ('current_uses', models.PositiveIntegerField(default=0, verbose_name='Поточна кількість використань')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоди',
                'ordering': ['-created_at'],
            },
        ),
    ]
