# Generated by Django 5.2.5 on 2025-08-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0005_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Код промокоду'),
        ),
    ]
