# Generated by Django 5.2.5 on 2025-08-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0006_alter_promocode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='points_reward',
            field=models.PositiveIntegerField(default=0, verbose_name='Бали за покупку'),
        ),
    ]
