# Generated by Django 5.2.5 on 2025-08-28 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0007_product_points_reward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_discount',
        ),
    ]
