# Generated by Django 5.2.5 on 2025-09-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0008_remove_has_discount_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва магазину')),
                ('address', models.TextField(verbose_name='Адреса')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('working_hours', models.CharField(blank=True, max_length=100, null=True, verbose_name='Робочі години')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок відображення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Оффлайн магазин',
                'verbose_name_plural': 'Оффлайн магазини',
                'ordering': ['order', 'name'],
            },
        ),
    ]
