# Generated by Django 5.2.5 on 2025-09-06 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0009_offlinestore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='print_proposals/', verbose_name='Зображення')),
                ('link_url', models.URLField(blank=True, verbose_name='Посилання на зображення')),
                ('description', models.TextField(blank=True, verbose_name='Опис / примітки')),
                ('status', models.CharField(choices=[('pending', 'На розгляді'), ('approved', 'Схвалено'), ('rejected', 'Відхилено')], default='pending', max_length=10, verbose_name='Статус')),
                ('awarded_points', models.PositiveIntegerField(default=0, verbose_name='Нараховані бали')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('awarded_promocode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storefront.promocode', verbose_name='Промокод')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Пропозиція принта',
                'verbose_name_plural': 'Пропозиції принтів',
                'ordering': ['-created_at'],
            },
        ),
    ]
