# Generated by Django 5.2.6 on 2025-09-10 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0021_add_alt_text_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Номер накладної')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примітки')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Створено користувачем')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='storefront.offlinestore', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Накладна магазину',
                'verbose_name_plural': 'Накладні магазинів',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=10, null=True, verbose_name='Розмір')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Колір')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Собівартість')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна продажу')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storefront.product', verbose_name='Товар')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='storefront.offlinestore', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Товар в магазині',
                'verbose_name_plural': 'Товари в магазинах',
                'ordering': ['-created_at'],
                'unique_together': {('store', 'product', 'size', 'color')},
            },
        ),
        migrations.CreateModel(
            name='StoreInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Кількість')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='storefront.storeinvoice', verbose_name='Накладна')),
                ('store_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storefront.storeproduct', verbose_name='Товар в магазині')),
            ],
            options={
                'verbose_name': 'Позиція накладної',
                'verbose_name_plural': 'Позиції накладних',
                'unique_together': {('invoice', 'store_product')},
            },
        ),
    ]
