# Generated by Django 5.2.6 on 2025-09-10 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productcolors', '0002_add_alt_text_field'),
        ('storefront', '0022_storeinvoice_storeproduct_storeinvoiceitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeinvoice',
            options={'ordering': ['-created_at'], 'verbose_name': 'Накладна', 'verbose_name_plural': 'Накладні'},
        ),
        migrations.RemoveField(
            model_name='storeinvoice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='storeinvoice',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='storeinvoice',
            name='notes',
        ),
        migrations.AddField(
            model_name='storeinvoice',
            name='file_name',
            field=models.CharField(default='', max_length=255, verbose_name='Назва файлу'),
        ),
        migrations.AddField(
            model_name='storeinvoice',
            name='file_path',
            field=models.CharField(default='', max_length=500, verbose_name='Шлях до файлу'),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productcolors.color', verbose_name='Колір'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='cost_price',
            field=models.PositiveIntegerField(verbose_name='Собівартість (грн)'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='selling_price',
            field=models.PositiveIntegerField(verbose_name='Ціна продажу (грн)'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_products', to='storefront.offlinestore', verbose_name='Магазин'),
        ),
        migrations.CreateModel(
            name='StoreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('pending', 'В обробці'), ('confirmed', 'Підтверджено'), ('completed', 'Виконано'), ('cancelled', 'Скасовано')], default='draft', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_orders', to='storefront.offlinestore', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Заказ магазина',
                'verbose_name_plural': 'Заказы магазинов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='storeinvoice',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='storefront.storeorder', verbose_name='Заказ'),
        ),
        migrations.CreateModel(
            name='StoreOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=10, null=True, verbose_name='Розмір')),
                ('cost_price', models.PositiveIntegerField(verbose_name='Собівартість (грн)')),
                ('selling_price', models.PositiveIntegerField(verbose_name='Ціна продажу (грн)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productcolors.color', verbose_name='Колір')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='storefront.storeorder', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storefront.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в заказі',
                'verbose_name_plural': 'Товари в заказах',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='StoreInvoiceItem',
        ),
    ]
