# Generated by Django 5.2.6 on 2025-10-14 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0024_store_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='offlinestore',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='offlinestore',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активний'),
        ),
        migrations.AlterField(
            model_name='offlinestore',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='printproposal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='printproposal',
            name='status',
            field=models.CharField(choices=[('pending', 'На розгляді'), ('approved', 'Схвалено'), ('rejected', 'Відхилено')], db_index=True, default='pending', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='printproposal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активний'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='storeinvoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Чернетка'), ('pending', 'В обробці'), ('confirmed', 'Підтверджено'), ('completed', 'Виконано'), ('cancelled', 'Скасовано')], db_index=True, default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активний'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Оновлено'),
        ),
    ]
