# Generated by Django 5.2.6 on 2025-10-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0026_product_drop_price_product_recommended_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dropship_note',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Примітка для дропшипа'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_dropship_available',
            field=models.BooleanField(default=True, verbose_name='Доступний для дропшипа'),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Оптова ціна (грн)'),
        ),
    ]
