# Generated by Django 5.2.6 on 2025-10-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0028_merge_20251017_0533'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-id'], name='idx_product_id_desc'),
        ),
    ]
