# Generated by Django 5.2.6 on 2025-11-16 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0032_catalog_redesign_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('page_view', 'Перегляд сторінки'), ('product_view', 'Перегляд товару'), ('add_to_cart', 'Додано в кошик'), ('remove_from_cart', 'Видалено з кошика'), ('initiate_checkout', 'Початок оформлення'), ('lead', 'Лід (передплата)'), ('purchase', 'Покупка'), ('search', 'Пошук'), ('click', 'Клік'), ('scroll', 'Прокрутка'), ('time_on_page', 'Час на сторінці')], db_index=True, max_length=50, verbose_name='Тип дії')),
                ('page_path', models.CharField(blank=True, max_length=512, null=True, verbose_name='Шлях сторінки')),
                ('product_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID товару')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Назва товару')),
                ('cart_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сума кошика')),
                ('order_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID замовлення')),
                ('order_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер замовлення')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метадані')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Час')),
                ('points_earned', models.IntegerField(default=0, verbose_name='Нараховані бали')),
            ],
            options={
                'verbose_name': 'Дія користувача',
                'verbose_name_plural': 'Дії користувачів',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UTMSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('utm_source', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Джерело (utm_source)')),
                ('utm_medium', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Канал (utm_medium)')),
                ('utm_campaign', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Кампанія (utm_campaign)')),
                ('utm_content', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Контент/Креатив (utm_content)')),
                ('utm_term', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Ключове слово (utm_term)')),
                ('fbclid', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Facebook Click ID')),
                ('gclid', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Google Click ID')),
                ('ttclid', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='TikTok Click ID')),
                ('fbc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook Click Cookie')),
                ('fbp', models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook Browser Cookie')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='IP-адреса')),
                ('country', models.CharField(blank=True, db_index=True, max_length=2, null=True, verbose_name='Код країни (ISO 3166-1)')),
                ('country_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Назва країни')),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Місто')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Регіон/Область')),
                ('timezone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Часовий пояс')),
                ('device_type', models.CharField(blank=True, choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], db_index=True, max_length=20, null=True, verbose_name='Тип пристрою')),
                ('device_brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='Бренд пристрою')),
                ('device_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Модель пристрою')),
                ('os_name', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Операційна система')),
                ('os_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='Версія ОС')),
                ('browser_name', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Браузер')),
                ('browser_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='Версія браузера')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('referrer', models.URLField(blank=True, max_length=512, null=True, verbose_name='Реферер')),
                ('landing_page', models.CharField(blank=True, max_length=512, null=True, verbose_name='Посадкова сторінка')),
                ('visit_count', models.PositiveIntegerField(db_index=True, default=1, verbose_name='Кількість візитів')),
                ('is_first_visit', models.BooleanField(db_index=True, default=True, verbose_name='Перший візит')),
                ('is_returning_visitor', models.BooleanField(db_index=True, default=False, verbose_name='Постійний відвідувач')),
                ('user_registered', models.BooleanField(db_index=True, default=False, verbose_name='Користувач зареєструвався')),
                ('user_registered_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата реєстрації')),
                ('first_seen', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Перший візит')),
                ('last_seen', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Останній візит')),
                ('is_converted', models.BooleanField(db_index=True, default=False, verbose_name='Конверсія відбулася')),
                ('converted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата конверсії')),
                ('conversion_type', models.CharField(blank=True, choices=[('lead', 'Лід (передплата)'), ('purchase', 'Покупка')], db_index=True, max_length=20, null=True, verbose_name='Тип конверсії')),
            ],
            options={
                'verbose_name': 'UTM Сесія',
                'verbose_name_plural': 'UTM Сесії',
                'ordering': ['-first_seen'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='catalogoption',
            name='unique_catalog_option_name',
        ),
        migrations.RemoveConstraint(
            model_name='catalogoptionvalue',
            name='unique_catalog_option_value',
        ),
        migrations.AlterUniqueTogether(
            name='catalogoption',
            unique_together={('catalog', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='catalogoptionvalue',
            unique_together={('option', 'value')},
        ),
        migrations.AddField(
            model_name='useraction',
            name='site_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_actions', to='storefront.sitesession', verbose_name='Сесія сайту'),
        ),
        migrations.AddField(
            model_name='useraction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AddField(
            model_name='utmsession',
            name='session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utm_data', to='storefront.sitesession'),
        ),
        migrations.AddField(
            model_name='useraction',
            name='utm_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='storefront.utmsession', verbose_name='UTM Сесія'),
        ),
        migrations.AddIndex(
            model_name='utmsession',
            index=models.Index(fields=['utm_source', 'utm_medium', 'utm_campaign'], name='idx_utm_source_medium_campaign'),
        ),
        migrations.AddIndex(
            model_name='utmsession',
            index=models.Index(fields=['-first_seen'], name='idx_utm_first_seen'),
        ),
        migrations.AddIndex(
            model_name='utmsession',
            index=models.Index(fields=['is_converted', '-converted_at'], name='idx_utm_converted'),
        ),
        migrations.AddIndex(
            model_name='utmsession',
            index=models.Index(fields=['country', 'city'], name='idx_utm_geo'),
        ),
        migrations.AddIndex(
            model_name='utmsession',
            index=models.Index(fields=['device_type', 'os_name'], name='idx_utm_device'),
        ),
        migrations.AddIndex(
            model_name='utmsession',
            index=models.Index(fields=['is_returning_visitor', '-first_seen'], name='idx_utm_returning'),
        ),
        migrations.AddIndex(
            model_name='utmsession',
            index=models.Index(fields=['user_registered', '-first_seen'], name='idx_utm_registered'),
        ),
        migrations.AddIndex(
            model_name='useraction',
            index=models.Index(fields=['action_type', '-timestamp'], name='idx_action_type_time'),
        ),
        migrations.AddIndex(
            model_name='useraction',
            index=models.Index(fields=['utm_session', 'action_type'], name='idx_action_utm_type'),
        ),
        migrations.AddIndex(
            model_name='useraction',
            index=models.Index(fields=['product_id', '-timestamp'], name='idx_action_product'),
        ),
        migrations.AddIndex(
            model_name='useraction',
            index=models.Index(fields=['order_id'], name='idx_action_order'),
        ),
    ]
