# Generated by Django 5.2.6 on 2025-11-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0034_fix_utm_indexes_mysql'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Ціна (грн)'),
        ),
    ]
