# Generated by Django 6.0.3 on 2026-04-09 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0037_survey_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPrintLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_number', models.CharField(blank=True, max_length=24, unique=True, verbose_name='Номер заявки')),
                ('status', models.CharField(choices=[('new', 'Нова'), ('in_progress', 'В роботі'), ('closed', 'Закрита')], default='new', max_length=20, verbose_name='Статус')),
                ('service_kind', models.CharField(choices=[('ready', 'Маю готовий файл'), ('adjust', 'Потрібно допрацювати файл'), ('design', 'Потрібен дизайн з нуля')], max_length=20, verbose_name='Тип послуги')),
                ('product_type', models.CharField(choices=[('tshirt', 'Футболка'), ('hoodie', 'Худі'), ('longsleeve', 'Лонгслів')], max_length=20, verbose_name='Тип виробу')),
                ('placements', models.JSONField(blank=True, default=list, verbose_name='Зони нанесення')),
                ('placement_note', models.CharField(blank=True, max_length=255, verbose_name='Нестандартне розміщення')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('sizes_note', models.CharField(blank=True, max_length=255, verbose_name='Розміри')),
                ('client_kind', models.CharField(choices=[('personal', 'Для себе'), ('brand', 'Для бренду / команди / події')], default='personal', max_length=20, verbose_name='Тип клієнта')),
                ('brand_name', models.CharField(blank=True, max_length=255, verbose_name='Бренд / команда')),
                ('name', models.CharField(max_length=200, verbose_name="Ім'я")),
                ('contact_channel', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('phone', 'Телефон')], default='telegram', max_length=20, verbose_name="Канал зв'язку")),
                ('contact_value', models.CharField(max_length=255, verbose_name='Контакт')),
                ('brief', models.TextField(blank=True, verbose_name='Опис задачі')),
                ('source', models.CharField(blank=True, default='main_custom_print', max_length=50, verbose_name='Джерело')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Заявка на кастомний принт',
                'verbose_name_plural': 'Заявки на кастомний принт',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='idx_cprint_status'), models.Index(fields=['service_kind'], name='idx_cprint_service'), models.Index(fields=['created_at'], name='idx_cprint_created')],
            },
        ),
        migrations.CreateModel(
            name='CustomPrintLeadAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='custom_print/leads/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='storefront.customprintlead', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Файл заявки на кастомний принт',
                'verbose_name_plural': 'Файли заявок на кастомний принт',
            },
        ),
    ]
