# Generated by Django 6.0.3 on 2026-04-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0038_customprintlead_customprintleadattachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customprintlead",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("tshirt", "Футболка"),
                    ("hoodie", "Худі"),
                    ("longsleeve", "Лонгслів"),
                    ("customer_garment", "Свій одяг"),
                ],
                max_length=20,
                verbose_name="Тип виробу",
            ),
        ),
        migrations.AddField(
            model_name="customprintlead",
            name="business_kind",
            field=models.CharField(
                blank=True,
                choices=[("bulk", "Оптова партія"), ("branding", "Брендування / мерч")],
                default="",
                max_length=20,
                verbose_name="B2B сценарій",
            ),
        ),
        migrations.AddField(
            model_name="customprintlead",
            name="garment_note",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Опис виробу клієнта"),
        ),
        migrations.AddField(
            model_name="customprintlead",
            name="placement_specs_json",
            field=models.JSONField(blank=True, default=list, verbose_name="Специфікації зон нанесення"),
        ),
        migrations.AddField(
            model_name="customprintlead",
            name="pricing_snapshot_json",
            field=models.JSONField(blank=True, default=dict, verbose_name="Снапшот прорахунку"),
        ),
        migrations.AddField(
            model_name="customprintlead",
            name="size_mode",
            field=models.CharField(
                blank=True,
                choices=[("single", "Один розмір"), ("mixed", "Мікс"), ("manager", "Уточню з менеджером")],
                default="",
                max_length=20,
                verbose_name="Режим розмірів",
            ),
        ),
        migrations.AddField(
            model_name="customprintleadattachment",
            name="attachment_role",
            field=models.CharField(
                choices=[("design", "Макет / дизайн"), ("reference", "Референс")],
                default="design",
                max_length=20,
                verbose_name="Роль файлу",
            ),
        ),
        migrations.AddField(
            model_name="customprintleadattachment",
            name="placement_zone",
            field=models.CharField(blank=True, default="", max_length=32, verbose_name="Зона нанесення"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customprintleadattachment",
            name="sort_order",
            field=models.PositiveIntegerField(default=0, verbose_name="Порядок"),
        ),
    ]
