# Generated by Django 5.2.11 on 2026-04-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0039_custom_print_lead_expansion"),
    ]

    operations = [
        migrations.AddField(
            model_name="customprintlead",
            name="color_choice",
            field=models.CharField(blank=True, default="", max_length=64, verbose_name="Колір виробу"),
        ),
        migrations.AddField(
            model_name="customprintlead",
            name="config_draft_json",
            field=models.JSONField(blank=True, default=dict, verbose_name="Чернетка конфігуратора"),
        ),
        migrations.AddField(
            model_name="customprintlead",
            name="exit_step",
            field=models.CharField(blank=True, default="", max_length=32, verbose_name="Крок safe exit"),
        ),
        migrations.AddField(
            model_name="customprintlead",
            name="fabric",
            field=models.CharField(blank=True, default="", max_length=32, verbose_name="Тканина / рівень"),
        ),
        migrations.AddField(
            model_name="customprintlead",
            name="file_triage_status",
            field=models.CharField(blank=True, default="", max_length=32, verbose_name="Статус triage файлу"),
        ),
        migrations.AddField(
            model_name="customprintlead",
            name="fit",
            field=models.CharField(blank=True, default="", max_length=32, verbose_name="Посадка"),
        ),
    ]
