# Generated by Django 5.2.11 on 2026-04-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0041_customprintlead_moderation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customprintlead',
            name='moderation_status',
            field=models.CharField(choices=[('draft', 'Чернетка'), ('awaiting_review', 'На перевірці менеджера'), ('approved', 'Погоджено — оплата доступна'), ('rejected', 'Відхилено менеджером')], db_default='draft', default='draft', max_length=20, verbose_name='Статус модерації кастомного кошика'),
        ),
    ]
