# Generated by Django 5.2.11 on 2026-04-21 23:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0044_sizegrid_guide_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotificationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('body', models.CharField(max_length=240, verbose_name='Текст повідомлення')),
                ('target_url', models.CharField(max_length=500, verbose_name='Посилання переходу')),
                ('image', models.ImageField(blank=True, null=True, upload_to='push_notifications/', verbose_name='Зображення сповіщення')),
                ('audience_mode', models.CharField(choices=[('all_active', 'Усі активні підписки')], default='all_active', max_length=20, verbose_name='Аудиторія')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('sending', 'Надсилання'), ('sent', 'Надіслано'), ('partial', 'Частково доставлено'), ('failed', 'Помилка')], db_index=True, default='draft', max_length=20, verbose_name='Статус')),
                ('last_error', models.CharField(blank=True, max_length=255, verbose_name='Остання помилка')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('sent_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Початок надсилання')),
                ('sent_finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершення надсилання')),
                ('targeted_count', models.PositiveIntegerField(default=0, verbose_name='Заплановано')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Прийнято push-сервісом')),
                ('displayed_count', models.PositiveIntegerField(default=0, verbose_name='Показано')),
                ('clicked_count', models.PositiveIntegerField(default=0, verbose_name='Кліки')),
                ('closed_count', models.PositiveIntegerField(default=0, verbose_name='Закрито')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Помилки')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='push_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
            ],
            options={
                'verbose_name': 'Push кампанія',
                'verbose_name_plural': 'Push кампанії',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebPushDeviceSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='ID браузерної інсталяції')),
                ('endpoint', models.URLField(max_length=1000, unique=True, verbose_name='Push endpoint')),
                ('auth_key', models.CharField(max_length=255, verbose_name='Ключ auth')),
                ('p256dh_key', models.CharField(max_length=255, verbose_name='Ключ p256dh')),
                ('language', models.CharField(blank=True, max_length=16, verbose_name='Мова браузера')),
                ('timezone', models.CharField(blank=True, max_length=64, verbose_name='Часовий пояс')),
                ('browser_family', models.CharField(blank=True, max_length=64, verbose_name='Браузер')),
                ('operating_system', models.CharField(blank=True, max_length=64, verbose_name='ОС')),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20, verbose_name='Тип пристрою')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('last_seen_path', models.CharField(blank=True, max_length=512, verbose_name='Остання сторінка')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метадані')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Підписано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('last_seen_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Остання активність')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='Відписано')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='Остання успішна доставка')),
                ('last_failure_at', models.DateTimeField(blank=True, null=True, verbose_name='Остання помилка')),
                ('failure_count', models.PositiveIntegerField(default=0, verbose_name='Кількість помилок')),
                ('last_error', models.CharField(blank=True, max_length=255, verbose_name='Остання помилка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Web Push підписка',
                'verbose_name_plural': 'Web Push підписки',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='PushNotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Токен події')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('sent', 'Надіслано'), ('displayed', 'Показано'), ('clicked', 'Клік'), ('closed', 'Закрито'), ('failed', 'Помилка'), ('expired', 'Недійсна підписка')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('push_service_status_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='HTTP статус push-сервісу')),
                ('error_code', models.CharField(blank=True, max_length=64, verbose_name='Код помилки')),
                ('error_message', models.CharField(blank=True, max_length=255, verbose_name='Повідомлення помилки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Надіслано')),
                ('displayed_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Показано')),
                ('clicked_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Клік')),
                ('closed_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Закрито')),
                ('failed_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Помилка')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='storefront.pushnotificationcampaign', verbose_name='Кампанія')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='storefront.webpushdevicesubscription', verbose_name='Підписка')),
            ],
            options={
                'verbose_name': 'Push доставка',
                'verbose_name_plural': 'Push доставки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pushnotificationcampaign',
            index=models.Index(fields=['status', '-created_at'], name='idx_push_campaign_status'),
        ),
        migrations.AddIndex(
            model_name='webpushdevicesubscription',
            index=models.Index(fields=['is_active', '-last_seen_at'], name='idx_push_sub_active_seen'),
        ),
        migrations.AddIndex(
            model_name='webpushdevicesubscription',
            index=models.Index(fields=['installation_id', 'is_active'], name='idx_push_subscription_install'),
        ),
        migrations.AddIndex(
            model_name='webpushdevicesubscription',
            index=models.Index(fields=['user', 'is_active'], name='idx_push_subscription_user'),
        ),
        migrations.AddIndex(
            model_name='webpushdevicesubscription',
            index=models.Index(fields=['device_type', 'is_active'], name='idx_push_subscription_device'),
        ),
        migrations.AddIndex(
            model_name='pushnotificationdelivery',
            index=models.Index(fields=['campaign', 'status'], name='idx_push_deliv_cmp_status'),
        ),
        migrations.AddIndex(
            model_name='pushnotificationdelivery',
            index=models.Index(fields=['subscription', '-created_at'], name='idx_push_delivery_subscription'),
        ),
        migrations.AddConstraint(
            model_name='pushnotificationdelivery',
            constraint=models.UniqueConstraint(fields=('campaign', 'subscription'), name='uniq_push_delivery_campaign_subscription'),
        ),
    ]
