# Generated by Django 5.2.11 on 2026-04-27 20:00

import re

import django.db.models.deletion
from django.db import migrations, models


def _is_tshirt(product):
    category = getattr(product, 'category', None)
    catalog = getattr(product, 'catalog', None)
    candidates = [
        getattr(product, 'title', ''),
        getattr(category, 'name', ''),
        getattr(category, 'slug', ''),
        getattr(catalog, 'name', ''),
        getattr(catalog, 'slug', ''),
    ]
    normalized = ' '.join(str(item or '').lower() for item in candidates)
    tshirt_pattern = re.compile(r'(^|[^a-z0-9а-яіїєґ])(?:футбол\w*|t-?shirts?|tees?)(?=$|[^a-z0-9а-яіїєґ])')
    return bool(tshirt_pattern.search(normalized))


def create_default_tshirt_fit_options(apps, schema_editor):
    Product = apps.get_model('storefront', 'Product')
    ProductFitOption = apps.get_model('storefront', 'ProductFitOption')
    defaults = [
        {
            'code': 'classic',
            'label': 'Класичний',
            'description': 'Прямий крій, стандартна посадка',
            'icon': 'tshirt-classic',
            'order': 0,
            'is_default': True,
            'is_active': True,
        },
        {
            'code': 'oversize',
            'label': 'Оверсайз',
            'description': 'Вільний крій, спущене плече',
            'icon': 'tshirt-oversize',
            'order': 1,
            'is_default': False,
            'is_active': True,
        },
    ]

    queryset = Product.objects.select_related('category', 'catalog').all()
    for product in queryset.iterator():
        if not _is_tshirt(product):
            continue
        for option in defaults:
            ProductFitOption.objects.get_or_create(
                product_id=product.id,
                code=option['code'],
                defaults=option,
            )


def remove_default_tshirt_fit_options(apps, schema_editor):
    Product = apps.get_model('storefront', 'Product')
    ProductFitOption = apps.get_model('storefront', 'ProductFitOption')
    seeded_options = {
        'classic': {
            'label': 'Класичний',
            'description': 'Прямий крій, стандартна посадка',
            'icon': 'tshirt-classic',
            'order': 0,
            'is_default': True,
            'is_active': True,
        },
        'oversize': {
            'label': 'Оверсайз',
            'description': 'Вільний крій, спущене плече',
            'icon': 'tshirt-oversize',
            'order': 1,
            'is_default': False,
            'is_active': True,
        },
    }
    tshirt_ids = [
        product.id
        for product in Product.objects.select_related('category', 'catalog').all().iterator()
        if _is_tshirt(product)
    ]
    if not tshirt_ids:
        return

    delete_ids = []
    for option in ProductFitOption.objects.filter(product_id__in=tshirt_ids, code__in=seeded_options):
        seed = seeded_options[option.code]
        if all(getattr(option, field) == value for field, value in seed.items()):
            delete_ids.append(option.id)

    if delete_ids:
        ProductFitOption.objects.filter(id__in=delete_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0046_merge_20260422_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFitOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(verbose_name='Код посадки')),
                ('label', models.CharField(max_length=100, verbose_name='Назва')),
                ('description', models.CharField(blank=True, max_length=220, verbose_name='Опис')),
                ('icon', models.CharField(blank=True, max_length=64, verbose_name='Іконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_default', models.BooleanField(default=False, verbose_name='За замовчуванням')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fit_options', to='storefront.product')),
            ],
            options={
                'verbose_name': 'Посадка товару',
                'verbose_name_plural': 'Посадки товарів',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['product', 'order'], name='idx_fit_product_order'), models.Index(fields=['product', 'is_active'], name='idx_fit_product_active'), models.Index(fields=['product', 'is_default'], name='idx_fit_product_default')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('product',), name='uniq_default_fit_per_product')],
                'unique_together': {('product', 'code')},
            },
        ),
        migrations.RunPython(create_default_tshirt_fit_options, remove_default_tshirt_fit_options),
    ]
