# Generated by Django 5.2.11 on 2026-04-28 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0048_product_home_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='care_instructions',
            field=models.TextField(blank=True, verbose_name='Догляд за товаром'),
        ),
        migrations.AddField(
            model_name='product',
            name='details_text',
            field=models.TextField(blank=True, verbose_name='Деталі товару'),
        ),
        migrations.AddField(
            model_name='product',
            name='target_audience',
            field=models.TextField(blank=True, verbose_name='Кому підійде'),
        ),
        migrations.CreateModel(
            name='ProductFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Питання')),
                ('answer', models.TextField(verbose_name='Відповідь')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='storefront.product')),
            ],
            options={
                'verbose_name': 'FAQ товару',
                'verbose_name_plural': 'FAQ товарів',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['product', 'order'], name='idx_product_faq_order'), models.Index(fields=['product', 'is_active'], name='idx_product_faq_active')],
            },
        ),
    ]
