# Generated by Django 5.2.11 on 2026-05-09 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0050_seo_ai_optin_and_fit_toggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='seo_text_title',
            field=models.CharField(blank=True, help_text='H2 над довгим SEO-текстом категорії. Якщо порожньо — використовується назва категорії.', max_length=200, verbose_name='SEO-заголовок над описом'),
        ),
        migrations.CreateModel(
            name='CategorySeoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('top_filters', 'Топ фільтри'), ('top_queries', 'Топ запити'), ('top_cards', 'Топ карточки'), ('top_menu', 'Розділи категорії'), ('best_prices', 'Найкращі ціни')], max_length=20, verbose_name='Тип блоку')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок (H2 / H3)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_blocks', to='storefront.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'SEO-блок категорії',
                'verbose_name_plural': 'SEO-блоки категорій',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CategorySeoBlockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Текст')),
                ('url', models.CharField(blank=True, help_text='Може бути порожнім для top_cards — тоді використовується extra.product_id.', max_length=500, verbose_name='URL (відносний або абсолютний)')),
                ('extra', models.JSONField(blank=True, default=dict, help_text="Наприклад {'product_id': 42} для top_cards або {'price': 599} для best_prices.", verbose_name='Додаткові дані')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='storefront.categoryseoblock', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Елемент SEO-блоку',
                'verbose_name_plural': 'Елементи SEO-блоків',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='categoryseoblock',
            index=models.Index(fields=['category', 'is_active', 'order'], name='idx_seoblock_cat_act_order'),
        ),
        migrations.AddIndex(
            model_name='categoryseoblock',
            index=models.Index(fields=['block_type'], name='idx_seoblock_type'),
        ),
        migrations.AddIndex(
            model_name='categoryseoblockitem',
            index=models.Index(fields=['block', 'order'], name='idx_seoblock_item_order'),
        ),
    ]
