# Generated by Django 5.2.11 on 2026-05-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0056_phase19h_seo_admin_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Мета-опис категорії (≤ 320 символів). Якщо порожньо — використовується автогенерований fallback.', max_length=320, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_h1',
            field=models.CharField(blank=True, help_text='Кастомний H1 для сторінки категорії (для випадку, коли видимий заголовок має відрізнятися від назви в навігації).', max_length=180, verbose_name='SEO H1'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Кастомний <title> для цієї категорії. Якщо порожньо — використовується «{Назва} - TwoComms».', max_length=180, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='catalogcolorseooverride',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='catalogcolorseooverride',
            name='queries_json',
            field=models.JSONField(blank=True, default=list, help_text="JSON-масив об’єктів {label, url, freq}, де freq — 'hf' / 'mf' / 'lf'. Якщо порожньо — використовуються куровані з коду.", verbose_name='Чипи-запити'),
        ),
    ]
