# Generated by Django 5.2.11 on 2026-05-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0058_phase21_seed_category_seo_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description_uk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uk',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_description_en',
            field=models.CharField(blank=True, help_text='Мета-опис категорії (≤ 320 символів). Якщо порожньо — використовується автогенерований fallback.', max_length=320, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_description_ru',
            field=models.CharField(blank=True, help_text='Мета-опис категорії (≤ 320 символів). Якщо порожньо — використовується автогенерований fallback.', max_length=320, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_description_uk',
            field=models.CharField(blank=True, help_text='Мета-опис категорії (≤ 320 символів). Якщо порожньо — використовується автогенерований fallback.', max_length=320, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_h1_en',
            field=models.CharField(blank=True, help_text='Кастомний H1 для сторінки категорії (для випадку, коли видимий заголовок має відрізнятися від назви в навігації).', max_length=180, null=True, verbose_name='SEO H1'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_h1_ru',
            field=models.CharField(blank=True, help_text='Кастомний H1 для сторінки категорії (для випадку, коли видимий заголовок має відрізнятися від назви в навігації).', max_length=180, null=True, verbose_name='SEO H1'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_h1_uk',
            field=models.CharField(blank=True, help_text='Кастомний H1 для сторінки категорії (для випадку, коли видимий заголовок має відрізнятися від назви в навігації).', max_length=180, null=True, verbose_name='SEO H1'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_intro_html_en',
            field=models.TextField(blank=True, help_text='Короткий HTML-блок під H1 (1–3 речення з основними ключами + опційно <details>...</details> або <div data-seo-collapsible> для розгортуваного блоку). Не показується на /catalog/ без фільтру категорії.', null=True, verbose_name='SEO-інтро над сіткою товарів'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_intro_html_ru',
            field=models.TextField(blank=True, help_text='Короткий HTML-блок під H1 (1–3 речення з основними ключами + опційно <details>...</details> або <div data-seo-collapsible> для розгортуваного блоку). Не показується на /catalog/ без фільтру категорії.', null=True, verbose_name='SEO-інтро над сіткою товарів'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_intro_html_uk',
            field=models.TextField(blank=True, help_text='Короткий HTML-блок під H1 (1–3 речення з основними ключами + опційно <details>...</details> або <div data-seo-collapsible> для розгортуваного блоку). Не показується на /catalog/ без фільтру категорії.', null=True, verbose_name='SEO-інтро над сіткою товарів'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_text_title_en',
            field=models.CharField(blank=True, help_text='H2 над довгим SEO-текстом категорії. Якщо порожньо — використовується назва категорії.', max_length=200, null=True, verbose_name='SEO-заголовок над описом'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_text_title_ru',
            field=models.CharField(blank=True, help_text='H2 над довгим SEO-текстом категорії. Якщо порожньо — використовується назва категорії.', max_length=200, null=True, verbose_name='SEO-заголовок над описом'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_text_title_uk',
            field=models.CharField(blank=True, help_text='H2 над довгим SEO-текстом категорії. Якщо порожньо — використовується назва категорії.', max_length=200, null=True, verbose_name='SEO-заголовок над описом'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_title_en',
            field=models.CharField(blank=True, help_text='Кастомний <title> для цієї категорії. Якщо порожньо — використовується «{Назва} - TwoComms».', max_length=180, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_title_ru',
            field=models.CharField(blank=True, help_text='Кастомний <title> для цієї категорії. Якщо порожньо — використовується «{Назва} - TwoComms».', max_length=180, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_title_uk',
            field=models.CharField(blank=True, help_text='Кастомний <title> для цієї категорії. Якщо порожньо — використовується «{Назва} - TwoComms».', max_length=180, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='care_instructions_en',
            field=models.TextField(blank=True, null=True, verbose_name='Догляд за товаром'),
        ),
        migrations.AddField(
            model_name='product',
            name='care_instructions_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Догляд за товаром'),
        ),
        migrations.AddField(
            model_name='product',
            name='care_instructions_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Догляд за товаром'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Опис (legacy)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Опис (legacy)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Опис (legacy)'),
        ),
        migrations.AddField(
            model_name='product',
            name='full_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Повний опис'),
        ),
        migrations.AddField(
            model_name='product',
            name='full_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Повний опис'),
        ),
        migrations.AddField(
            model_name='product',
            name='full_description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Повний опис'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_image_alt_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt-текст головного зображення'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_image_alt_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt-текст головного зображення'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_image_alt_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt-текст головного зображення'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_bottom_html_en',
            field=models.TextField(blank=True, default='', help_text='Опційний HTML-блок, який рендериться у нижній частині картки товару перед футером. Якщо порожній — генерується автоматично з тем та категорії товару.', null=True, verbose_name='SEO-блок внизу сторінки (опційно)'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_bottom_html_ru',
            field=models.TextField(blank=True, default='', help_text='Опційний HTML-блок, який рендериться у нижній частині картки товару перед футером. Якщо порожній — генерується автоматично з тем та категорії товару.', null=True, verbose_name='SEO-блок внизу сторінки (опційно)'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_bottom_html_uk',
            field=models.TextField(blank=True, default='', help_text='Опційний HTML-блок, який рендериться у нижній частині картки товару перед футером. Якщо порожній — генерується автоматично з тем та категорії товару.', null=True, verbose_name='SEO-блок внизу сторінки (опційно)'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_description_en',
            field=models.CharField(blank=True, max_length=320, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_description_ru',
            field=models.CharField(blank=True, max_length=320, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_description_uk',
            field=models.CharField(blank=True, max_length=320, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_keywords_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='SEO ключові слова'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_keywords_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='SEO ключові слова'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_keywords_uk',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='SEO ключові слова'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title_en',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title_ru',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title_uk',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Короткий опис'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Короткий опис'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_uk',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Короткий опис'),
        ),
        migrations.AddField(
            model_name='product',
            name='target_audience_en',
            field=models.TextField(blank=True, null=True, verbose_name='Кому підійде'),
        ),
        migrations.AddField(
            model_name='product',
            name='target_audience_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Кому підійде'),
        ),
        migrations.AddField(
            model_name='product',
            name='target_audience_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Кому підійде'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_uk',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productfaq',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='Відповідь'),
        ),
        migrations.AddField(
            model_name='productfaq',
            name='answer_ru',
            field=models.TextField(null=True, verbose_name='Відповідь'),
        ),
        migrations.AddField(
            model_name='productfaq',
            name='answer_uk',
            field=models.TextField(null=True, verbose_name='Відповідь'),
        ),
        migrations.AddField(
            model_name='productfaq',
            name='question_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Питання'),
        ),
        migrations.AddField(
            model_name='productfaq',
            name='question_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Питання'),
        ),
        migrations.AddField(
            model_name='productfaq',
            name='question_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Питання'),
        ),
    ]
