# Generated by Django 5.2.11 on 2026-05-15 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productcolors', '0007_normalize_slugs'),
        ('storefront', '0060_analyticsexclusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryColorLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_slug', models.SlugField(help_text="Англійський slug кольору (наприклад 'black' або 'navy-blue'). Заповнюється автоматично з імені кольору.", max_length=64, verbose_name='URL slug кольору')),
                ('seo_title', models.CharField(help_text='<title> сторінки. До 60 символів — оптимум для Google.', max_length=180, verbose_name='SEO Title')),
                ('seo_h1', models.CharField(blank=True, help_text='Якщо порожньо — використовується SEO Title.', max_length=180, verbose_name='SEO H1')),
                ('seo_description', models.CharField(help_text='meta description. 140–160 символів — оптимум.', max_length=320, verbose_name='SEO Description')),
                ('editorial_html', models.TextField(help_text='Унікальний редакційний текст українською (HTML). Для публікації потрібно мінімум 800 символів.', verbose_name='Editorial copy (HTML)')),
                ('faq_items', models.JSONField(blank=True, default=list, help_text="Список словників: [{'question': '...', 'answer': '...'}, ...]. Рекомендовано 4–6 пунктів.", verbose_name='FAQ Q/A пари')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубліковано')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_landings', to='storefront.category', verbose_name='Категорія')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_landings', to='productcolors.color', verbose_name='Колір')),
            ],
            options={
                'verbose_name': 'Color-category landing',
                'verbose_name_plural': 'Color-category landings',
                'ordering': ['category__order', 'order', 'color_slug'],
                'indexes': [models.Index(fields=['is_published'], name='idx_cclanding_published'), models.Index(fields=['category', 'is_published'], name='idx_cclanding_cat_pub')],
                'unique_together': {('category', 'color_slug')},
            },
        ),
    ]
