# Generated by Django 5.2.11 on 2026-05-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0063_seed_not_money_products_seo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleIndexingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=512, verbose_name='URL')),
                ('notification_type', models.CharField(choices=[('URL_UPDATED', 'URL_UPDATED'), ('URL_DELETED', 'URL_DELETED')], default='URL_UPDATED', max_length=16)),
                ('status', models.CharField(choices=[('success', 'Прийнято'), ('failed', 'Помилка')], max_length=16)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, help_text="Звідки прилетів пінг: 'admin', 'signal', 'cron', 'manual'.", max_length=32)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submission_date', models.DateField(db_index=True, help_text="Денна агрегація (UTC дата відправлення) — для дешевих 'сьогодні' запитів.")),
            ],
            options={
                'verbose_name': 'Google Indexing submission',
                'verbose_name_plural': 'Google Indexing submissions',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['submission_date', 'status'], name='idx_gix_date_status'), models.Index(fields=['-submitted_at'], name='idx_gix_submitted_desc')],
            },
        ),
    ]
