# Generated by Django 5.2.11 on 2026-05-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0065_customprintlead_notification_dedupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='customprintlead',
            name='telegram_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Коли підтверджено Telegram'),
        ),
        migrations.AddField(
            model_name='customprintlead',
            name='telegram_verified_first_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Імʼя у Telegram'),
        ),
        migrations.AddField(
            model_name='customprintlead',
            name='telegram_verified_last_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Прізвище у Telegram'),
        ),
        migrations.AddField(
            model_name='customprintlead',
            name='telegram_verified_phone',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Телефон (підтверджено через Telegram)'),
        ),
        migrations.AddField(
            model_name='customprintlead',
            name='telegram_verified_user_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Telegram user_id (підтверджено через бота)'),
        ),
        migrations.AddField(
            model_name='customprintlead',
            name='telegram_verified_username',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Telegram @username (підтверджено)'),
        ),
    ]
