# Generated by Django 5.2.11 on 2026-05-24 22:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0067_product_search_keywords'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True, verbose_name='Назва')),
                ('name_uk', models.CharField(max_length=140, null=True, unique=True, verbose_name='Назва')),
                ('name_ru', models.CharField(max_length=140, null=True, unique=True, verbose_name='Назва')),
                ('name_en', models.CharField(max_length=140, null=True, unique=True, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='URL slug')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('description_uk', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('seo_title', models.CharField(blank=True, max_length=180, verbose_name='SEO Title')),
                ('seo_title_uk', models.CharField(blank=True, max_length=180, null=True, verbose_name='SEO Title')),
                ('seo_title_ru', models.CharField(blank=True, max_length=180, null=True, verbose_name='SEO Title')),
                ('seo_title_en', models.CharField(blank=True, max_length=180, null=True, verbose_name='SEO Title')),
                ('seo_h1', models.CharField(blank=True, max_length=180, verbose_name='SEO H1')),
                ('seo_h1_uk', models.CharField(blank=True, max_length=180, null=True, verbose_name='SEO H1')),
                ('seo_h1_ru', models.CharField(blank=True, max_length=180, null=True, verbose_name='SEO H1')),
                ('seo_h1_en', models.CharField(blank=True, max_length=180, null=True, verbose_name='SEO H1')),
                ('seo_description', models.CharField(blank=True, max_length=320, verbose_name='SEO Description')),
                ('seo_description_uk', models.CharField(blank=True, max_length=320, null=True, verbose_name='SEO Description')),
                ('seo_description_ru', models.CharField(blank=True, max_length=320, null=True, verbose_name='SEO Description')),
                ('seo_description_en', models.CharField(blank=True, max_length=320, null=True, verbose_name='SEO Description')),
                ('bottom_title', models.CharField(blank=True, max_length=180, verbose_name='Нижній SEO-заголовок')),
                ('bottom_title_uk', models.CharField(blank=True, max_length=180, null=True, verbose_name='Нижній SEO-заголовок')),
                ('bottom_title_ru', models.CharField(blank=True, max_length=180, null=True, verbose_name='Нижній SEO-заголовок')),
                ('bottom_title_en', models.CharField(blank=True, max_length=180, null=True, verbose_name='Нижній SEO-заголовок')),
                ('bottom_text', models.TextField(blank=True, verbose_name='Нижній SEO-текст')),
                ('bottom_text_uk', models.TextField(blank=True, null=True, verbose_name='Нижній SEO-текст')),
                ('bottom_text_ru', models.TextField(blank=True, null=True, verbose_name='Нижній SEO-текст')),
                ('bottom_text_en', models.TextField(blank=True, null=True, verbose_name='Нижній SEO-текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Категорія блогу',
                'verbose_name_plural': 'Категорії блогу',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='idx_blogcat_active_order'), models.Index(fields=['slug'], name='idx_blogcat_slug')],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Заголовок')),
                ('title_uk', models.CharField(max_length=220, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=220, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=220, null=True, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='URL slug')),
                ('excerpt', models.TextField(blank=True, verbose_name='Короткий опис')),
                ('excerpt_uk', models.TextField(blank=True, null=True, verbose_name='Короткий опис')),
                ('excerpt_ru', models.TextField(blank=True, null=True, verbose_name='Короткий опис')),
                ('excerpt_en', models.TextField(blank=True, null=True, verbose_name='Короткий опис')),
                ('content_html', models.TextField(verbose_name='HTML-контент')),
                ('content_html_uk', models.TextField(null=True, verbose_name='HTML-контент')),
                ('content_html_ru', models.TextField(null=True, verbose_name='HTML-контент')),
                ('content_html_en', models.TextField(null=True, verbose_name='HTML-контент')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/covers/', verbose_name='Обкладинка')),
                ('cover_alt', models.CharField(blank=True, max_length=180, verbose_name='Alt обкладинки')),
                ('cover_alt_uk', models.CharField(blank=True, max_length=180, null=True, verbose_name='Alt обкладинки')),
                ('cover_alt_ru', models.CharField(blank=True, max_length=180, null=True, verbose_name='Alt обкладинки')),
                ('cover_alt_en', models.CharField(blank=True, max_length=180, null=True, verbose_name='Alt обкладинки')),
                ('source_url', models.URLField(blank=True, verbose_name='Джерело')),
                ('seo_title', models.CharField(blank=True, max_length=180, verbose_name='SEO Title')),
                ('seo_title_uk', models.CharField(blank=True, max_length=180, null=True, verbose_name='SEO Title')),
                ('seo_title_ru', models.CharField(blank=True, max_length=180, null=True, verbose_name='SEO Title')),
                ('seo_title_en', models.CharField(blank=True, max_length=180, null=True, verbose_name='SEO Title')),
                ('seo_description', models.CharField(blank=True, max_length=320, verbose_name='SEO Description')),
                ('seo_description_uk', models.CharField(blank=True, max_length=320, null=True, verbose_name='SEO Description')),
                ('seo_description_ru', models.CharField(blank=True, max_length=320, null=True, verbose_name='SEO Description')),
                ('seo_description_en', models.CharField(blank=True, max_length=320, null=True, verbose_name='SEO Description')),
                ('seo_keywords', models.CharField(blank=True, max_length=320, verbose_name='SEO keywords')),
                ('seo_keywords_uk', models.CharField(blank=True, max_length=320, null=True, verbose_name='SEO keywords')),
                ('seo_keywords_ru', models.CharField(blank=True, max_length=320, null=True, verbose_name='SEO keywords')),
                ('seo_keywords_en', models.CharField(blank=True, max_length=320, null=True, verbose_name='SEO keywords')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публікації')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Перегляди')),
                ('unique_view_count', models.PositiveIntegerField(default=0, verbose_name='Унікальні перегляди')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='storefront.blogcategory', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Пост блогу',
                'verbose_name_plural': 'Пости блогу',
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BlogPostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_key', models.CharField(max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('path', models.CharField(blank=True, max_length=300)),
                ('views', models.PositiveIntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_events', to='storefront.blogpost')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_post_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Перегляд поста блогу',
                'verbose_name_plural': 'Перегляди постів блогу',
            },
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['is_published', '-published_at'], name='idx_blogpost_pub_date'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['category', 'is_published'], name='idx_blogpost_cat_pub'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['slug'], name='idx_blogpost_slug'),
        ),
        migrations.AddIndex(
            model_name='blogpostview',
            index=models.Index(fields=['post', 'last_seen'], name='idx_blogview_post_seen'),
        ),
        migrations.AddIndex(
            model_name='blogpostview',
            index=models.Index(fields=['visitor_key'], name='idx_blogview_visitor'),
        ),
        migrations.AddConstraint(
            model_name='blogpostview',
            constraint=models.UniqueConstraint(fields=('post', 'visitor_key'), name='uniq_blog_post_view_key'),
        ),
    ]
