# Generated by Django 5.2.11 on 2026-05-25 09:46

from django.db import migrations, models


def upgrade_veteran_fund_post(apps, schema_editor):
    BlogPost = apps.get_model("storefront", "BlogPost")
    db_alias = schema_editor.connection.alias
    try:
        post = BlogPost.objects.using(db_alias).get(slug="twocomms-veteran-fund-progress")
    except BlogPost.DoesNotExist:
        return

    uk_content = """
<section class="article-lede-panel">
  <p>TwoComms продовжує розвиток після підтримки Українського ветеранського фонду. Для нас це не просто новина в блозі, а робочий звіт про те, як бренд стає сильнішим, зрозумілішим і кориснішим для людей, які хочуть одяг із власним характером.</p>
</section>
<h2>Що вже закрито у другому етапі</h2>
<p>За внутрішнім планом команди вже закрито 2 з 4 етапів. Другий етап був сфокусований на продуктивності: ми стабілізували базові процеси, посилили контентну систему і зробили окремий акцент на напрямі кастомних принтів.</p>
<div class="article-stage-board">
  <div class="stage-card done"><span>01</span><strong>База виробництва</strong><p>Стабілізація процесів, підготовка речей і контроль якості.</p></div>
  <div class="stage-card done"><span>02</span><strong>Кастомні принти</strong><p>Розширення напряму, де клієнт може створити власний знак, текст або ідею для друку.</p></div>
  <div class="stage-card"><span>03</span><strong>Матеріали і масштаб</strong><p>Наступний крок — більше варіантів, сильніша подача і зрозуміліша система вибору.</p></div>
  <div class="stage-card"><span>04</span><strong>Відео і прозорість</strong><p>Плануємо показати процеси детальніше через відео, огляди і практичні пояснення.</p></div>
</div>
<h2>Чому це важливо для грантодавця</h2>
<p>Підтримка фонду перетворюється на конкретний результат: бренд не стоїть на місці, а підсилює виробничу дисципліну, швидкість роботи і напрям кастомізації. Це напряму впливає на те, наскільки швидко TwoComms може приймати ідеї клієнтів, готувати принти та пояснювати якість готової речі.</p>
<div class="article-callout type-tip">
  <div class="callout-icon"><i class="fas fa-bolt" aria-hidden="true"></i></div>
  <div class="callout-content"><strong>Фокус другого етапу:</strong> більше продуктивності, чіткіший процес створення кастомних принтів і готовність масштабувати цей напрям без втрати характеру бренда.</div>
</div>
<h2>Кастомний принт як окремий напрям</h2>
<p>Ми хочемо, щоб клієнт міг прийти не тільки за готовою річчю, а й за власним принтом: для команди, події, підрозділу, бренда або особистого символу. Тому на цьому етапі ми винесли кастомізацію в окремий маршрут і будемо розвивати його як одну з ключових можливостей TwoComms.</p>
<div class="article-action-box">
  <a href="/custom-print/" class="article-action-btn">Створити кастомний принт <i class="fas fa-arrow-right" aria-hidden="true"></i></a>
</div>
<h2>Що буде далі</h2>
<p>Наступні етапи стосуватимуться масштабування, нових матеріалів, кращої комунікації навколо речей TwoComms і більш наочного контенту. Ми плануємо підготувати розширене відео та огляди, щоб показати, що саме отримує клієнт з кожним наступним кроком розвитку бренда.</p>
<blockquote>
  <p>Кожен етап робить TwoComms універсальнішим, швидшим і точнішим, але головна ідея лишається незмінною: одяг має мати характер.</p>
  <cite>TwoComms editorial</cite>
</blockquote>
"""
    ru_content = """
<section class="article-lede-panel">
  <p>TwoComms продолжает развиваться после поддержки Украинского ветеранского фонда. Для нас это не просто новость в блоге, а рабочий отчет о том, как бренд становится сильнее, понятнее и полезнее для людей, которым нужна одежда с собственным характером.</p>
</section>
<h2>Что уже закрыто во втором этапе</h2>
<p>По внутреннему плану команды уже закрыты 2 из 4 этапов. Второй этап был сфокусирован на продуктивности: мы стабилизировали базовые процессы, усилили контентную систему и сделали отдельный акцент на направлении кастомных принтов.</p>
<div class="article-stage-board">
  <div class="stage-card done"><span>01</span><strong>База производства</strong><p>Стабилизация процессов, подготовка вещей и контроль качества.</p></div>
  <div class="stage-card done"><span>02</span><strong>Кастомные принты</strong><p>Расширение направления, где клиент может создать собственный знак, текст или идею для печати.</p></div>
  <div class="stage-card"><span>03</span><strong>Материалы и масштаб</strong><p>Следующий шаг — больше вариантов, сильнее подача и понятнее система выбора.</p></div>
  <div class="stage-card"><span>04</span><strong>Видео и прозрачность</strong><p>Планируем показать процессы подробнее через видео, обзоры и практические объяснения.</p></div>
</div>
<h2>Почему это важно для грантодателя</h2>
<p>Поддержка фонда превращается в конкретный результат: бренд не стоит на месте, а усиливает производственную дисциплину, скорость работы и направление кастомизации.</p>
<div class="article-callout type-tip">
  <div class="callout-icon"><i class="fas fa-bolt" aria-hidden="true"></i></div>
  <div class="callout-content"><strong>Фокус второго этапа:</strong> больше продуктивности, четче процесс создания кастомных принтов и готовность масштабировать это направление без потери характера бренда.</div>
</div>
<h2>Кастомный принт как отдельное направление</h2>
<p>Мы хотим, чтобы клиент мог прийти не только за готовой вещью, но и за собственным принтом: для команды, события, подразделения, бренда или личного символа.</p>
<div class="article-action-box">
  <a href="/custom-print/" class="article-action-btn">Создать кастомный принт <i class="fas fa-arrow-right" aria-hidden="true"></i></a>
</div>
<h2>Что будет дальше</h2>
<p>Следующие этапы будут связаны с масштабированием, новыми материалами, более сильной коммуникацией вокруг вещей TwoComms и более наглядным контентом.</p>
<blockquote>
  <p>Каждый этап делает TwoComms универсальнее, быстрее и точнее, но главная идея остается неизменной: одежда должна иметь характер.</p>
  <cite>TwoComms editorial</cite>
</blockquote>
"""
    en_content = """
<section class="article-lede-panel">
  <p>TwoComms continues to grow after support from the Ukrainian Veterans Fund. This is a working update on how the brand is becoming more productive, clearer and more useful for people who want apparel with character.</p>
</section>
<h2>What the second stage closed</h2>
<p>According to the team's internal roadmap, 2 of 4 stages are already complete. The second stage focused on productivity: stabilizing core processes, strengthening the content system and separating custom prints into a clearer direction.</p>
<div class="article-stage-board">
  <div class="stage-card done"><span>01</span><strong>Production base</strong><p>Process stabilization, garment preparation and quality control.</p></div>
  <div class="stage-card done"><span>02</span><strong>Custom prints</strong><p>A stronger route where a customer can create a personal sign, text or print idea.</p></div>
  <div class="stage-card"><span>03</span><strong>Materials and scale</strong><p>More options, stronger presentation and a clearer choice system.</p></div>
  <div class="stage-card"><span>04</span><strong>Video and clarity</strong><p>More process visibility through video, reviews and practical explanations.</p></div>
</div>
<h2>Why this matters for the grantor</h2>
<p>The fund's support is turning into concrete progress: the brand is improving production discipline, speed and customization capabilities.</p>
<div class="article-callout type-tip">
  <div class="callout-icon"><i class="fas fa-bolt" aria-hidden="true"></i></div>
  <div class="callout-content"><strong>Second-stage focus:</strong> more productivity, a clearer custom-print process and readiness to scale without losing the brand character.</div>
</div>
<h2>Custom print as a separate direction</h2>
<p>We want a customer to come not only for a finished piece, but also for a personal print: for a team, event, unit, brand or personal symbol.</p>
<div class="article-action-box">
  <a href="/custom-print/" class="article-action-btn">Create a custom print <i class="fas fa-arrow-right" aria-hidden="true"></i></a>
</div>
<h2>What comes next</h2>
<p>The next stages will focus on scaling, new materials, stronger communication around TwoComms pieces and more visual content.</p>
<blockquote>
  <p>Every stage makes TwoComms more universal, faster and clearer, while the main idea stays the same: apparel should have character.</p>
  <cite>TwoComms editorial</cite>
</blockquote>
"""
    fields = {
        "content_html": uk_content.strip(),
        "content_html_uk": uk_content.strip(),
        "content_html_ru": ru_content.strip(),
        "content_html_en": en_content.strip(),
        "excerpt": "Другий етап внутрішнього плану вже закрито: TwoComms посилив продуктивність, стабілізував процеси і зробив окремий акцент на кастомних принтах.",
        "excerpt_uk": "Другий етап внутрішнього плану вже закрито: TwoComms посилив продуктивність, стабілізував процеси і зробив окремий акцент на кастомних принтах.",
        "excerpt_ru": "Второй этап внутреннего плана уже закрыт: TwoComms усилил продуктивность, стабилизировал процессы и сделал отдельный акцент на кастомных принтах.",
        "excerpt_en": "The second internal stage is complete: TwoComms improved productivity, stabilized processes and separated custom prints as a stronger direction.",
        "cta_label": "Створити кастомний принт",
        "cta_label_uk": "Створити кастомний принт",
        "cta_label_ru": "Создать кастомный принт",
        "cta_label_en": "Create a custom print",
        "cta_url": "/custom-print/",
        "cta_text": "Другий етап посилив напрям кастомізації. Якщо у вас є символ, текст або ідея для речі, її вже можна перевести у власний принт TwoComms.",
        "cta_text_uk": "Другий етап посилив напрям кастомізації. Якщо у вас є символ, текст або ідея для речі, її вже можна перевести у власний принт TwoComms.",
        "cta_text_ru": "Второй этап усилил направление кастомизации. Если у вас есть символ, текст или идея для вещи, ее уже можно превратить в собственный принт TwoComms.",
        "cta_text_en": "The second stage strengthened customization. If you have a symbol, text or idea for a piece, it can already become a custom TwoComms print.",
    }
    for field, value in fields.items():
        if hasattr(post, field):
            setattr(post, field, value)
    post.save(using=db_alias)


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0069_seed_blog_categories_and_first_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cta_label',
            field=models.CharField(blank=True, max_length=140, verbose_name='CTA текст'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cta_label_en',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='CTA текст'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cta_label_ru',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='CTA текст'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cta_label_uk',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='CTA текст'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cta_text',
            field=models.CharField(blank=True, max_length=260, verbose_name='CTA підпис'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cta_text_en',
            field=models.CharField(blank=True, max_length=260, null=True, verbose_name='CTA підпис'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cta_text_ru',
            field=models.CharField(blank=True, max_length=260, null=True, verbose_name='CTA підпис'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cta_text_uk',
            field=models.CharField(blank=True, max_length=260, null=True, verbose_name='CTA підпис'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cta_url',
            field=models.CharField(blank=True, max_length=300, verbose_name='CTA URL'),
        ),
        migrations.RunPython(upgrade_veteran_fund_post, migrations.RunPython.noop),
    ]
