# Generated by Django 5.2.11 on 2026-05-27 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0071_polish_veteran_fund_blog_article'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogMediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='blog/media/', verbose_name='Файл')),
                ('width', models.PositiveIntegerField(default=0, verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='Висота')),
                ('alt', models.JSONField(blank=True, default=dict, verbose_name='Alt за мовами')),
                ('caption', models.JSONField(blank=True, default=dict, verbose_name='Підпис за мовами')),
                ('credit', models.JSONField(blank=True, default=dict, verbose_name='Автор/джерело за мовами')),
                ('focal_x', models.PositiveSmallIntegerField(default=50, verbose_name='Фокус X')),
                ('focal_y', models.PositiveSmallIntegerField(default=50, verbose_name='Фокус Y')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Медіа блогу',
                'verbose_name_plural': 'Медіа блогу',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BlogPostBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('rich_text', 'Текст'), ('image', 'Зображення'), ('gallery', 'Галерея'), ('youtube_video', 'YouTube'), ('cta_group', 'CTA / соцмережі'), ('product_cta', 'Товар'), ('metric_cards', 'Метрики'), ('table_specs', 'Таблиця / specs'), ('quote', 'Цитата'), ('callout', 'Callout'), ('faq', 'FAQ'), ('source_list', 'Джерела'), ('locked_content', 'Прихований контент'), ('promo_claim', 'Промокод')], max_length=32, verbose_name='Тип блоку')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Увімкнено')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Дані блоку')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Блок поста блогу',
                'verbose_name_plural': 'Блоки постів блогу',
                'ordering': ['post', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BlogPromoCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Назва кампанії')),
                ('code_prefix', models.CharField(default='BLOG', max_length=8, verbose_name='Префікс коду')),
                ('discount_type', models.CharField(choices=[('percentage', 'Відсоток'), ('fixed', 'Фіксована сума')], max_length=10, verbose_name='Тип знижки')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Значення знижки')),
                ('max_claims', models.PositiveIntegerField(default=0, verbose_name='Максимум видач (0 = безліміт)')),
                ('valid_days', models.PositiveIntegerField(default=14, verbose_name='Днів дії після видачі')),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Мін. сума')),
                ('one_time_per_user', models.BooleanField(default=True, verbose_name='Одноразово для користувача')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Промо-кампанія блогу',
                'verbose_name_plural': 'Промо-кампанії блогу',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BlogPromoClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Видача промокоду з блогу',
                'verbose_name_plural': 'Видачі промокодів з блогу',
            },
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='storefront.blogcategory', verbose_name='Батьківська категорія'),
        ),
        migrations.AddIndex(
            model_name='blogcategory',
            index=models.Index(fields=['parent', 'is_active', 'order'], name='idx_blogcat_parent_active'),
        ),
        migrations.AddField(
            model_name='blogpostblock',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='storefront.blogpost', verbose_name='Пост'),
        ),
        migrations.AddIndex(
            model_name='blogpromocampaign',
            index=models.Index(fields=['is_active', '-created_at'], name='idx_blogpromo_active'),
        ),
        migrations.AddField(
            model_name='blogpromoclaim',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_claims', to='storefront.blogpostblock', verbose_name='Блок'),
        ),
        migrations.AddField(
            model_name='blogpromoclaim',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='storefront.blogpromocampaign', verbose_name='Кампанія'),
        ),
        migrations.AddField(
            model_name='blogpromoclaim',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_claims', to='storefront.blogpost', verbose_name='Пост'),
        ),
        migrations.AddField(
            model_name='blogpromoclaim',
            name='promo_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='blog_claim', to='storefront.promocode'),
        ),
        migrations.AddField(
            model_name='blogpromoclaim',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_promo_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='blogpostblock',
            index=models.Index(fields=['post', 'is_enabled', 'sort_order'], name='idx_blogblock_post_order'),
        ),
        migrations.AddIndex(
            model_name='blogpostblock',
            index=models.Index(fields=['block_type'], name='idx_blogblock_type'),
        ),
        migrations.AddIndex(
            model_name='blogpromoclaim',
            index=models.Index(fields=['post', 'created_at'], name='idx_blogclaim_post_created'),
        ),
        migrations.AddIndex(
            model_name='blogpromoclaim',
            index=models.Index(fields=['user', 'created_at'], name='idx_blogclaim_user_created'),
        ),
        migrations.AddConstraint(
            model_name='blogpromoclaim',
            constraint=models.UniqueConstraint(fields=('campaign', 'user'), name='uniq_blogpromo_campaign_user'),
        ),
        migrations.AddConstraint(
            model_name='blogpromoclaim',
            constraint=models.UniqueConstraint(fields=('block', 'user'), name='uniq_blogpromo_block_user'),
        ),
    ]
