# Generated by Django 5.2.11 on 2026-05-27 16:55

from django.db import migrations, models


def seed_veteran_cover_caption(apps, schema_editor):
    BlogPost = apps.get_model("storefront", "BlogPost")
    db = schema_editor.connection.alias
    BlogPost.objects.using(db).filter(
        slug="twocomms-veteran-fund-progress",
        cover_caption="",
    ).update(
        cover_caption="TWOCOMMS / Український ветеранський фонд / DTF",
        cover_caption_uk="TWOCOMMS / Український ветеранський фонд / DTF",
        cover_caption_ru="TWOCOMMS / Украинский ветеранский фонд / DTF",
        cover_caption_en="TWOCOMMS / Ukrainian Veteran Fund / DTF",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0073_seed_blog_structured_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cover_caption',
            field=models.TextField(blank=True, default='', verbose_name='Підпис обкладинки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cover_caption_en',
            field=models.TextField(blank=True, null=True, verbose_name='Підпис обкладинки'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cover_caption_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Підпис обкладинки'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cover_caption_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Підпис обкладинки'),
        ),
        migrations.RunPython(seed_veteran_cover_caption, migrations.RunPython.noop),
    ]
