# Generated by Django 5.2.11 on 2026-08-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0089_indexnow_submission'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['order', 'name_uk'], name='idx_category_order-uk'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['order', 'name_ru'], name='idx_category_order-ru'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['order', 'name_en'], name='idx_category_order-en'),
        ),
    ]
