# Generated by Django 5.2.11 on 2026-08-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('storefront', '0092_repair_lord_lending_uk_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='utmsession',
            name='srsltid',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Google Free Listings Click ID'),
        ),
        migrations.AddField(
            model_name='utmsession',
            name='gbraid',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Google App Click ID (GBRAID)'),
        ),
        migrations.AddField(
            model_name='utmsession',
            name='wbraid',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Google Web-to-App Click ID (WBRAID)'),
        ),
        migrations.AddField(
            model_name='utmsession',
            name='msclkid',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Microsoft Click ID'),
        ),
        migrations.AddField(
            model_name='utmsession',
            name='yclid',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Yandex Click ID'),
        ),
    ]
