# Generated by Django 6.1 on 2026-08-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0095_promocode_guest_ugc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogcolorseooverride',
            name='body_html',
            field=models.TextField(blank=True, help_text="Параграфи у форматі HTML (наприклад '<p>Перший абзац…</p><p>Другий…</p>'). Дозволені теги <a>, <strong>, <em>. Для «general» порожнє поле нічого не публікує; для «brand»/«category» використовуються куровані параграфи з коду.", verbose_name='HTML-параграфи'),
        ),
        migrations.AlterField(
            model_name='catalogcolorseooverride',
            name='h2',
            field=models.CharField(blank=True, help_text='Для «general» порожнє поле не підставляє текст з коду. Для «brand»/«category» порожнє поле залишає курований заголовок.', max_length=300, verbose_name='Заголовок (H2)'),
        ),
        migrations.AlterField(
            model_name='catalogcolorseooverride',
            name='queries_json',
            field=models.JSONField(blank=True, default=list, help_text="JSON-масив об’єктів {label, url, freq}, де freq — 'hf' / 'mf' / 'lf'. Для «general» порожнє поле нічого не публікує; для «brand»/«category» використовуються куровані чипи з коду.", verbose_name='Чипи-запити'),
        ),
    ]
