# Generated by Django 5.2.11 on 2026-05-30 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_monobank_integration'),
        ('finance', '0002_user_settings_push'),
    ]

    operations = [
    ]
