# Generated by Django 5.2.11 on 2026-05-30 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_merge_20260530_1839'),
        ('finance', '0003_merge_20260531_0134'),
    ]

    operations = [
    ]
