# Generated by Django 5.2.11 on 2026-05-31 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_merge_20260531_0145'),
        ('finance', '0004_owner_drawings_category'),
    ]

    operations = [
    ]
