# Generated by Claude Opus 4.8 on 2026-05-31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_personal_expense_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurrencerule',
            name='next_occurrence',
            field=models.DateField(blank=True, null=True, help_text='Дата наступного автоматичного створення планової транзакції'),
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='auto_create',
            field=models.BooleanField(default=True, help_text='Автоматично створювати планові транзакції'),
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='notification_days_before',
            field=models.PositiveIntegerField(default=3, help_text='За скільки днів надсилати нагадування'),
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='last_generated_at',
            field=models.DateTimeField(blank=True, null=True, help_text='Коли останній раз генерували транзакцію'),
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='template_amount',
            field=models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True, help_text='Сума шаблону для створення транзакцій'),
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='template_account',
            field=models.ForeignKey(blank=True, help_text='Рахунок шаблону', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrence_rules_as_template', to='finance.account'),
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='template_category',
            field=models.ForeignKey(blank=True, help_text='Категорія шаблону', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrence_rules_as_template', to='finance.category'),
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='template_type',
            field=models.CharField(max_length=12, choices=[('income', 'Дохід'), ('expense', 'Витрата')], default='expense', help_text='Тип транзакції шаблону'),
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='template_comment',
            field=models.TextField(blank=True, default='', help_text='Коментар шаблону'),
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Чи активне правило'),
        ),
    ]
