# Generated by Django 5.2.11 on 2026-05-31 17:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_recurrence_improvements'),
        ('warehouse', '0004_consumable_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='counterparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='finance.counterparty'),
        ),
        migrations.CreateModel(
            name='ConsignmentShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, default='', max_length=64, verbose_name='Номер накладної')),
                ('date', models.DateField(verbose_name='Дата відправки')),
                ('debt_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('currency', models.CharField(default='UAH', max_length=3)),
                ('comment', models.TextField(blank=True, default='')),
                ('external_source', models.CharField(blank=True, default='', max_length=16)),
                ('external_ref', models.CharField(blank=True, default='', max_length=64)),
                ('is_demo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachments', models.ManyToManyField(blank=True, related_name='consignment_shipments', to='finance.attachment')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignment_shipments', to='finance.company')),
                ('debt_txn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.transaction')),
            ],
            options={
                'verbose_name': 'Поставка магазину',
                'verbose_name_plural': 'Поставки магазинів',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConsignmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_kind', models.CharField(choices=[('manual', 'Вручну'), ('stock', 'Склад'), ('external', 'Менеджмент')], default='manual', max_length=12)),
                ('external_ref', models.CharField(blank=True, default='', max_length=64)),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('print_name', models.CharField(blank=True, default='', max_length=128, verbose_name='Принт')),
                ('color', models.CharField(blank=True, default='', max_length=64, verbose_name='Колір')),
                ('size', models.CharField(blank=True, default='', max_length=16, verbose_name='Розмір')),
                ('qty', models.PositiveIntegerField(default=0, verbose_name='Кількість')),
                ('sold_qty', models.PositiveIntegerField(default=0, verbose_name='Продано')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Собівартість за од.')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, verbose_name='Ціна продажу за од.')),
                ('is_consignment', models.BooleanField(default=True, verbose_name='Під реалізацію')),
                ('comment', models.TextField(blank=True, default='')),
                ('is_demo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignment_items', to='finance.company')),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='warehouse.stockitem')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.consignmentshipment')),
            ],
            options={
                'verbose_name': 'Позиція поставки',
                'verbose_name_plural': 'Позиції поставок',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Reseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва магазину')),
                ('status', models.CharField(choices=[('active', 'Активний'), ('paused', 'Призупинено'), ('closed', 'Закрито')], default='active', max_length=16)),
                ('terms_kind', models.CharField(choices=[('onetime', 'Одноразово (через N днів)'), ('installment', 'Розстрочка (період × сума)'), ('periodic', 'Безстроково періодично')], default='installment', max_length=16)),
                ('terms', models.JSONField(blank=True, default=dict)),
                ('contacts', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_demo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resellers', to='finance.company')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resellers', to='finance.counterparty', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'Магазин (реалізація)',
                'verbose_name_plural': 'Магазини (реалізація)',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='consignmentshipment',
            name='reseller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='finance.reseller'),
        ),
        migrations.CreateModel(
            name='ConsignmentSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('creates_debt', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignment_sales', to='finance.company')),
                ('debt_txn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.transaction')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='finance.consignmentitem')),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='finance.reseller')),
            ],
            options={
                'verbose_name': 'Продаж під реалізацію',
                'verbose_name_plural': 'Продажі під реалізацію',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='consignmentitem',
            name='reseller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignment_items', to='finance.reseller'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reseller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.reseller'),
        ),
        migrations.CreateModel(
            name='ResellerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='UAH', max_length=3)),
                ('comment', models.TextField(blank=True, default='')),
                ('is_demo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseller_payments', to='finance.company')),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.reseller')),
                ('txn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.transaction')),
            ],
            options={
                'verbose_name': 'Виплата магазину',
                'verbose_name_plural': 'Виплати магазинів',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='reseller',
            index=models.Index(fields=['company', 'status'], name='idx_reseller_comp_status'),
        ),
        migrations.AddIndex(
            model_name='consignmentshipment',
            index=models.Index(fields=['company', 'reseller'], name='idx_cons_ship_comp_res'),
        ),
        migrations.AddIndex(
            model_name='consignmentitem',
            index=models.Index(fields=['reseller', 'is_consignment'], name='idx_cons_item_res_cons'),
        ),
        migrations.AddIndex(
            model_name='consignmentitem',
            index=models.Index(fields=['shipment'], name='idx_cons_item_ship'),
        ),
    ]
