# Generated by Django 5.2.11 on 2026-05-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_account_counterparty_and_consignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignmentshipment',
            name='ttn',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='ТТН Нової Пошти'),
        ),
    ]
