# Generated by Django 5.2.11 on 2026-05-31 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_consignment_ttn'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='color',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
