# Generated by Django 5.2.11 on 2026-06-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_account_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='icon_image',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='account',
            name='icon_type',
            field=models.CharField(blank=True, choices=[('', 'Без іконки'), ('emoji', 'Емодзі'), ('bank', 'Банк'), ('image', 'Своє зображення')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='account',
            name='icon_value',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
