# Generated by Django 5.2.11 on 2026-06-01 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_account_icons'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurrencerule',
            name='end_mode',
            field=models.CharField(choices=[('never', 'Безстроково'), ('until', 'До дати'), ('count', 'Певну кількість разів')], default='never', max_length=8),
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='template_counterparty',
            field=models.ForeignKey(blank=True, help_text='Контрагент шаблону', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrence_rules_as_template', to='finance.counterparty'),
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='template_currency',
            field=models.CharField(blank=True, default='UAH', max_length=3),
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='template_is_business',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='template_project',
            field=models.ForeignKey(blank=True, help_text='Проєкт шаблону', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrence_rules_as_template', to='finance.project'),
        ),
        migrations.AddField(
            model_name='recurrencerule',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
