# Generated by Django 5.2.11 on 2026-06-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_estimated_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='push_health_alerts',
            field=models.BooleanField(default=True, verbose_name='Сповіщення про фінансові ризики'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='push_weekly_time',
            field=models.TimeField(default='10:00', verbose_name='Час тижневого звіту'),
        ),
    ]
