# Generated by Django 5.2.11 on 2026-06-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_usersettings_push_health_alerts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='push_large_txn',
            field=models.BooleanField(default=False, verbose_name='Сповіщення про великі операції'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='push_large_txn_threshold',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=18, verbose_name='Поріг великої операції'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='push_planned_reminders',
            field=models.BooleanField(default=False, verbose_name='Нагадування про планові платежі'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='type',
            field=models.CharField(choices=[('client', 'Клієнт'), ('supplier', 'Постачальник'), ('reseller_partner', 'Магазин-партнер (реалізація)'), ('collaboration', 'Колаборація'), ('landlord_business', 'Орендодавець (бізнес)'), ('landlord_personal', 'Орендодавець (житло)'), ('contractor', 'Підрядник / виконавець'), ('marketplace', 'Маркетплейс'), ('logistics', 'Логістика / доставка'), ('employee', 'Співробітник'), ('investor', 'Інвестор / партнер'), ('bank', 'Банк / фінустанова'), ('government', 'Держоргани'), ('other', 'Інше')], default='client', max_length=20),
        ),
    ]
