# Generated by Django 5.2.11 on 2026-06-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_usersettings_push_large_txn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('daily', 'Щоденний звіт'), ('weekly', 'Тижневий звіт'), ('planned', 'Нагадування про платежі'), ('large_txn', 'Велика операція'), ('custom', 'Кастомне повідомлення')], max_length=20, verbose_name='Тип повідомлення'),
        ),
    ]
