# Generated by Django 5.2.11 on 2026-06-13 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_notification_ack_and_debts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterpartyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_mask', models.CharField(blank=True, default='', max_length=32)),
                ('last4', models.CharField(blank=True, db_index=True, default='', max_length=4)),
                ('bank', models.CharField(blank=True, default='', max_length=64)),
                ('iban', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('label', models.CharField(blank=True, default='', max_length=128)),
                ('is_primary', models.BooleanField(default=False)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterparty_cards', to='finance.company')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='finance.counterparty')),
            ],
            options={
                'verbose_name': 'Картка контрагента',
                'verbose_name_plural': 'Картки контрагентів',
                'ordering': ['-is_primary', '-last_used_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ObligationSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_key', models.CharField(blank=True, default='', max_length=16)),
                ('period_label', models.CharField(blank=True, default='', max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='UAH', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligation_settlements', to='finance.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='finance.transaction')),
                ('planned_txn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_settlements', to='finance.transaction')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='finance.recurrencerule')),
            ],
            options={
                'verbose_name': "Погашення зобов'язання",
                'verbose_name_plural': "Погашення зобов'язань",
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['company', 'rule'], name='finance_obl_company_4ee823_idx'), models.Index(fields=['payment'], name='finance_obl_payment_25261d_idx')],
            },
        ),
    ]
