# Generated by Django 5.2.11 on 2026-05-11 19:18

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('orders', '0044_orderitem_fit_options'),
        ('productcolors', '0007_normalize_slugs'),
        ('storefront', '0059_phase17c_modeltranslation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evening_reminder_enabled', models.BooleanField(default=True)),
                ('evening_reminder_hour', models.PositiveSmallIntegerField(default=22)),
                ('evening_reminder_minute', models.PositiveSmallIntegerField(default=0)),
                ('evening_reminder_chat_ids', models.CharField(blank=True, default='', help_text='Список chat_id Telegram, розділених комами', max_length=512)),
                ('last_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Налаштування складу',
                'verbose_name_plural': 'Налаштування складу',
            },
        ),
        migrations.CreateModel(
            name='Print',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='warehouse/prints/', verbose_name='Основне фото')),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_products', models.ManyToManyField(blank=True, help_text='Якщо у замовленні присутній один із цих товарів, цей принт пропонується за замовчуванням під час списання.', related_name='warehouse_default_prints', to='storefront.product', verbose_name="Зв'язані товари сайту")),
            ],
            options={
                'verbose_name': 'Принт',
                'verbose_name_plural': 'Принти',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StorageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('icon', models.CharField(blank=True, default='', help_text='Назва lucide-іконки або emoji', max_length=64)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_storefront_category', models.ForeignKey(blank=True, help_text='Використовується для співпадіння OrderItem → склад', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_categories', to='storefront.category', verbose_name="Пов'язана категорія сайту")),
            ],
            options={
                'verbose_name': 'Складська категорія',
                'verbose_name_plural': 'Складські категорії',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StorageSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Назва (крій / тип)')),
                ('slug', models.SlugField(blank=True, max_length=140)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_default', models.BooleanField(default=False, help_text='Підкатегорія за замовчуванням під час списання')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='warehouse.storagecategory', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Підкатегорія (крій)',
                'verbose_name_plural': 'Підкатегорії (крої)',
                'ordering': ['category__order', 'order', 'name'],
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='WriteOffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('pending', 'В очікуванні'), ('completed', 'Виконано'), ('cancelled', 'Скасовано')], default='pending', max_length=16)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_writeoffs_completed', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_writeoffs_opened', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_write_off_requests', to='orders.order')),
            ],
            options={
                'verbose_name': 'Запит на списання',
                'verbose_name_plural': 'Запити на списання',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintColorVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=80, verbose_name='Назва кольору')),
                ('color_hex', models.CharField(blank=True, default='', help_text='#RRGGBB (для індикатора)', max_length=7)),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Кількість')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Собівартість (грн)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='warehouse/prints/variants/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False, help_text='Варіант, що пропонується за замовчуванням')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('print', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_variants', to='warehouse.print', verbose_name='Принт')),
            ],
            options={
                'verbose_name': 'Варіант кольору принта',
                'verbose_name_plural': 'Варіанти кольорів принтів',
                'ordering': ['order', 'id'],
                'unique_together': {('print', 'color_name')},
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=16, verbose_name='Розмір')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Залишок')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Собівартість (грн)')),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_stock_items', to='productcolors.color', verbose_name='Колір')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='warehouse.storagesubcategory', verbose_name='Підкатегорія')),
            ],
            options={
                'verbose_name': 'Складська позиція (одяг)',
                'verbose_name_plural': 'Складські позиції (одяг)',
                'ordering': ['subcategory__category__order', 'subcategory__order', 'size'],
                'indexes': [models.Index(fields=['subcategory', 'size'], name='idx_stock_subcat_size'), models.Index(fields=['color', 'size'], name='idx_stock_color_size')],
                'unique_together': {('subcategory', 'color', 'size')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('delta', models.IntegerField(verbose_name='Зміна кількості (+/-)')),
                ('quantity_after', models.IntegerField(default=0, verbose_name='Залишок після операції')),
                ('reason', models.CharField(choices=[('manual_add', 'Ручне додавання'), ('manual_remove', 'Ручне списання'), ('bulk_add', 'Партія (масове додавання)'), ('order_write_off', 'Списання за замовленням'), ('recount', 'Інвентаризація'), ('print_add', 'Додавання принта'), ('print_remove', 'Списання принта'), ('adjustment', 'Коригування')], default='manual_add', max_length=32)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('verified', models.BooleanField(db_index=True, default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_movements', to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_movements_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_movements', to='orders.order')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_movements_verified', to=settings.AUTH_USER_MODEL)),
                ('write_off_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='warehouse.writeoffrequest')),
            ],
            options={
                'verbose_name': 'Рух складу',
                'verbose_name_plural': 'Рухи складу',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='idx_mov_target'), models.Index(fields=['created_at'], name='idx_mov_created'), models.Index(fields=['reason'], name='idx_mov_reason'), models.Index(fields=['verified'], name='idx_mov_verified')],
            },
        ),
    ]
