# Generated by Django 5.2.11 on 2026-05-11 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0059_phase17c_modeltranslation'),
        ('warehouse', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagecategory',
            name='sizes',
            field=models.JSONField(blank=True, default=list, help_text='Список розмірів, доступних для цієї категорії (наприклад ["XS","S","M","L","XL"]). Якщо порожній — береться з товарів сайту або стандартний набір.', verbose_name='Розміри'),
        ),
        migrations.AlterField(
            model_name='storagecategory',
            name='linked_storefront_category',
            field=models.ForeignKey(blank=True, help_text='Використовується для співпадіння OrderItem → склад. Можна залишити порожнім — тоді категорія буде тільки для внутрішнього обліку (warehouse-only).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_categories', to='storefront.category', verbose_name="Пов'язана категорія сайту"),
        ),
    ]
