# Generated by Django 5.2.11 on 2026-05-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productcolors', '0007_normalize_slugs'),
        ('warehouse', '0003_storagecategory_sizes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagesubcategory',
            name='colors',
            field=models.ManyToManyField(blank=True, help_text='Список кольорів, у яких випускається цей крій. Якщо порожній — у партії можна обрати будь-який колір.', related_name='storage_subcategories', to='productcolors.color', verbose_name='Доступні кольори'),
        ),
    ]
