# Generated by Claude Opus 4.8 on 2026-05-31

from django.db import migrations, models
import django.db.models.deletion
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_recurrence_improvements'),
        ('warehouse', '0002_writeoffrequest_packaging_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(
                    max_length=32,
                    choices=[
                        ('ink', 'Фарба для принтера'),
                        ('glue', 'Клей'),
                        ('film', 'Плівка (рулони)'),
                        ('tags', 'Брендовані бірки'),
                        ('patches', 'Шеврони'),
                        ('bags_small', 'Пакети малі'),
                        ('bags_medium', 'Пакети середні'),
                        ('bags_large', 'Пакети великі'),
                        ('bags_branded', 'Брендовані пакети'),
                        ('cleaner', 'Очисна рідина'),
                        ('other', 'Інше'),
                    ],
                    verbose_name='Категорія'
                )),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('quantity', models.DecimalField(max_digits=10, decimal_places=2, default=Decimal('0'), verbose_name='Залишок')),
                ('unit', models.CharField(max_length=16, default='шт', verbose_name='Одиниця виміру')),
                ('cost_per_unit', models.DecimalField(max_digits=10, decimal_places=2, default=Decimal('0'), verbose_name='Ціна за одиницю')),
                ('total_cost', models.DecimalField(max_digits=10, decimal_places=2, default=Decimal('0'), verbose_name='Загальна вартість')),
                ('supplier', models.ForeignKey(
                    on_delete=django.db.models.deletion.SET_NULL,
                    null=True,
                    blank=True,
                    to='finance.counterparty',
                    related_name='consumable_supplies',
                    verbose_name='Постачальник'
                )),
                ('purchase_date', models.DateField(verbose_name='Дата закупівлі')),
                ('min_stock_alert', models.DecimalField(
                    max_digits=10,
                    decimal_places=2,
                    default=Decimal('0'),
                    verbose_name='Мінімальний залишок для сповіщення'
                )),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Розхідний матеріал',
                'verbose_name_plural': 'Розхідні матеріали',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='writeoffrequest',
            name='packaging_used',
            field=models.JSONField(
                default=dict,
                blank=True,
                verbose_name='Використане пакування',
                help_text='{"bags_branded": 1, "tags": 2}'
            ),
        ),
        migrations.AddIndex(
            model_name='consumableitem',
            index=models.Index(fields=['category'], name='warehouse_co_categor_idx'),
        ),
        migrations.AddIndex(
            model_name='consumableitem',
            index=models.Index(fields=['quantity'], name='warehouse_co_quantit_idx'),
        ),
    ]
