# Generated by Django 5.2.11 on 2026-05-11 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_storagesubcategory_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('icon', models.CharField(blank=True, default='', help_text='Опціонально: одна emoji для індикатора (🎯 ⚔️ 🌿)', max_length=8, verbose_name='Іконка (emoji)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Категорія принтів',
                'verbose_name_plural': 'Категорії принтів',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='print',
            options={'ordering': ['category__order', 'category__name', 'name'], 'verbose_name': 'Принт', 'verbose_name_plural': 'Принти'},
        ),
        migrations.AddField(
            model_name='print',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prints', to='warehouse.printcategory', verbose_name='Категорія'),
        ),
    ]
