# Generated by Claude Opus 4.8 on 2026-06-03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_consumable_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumableCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('icon', models.CharField(blank=True, default='', help_text='Опціонально: одна emoji для індикатора (🖨️ 👕 📦)', max_length=8, verbose_name='Іконка (emoji)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Категорія розхідників',
                'verbose_name_plural': 'Категорії розхідників',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='consumableitem',
            name='category',
            field=models.CharField(
                blank=True,
                null=True,
                choices=[
                    ('ink', 'Фарба для принтера'),
                    ('glue', 'Клей'),
                    ('film', 'Плівка (рулони)'),
                    ('tags', 'Брендовані бірки'),
                    ('patches', 'Шеврони'),
                    ('bags_small', 'Пакети малі'),
                    ('bags_medium', 'Пакети середні'),
                    ('bags_large', 'Пакети великі'),
                    ('bags_branded', 'Брендовані пакети'),
                    ('cleaner', 'Очисна рідина'),
                    ('other', 'Інше'),
                ],
                help_text='Застаріле поле; нові позиції використовують category_fk.',
                max_length=32,
                verbose_name='Категорія (legacy)',
            ),
        ),
        migrations.AddField(
            model_name='consumableitem',
            name='category_fk',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='items',
                to='warehouse.consumablecategory',
                verbose_name='Категорія',
            ),
        ),
        migrations.AlterModelOptions(
            name='consumableitem',
            options={
                'ordering': ['name'],
                'verbose_name': 'Розхідний матеріал',
                'verbose_name_plural': 'Розхідні матеріали',
            },
        ),
    ]
