# Generated by Django 5.2.11 on 2026-06-03 11:56

from decimal import Decimal
from django.db import migrations, models


def backfill_last_cost(apps, schema_editor):
    """Існуючим позиціям ставимо last_cost_price = cost_price,
    щоб вони не позначались як «ціна змінилась» одразу після релізу."""
    StockItem = apps.get_model("warehouse", "StockItem")
    StockItem.objects.filter(last_cost_price=Decimal("0.00")).exclude(
        cost_price=Decimal("0.00")
    ).update(last_cost_price=models.F("cost_price"))


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_seed_consumable_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='last_cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ціна останньої партії. Якщо відрізняється від середньозваженої cost_price — значить ціна між партіями змінилась (показуємо мітку).', max_digits=10, verbose_name='Остання ціна закупки (грн)'),
        ),
        migrations.RunPython(backfill_last_cost, noop),
    ]

