# Generated by Django 5.2.11 on 2026-06-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productcolors', '0007_normalize_slugs'),
        ('warehouse', '0008_stockitem_last_cost_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='printcolorvariant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='print',
            name='garment_colors',
            field=models.ManyToManyField(blank=True, help_text='Заповнюється, коли «Під яку одежу» = «Тільки для кольорів».', related_name='prints_fit', to='productcolors.color', verbose_name='Кольори одягу'),
        ),
        migrations.AddField(
            model_name='print',
            name='garment_fit',
            field=models.CharField(choices=[('any', 'Будь-яка'), ('dark', 'Під темну'), ('light', 'Під світлу'), ('specific', 'Тільки для кольорів')], default='any', help_text='Під темну / світлу або тільки під конкретні кольори.', max_length=16, verbose_name='Під яку одежу'),
        ),
        migrations.AddField(
            model_name='print',
            name='placement',
            field=models.CharField(blank=True, choices=[('chest', 'На грудь'), ('back', 'На спину'), ('sleeve', 'На рукав'), ('pocket', 'Кишеня'), ('full', 'Повний друк'), ('other', 'Інше')], default='', help_text='Куди наноситься принт (грудь / спина / рукав).', max_length=16, verbose_name='Розташування'),
        ),
        migrations.AddField(
            model_name='printcolorvariant',
            name='color_mode',
            field=models.CharField(choices=[('single', 'Один колір'), ('combo', 'Поєднання кольорів'), ('mix', 'Мікс'), ('standard', 'Стандарт')], default='single', max_length=16, verbose_name='Тип кольору'),
        ),
        migrations.AddField(
            model_name='printcolorvariant',
            name='colors',
            field=models.ManyToManyField(blank=True, help_text='Один колір для single, кілька для combo. Для mix/standard — порожньо.', related_name='print_variants', to='productcolors.color', verbose_name='Кольори друку'),
        ),
        migrations.AlterField(
            model_name='printcolorvariant',
            name='color_name',
            field=models.CharField(blank=True, help_text='Обчислюється автоматично за типом і обраними кольорами.', max_length=120, verbose_name='Підпис кольору'),
        ),
    ]
