# Generated by Django 5.2.11 on 2026-06-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_alter_printcolorvariant_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousesettings',
            name='push_content',
            field=models.JSONField(blank=True, default=list, help_text='Список блоків: ["movements","unverified","low_stock","frozen_value","prints"]', verbose_name='Вміст сповіщення'),
        ),
        migrations.AddField(
            model_name='warehousesettings',
            name='push_enabled',
            field=models.BooleanField(default=False, verbose_name='Пуш-сповіщення увімкнено'),
        ),
        migrations.AddField(
            model_name='warehousesettings',
            name='push_frequency',
            field=models.CharField(choices=[('daily', 'Щоденний пуш'), ('weekly', 'Щотижневий звіт')], default='daily', max_length=16, verbose_name='Частота'),
        ),
        migrations.AddField(
            model_name='warehousesettings',
            name='push_to_telegram',
            field=models.BooleanField(default=True, verbose_name='Дублювати в Telegram'),
        ),
        migrations.AddField(
            model_name='warehousesettings',
            name='push_weekly_day',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = понеділок … 6 = неділя (для щотижневого звіту).', verbose_name='День тижневого звіту'),
        ),
    ]
