# Generated by Django 5.2.11 on 2026-06-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_warehousesettings_push_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('manual_add', 'Ручне додавання'), ('manual_remove', 'Ручне списання'), ('bulk_add', 'Партія (масове додавання)'), ('order_write_off', 'Продаж за замовленням'), ('recount', 'Інвентаризація'), ('print_add', 'Додавання принта'), ('print_remove', 'Списання принта'), ('adjustment', 'Коригування'), ('sale', 'Продаж (ручний)'), ('damage', 'Брак / пошкодження'), ('return', 'Повернення на склад')], default='manual_add', max_length=32),
        ),
    ]
